<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AiReporteEvasionsTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ai_reporte_evasions')->delete();
        
        \DB::table('ai_reporte_evasions')->insert(array (
            0 => 
            array (
                'prm_rostro_id' => '1445',
                'prm_contextura_id' => '1440',
                'nnaj_peso' => '60',
                'nnaj_talla' => '170',
                'hora_evasion' => '2021-05-06 15:00:00',
                'fecha_evasion' => '2021-05-06 00:00:00',
                'lugar_evasion' => 'UPI EDEN KM95 VIA BOGOTA LA ESCOBITA',
                'prm_upi_id' => '8',
                'fecha_diligenciamiento' => '2021-05-06 00:00:00',
                'municipio_id' => '748',
                'departamento_id' => '31',
                'sis_nnaj_id' => '1113',
                'id' => '1',
                'updated_at' => '2021-05-13 10:53:47',
                'created_at' => '2021-05-13 10:53:47',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'prm_hor_denuncia_id' => NULL,
                'hora_denuncia' => '2021-05-07 08:53:00',
                'fecha_denuncia' => '2021-05-07 00:00:00',
                'placa_recibe' => 'NO APLICA',
                'cargo_recibe' => 'ASESOR LINEA 141',
                'nombre_recibe' => 'LORENA NORIEGA',
                'institucion' => 'ICBF',
                'responsable' => '2135',
                'user_doc2_id' => '398',
                'user_doc1_id' => '1335',
                'recibe_denuncia' => 'LORENA NORIEGA',
                'radicado' => '1762565676',
                'prm_llamada_id' => '1657',
                'prm_reporta_id' => '227',
                'observaciones_fam' => 'SE INFORMA A LA PROGENITORA LA SEÑORA HEIDY SALVO AL NÚMERO 3132495777. Y SE SOLICITA MANTENER CONTACTO CON LA UNIDAD, SI EL ADOLESCENTE LLEGA A SU HOGAR.',
                'circunstancias' => 'EL ADOLESCENTE MANIFIESTA QUE SE QUIERE EVADIR DE LA UNIDAD CON ALGUNOS DE SUS PARES, DANDO FINALIZACION A SU PROCESO, SE REALIZA COMITE CON EL ADOLESCENTE CON EL FIN DE HACER CONTENCION CON EL ADOLESCENTE Y EVITAR POSIBLE EVASION, PERO ÉL HACE CASO OMISO Y DECIDE EVADIRSE DE LA UNIDAD SALTANDO LA REJA DE LA MISMA.',
                's_doc_adjunto' => NULL,
                'senias' => 'MANCHAS EN LOS BRAZOS',
                'prm_tamlunar_id' => NULL,
                'cuantos' => NULL,
                'prm_tienelunar_id' => '228',
                'prm_nariz_id' => '1467',
                'prm_ojos_id' => '1453',
                'prm_corcabello_id' => '1211',
                'prm_tipcabello_id' => '1457',
                'tintura' => NULL,
                'prm_tinturado_id' => '228',
                'prm_colcabello_id' => '1453',
                'prm_piel_id' => '1448',
            ),
            1 => 
            array (
                'prm_rostro_id' => '1445',
                'prm_contextura_id' => '1439',
                'nnaj_peso' => '65',
                'nnaj_talla' => '172',
                'hora_evasion' => '2021-05-06 15:00:00',
                'fecha_evasion' => '2021-05-06 00:00:00',
                'lugar_evasion' => 'UPI EDEN KM95 VIA BOGOTA LA ESCOBITA',
                'prm_upi_id' => '8',
                'fecha_diligenciamiento' => '2021-05-06 00:00:00',
                'municipio_id' => '748',
                'departamento_id' => '31',
                'sis_nnaj_id' => '1130',
                'id' => '3',
                'updated_at' => '2021-05-13 12:07:58',
                'created_at' => '2021-05-13 12:07:58',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'prm_hor_denuncia_id' => NULL,
                'hora_denuncia' => '2021-05-07 15:00:00',
                'fecha_denuncia' => '2021-05-07 00:00:00',
                'placa_recibe' => 'NO APLICA',
                'cargo_recibe' => 'ASESOR LINEA 141',
                'nombre_recibe' => 'LORENA NORIEGA',
                'institucion' => 'ICBF',
                'responsable' => '2135',
                'user_doc2_id' => '398',
                'user_doc1_id' => '1335',
                'recibe_denuncia' => 'LORENA NORIEGA',
                'radicado' => '13833280',
                'prm_llamada_id' => '1657',
                'prm_reporta_id' => '227',
                'observaciones_fam' => 'SE ESTABLECE CONTACTO TELEFÓNICO CON PROGENITOR DEL ADOLESCENTE EL SR. MARTIN AL NUMERO 3046760549',
                'circunstancias' => 'EL ADOLESCENTE MANIFIESTA QUE SE QUIERE EVADIR DE LA UNIDAD CON ALGUNOS DE SUS PARES, DANDO FINALIZACION A SU PROCESO, SIENDO ESTE COMPORTAMIENTO REITERATIVO EN EL ADOLESCENTE. SE REALIZA COMITE CON EL ADOLESCENTE CON EL FIN DE HACER CONTENCION Y EVITAR POSIBLE EVASION PERO EL HACE CASO OMISO Y DECIDE EVADIRSE DE LA UNIDAD SALTANDO LA REJA DE LA MISMA.',
                's_doc_adjunto' => NULL,
                'senias' => 'EL ADOLESCENTE USA BRAKETS',
                'prm_tamlunar_id' => NULL,
                'cuantos' => NULL,
                'prm_tienelunar_id' => '228',
                'prm_nariz_id' => '1467',
                'prm_ojos_id' => '1463',
                'prm_corcabello_id' => '1211',
                'prm_tipcabello_id' => '1456',
                'tintura' => NULL,
                'prm_tinturado_id' => '228',
                'prm_colcabello_id' => '1453',
                'prm_piel_id' => '1448',
            ),
            2 => 
            array (
                'prm_rostro_id' => '1445',
                'prm_contextura_id' => '1439',
                'nnaj_peso' => '60',
                'nnaj_talla' => '170',
                'hora_evasion' => '2021-05-06 15:00:00',
                'fecha_evasion' => '2021-05-06 00:00:00',
                'lugar_evasion' => 'UPI EDEN KM95 VIA BOGOTA LA ESCOBITA',
                'prm_upi_id' => '8',
                'fecha_diligenciamiento' => '2021-05-06 00:00:00',
                'municipio_id' => '748',
                'departamento_id' => '31',
                'sis_nnaj_id' => '1141',
                'id' => '4',
                'updated_at' => '2021-05-13 13:08:27',
                'created_at' => '2021-05-13 13:08:27',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'prm_hor_denuncia_id' => NULL,
                'hora_denuncia' => NULL,
                'fecha_denuncia' => '2021-05-06 00:00:00',
                'placa_recibe' => 'N/A',
                'cargo_recibe' => 'N/A',
                'nombre_recibe' => 'N/A',
                'institucion' => 'N/A',
                'responsable' => '2135',
                'user_doc2_id' => '398',
                'user_doc1_id' => '1335',
                'recibe_denuncia' => NULL,
                'radicado' => NULL,
                'prm_llamada_id' => NULL,
                'prm_reporta_id' => '228',
                'observaciones_fam' => 'SE ESTABLECE CONTACTO TELEFONICO CON PROGENITORA LA SEÑORA FANNY SILVA AL NÚMERO 3143422673. 
EL ADOLESCENTE RETORNA A LA UNIDAD  SIENDO LAS  12:30 DE LA NOCHE, SIN PRESENTAR NOVEDADDES A NIVEL FISICO, Y SE INGRESA A AISLAMIENTO. NO SE REALIZA REPORTE A LAS ENTIDADES',
                'circunstancias' => 'EL ADOLESCENTE MANIFIESTA QUE SE QUIERE EVADIR DE LA UNIDAD CON ALGUNOS DE SUS PARES, DANDO FINALIZACION A SU PROCESO, SE REALIZA COMITE CON EL ADOLESCENTE CON EL FIN DE HACER CONTENCION CON EL ADOLESCENTE Y EVITAR POSIBLE EVASION, PERO ÉL HACE CASO OMISO Y DECIDE EVADIRSE DE LA UNIDAD SALTANDO LA REJA DE LA MISMA',
                's_doc_adjunto' => 'Archivos/aievasion/adjunto/documento_2021_05_13_13_05_27.pdf',
                'senias' => 'NINGUNA',
                'prm_tamlunar_id' => NULL,
                'cuantos' => NULL,
                'prm_tienelunar_id' => '228',
                'prm_nariz_id' => '1467',
                'prm_ojos_id' => '1463',
                'prm_corcabello_id' => '1211',
                'prm_tipcabello_id' => '1457',
                'tintura' => NULL,
                'prm_tinturado_id' => '228',
                'prm_colcabello_id' => '1453',
                'prm_piel_id' => '1448',
            ),
            3 => 
            array (
                'prm_rostro_id' => '1443',
                'prm_contextura_id' => '1440',
                'nnaj_peso' => '62',
                'nnaj_talla' => '170',
                'hora_evasion' => '2021-05-11 14:30:00',
                'fecha_evasion' => '2021-05-11 00:00:00',
                'lugar_evasion' => 'UPI EDEN KM95 VIA BOGOTA LA ESCOBITA',
                'prm_upi_id' => '8',
                'fecha_diligenciamiento' => '2021-05-11 00:00:00',
                'municipio_id' => '749',
                'departamento_id' => '31',
                'sis_nnaj_id' => '1285',
                'id' => '5',
                'updated_at' => '2021-05-13 15:04:49',
                'created_at' => '2021-05-13 15:04:49',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'prm_hor_denuncia_id' => NULL,
                'hora_denuncia' => '2021-05-11 16:00:00',
                'fecha_denuncia' => '2021-05-11 00:00:00',
                'placa_recibe' => 'N/A',
                'cargo_recibe' => 'AGENTE LINEA141',
                'nombre_recibe' => 'DAIHAN VANEESA MORA',
                'institucion' => 'ICBF',
                'responsable' => '2135',
                'user_doc2_id' => '398',
                'user_doc1_id' => '452',
                'recibe_denuncia' => 'DAIHAN VANESSA MORA MORA',
                'radicado' => '13834082',
                'prm_llamada_id' => '1657',
                'prm_reporta_id' => '227',
                'observaciones_fam' => 'RECIBE LA DENUNCIA LA AGENTE DE ICBF DAIHAM VANESSA MORA MORA, QUIEN REMITE A DEFENSORA DE FAMILIA DRA. GINA TATIANA LUGO ORTIZ DE CENTRO ZONAL REVIVIR, CORREO ELECTRÓNICO YINA.LUGO@ICBF.GOV.CO, CONTACTO TELEFÓNICO 4377630 EXT.149027. QUEDA EN CONOCIMIENTO DE LA DEFENSORA LA EVASIÓN DEL MENOR.',
                'circunstancias' => 'EL ADOLESCENTE SE EVADE EN COMPAÑÍA DE SUS PARES, DURANTE LA SITUACION CONFLICTVA QUE SE PRESENTA DE PARTE DE SU COMPAÑERO HACIA LA COMUNIDAD, MANIFESTANDO QUE SE IRIA CON EL PARA NO DEJARLO SOLO. A PESAR DE LA SENSIBILIZACION Y CONTENCION REALIZADA POR LOS FUNCIONARIOS EL ADOLESCENTE SALTA LA REJA DE LA ENTRADA PRINCIPAL DE LA UNIDAD Y SE  EVADE.',
                's_doc_adjunto' => 'Archivos/aievasion/adjunto/documento_2021_05_13_15_05_49.pdf',
                'senias' => 'NO',
                'prm_tamlunar_id' => NULL,
                'cuantos' => NULL,
                'prm_tienelunar_id' => '228',
                'prm_nariz_id' => '1467',
                'prm_ojos_id' => '1453',
                'prm_corcabello_id' => '1211',
                'prm_tipcabello_id' => '1457',
                'tintura' => NULL,
                'prm_tinturado_id' => '228',
                'prm_colcabello_id' => '1453',
                'prm_piel_id' => '1450',
            ),
            4 => 
            array (
                'prm_rostro_id' => '1445',
                'prm_contextura_id' => '1439',
                'nnaj_peso' => '55',
                'nnaj_talla' => '172',
                'hora_evasion' => '2021-05-06 15:00:00',
                'fecha_evasion' => '2021-05-06 00:00:00',
                'lugar_evasion' => 'UPI EDEN KM95 VIA BOGOTA LA ESCOBITA',
                'prm_upi_id' => '8',
                'fecha_diligenciamiento' => '2021-05-06 00:00:00',
                'municipio_id' => '748',
                'departamento_id' => '31',
                'sis_nnaj_id' => '1123',
                'id' => '2',
                'updated_at' => '2021-05-13 11:58:32',
                'created_at' => '2021-05-13 11:58:32',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'prm_hor_denuncia_id' => NULL,
                'hora_denuncia' => '2021-05-07 15:00:00',
                'fecha_denuncia' => '2021-05-07 00:00:00',
                'placa_recibe' => 'NO APLICA',
                'cargo_recibe' => 'ASESOR LINEA 141',
                'nombre_recibe' => 'LORENA NORIEGA',
                'institucion' => 'ICBF',
                'responsable' => '2135',
                'user_doc2_id' => '398',
                'user_doc1_id' => '1335',
                'recibe_denuncia' => 'LORENA NORIEGA',
                'radicado' => '13833723',
                'prm_llamada_id' => '1657',
                'prm_reporta_id' => '227',
            'observaciones_fam' => 'NO ES POSIBLE ESTABLECER CONTACTO CON LA SEÑORA SRA. ERIKA ACOSTA  AL NUMERO 3132952143 PARA INFORMAR EVASIÓN (TIA MATERNA)',
                'circunstancias' => 'EL ADOLESCENTE MANIFIESTA QUE SE QUIERE EVADIR DE LA UNIDAD CON ALGUNOS DE SUS PARES, DANDO FINALIZACION A SU PROCESO, SE REALIZA COMITE CON EL ADOLESCENTE CON EL FIN DE HACER CONTENCION CON EL ADOLESCENTE Y EVITAR POSIBLE EVASION, PERO EL HACE CASO OMISO Y DECIDE EVADIRSE DE LA UNIDAD SALTANDO LA REJA DE LA MISMA.',
                's_doc_adjunto' => 'Archivos/aievasion/adjunto/documento_2021_05_13_11_05_32.pdf',
                'senias' => 'NO',
                'prm_tamlunar_id' => NULL,
                'cuantos' => NULL,
                'prm_tienelunar_id' => '228',
                'prm_nariz_id' => '1467',
                'prm_ojos_id' => '1464',
                'prm_corcabello_id' => '1211',
                'prm_tipcabello_id' => '1457',
                'tintura' => NULL,
                'prm_tinturado_id' => '228',
                'prm_colcabello_id' => '1452',
                'prm_piel_id' => '1447',
            ),
            5 => 
            array (
                'prm_rostro_id' => '1442',
                'prm_contextura_id' => '1439',
                'nnaj_peso' => '50',
                'nnaj_talla' => '168',
                'hora_evasion' => '2021-05-11 14:30:00',
                'fecha_evasion' => '2021-05-11 00:00:00',
                'lugar_evasion' => 'UPI EDEN KM95 VIA BOGOTA LA ESCOBITA',
                'prm_upi_id' => '8',
                'fecha_diligenciamiento' => '2021-05-11 00:00:00',
                'municipio_id' => '748',
                'departamento_id' => '31',
                'sis_nnaj_id' => '1286',
                'id' => '6',
                'updated_at' => '2021-05-13 15:16:07',
                'created_at' => '2021-05-13 15:16:07',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'prm_hor_denuncia_id' => NULL,
                'hora_denuncia' => '2021-05-11 16:00:00',
                'fecha_denuncia' => '2021-05-11 00:00:00',
                'placa_recibe' => 'N/A',
                'cargo_recibe' => 'AGENTE LINEA141',
                'nombre_recibe' => 'DAIHAN VANEESA MORA',
                'institucion' => 'ICBF',
                'responsable' => '2135',
                'user_doc2_id' => '398',
                'user_doc1_id' => '452',
                'recibe_denuncia' => 'DAIHAN VANESSA MORA MORA',
                'radicado' => '14439406',
                'prm_llamada_id' => '1657',
                'prm_reporta_id' => '227',
                'observaciones_fam' => 'RECIBE LA DENUNCIA LA AGENTE DE ICBF DAIHAM VANESSA MORA MORA.',
                'circunstancias' => 'EL ADOLESCENTE PRESENTA CONDUCTAS DESAFIANTES Y AGRESIÓN FÍSICA Y VERBAL COMO PRINCIPAL MEDIO DE INTERACCIÓN CON COMPAÑEROS Y EDUCADORES, EN ESTE SENTIDO AL TRATAR DE MANERA VULGAR A UNO DE SUS COMPAÑEROS, LA EDUCADORA LO INVITA A REFLEXIONAR Y MEJORAR ESTA CONDUCTA, SIN EMBARGO, EL ADOLESCENTE LA INSULTA, ROMPE UN VIDRIO DE UNO DE LOSCUARTOS E INTENTA AGREDIRLA, RAZÓN POR LA CUAL INTERVIENEN TODOS LOS MIEMBROS DE LA COMUNIDAD. EL ADOLESCENTE AMENAZA A TODAS LAS PERSONAS CON UN PEDAZO DE VIDRIO ROTO EN LA MANO, Y DECIDE TOMAR SU ROPA Y SALIR DE LA UNIDAD SALTANDO LA REJA DE LA ENTRADA PRINCIPAL, EN COMPAÑÍA DE LOS ADOLESCENTES QUE HABIAN INGRESADO EL MISMO DIA QUE ÉL',
                's_doc_adjunto' => 'Archivos/aievasion/adjunto/documento_2021_05_13_15_05_07.pdf',
                'senias' => 'NO',
                'prm_tamlunar_id' => NULL,
                'cuantos' => NULL,
                'prm_tienelunar_id' => '228',
                'prm_nariz_id' => '1466',
                'prm_ojos_id' => '1453',
                'prm_corcabello_id' => '1211',
                'prm_tipcabello_id' => '1457',
                'tintura' => NULL,
                'prm_tinturado_id' => '228',
                'prm_colcabello_id' => '1453',
                'prm_piel_id' => '1450',
            ),
            6 => 
            array (
                'prm_rostro_id' => '1442',
                'prm_contextura_id' => '1440',
                'nnaj_peso' => '65',
                'nnaj_talla' => '175',
                'hora_evasion' => '2021-05-11 14:30:00',
                'fecha_evasion' => '2021-05-11 00:00:00',
                'lugar_evasion' => 'UPI EDEN KM95 VIA BOGOTA LA ESCOBITA',
                'prm_upi_id' => '8',
                'fecha_diligenciamiento' => '2021-05-11 00:00:00',
                'municipio_id' => '748',
                'departamento_id' => '31',
                'sis_nnaj_id' => '1278',
                'id' => '7',
                'updated_at' => '2021-05-13 15:24:55',
                'created_at' => '2021-05-13 15:24:55',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'prm_hor_denuncia_id' => NULL,
                'hora_denuncia' => '2021-05-11 16:00:00',
                'fecha_denuncia' => '2021-05-11 00:00:00',
                'placa_recibe' => 'N/A',
                'cargo_recibe' => 'AGENTE LINEA141',
                'nombre_recibe' => 'DAIHAN VANEESA MORA',
                'institucion' => 'ICBF',
                'responsable' => '2135',
                'user_doc2_id' => '398',
                'user_doc1_id' => '452',
                'recibe_denuncia' => 'DAIHAN VANESSA MORA MORA',
                'radicado' => '13984938',
                'prm_llamada_id' => '1657',
                'prm_reporta_id' => '227',
                'observaciones_fam' => 'RECIBE LA DENUNCIA LA AGENTE DE ICBF DAIHAM VANESSA MORA MORA, ALLI SE REMITE EL REPORTE AL DEFENSOR DE FAMILIA DR. RAFAEL CASTILLO AYALA DE CENTRO ZONAL PUENTE ARANDA, CORREO ELECTRÓNICO RAFAEL.CASTILLO@ICBF.GOV.CO CONTACTO TELEFÓNICO 4376630 - 3241900 EXT.149027, QUEDANDO EN CONOCIMIENTO LA EVASIÓN DEL MENOR. SE INTENTA AVISAR A LA PROGENITORA PERO LOS TELEFONOS BRINDADOS ESTAN FUERA DE SERVICIO.',
                'circunstancias' => 'EL ADOLESCENTE SE EVADE EN COMPAÑÍA DE SUS PARES, DURANTE LA SITUACION CONFLICTVA QUE SE PRESENTA DE PARTE DE SU COMPAÑERO HACIA LA COMUNIDAD, MANIFESTANDO QUE SE IRIA CON EL PARA NO DEJARLO SOLO. A PESAR DE LA SENSIBILIZACION Y CONTENCION REALIZADA POR LOS FUNCIONARIOS EL ADOLESCENTE SALTA LA REJA DE LA ENTRADA PRINCIPAL DE LA UNIDAD Y SE EVADE',
                's_doc_adjunto' => 'Archivos/aievasion/adjunto/documento_2021_05_13_15_05_55.pdf',
                'senias' => 'NO',
                'prm_tamlunar_id' => NULL,
                'cuantos' => NULL,
                'prm_tienelunar_id' => '228',
                'prm_nariz_id' => '1466',
                'prm_ojos_id' => '1453',
                'prm_corcabello_id' => '1211',
                'prm_tipcabello_id' => '1457',
                'tintura' => NULL,
                'prm_tinturado_id' => '228',
                'prm_colcabello_id' => '1453',
                'prm_piel_id' => '1450',
            ),
        ));
        
        
    }
}