<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CsdViolenciasTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('csd_violencias')->delete();
        
        \DB::table('csd_violencias')->insert(array (
            0 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '78',
                'id' => '1',
            ),
            1 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '14',
                'id' => '2',
            ),
            2 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '471',
                'departamento_cert_id' => '23',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '471',
                'departamento_cond_id' => '23',
                'prm_condicion_id' => '936',
                'csd_id' => '19',
                'id' => '3',
            ),
            3 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '6',
                'id' => '4',
            ),
            4 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '16',
                'id' => '5',
            ),
            5 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '36',
                'id' => '6',
            ),
            6 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '70',
                'id' => '7',
            ),
            7 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '33',
                'id' => '8',
            ),
            8 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '16',
                'prm_condicion_id' => '853',
                'csd_id' => '66',
                'id' => '9',
            ),
            9 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '32',
                'id' => '10',
            ),
            10 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '83',
                'id' => '11',
            ),
            11 => 
            array (
                'updated_at' => '2021-04-27 12:00:59',
                'created_at' => '2021-04-27 12:00:59',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '820',
                'departamento_cert_id' => '34',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '820',
                'departamento_cond_id' => '34',
                'prm_condicion_id' => '454',
                'csd_id' => '25',
                'id' => '12',
            ),
            12 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '28',
                'id' => '13',
            ),
            13 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '29',
                'id' => '14',
            ),
            14 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '85',
                'id' => '15',
            ),
            15 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '356',
                'departamento_cert_id' => '19',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '356',
                'departamento_cond_id' => '19',
                'prm_condicion_id' => '454',
                'csd_id' => '87',
                'id' => '16',
            ),
            16 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '48',
                'id' => '17',
            ),
            17 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '256',
                'csd_id' => '84',
                'id' => '18',
            ),
            18 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '256',
                'csd_id' => '9',
                'id' => '19',
            ),
            19 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '256',
                'csd_id' => '3',
                'id' => '20',
            ),
            20 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '256',
                'csd_id' => '50',
                'id' => '21',
            ),
            21 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '256',
                'csd_id' => '4',
                'id' => '22',
            ),
            22 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '35',
                'id' => '23',
            ),
            23 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '54',
                'id' => '24',
            ),
            24 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '10',
                'id' => '25',
            ),
            25 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '753',
                'departamento_cert_id' => '31',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '753',
                'departamento_cond_id' => '31',
                'prm_condicion_id' => '454',
                'csd_id' => '8',
                'id' => '26',
            ),
            26 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '13',
                'id' => '27',
            ),
            27 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '6',
                'prm_condicion_id' => '454',
                'csd_id' => '51',
                'id' => '28',
            ),
            28 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '15',
                'id' => '29',
            ),
            29 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '67',
                'id' => '30',
            ),
            30 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '7',
                'id' => '31',
            ),
            31 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '12',
                'id' => '32',
            ),
            32 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '11',
                'id' => '33',
            ),
            33 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '6',
                'prm_condicion_id' => '936',
                'csd_id' => '43',
                'id' => '34',
            ),
            34 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '80',
                'id' => '35',
            ),
            35 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '174',
                'departamento_cert_id' => '14',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '174',
                'departamento_cond_id' => '14',
                'prm_condicion_id' => '936',
                'csd_id' => '73',
                'id' => '36',
            ),
            36 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '259',
                'csd_id' => '63',
                'id' => '37',
            ),
            37 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '40',
                'id' => '38',
            ),
            38 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '6',
                'prm_condicion_id' => '259',
                'csd_id' => '53',
                'id' => '39',
            ),
            39 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '41',
                'id' => '40',
            ),
            40 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '30',
                'id' => '41',
            ),
            41 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '52',
                'id' => '42',
            ),
            42 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '366',
                'departamento_cert_id' => '19',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '366',
                'departamento_cond_id' => '19',
                'prm_condicion_id' => '454',
                'csd_id' => '49',
                'id' => '43',
            ),
            43 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '454',
                'csd_id' => '2',
                'id' => '44',
            ),
            44 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '18',
                'id' => '45',
            ),
            45 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '86',
                'id' => '46',
            ),
            46 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '20',
                'id' => '47',
            ),
            47 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '72',
                'id' => '48',
            ),
            48 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '39',
                'id' => '49',
            ),
            49 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '26',
                'id' => '50',
            ),
            50 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '55',
                'id' => '51',
            ),
            51 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '356',
                'departamento_cert_id' => '19',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '356',
                'departamento_cond_id' => '19',
                'prm_condicion_id' => '454',
                'csd_id' => '88',
                'id' => '52',
            ),
            52 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '71',
                'id' => '53',
            ),
            53 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '57',
                'id' => '54',
            ),
            54 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '439',
                'departamento_cert_id' => '22',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '439',
                'departamento_cond_id' => '22',
                'prm_condicion_id' => '936',
                'csd_id' => '90',
                'id' => '55',
            ),
            55 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '75',
                'id' => '56',
            ),
            56 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '23',
                'id' => '57',
            ),
            57 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '31',
                'id' => '58',
            ),
            58 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '69',
                'id' => '59',
            ),
            59 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '82',
                'id' => '60',
            ),
            60 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '5',
                'id' => '61',
            ),
            61 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '17',
                'id' => '62',
            ),
            62 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '478',
                'departamento_cert_id' => '15',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '478',
                'departamento_cond_id' => '15',
                'prm_condicion_id' => '454',
                'csd_id' => '79',
                'id' => '63',
            ),
            63 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '6',
                'prm_condicion_id' => '936',
                'csd_id' => '42',
                'id' => '64',
            ),
            64 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '6',
                'prm_condicion_id' => '455',
                'csd_id' => '22',
                'id' => '65',
            ),
            65 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '68',
                'id' => '66',
            ),
            66 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '148',
                'departamento_cert_id' => '13',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '148',
                'departamento_cond_id' => '13',
                'prm_condicion_id' => '936',
                'csd_id' => '47',
                'id' => '67',
            ),
            67 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '110',
                'departamento_cert_id' => '12',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '110',
                'departamento_cond_id' => '12',
                'prm_condicion_id' => '936',
                'csd_id' => '37',
                'id' => '68',
            ),
            68 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '81',
                'id' => '69',
            ),
            69 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '1',
                'id' => '70',
            ),
            70 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '56',
                'id' => '71',
            ),
            71 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '371',
                'departamento_cert_id' => '19',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '371',
                'departamento_cond_id' => '19',
                'prm_condicion_id' => '454',
                'csd_id' => '89',
                'id' => '72',
            ),
            72 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '21',
                'id' => '73',
            ),
            73 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '91',
                'id' => '74',
            ),
            74 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '77',
                'id' => '75',
            ),
            75 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '2316',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '62',
                'id' => '76',
            ),
            76 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '853',
                'csd_id' => '45',
                'id' => '77',
            ),
            77 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '59',
                'id' => '78',
            ),
            78 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '6',
                'prm_condicion_id' => '936',
                'csd_id' => '44',
                'id' => '79',
            ),
            79 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '65',
                'id' => '80',
            ),
            80 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '16',
                'prm_condicion_id' => '454',
                'csd_id' => '61',
                'id' => '81',
            ),
            81 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '76',
                'id' => '82',
            ),
            82 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '2316',
                'csd_id' => '60',
                'id' => '83',
            ),
            83 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '34',
                'id' => '84',
            ),
            84 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '58',
                'id' => '85',
            ),
            85 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '300',
                'departamento_cert_id' => '16',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '300',
                'departamento_cond_id' => '16',
                'prm_condicion_id' => '936',
                'csd_id' => '64',
                'id' => '86',
            ),
            86 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '38',
                'id' => '87',
            ),
            87 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '233',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '233',
                'departamento_cond_id' => '16',
                'prm_condicion_id' => '936',
                'csd_id' => '46',
                'id' => '88',
            ),
            88 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '24',
                'id' => '89',
            ),
            89 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '74',
                'id' => '90',
            ),
            90 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '228',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '92',
                'id' => '91',
            ),
            91 => 
            array (
                'updated_at' => '2021-04-27 12:01:00',
                'created_at' => '2021-04-27 12:01:00',
                'prm_tipofuen_id' => '2316',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'municipio_cert_id' => '1',
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '259',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '455',
                'csd_id' => '27',
                'id' => '92',
            ),
            92 => 
            array (
                'updated_at' => '2021-05-17 15:34:31',
                'created_at' => '2021-05-17 15:34:31',
                'prm_tipofuen_id' => '2315',
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'municipio_cert_id' => '231',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '67',
                'departamento_cond_id' => '10',
                'prm_condicion_id' => '454',
                'csd_id' => '93',
                'id' => '93',
            ),
            93 => 
            array (
                'updated_at' => '2021-05-27 14:14:29',
                'created_at' => '2021-05-27 14:14:29',
                'prm_tipofuen_id' => '2315',
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'municipio_cert_id' => NULL,
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '235',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '853',
                'csd_id' => '95',
                'id' => '95',
            ),
            94 => 
            array (
                'updated_at' => '2021-06-02 18:58:17',
                'created_at' => '2021-06-02 18:58:17',
                'prm_tipofuen_id' => '2315',
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'municipio_cert_id' => NULL,
                'departamento_cert_id' => '1',
                'prm_certificado_id' => '235',
                'municipio_cond_id' => '1',
                'departamento_cond_id' => '1',
                'prm_condicion_id' => '853',
                'csd_id' => '96',
                'id' => '96',
            ),
            95 => 
            array (
                'updated_at' => '2021-05-18 18:46:36',
                'created_at' => '2021-05-18 18:46:36',
                'prm_tipofuen_id' => '2315',
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'municipio_cert_id' => '231',
                'departamento_cert_id' => '6',
                'prm_certificado_id' => '227',
                'municipio_cond_id' => '71',
                'departamento_cond_id' => '10',
                'prm_condicion_id' => '454',
                'csd_id' => '94',
                'id' => '94',
            ),
        ));
        
        
    }
}