<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FiVestuarioNnajsTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('fi_vestuario_nnajs')->delete();
        
        \DB::table('fi_vestuario_nnajs')->insert(array (
            0 => 
            array (
                'updated_at' => '2021-05-11 10:29:04',
                'created_at' => '2021-05-11 10:29:04',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1274',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '56',
                'prm_t_camisa_id' => '702',
                'prm_t_pantalon_id' => '54',
                'user_edita_id' => '2067',
                'user_crea_id' => '2067',
                'id' => '1',
            ),
            1 => 
            array (
                'updated_at' => '2021-05-11 11:28:31',
                'created_at' => '2021-05-11 11:28:31',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1277',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '7',
            ),
            2 => 
            array (
                'updated_at' => '2021-05-12 07:38:26',
                'created_at' => '2021-05-12 07:38:26',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1278',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '698',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '48',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'id' => '10',
            ),
            3 => 
            array (
                'updated_at' => '2021-05-12 13:11:02',
                'created_at' => '2021-05-12 13:11:02',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1294',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '58',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '50',
                'user_edita_id' => '2067',
                'user_crea_id' => '2067',
                'id' => '11',
            ),
            4 => 
            array (
                'updated_at' => '2021-06-01 14:19:35',
                'created_at' => '2021-06-01 14:19:35',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1595',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '48',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '25',
            ),
            5 => 
            array (
                'updated_at' => '2021-05-17 14:30:37',
                'created_at' => '2021-05-17 14:30:37',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1397',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '56',
                'prm_t_camisa_id' => '701',
                'prm_t_pantalon_id' => '50',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '13',
            ),
            6 => 
            array (
                'updated_at' => '2021-06-03 10:19:39',
                'created_at' => '2021-06-03 10:19:39',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1708',
                'prm_sexo_etario_id' => '707',
                'prm_t_zapato_id' => '48',
                'prm_t_camisa_id' => '518',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'id' => '29',
            ),
            7 => 
            array (
                'updated_at' => '2021-05-11 11:28:28',
                'created_at' => '2021-05-11 11:28:28',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1277',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '4',
            ),
            8 => 
            array (
                'updated_at' => '2021-05-11 11:28:30',
                'created_at' => '2021-05-11 11:28:30',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1277',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '5',
            ),
            9 => 
            array (
                'updated_at' => '2021-05-11 11:28:32',
                'created_at' => '2021-05-11 11:28:32',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1277',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '9',
            ),
            10 => 
            array (
                'updated_at' => '2021-05-19 10:41:45',
                'created_at' => '2021-05-19 10:41:45',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1420',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '56',
                'prm_t_camisa_id' => '701',
                'prm_t_pantalon_id' => '54',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '16',
            ),
            11 => 
            array (
                'updated_at' => '2021-05-19 12:28:38',
                'created_at' => '2021-05-19 12:28:38',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1421',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '56',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '697',
                'user_edita_id' => '2067',
                'user_crea_id' => '2067',
                'id' => '18',
            ),
            12 => 
            array (
                'updated_at' => '2021-06-01 11:38:18',
                'created_at' => '2021-06-01 11:38:18',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1586',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '56',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '36',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '22',
            ),
            13 => 
            array (
                'updated_at' => '2021-06-01 17:23:12',
                'created_at' => '2021-06-01 17:23:12',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1599',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '698',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '697',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '27',
            ),
            14 => 
            array (
                'updated_at' => '2021-06-01 17:50:56',
                'created_at' => '2021-06-01 17:50:56',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1565',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '53',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '302',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'id' => '28',
            ),
            15 => 
            array (
                'updated_at' => '2021-05-11 11:28:31',
                'created_at' => '2021-05-11 11:28:31',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1277',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '6',
            ),
            16 => 
            array (
                'updated_at' => '2021-05-18 09:43:10',
                'created_at' => '2021-05-18 09:43:10',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1151',
                'prm_sexo_etario_id' => '707',
                'prm_t_zapato_id' => '49',
                'prm_t_camisa_id' => '38',
                'prm_t_pantalon_id' => '34',
                'user_edita_id' => '1572',
                'user_crea_id' => '1572',
                'id' => '14',
            ),
            17 => 
            array (
                'updated_at' => '2021-05-20 18:05:34',
                'created_at' => '2021-05-20 18:05:34',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1430',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '699',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '50',
                'user_edita_id' => '2090',
                'user_crea_id' => '2090',
                'id' => '19',
            ),
            18 => 
            array (
                'updated_at' => '2021-05-31 11:44:09',
                'created_at' => '2021-05-31 11:44:09',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '116',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '53',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '50',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'id' => '20',
            ),
            19 => 
            array (
                'updated_at' => '2021-06-01 11:38:13',
                'created_at' => '2021-06-01 11:38:13',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1586',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '56',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '36',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '21',
            ),
            20 => 
            array (
                'updated_at' => '2021-06-01 11:38:19',
                'created_at' => '2021-06-01 11:38:19',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1586',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '56',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '36',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '23',
            ),
            21 => 
            array (
                'updated_at' => '2021-05-11 11:28:25',
                'created_at' => '2021-05-11 11:28:25',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1277',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '2',
            ),
            22 => 
            array (
                'updated_at' => '2021-05-11 11:28:27',
                'created_at' => '2021-05-11 11:28:27',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1277',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '3',
            ),
            23 => 
            array (
                'updated_at' => '2021-05-11 11:28:32',
                'created_at' => '2021-05-11 11:28:32',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1277',
                'prm_sexo_etario_id' => '705',
                'prm_t_zapato_id' => '55',
                'prm_t_camisa_id' => '138',
                'prm_t_pantalon_id' => '518',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '8',
            ),
            24 => 
            array (
                'updated_at' => '2021-05-12 15:45:28',
                'created_at' => '2021-05-12 15:45:28',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1304',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '698',
                'prm_t_camisa_id' => '701',
                'prm_t_pantalon_id' => '697',
                'user_edita_id' => '2067',
                'user_crea_id' => '2067',
                'id' => '12',
            ),
            25 => 
            array (
                'updated_at' => '2021-05-18 14:58:20',
                'created_at' => '2021-05-18 14:58:20',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1412',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '54',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '48',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'id' => '15',
            ),
            26 => 
            array (
                'updated_at' => '2021-05-19 10:41:47',
                'created_at' => '2021-05-19 10:41:47',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1420',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '56',
                'prm_t_camisa_id' => '701',
                'prm_t_pantalon_id' => '54',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '17',
            ),
            27 => 
            array (
                'updated_at' => '2021-06-01 12:47:53',
                'created_at' => '2021-06-01 12:47:53',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1588',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '698',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '697',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '24',
            ),
            28 => 
            array (
                'updated_at' => '2021-06-01 14:45:30',
                'created_at' => '2021-06-01 14:45:30',
                'sis_esta_id' => '1',
                'sis_nnaj_id' => '1481',
                'prm_sexo_etario_id' => '505',
                'prm_t_zapato_id' => '698',
                'prm_t_camisa_id' => '93',
                'prm_t_pantalon_id' => '50',
                'user_edita_id' => '2045',
                'user_crea_id' => '2045',
                'id' => '26',
            ),
        ));
        
        
    }
}