<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VsiFacRiesgosTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vsi_fac_riesgos')->delete();
        
        \DB::table('vsi_fac_riesgos')->insert(array (
            0 => 
            array (
                'updated_at' => '2021-05-12 11:29:00',
                'created_at' => '2021-05-12 11:29:00',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'HABITABILIDAD CALLE',
                'vsi_id' => '334',
                'id' => '156',
            ),
            1 => 
            array (
                'updated_at' => '2021-05-12 11:29:16',
                'created_at' => '2021-05-12 11:29:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'PARES NEGATIVOS',
                'vsi_id' => '334',
                'id' => '157',
            ),
            2 => 
            array (
                'updated_at' => '2021-05-12 12:49:01',
                'created_at' => '2021-05-12 12:49:01',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '336',
                'id' => '159',
            ),
            3 => 
            array (
                'updated_at' => '2021-05-16 19:57:28',
                'created_at' => '2021-05-16 19:57:28',
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'riesgo' => 'DESESCOLARIZACIÓN',
                'vsi_id' => '337',
                'id' => '166',
            ),
            4 => 
            array (
                'updated_at' => '2021-05-16 19:58:27',
                'created_at' => '2021-05-16 19:58:27',
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '337',
                'id' => '167',
            ),
            5 => 
            array (
                'updated_at' => '2021-05-18 11:45:02',
                'created_at' => '2021-05-18 11:45:02',
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'riesgo' => 'SITUACIÓN ECONÓMICA',
                'vsi_id' => '339',
                'id' => '168',
            ),
            6 => 
            array (
                'updated_at' => '2021-06-02 10:11:30',
                'created_at' => '2021-06-02 10:11:30',
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'riesgo' => 'DESPLAZAMIENTO',
                'vsi_id' => '352',
                'id' => '183',
            ),
            7 => 
            array (
                'updated_at' => '2021-05-12 09:11:25',
                'created_at' => '2021-05-12 09:11:25',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'HABITABILIDAD CALLE',
                'vsi_id' => '332',
                'id' => '150',
            ),
            8 => 
            array (
                'updated_at' => '2021-05-12 09:11:58',
                'created_at' => '2021-05-12 09:11:58',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'CONSUMO SPA',
                'vsi_id' => '332',
                'id' => '152',
            ),
            9 => 
            array (
                'updated_at' => '2021-05-12 09:52:27',
                'created_at' => '2021-05-12 09:52:27',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'TRASLADO DE VIVIENDA POR SITUACIONES ECONOMICAS',
                'vsi_id' => '333',
                'id' => '154',
            ),
            10 => 
            array (
                'updated_at' => '2021-05-18 11:45:21',
                'created_at' => '2021-05-18 11:45:21',
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '339',
                'id' => '169',
            ),
            11 => 
            array (
                'updated_at' => '2021-05-18 11:45:41',
                'created_at' => '2021-05-18 11:45:41',
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'riesgo' => 'SIN REDES DE APOYO FAMILIARES',
                'vsi_id' => '339',
                'id' => '170',
            ),
            12 => 
            array (
                'updated_at' => '2021-06-02 15:54:52',
                'created_at' => '2021-06-02 15:54:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '355',
                'id' => '186',
            ),
            13 => 
            array (
                'updated_at' => '2021-06-02 16:42:19',
                'created_at' => '2021-06-02 16:42:19',
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'riesgo' => 'DESEMPLEO',
                'vsi_id' => '356',
                'id' => '188',
            ),
            14 => 
            array (
                'updated_at' => '2020-07-24 14:08:09',
                'created_at' => '2020-07-24 14:08:09',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'EJERCICIO DE PROSTITUCIÓN',
                'vsi_id' => '2',
                'id' => '1',
            ),
            15 => 
            array (
                'updated_at' => '2020-07-24 14:08:09',
                'created_at' => '2020-07-24 14:08:09',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO OCASIONAL DE SPA',
                'vsi_id' => '2',
                'id' => '2',
            ),
            16 => 
            array (
                'updated_at' => '2020-07-24 14:08:09',
                'created_at' => '2020-07-24 14:08:09',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INFLUENCIA DE PARES NEGATIVOS',
                'vsi_id' => '2',
                'id' => '3',
            ),
            17 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AMISTAD',
                'vsi_id' => '3',
                'id' => '4',
            ),
            18 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'STADO DE ANIMO BAJO',
                'vsi_id' => '3',
                'id' => '5',
            ),
            19 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DUELO NO ELABORADO',
                'vsi_id' => '4',
                'id' => '6',
            ),
            20 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO OCASIONAL DE SPA',
                'vsi_id' => '4',
                'id' => '7',
            ),
            21 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INCURSION EN CONTEXTOS DESFABORABLES',
                'vsi_id' => '4',
                'id' => '8',
            ),
            22 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '7',
                'id' => '9',
            ),
            23 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIF ECONOMICAS',
                'vsi_id' => '7',
                'id' => '10',
            ),
            24 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '12',
                'id' => '11',
            ),
            25 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '17',
                'id' => '12',
            ),
            26 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AUSENCIA DE REDES SOCIALES DE APOYO',
                'vsi_id' => '19',
                'id' => '13',
            ),
            27 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTES DE CONDUCTA SUICIDA',
                'vsi_id' => '20',
                'id' => '14',
            ),
            28 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '20',
                'id' => '15',
            ),
            29 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIFICULTADES FAMILIARES',
                'vsi_id' => '20',
                'id' => '16',
            ),
            30 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DESAPROVECHAMIENTO DE TIEMPO LIBRE',
                'vsi_id' => '20',
                'id' => '17',
            ),
            31 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'RIESGO DE VINCULACIÓN A ACTIVIDADES DELICTIVAS',
                'vsi_id' => '20',
                'id' => '18',
            ),
            32 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'FALTA DE OPORTUNIDADES',
                'vsi_id' => '25',
                'id' => '19',
            ),
            33 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'TIEMPO LIBRE',
                'vsi_id' => '34',
                'id' => '20',
            ),
            34 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACION ECONOMICA',
                'vsi_id' => '35',
                'id' => '21',
            ),
            35 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE PRESUNTO AS',
                'vsi_id' => '35',
                'id' => '22',
            ),
            36 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE CONSUMO DE SPA',
                'vsi_id' => '35',
                'id' => '23',
            ),
            37 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE FAMILIAR DE CONDUCTAS DELICTIVAS',
                'vsi_id' => '35',
                'id' => '24',
            ),
            38 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INFLUENCIA DE PARES NEGATIVOS',
                'vsi_id' => '37',
                'id' => '25',
            ),
            39 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE CONSUMO DE SPA',
                'vsi_id' => '39',
                'id' => '26',
            ),
            40 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '46',
                'id' => '27',
            ),
            41 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '46',
                'id' => '28',
            ),
            42 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AMIGOS',
                'vsi_id' => '48',
                'id' => '29',
            ),
            43 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO SOCIAL',
                'vsi_id' => '48',
                'id' => '30',
            ),
            44 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'NO AFILIACION A EPS',
                'vsi_id' => '49',
                'id' => '31',
            ),
            45 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AUSENCIA DE REDES SOCIALES DE APOYO',
                'vsi_id' => '49',
                'id' => '32',
            ),
            46 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '49',
                'id' => '33',
            ),
            47 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CALLE',
                'vsi_id' => '50',
                'id' => '34',
            ),
            48 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACION ECONOMICA',
                'vsi_id' => '51',
                'id' => '35',
            ),
            49 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE PRESUNTO AS',
                'vsi_id' => '51',
                'id' => '36',
            ),
            50 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE CONSUMO DE SPA',
                'vsi_id' => '51',
                'id' => '37',
            ),
            51 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DUELO NO ELABORADO',
                'vsi_id' => '51',
                'id' => '38',
            ),
            52 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECENDENTE PERSONAL DE SALUD MENTAL',
                'vsi_id' => '51',
                'id' => '39',
            ),
            53 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACION ECONOMICA',
                'vsi_id' => '52',
                'id' => '40',
            ),
            54 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE PRESUNTO AS',
                'vsi_id' => '52',
                'id' => '41',
            ),
            55 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE CONSUMO DE SPA',
                'vsi_id' => '52',
                'id' => '42',
            ),
            56 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DUELO NO ELABORADO',
                'vsi_id' => '52',
                'id' => '43',
            ),
            57 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECENDENTE PERSONAL DE SALUD MENTAL',
                'vsi_id' => '52',
                'id' => '44',
            ),
            58 => 
            array (
                'updated_at' => '2020-07-24 14:08:11',
                'created_at' => '2020-07-24 14:08:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIF ECONOMICAS',
                'vsi_id' => '58',
                'id' => '45',
            ),
            59 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACION ECONOMICA',
                'vsi_id' => '60',
                'id' => '46',
            ),
            60 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DESAPROVECHAMIENTO DE TIEMPO LIBRE',
                'vsi_id' => '70',
                'id' => '47',
            ),
            61 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '73',
                'id' => '48',
            ),
            62 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DESAPROVECHAMIENTO DE TIEMPO LIBRE',
                'vsi_id' => '75',
                'id' => '49',
            ),
            63 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIFICULTADES EN LAS RELACIONES FAMILIARES',
                'vsi_id' => '75',
                'id' => '50',
            ),
            64 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACION ECONOMICA',
                'vsi_id' => '80',
                'id' => '51',
            ),
            65 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INFLUENCIA DE PARES NEGATIVOS',
                'vsi_id' => '80',
                'id' => '52',
            ),
            66 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIF ECONOMICAS',
                'vsi_id' => '82',
                'id' => '53',
            ),
            67 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTES DE CONDUCTA SUICIDA',
                'vsi_id' => '98',
                'id' => '54',
            ),
            68 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DESAPROVECHAMIENTO DE TIEMPO LIBRE',
                'vsi_id' => '98',
                'id' => '55',
            ),
            69 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'FALTA DE OPORTUNIDADES LABORALES',
                'vsi_id' => '99',
                'id' => '56',
            ),
            70 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DUELO NO ELABORADO',
                'vsi_id' => '106',
                'id' => '57',
            ),
            71 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTES DE CONDUCTA SUICIDA',
                'vsi_id' => '106',
                'id' => '58',
            ),
            72 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIF ECONOMICAS',
                'vsi_id' => '106',
                'id' => '59',
            ),
            73 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DEFICIT DE HABILIDADES SOCIALES',
                'vsi_id' => '106',
                'id' => '60',
            ),
            74 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ASUME ROL PROTECTOR HACIA FAMILIA EXTENSA',
                'vsi_id' => '106',
                'id' => '61',
            ),
            75 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'VOLVER A SER CHC',
                'vsi_id' => '113',
                'id' => '62',
            ),
            76 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '113',
                'id' => '63',
            ),
            77 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIF ECONOMICAS',
                'vsi_id' => '137',
                'id' => '64',
            ),
            78 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'VOLVER A SER CHC',
                'vsi_id' => '139',
                'id' => '65',
            ),
            79 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AUMENTAR EL CONSUMO DE SPA',
                'vsi_id' => '139',
                'id' => '66',
            ),
            80 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '144',
                'id' => '67',
            ),
            81 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '144',
                'id' => '68',
            ),
            82 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DEPENDENCIA AFECTIVA',
                'vsi_id' => '146',
                'id' => '69',
            ),
            83 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO OCASIONAL DE SPA',
                'vsi_id' => '146',
                'id' => '70',
            ),
            84 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INFLUENCIA DE PARES NEGATIVOS',
                'vsi_id' => '146',
                'id' => '71',
            ),
            85 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIFICULTADES FAMILIARES',
                'vsi_id' => '151',
                'id' => '72',
            ),
            86 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '151',
                'id' => '73',
            ),
            87 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DESERCION ESCOLAR',
                'vsi_id' => '151',
                'id' => '74',
            ),
            88 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIFICULTADES FAMILIARES',
                'vsi_id' => '160',
                'id' => '75',
            ),
            89 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE HABITABILIDAD EN CALLE',
                'vsi_id' => '160',
                'id' => '76',
            ),
            90 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '176',
                'id' => '77',
            ),
            91 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DESAPROVECHAMIENTO DE TIEMPO LIBRE',
                'vsi_id' => '177',
                'id' => '78',
            ),
            92 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTES DE CONDUCTA SUICIDA',
                'vsi_id' => '177',
                'id' => '79',
            ),
            93 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO DE RIESGO DELICTIVO',
                'vsi_id' => '177',
                'id' => '80',
            ),
            94 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ALTAMENTE INFLUENCIABLE',
                'vsi_id' => '181',
                'id' => '81',
            ),
            95 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO OCASIONAL DE SPA',
                'vsi_id' => '181',
                'id' => '82',
            ),
            96 => 
            array (
                'updated_at' => '2020-07-24 14:08:12',
                'created_at' => '2020-07-24 14:08:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INCLUSIÓN EN CONTEXTOS DE USO SPA',
                'vsi_id' => '181',
                'id' => '83',
            ),
            97 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO OCASIONAL DE SPA',
                'vsi_id' => '181',
                'id' => '84',
            ),
            98 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DESAPROVECHAMIENTO DE TIEMPO LIBRE',
                'vsi_id' => '183',
                'id' => '85',
            ),
            99 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE CONSUMO DE SPA',
                'vsi_id' => '183',
                'id' => '86',
            ),
            100 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'EL BARRIO',
                'vsi_id' => '187',
                'id' => '87',
            ),
            101 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACION ECONOMICA',
                'vsi_id' => '195',
                'id' => '88',
            ),
            102 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE DE CONSUMO DE SPA Y HABITABILIDAD EN CALLE',
                'vsi_id' => '195',
                'id' => '89',
            ),
            103 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE FAMILIAR DE CONDUCTAS DELICTIVAS',
                'vsi_id' => '195',
                'id' => '90',
            ),
            104 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTE FAMILIAR DE PRIVACIÓN DE LA LIBERTAD',
                'vsi_id' => '195',
                'id' => '91',
            ),
            105 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'RELACIONES FAMILIARES CONFLICTIVAS',
                'vsi_id' => '195',
                'id' => '92',
            ),
            106 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIFICULTADES EMOCIONALES',
                'vsi_id' => '197',
                'id' => '93',
            ),
            107 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DUELO NO ELABORADO',
                'vsi_id' => '197',
                'id' => '94',
            ),
            108 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'HABITABILIDAD EN CALLE',
                'vsi_id' => '197',
                'id' => '95',
            ),
            109 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACIÓN DE VIOLENCIA',
                'vsi_id' => '199',
                'id' => '96',
            ),
            110 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'PRESUNTA APNEA DEL SUEÑO',
                'vsi_id' => '199',
                'id' => '97',
            ),
            111 => 
            array (
                'updated_at' => '2020-07-24 14:08:13',
                'created_at' => '2020-07-24 14:08:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACIÓN ECONOMICA PRECARIA',
                'vsi_id' => '199',
                'id' => '98',
            ),
            112 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ESCASAS REDES DE APOYO FAMILIAR',
                'vsi_id' => '199',
                'id' => '99',
            ),
            113 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTES DE CONDUCTA SUICIDA',
                'vsi_id' => '199',
                'id' => '100',
            ),
            114 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACION ECONOMICA',
                'vsi_id' => '200',
                'id' => '101',
            ),
            115 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'SITUACION ECONOMICA',
                'vsi_id' => '203',
                'id' => '102',
            ),
            116 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTETO FAMILIAR',
                'vsi_id' => '205',
                'id' => '103',
            ),
            117 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INCONVENIENTES FAMILIARES',
                'vsi_id' => '205',
                'id' => '104',
            ),
            118 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '206',
                'id' => '105',
            ),
            119 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '206',
                'id' => '106',
            ),
            120 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ANTECEDENTES DE CONSUMO Y CONDUCTAS DELICTIVAS',
                'vsi_id' => '206',
                'id' => '107',
            ),
            121 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO SOCIAL',
                'vsi_id' => '209',
                'id' => '108',
            ),
            122 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '233',
                'id' => '109',
            ),
            123 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'RIESGO DE CONDUCTA SUICIDA',
                'vsi_id' => '233',
                'id' => '110',
            ),
            124 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIFICULTADES FAMILIARES',
                'vsi_id' => '233',
                'id' => '111',
            ),
            125 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DESAPROVECHAMIENTO DE TIEMPO LIBRE',
                'vsi_id' => '233',
                'id' => '112',
            ),
            126 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INFLUENCIA DE PARES NEGATIVOS',
                'vsi_id' => '246',
                'id' => '113',
            ),
            127 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AMIGOS',
                'vsi_id' => '257',
                'id' => '114',
            ),
            128 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AMIGOS',
                'vsi_id' => '258',
                'id' => '115',
            ),
            129 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIF ECONOMICAS',
                'vsi_id' => '259',
                'id' => '116',
            ),
            130 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIFICULTADES EMOCIONALES',
                'vsi_id' => '259',
                'id' => '117',
            ),
            131 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'IDIPRON',
                'vsi_id' => '259',
                'id' => '118',
            ),
            132 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO SOCIAL- INFLUENCIA DE PARES',
                'vsi_id' => '263',
                'id' => '119',
            ),
            133 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE ALCOHOL',
                'vsi_id' => '263',
                'id' => '120',
            ),
            134 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'PERMISIVIDAD RELACIONADA CON CONSUMO',
                'vsi_id' => '263',
                'id' => '121',
            ),
            135 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIFICULTADES DE APRENDIZAJE',
                'vsi_id' => '268',
                'id' => '122',
            ),
            136 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '270',
                'id' => '123',
            ),
            137 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'VIVIR EN LA CALLE',
                'vsi_id' => '274',
                'id' => '124',
            ),
            138 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AUMENTAR EL CONSUMO DE SPA',
                'vsi_id' => '274',
                'id' => '125',
            ),
            139 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CORRER RIESGO FISICO Y MENTAL',
                'vsi_id' => '274',
                'id' => '126',
            ),
            140 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DX POR SALUD MENTAL "ESQUIZOFRENIA"',
                'vsi_id' => '278',
                'id' => '127',
            ),
            141 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'NO PRESENTA RED VINCULAR DE APOYO EN BOGOTA',
                'vsi_id' => '278',
                'id' => '128',
            ),
            142 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONDUCTAS AUTOLESIVAS',
                'vsi_id' => '286',
                'id' => '129',
            ),
            143 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INFLUENCIA DE PARES NEGATIVOS',
                'vsi_id' => '289',
                'id' => '130',
            ),
            144 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '289',
                'id' => '131',
            ),
            145 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INCLUSIÓN A CONTEXTOS INFAVORABLES',
                'vsi_id' => '296',
                'id' => '132',
            ),
            146 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DUELO NO ELABORADO',
                'vsi_id' => '296',
                'id' => '133',
            ),
            147 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO OCASIONAL DE SPA',
                'vsi_id' => '296',
                'id' => '134',
            ),
            148 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'PROYECTO DE VIDA SIN ESTRUCTURACIÓN',
                'vsi_id' => '297',
                'id' => '135',
            ),
            149 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'INFLUENCIA DE PARES NEGATIVOS',
                'vsi_id' => '301',
                'id' => '136',
            ),
            150 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '301',
                'id' => '137',
            ),
            151 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '301',
                'id' => '138',
            ),
            152 => 
            array (
                'updated_at' => '2020-07-24 14:08:14',
                'created_at' => '2020-07-24 14:08:14',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'PERDIDA DE UN SER QUERIDO -RECAIDA EN CONSUMO SPA',
                'vsi_id' => '304',
                'id' => '139',
            ),
            153 => 
            array (
                'updated_at' => '2020-07-24 14:08:15',
                'created_at' => '2020-07-24 14:08:15',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO DE BAZUCO',
                'vsi_id' => '307',
                'id' => '140',
            ),
            154 => 
            array (
                'updated_at' => '2020-07-24 14:08:15',
                'created_at' => '2020-07-24 14:08:15',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONDUCTAS AUTOLESIVAS',
                'vsi_id' => '307',
                'id' => '141',
            ),
            155 => 
            array (
                'updated_at' => '2020-07-24 14:08:15',
                'created_at' => '2020-07-24 14:08:15',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIF ECONOMICAS',
                'vsi_id' => '307',
                'id' => '142',
            ),
            156 => 
            array (
                'updated_at' => '2020-07-24 14:08:16',
                'created_at' => '2020-07-24 14:08:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'ACOMULACION DE ESTRÉS/ PROBLEMAS',
                'vsi_id' => '308',
                'id' => '143',
            ),
            157 => 
            array (
                'updated_at' => '2020-07-24 14:08:16',
                'created_at' => '2020-07-24 14:08:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'MAL IMPULSO/ NO CONTROLARME',
                'vsi_id' => '308',
                'id' => '144',
            ),
            158 => 
            array (
                'updated_at' => '2020-07-24 14:08:16',
                'created_at' => '2020-07-24 14:08:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'PERDER LAS GANAS DE LUCHAR',
                'vsi_id' => '308',
                'id' => '145',
            ),
            159 => 
            array (
                'updated_at' => '2020-07-24 14:08:16',
                'created_at' => '2020-07-24 14:08:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '316',
                'id' => '146',
            ),
            160 => 
            array (
                'updated_at' => '2020-07-24 14:08:16',
                'created_at' => '2020-07-24 14:08:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'DIF ECONOMICAS',
                'vsi_id' => '316',
                'id' => '147',
            ),
            161 => 
            array (
                'updated_at' => '2020-07-24 14:08:16',
                'created_at' => '2020-07-24 14:08:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'AUSENCIA DE REDES SOCIALES DE APOYO',
                'vsi_id' => '321',
                'id' => '148',
            ),
            162 => 
            array (
                'updated_at' => '2020-07-24 14:08:16',
                'created_at' => '2020-07-24 14:08:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'riesgo' => 'CONSUMO',
                'vsi_id' => '321',
                'id' => '149',
            ),
            163 => 
            array (
                'updated_at' => '2021-05-12 09:51:44',
                'created_at' => '2021-05-12 09:51:44',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'FALTA DE RECURSOS ECONOMICOS',
                'vsi_id' => '333',
                'id' => '153',
            ),
            164 => 
            array (
                'updated_at' => '2021-05-12 09:52:58',
                'created_at' => '2021-05-12 09:52:58',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '333',
                'id' => '155',
            ),
            165 => 
            array (
                'updated_at' => '2021-05-12 12:48:46',
                'created_at' => '2021-05-12 12:48:46',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'DIFICULTADES ECONOMICAS',
                'vsi_id' => '336',
                'id' => '158',
            ),
            166 => 
            array (
                'updated_at' => '2021-05-12 13:02:26',
                'created_at' => '2021-05-12 13:02:26',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'AMENAZAS CONTRA SU VIDA',
                'vsi_id' => '335',
                'id' => '160',
            ),
            167 => 
            array (
                'updated_at' => '2021-05-12 13:02:52',
                'created_at' => '2021-05-12 13:02:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'BAJA CORRESPONSABILIDAD DEL PROGENITOR',
                'vsi_id' => '335',
                'id' => '161',
            ),
            168 => 
            array (
                'updated_at' => '2021-05-12 13:03:17',
                'created_at' => '2021-05-12 13:03:17',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'CONSUMO SPA',
                'vsi_id' => '335',
                'id' => '162',
            ),
            169 => 
            array (
                'updated_at' => '2021-05-12 13:03:58',
                'created_at' => '2021-05-12 13:03:58',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'DINAMICA CONFLICTIVA',
                'vsi_id' => '335',
                'id' => '163',
            ),
            170 => 
            array (
                'updated_at' => '2021-05-15 20:13:09',
                'created_at' => '2021-05-15 20:13:09',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'HABITABILIDAD CALLE',
                'vsi_id' => '338',
                'id' => '164',
            ),
            171 => 
            array (
                'updated_at' => '2021-05-15 20:13:35',
                'created_at' => '2021-05-15 20:13:35',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'CONSUMO SPA',
                'vsi_id' => '338',
                'id' => '165',
            ),
            172 => 
            array (
                'updated_at' => '2021-05-20 16:47:12',
                'created_at' => '2021-05-20 16:47:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'FALTA DE APORTUNIDADES LABORALES',
                'vsi_id' => '343',
                'id' => '173',
            ),
            173 => 
            array (
                'updated_at' => '2021-05-25 09:29:07',
                'created_at' => '2021-05-25 09:29:07',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'CONSUMO DE SPA',
                'vsi_id' => '348',
                'id' => '175',
            ),
            174 => 
            array (
                'updated_at' => '2021-05-25 09:29:32',
                'created_at' => '2021-05-25 09:29:32',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'DIFICULTADES FAMILIARES',
                'vsi_id' => '348',
                'id' => '176',
            ),
            175 => 
            array (
                'updated_at' => '2021-05-25 09:30:03',
                'created_at' => '2021-05-25 09:30:03',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'PRESUNTA NEGLIGENCIA POR PROGENITORES',
                'vsi_id' => '348',
                'id' => '177',
            ),
            176 => 
            array (
                'updated_at' => '2021-05-25 21:33:04',
                'created_at' => '2021-05-25 21:33:04',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'riesgo' => 'FAMILIA NO PROTECTORA',
                'vsi_id' => '349',
                'id' => '178',
            ),
            177 => 
            array (
                'updated_at' => '2021-05-25 21:33:23',
                'created_at' => '2021-05-25 21:33:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'riesgo' => 'CONSUMO DE SPA',
                'vsi_id' => '349',
                'id' => '179',
            ),
            178 => 
            array (
                'updated_at' => '2021-05-25 21:34:04',
                'created_at' => '2021-05-25 21:34:04',
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'riesgo' => 'CARENCIA DE REDES DE APOYO',
                'vsi_id' => '349',
                'id' => '180',
            ),
            179 => 
            array (
                'updated_at' => '2021-05-28 19:09:20',
                'created_at' => '2021-05-28 19:09:20',
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '344',
                'id' => '181',
            ),
            180 => 
            array (
                'updated_at' => '2021-05-28 19:10:08',
                'created_at' => '2021-05-28 19:10:08',
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'riesgo' => 'DIFICULTADES ECONOMICAS',
                'vsi_id' => '344',
                'id' => '182',
            ),
            181 => 
            array (
                'updated_at' => '2021-06-02 10:12:13',
                'created_at' => '2021-06-02 10:12:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'riesgo' => 'POSIBLE NEGLIGENCIA POR PARTE PROGENITORA BIOLOGICA',
                'vsi_id' => '352',
                'id' => '184',
            ),
            182 => 
            array (
                'updated_at' => '2021-06-02 15:54:24',
                'created_at' => '2021-06-02 15:54:24',
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'riesgo' => 'PARES NEGATIVOS',
                'vsi_id' => '355',
                'id' => '185',
            ),
            183 => 
            array (
                'updated_at' => '2021-05-12 09:11:45',
                'created_at' => '2021-05-12 09:11:45',
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'riesgo' => 'CONDUCTAS DELICITIVAS',
                'vsi_id' => '332',
                'id' => '151',
            ),
            184 => 
            array (
                'updated_at' => '2021-05-18 17:08:09',
                'created_at' => '2021-05-18 17:08:09',
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '341',
                'id' => '171',
            ),
            185 => 
            array (
                'updated_at' => '2021-05-20 16:46:49',
                'created_at' => '2021-05-20 16:46:49',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'FALTA DE OPORTUNIDADES ACADEMICAS',
                'vsi_id' => '343',
                'id' => '172',
            ),
            186 => 
            array (
                'updated_at' => '2021-05-20 16:47:35',
                'created_at' => '2021-05-20 16:47:35',
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'riesgo' => 'CONTEXTO BARRIAL',
                'vsi_id' => '343',
                'id' => '174',
            ),
            187 => 
            array (
                'updated_at' => '2021-06-02 16:42:03',
                'created_at' => '2021-06-02 16:42:03',
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'riesgo' => 'CONSUMO DE SPA',
                'vsi_id' => '356',
                'id' => '187',
            ),
        ));
        
        
    }
}