<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VsiGeningLaborTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vsi_gening_labor')->delete();
        
        \DB::table('vsi_gening_labor')->insert(array (
            0 => 
            array (
                'sys_nc00011$' => '338',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_geningreso_id' => '338',
                'parametro_id' => '627',
                'id' => '53',
            ),
            1 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_geningreso_id' => '335',
                'parametro_id' => '626',
                'id' => '48',
            ),
            2 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_geningreso_id' => '335',
                'parametro_id' => '627',
                'id' => '49',
            ),
            3 => 
            array (
                'sys_nc00011$' => '346',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_geningreso_id' => '346',
                'parametro_id' => '627',
                'id' => '62',
            ),
            4 => 
            array (
                'sys_nc00011$' => '337',
                'sys_nc00010$' => '628',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_geningreso_id' => '337',
                'parametro_id' => '628',
                'id' => '52',
            ),
            5 => 
            array (
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_geningreso_id' => '341',
                'parametro_id' => '626',
                'id' => '56',
            ),
            6 => 
            array (
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_geningreso_id' => '341',
                'parametro_id' => '627',
                'id' => '57',
            ),
            7 => 
            array (
                'sys_nc00011$' => '345',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_geningreso_id' => '345',
                'parametro_id' => '627',
                'id' => '61',
            ),
            8 => 
            array (
                'sys_nc00011$' => '349',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_geningreso_id' => '349',
                'parametro_id' => '627',
                'id' => '65',
            ),
            9 => 
            array (
                'sys_nc00011$' => '7',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '7',
                'parametro_id' => '627',
                'id' => '1',
            ),
            10 => 
            array (
                'sys_nc00011$' => '12',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '12',
                'parametro_id' => '627',
                'id' => '2',
            ),
            11 => 
            array (
                'sys_nc00011$' => '17',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '17',
                'parametro_id' => '627',
                'id' => '3',
            ),
            12 => 
            array (
                'sys_nc00011$' => '19',
                'sys_nc00010$' => '1542',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '19',
                'parametro_id' => '1542',
                'id' => '4',
            ),
            13 => 
            array (
                'sys_nc00011$' => '20',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '20',
                'parametro_id' => '626',
                'id' => '5',
            ),
            14 => 
            array (
                'sys_nc00011$' => '25',
                'sys_nc00010$' => '628',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '25',
                'parametro_id' => '628',
                'id' => '6',
            ),
            15 => 
            array (
                'sys_nc00011$' => '35',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '35',
                'parametro_id' => '627',
                'id' => '7',
            ),
            16 => 
            array (
                'sys_nc00011$' => '37',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '37',
                'parametro_id' => '626',
                'id' => '8',
            ),
            17 => 
            array (
                'sys_nc00011$' => '39',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '39',
                'parametro_id' => '626',
                'id' => '9',
            ),
            18 => 
            array (
                'sys_nc00011$' => '46',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '46',
                'parametro_id' => '627',
                'id' => '10',
            ),
            19 => 
            array (
                'sys_nc00011$' => '48',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '48',
                'parametro_id' => '626',
                'id' => '11',
            ),
            20 => 
            array (
                'sys_nc00011$' => '50',
                'sys_nc00010$' => '628',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '50',
                'parametro_id' => '628',
                'id' => '12',
            ),
            21 => 
            array (
                'sys_nc00011$' => '51',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '51',
                'parametro_id' => '627',
                'id' => '13',
            ),
            22 => 
            array (
                'sys_nc00011$' => '52',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '52',
                'parametro_id' => '627',
                'id' => '14',
            ),
            23 => 
            array (
                'sys_nc00011$' => '58',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '58',
                'parametro_id' => '626',
                'id' => '15',
            ),
            24 => 
            array (
                'sys_nc00011$' => '60',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '60',
                'parametro_id' => '626',
                'id' => '16',
            ),
            25 => 
            array (
                'sys_nc00011$' => '70',
                'sys_nc00010$' => '628',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '70',
                'parametro_id' => '628',
                'id' => '17',
            ),
            26 => 
            array (
                'sys_nc00011$' => '73',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '73',
                'parametro_id' => '627',
                'id' => '18',
            ),
            27 => 
            array (
                'sys_nc00011$' => '75',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '75',
                'parametro_id' => '626',
                'id' => '19',
            ),
            28 => 
            array (
                'sys_nc00011$' => '80',
                'sys_nc00010$' => '1851',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '80',
                'parametro_id' => '1851',
                'id' => '20',
            ),
            29 => 
            array (
                'sys_nc00011$' => '87',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '87',
                'parametro_id' => '626',
                'id' => '21',
            ),
            30 => 
            array (
                'sys_nc00011$' => '98',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '98',
                'parametro_id' => '626',
                'id' => '22',
            ),
            31 => 
            array (
                'sys_nc00011$' => '99',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '99',
                'parametro_id' => '626',
                'id' => '23',
            ),
            32 => 
            array (
                'sys_nc00011$' => '106',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '106',
                'parametro_id' => '627',
                'id' => '24',
            ),
            33 => 
            array (
                'sys_nc00011$' => '137',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '137',
                'parametro_id' => '626',
                'id' => '25',
            ),
            34 => 
            array (
                'sys_nc00011$' => '141',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '141',
                'parametro_id' => '626',
                'id' => '26',
            ),
            35 => 
            array (
                'sys_nc00011$' => '144',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '144',
                'parametro_id' => '626',
                'id' => '27',
            ),
            36 => 
            array (
                'sys_nc00011$' => '151',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '151',
                'parametro_id' => '627',
                'id' => '28',
            ),
            37 => 
            array (
                'sys_nc00011$' => '176',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '176',
                'parametro_id' => '627',
                'id' => '29',
            ),
            38 => 
            array (
                'sys_nc00011$' => '177',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '177',
                'parametro_id' => '627',
                'id' => '30',
            ),
            39 => 
            array (
                'sys_nc00011$' => '183',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '183',
                'parametro_id' => '627',
                'id' => '31',
            ),
            40 => 
            array (
                'sys_nc00011$' => '200',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '200',
                'parametro_id' => '626',
                'id' => '32',
            ),
            41 => 
            array (
                'sys_nc00011$' => '205',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '205',
                'parametro_id' => '626',
                'id' => '33',
            ),
            42 => 
            array (
                'sys_nc00011$' => '209',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '209',
                'parametro_id' => '627',
                'id' => '34',
            ),
            43 => 
            array (
                'sys_nc00011$' => '233',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '233',
                'parametro_id' => '626',
                'id' => '35',
            ),
            44 => 
            array (
                'sys_nc00011$' => '246',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '246',
                'parametro_id' => '626',
                'id' => '36',
            ),
            45 => 
            array (
                'sys_nc00011$' => '257',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '257',
                'parametro_id' => '626',
                'id' => '37',
            ),
            46 => 
            array (
                'sys_nc00011$' => '258',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '258',
                'parametro_id' => '626',
                'id' => '38',
            ),
            47 => 
            array (
                'sys_nc00011$' => '259',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '259',
                'parametro_id' => '627',
                'id' => '39',
            ),
            48 => 
            array (
                'sys_nc00011$' => '268',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '268',
                'parametro_id' => '627',
                'id' => '40',
            ),
            49 => 
            array (
                'sys_nc00011$' => '270',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '270',
                'parametro_id' => '627',
                'id' => '41',
            ),
            50 => 
            array (
                'sys_nc00011$' => '289',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '289',
                'parametro_id' => '627',
                'id' => '42',
            ),
            51 => 
            array (
                'sys_nc00011$' => '297',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '297',
                'parametro_id' => '626',
                'id' => '43',
            ),
            52 => 
            array (
                'sys_nc00011$' => '301',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_geningreso_id' => '301',
                'parametro_id' => '627',
                'id' => '44',
            ),
            53 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_geningreso_id' => '332',
                'parametro_id' => '627',
                'id' => '45',
            ),
            54 => 
            array (
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '628',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_geningreso_id' => '333',
                'parametro_id' => '628',
                'id' => '46',
            ),
            55 => 
            array (
                'sys_nc00011$' => '334',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_geningreso_id' => '334',
                'parametro_id' => '627',
                'id' => '47',
            ),
            56 => 
            array (
                'sys_nc00011$' => '336',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_geningreso_id' => '336',
                'parametro_id' => '627',
                'id' => '50',
            ),
            57 => 
            array (
                'sys_nc00011$' => '339',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'vsi_geningreso_id' => '339',
                'parametro_id' => '627',
                'id' => '54',
            ),
            58 => 
            array (
                'sys_nc00011$' => '340',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'vsi_geningreso_id' => '340',
                'parametro_id' => '853',
                'id' => '55',
            ),
            59 => 
            array (
                'sys_nc00011$' => '342',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_geningreso_id' => '342',
                'parametro_id' => '853',
                'id' => '58',
            ),
            60 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_geningreso_id' => '343',
                'parametro_id' => '853',
                'id' => '59',
            ),
            61 => 
            array (
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '626',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'vsi_geningreso_id' => '344',
                'parametro_id' => '626',
                'id' => '60',
            ),
            62 => 
            array (
                'sys_nc00011$' => '347',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'vsi_geningreso_id' => '347',
                'parametro_id' => '627',
                'id' => '63',
            ),
            63 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '627',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_geningreso_id' => '348',
                'parametro_id' => '627',
                'id' => '64',
            ),
        ));
        
        
    }
}