<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VsiNnajSocialTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vsi_nnaj_social')->delete();
        
        \DB::table('vsi_nnaj_social')->insert(array (
            0 => 
            array (
                'sys_nc00011$' => '352',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'vsi_id' => '352',
                'parametro_id' => '885',
                'id' => '64',
            ),
            1 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '348',
                'parametro_id' => '884',
                'id' => '60',
            ),
            2 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '887',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '348',
                'parametro_id' => '887',
                'id' => '61',
            ),
            3 => 
            array (
                'sys_nc00011$' => '356',
                'sys_nc00010$' => '2137',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_id' => '356',
                'parametro_id' => '2137',
                'id' => '67',
            ),
            4 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '332',
                'parametro_id' => '886',
                'id' => '39',
            ),
            5 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '888',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '332',
                'parametro_id' => '888',
                'id' => '40',
            ),
            6 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '1633',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '332',
                'parametro_id' => '1633',
                'id' => '41',
            ),
            7 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '2137',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '332',
                'parametro_id' => '2137',
                'id' => '42',
            ),
            8 => 
            array (
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '333',
                'parametro_id' => '884',
                'id' => '43',
            ),
            9 => 
            array (
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '333',
                'parametro_id' => '885',
                'id' => '44',
            ),
            10 => 
            array (
                'sys_nc00011$' => '355',
                'sys_nc00010$' => '2137',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_id' => '355',
                'parametro_id' => '2137',
                'id' => '66',
            ),
            11 => 
            array (
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_id' => '344',
                'parametro_id' => '885',
                'id' => '63',
            ),
            12 => 
            array (
                'sys_nc00011$' => '355',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_id' => '355',
                'parametro_id' => '886',
                'id' => '65',
            ),
            13 => 
            array (
                'sys_nc00011$' => '4',
                'sys_nc00010$' => '883',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '4',
                'parametro_id' => '883',
                'id' => '1',
            ),
            14 => 
            array (
                'sys_nc00011$' => '49',
                'sys_nc00010$' => '883',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '49',
                'parametro_id' => '883',
                'id' => '2',
            ),
            15 => 
            array (
                'sys_nc00011$' => '73',
                'sys_nc00010$' => '883',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '73',
                'parametro_id' => '883',
                'id' => '3',
            ),
            16 => 
            array (
                'sys_nc00011$' => '160',
                'sys_nc00010$' => '883',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '160',
                'parametro_id' => '883',
                'id' => '4',
            ),
            17 => 
            array (
                'sys_nc00011$' => '181',
                'sys_nc00010$' => '883',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '181',
                'parametro_id' => '883',
                'id' => '5',
            ),
            18 => 
            array (
                'sys_nc00011$' => '197',
                'sys_nc00010$' => '883',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '197',
                'parametro_id' => '883',
                'id' => '6',
            ),
            19 => 
            array (
                'sys_nc00011$' => '316',
                'sys_nc00010$' => '883',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '316',
                'parametro_id' => '883',
                'id' => '7',
            ),
            20 => 
            array (
                'sys_nc00011$' => '2',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '2',
                'parametro_id' => '884',
                'id' => '8',
            ),
            21 => 
            array (
                'sys_nc00011$' => '48',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '48',
                'parametro_id' => '884',
                'id' => '9',
            ),
            22 => 
            array (
                'sys_nc00011$' => '51',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '51',
                'parametro_id' => '884',
                'id' => '10',
            ),
            23 => 
            array (
                'sys_nc00011$' => '151',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '151',
                'parametro_id' => '884',
                'id' => '11',
            ),
            24 => 
            array (
                'sys_nc00011$' => '160',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '160',
                'parametro_id' => '884',
                'id' => '12',
            ),
            25 => 
            array (
                'sys_nc00011$' => '177',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '177',
                'parametro_id' => '884',
                'id' => '13',
            ),
            26 => 
            array (
                'sys_nc00011$' => '205',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '205',
                'parametro_id' => '884',
                'id' => '14',
            ),
            27 => 
            array (
                'sys_nc00011$' => '233',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '233',
                'parametro_id' => '884',
                'id' => '15',
            ),
            28 => 
            array (
                'sys_nc00011$' => '289',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '289',
                'parametro_id' => '884',
                'id' => '16',
            ),
            29 => 
            array (
                'sys_nc00011$' => '316',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '316',
                'parametro_id' => '884',
                'id' => '17',
            ),
            30 => 
            array (
                'sys_nc00011$' => '146',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '146',
                'parametro_id' => '885',
                'id' => '18',
            ),
            31 => 
            array (
                'sys_nc00011$' => '209',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '209',
                'parametro_id' => '885',
                'id' => '19',
            ),
            32 => 
            array (
                'sys_nc00011$' => '246',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '246',
                'parametro_id' => '885',
                'id' => '20',
            ),
            33 => 
            array (
                'sys_nc00011$' => '296',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '296',
                'parametro_id' => '885',
                'id' => '21',
            ),
            34 => 
            array (
                'sys_nc00011$' => '2',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '2',
                'parametro_id' => '886',
                'id' => '22',
            ),
            35 => 
            array (
                'sys_nc00011$' => '35',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '35',
                'parametro_id' => '886',
                'id' => '23',
            ),
            36 => 
            array (
                'sys_nc00011$' => '146',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '146',
                'parametro_id' => '886',
                'id' => '24',
            ),
            37 => 
            array (
                'sys_nc00011$' => '181',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '181',
                'parametro_id' => '886',
                'id' => '25',
            ),
            38 => 
            array (
                'sys_nc00011$' => '296',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '296',
                'parametro_id' => '886',
                'id' => '26',
            ),
            39 => 
            array (
                'sys_nc00011$' => '301',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '301',
                'parametro_id' => '886',
                'id' => '27',
            ),
            40 => 
            array (
                'sys_nc00011$' => '2',
                'sys_nc00010$' => '888',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '2',
                'parametro_id' => '888',
                'id' => '28',
            ),
            41 => 
            array (
                'sys_nc00011$' => '4',
                'sys_nc00010$' => '888',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '4',
                'parametro_id' => '888',
                'id' => '29',
            ),
            42 => 
            array (
                'sys_nc00011$' => '141',
                'sys_nc00010$' => '888',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '141',
                'parametro_id' => '888',
                'id' => '30',
            ),
            43 => 
            array (
                'sys_nc00011$' => '233',
                'sys_nc00010$' => '888',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '233',
                'parametro_id' => '888',
                'id' => '31',
            ),
            44 => 
            array (
                'sys_nc00011$' => '20',
                'sys_nc00010$' => '1633',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '20',
                'parametro_id' => '1633',
                'id' => '32',
            ),
            45 => 
            array (
                'sys_nc00011$' => '113',
                'sys_nc00010$' => '1633',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '113',
                'parametro_id' => '1633',
                'id' => '33',
            ),
            46 => 
            array (
                'sys_nc00011$' => '177',
                'sys_nc00010$' => '1633',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '177',
                'parametro_id' => '1633',
                'id' => '34',
            ),
            47 => 
            array (
                'sys_nc00011$' => '233',
                'sys_nc00010$' => '1633',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '233',
                'parametro_id' => '1633',
                'id' => '35',
            ),
            48 => 
            array (
                'sys_nc00011$' => '176',
                'sys_nc00010$' => '2137',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '176',
                'parametro_id' => '2137',
                'id' => '36',
            ),
            49 => 
            array (
                'sys_nc00011$' => '205',
                'sys_nc00010$' => '2137',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '205',
                'parametro_id' => '2137',
                'id' => '37',
            ),
            50 => 
            array (
                'sys_nc00011$' => '270',
                'sys_nc00010$' => '2137',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:52',
                'created_at' => '2021-04-27 12:01:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '270',
                'parametro_id' => '2137',
                'id' => '38',
            ),
            51 => 
            array (
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'vsi_id' => '341',
                'parametro_id' => '884',
                'id' => '56',
            ),
            52 => 
            array (
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '1633',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'vsi_id' => '341',
                'parametro_id' => '1633',
                'id' => '57',
            ),
            53 => 
            array (
                'sys_nc00011$' => '337',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_id' => '337',
                'parametro_id' => '884',
                'id' => '51',
            ),
            54 => 
            array (
                'sys_nc00011$' => '337',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_id' => '337',
                'parametro_id' => '885',
                'id' => '52',
            ),
            55 => 
            array (
                'sys_nc00011$' => '334',
                'sys_nc00010$' => '886',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '334',
                'parametro_id' => '886',
                'id' => '47',
            ),
            56 => 
            array (
                'sys_nc00011$' => '339',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'vsi_id' => '339',
                'parametro_id' => '884',
                'id' => '53',
            ),
            57 => 
            array (
                'sys_nc00011$' => '339',
                'sys_nc00010$' => '885',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'vsi_id' => '339',
                'parametro_id' => '885',
                'id' => '54',
            ),
            58 => 
            array (
                'sys_nc00011$' => '339',
                'sys_nc00010$' => '2137',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'vsi_id' => '339',
                'parametro_id' => '2137',
                'id' => '55',
            ),
            59 => 
            array (
                'sys_nc00011$' => '349',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'vsi_id' => '349',
                'parametro_id' => '884',
                'id' => '62',
            ),
            60 => 
            array (
                'sys_nc00011$' => '336',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '336',
                'parametro_id' => '884',
                'id' => '48',
            ),
            61 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '884',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '343',
                'parametro_id' => '884',
                'id' => '58',
            ),
            62 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '2137',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '343',
                'parametro_id' => '2137',
                'id' => '59',
            ),
        ));
        
        
    }
}