<?php

namespace Database\Seeds;

use Illuminate\Database\Seeder;

class AgRecursosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ag_recursos')->delete();
        
        \DB::table('ag_recursos')->insert(array (
            0 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 21:29:56',
                'created_at' => '2021-05-04 21:29:56',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'DULCES',
                'id' => '1',
            ),
            1 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 21:46:49',
                'created_at' => '2021-05-04 21:29:59',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2605',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'GALLETAS',
                'id' => '2',
            ),
            2 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 21:47:26',
                'created_at' => '2021-05-04 21:47:26',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'PONQUES',
                'id' => '3',
            ),
            3 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 21:47:54',
                'created_at' => '2021-05-04 21:47:54',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2605',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'PAPAS FRITAS',
                'id' => '4',
            ),
            4 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 21:58:45',
                'created_at' => '2021-05-04 21:58:45',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'JUGO',
                'id' => '5',
            ),
            5 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 21:59:25',
                'created_at' => '2021-05-04 21:59:25',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'LECHE',
                'id' => '6',
            ),
            6 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:00:04',
                'created_at' => '2021-05-04 22:00:04',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'CHOCORRAMO',
                'id' => '7',
            ),
            7 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:00:29',
                'created_at' => '2021-05-04 22:00:29',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'GALA',
                'id' => '8',
            ),
            8 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:00:55',
                'created_at' => '2021-05-04 22:00:55',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'HERPO',
                'id' => '9',
            ),
            9 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:01:20',
                'created_at' => '2021-05-04 22:01:20',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'BOCADILLO',
                'id' => '10',
            ),
            10 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:01:43',
                'created_at' => '2021-05-04 22:01:43',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'ALMUERZO',
                'id' => '11',
            ),
            11 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:02:05',
                'created_at' => '2021-05-04 22:02:05',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'SANDWICH',
                'id' => '12',
            ),
            12 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:02:27',
                'created_at' => '2021-05-04 22:02:27',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'MANTEC ADA',
                'id' => '13',
            ),
            13 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:03:48',
                'created_at' => '2021-05-04 22:03:48',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'PAN',
                'id' => '14',
            ),
            14 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:04:11',
                'created_at' => '2021-05-04 22:04:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'NARANJA',
                'id' => '15',
            ),
            15 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:04:33',
                'created_at' => '2021-05-04 22:04:33',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'MANDARINA',
                'id' => '16',
            ),
            16 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:04:56',
                'created_at' => '2021-05-04 22:04:56',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'PERA',
                'id' => '17',
            ),
            17 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:05:21',
                'created_at' => '2021-05-04 22:05:21',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'CENA',
                'id' => '18',
            ),
            18 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:05:45',
                'created_at' => '2021-05-04 22:05:45',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'DESAYUNO',
                'id' => '19',
            ),
            19 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:06:07',
                'created_at' => '2021-05-04 22:06:07',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'MERIENDA',
                'id' => '20',
            ),
            20 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:06:48',
                'created_at' => '2021-05-04 22:06:48',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'MANZANA',
                'id' => '21',
            ),
            21 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:08:04',
                'created_at' => '2021-05-04 22:08:04',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1687',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'CHOCOLATE',
                'id' => '22',
            ),
            22 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:11:48',
                'created_at' => '2021-05-04 22:11:48',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2606',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'DULCES',
                'id' => '23',
            ),
            23 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:12:15',
                'created_at' => '2021-05-04 22:12:15',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2606',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'COLOMBINAS',
                'id' => '24',
            ),
            24 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:14:44',
                'created_at' => '2021-05-04 22:14:44',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2607',
                'i_prm_trecurso_id' => '1768',
                's_recurso' => 'GASEOSA',
                'id' => '25',
            ),
            25 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:18:10',
                'created_at' => '2021-05-04 22:18:10',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'VIDEO BEAM',
                'id' => '26',
            ),
            26 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:18:37',
                'created_at' => '2021-05-04 22:18:37',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'PORTATIL',
                'id' => '27',
            ),
            27 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:19:02',
                'created_at' => '2021-05-04 22:19:02',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'TELEVISOR',
                'id' => '28',
            ),
            28 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:19:26',
                'created_at' => '2021-05-04 22:19:26',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'DVD',
                'id' => '29',
            ),
            29 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:20:08',
                'created_at' => '2021-05-04 22:20:08',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'SONIDO',
                'id' => '30',
            ),
            30 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:20:35',
                'created_at' => '2021-05-04 22:20:35',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'COMPUTADOR',
                'id' => '31',
            ),
            31 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:21:03',
                'created_at' => '2021-05-04 22:21:03',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'CELULAR',
                'id' => '32',
            ),
            32 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:21:28',
                'created_at' => '2021-05-04 22:21:28',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'TABLET',
                'id' => '33',
            ),
            33 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:22:33',
                'created_at' => '2021-05-04 22:22:33',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'CAMAS',
                'id' => '34',
            ),
            34 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:23:01',
                'created_at' => '2021-05-04 22:23:01',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'COMODAS',
                'id' => '35',
            ),
            35 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:23:24',
                'created_at' => '2021-05-04 22:23:24',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'CUBIERTOS',
                'id' => '36',
            ),
            36 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:24:10',
                'created_at' => '2021-05-04 22:24:10',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'CANECAS AMARILLAS',
                'id' => '37',
            ),
            37 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:24:34',
                'created_at' => '2021-05-04 22:24:34',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'CANECAS VERDES',
                'id' => '38',
            ),
            38 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:24:59',
                'created_at' => '2021-05-04 22:24:59',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'CANECAS AZULES',
                'id' => '39',
            ),
            39 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:25:23',
                'created_at' => '2021-05-04 22:25:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'CANECAS ROJAS',
                'id' => '40',
            ),
            40 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:25:49',
                'created_at' => '2021-05-04 22:25:49',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'TOALLAS',
                'id' => '41',
            ),
            41 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:26:20',
                'created_at' => '2021-05-04 22:26:20',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'CHANCLAS',
                'id' => '42',
            ),
            42 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:26:46',
                'created_at' => '2021-05-04 22:26:46',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'AZADÓN',
                'id' => '43',
            ),
            43 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:27:09',
                'created_at' => '2021-05-04 22:27:09',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'PALA',
                'id' => '44',
            ),
            44 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:27:33',
                'created_at' => '2021-05-04 22:27:33',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'PICA',
                'id' => '45',
            ),
            45 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:27:59',
                'created_at' => '2021-05-04 22:27:59',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'MANGUERA DE RIEGO',
                'id' => '46',
            ),
            46 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:28:23',
                'created_at' => '2021-05-04 22:28:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'RASTRILLO',
                'id' => '47',
            ),
            47 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:28:46',
                'created_at' => '2021-05-04 22:28:46',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'CARRETILLA',
                'id' => '48',
            ),
            48 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:32:31',
                'created_at' => '2021-05-04 22:32:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2609',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'ABONOS ORGANICOS CASCARILLA',
                'id' => '49',
            ),
            49 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:33:08',
                'created_at' => '2021-05-04 22:33:08',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2609',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'ABONOS ORGANICOS GALLINAZA',
                'id' => '50',
            ),
            50 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:33:45',
                'created_at' => '2021-05-04 22:33:45',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2610',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'ABONOS ORGANICOS CASCARILLA',
                'id' => '51',
            ),
            51 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:34:12',
                'created_at' => '2021-05-04 22:34:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2610',
                'i_prm_trecurso_id' => '1764',
                's_recurso' => 'ABONOS ORGANICOS GALLINAZA',
                'id' => '52',
            ),
            52 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:35:23',
                'created_at' => '2021-05-04 22:35:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'TÉMPERAS',
                'id' => '53',
            ),
            53 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:35:53',
                'created_at' => '2021-05-04 22:35:53',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PAPEL ORIGAMI',
                'id' => '54',
            ),
            54 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:36:19',
                'created_at' => '2021-05-04 22:36:19',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'MARCADOR',
                'id' => '55',
            ),
            55 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:36:58',
                'created_at' => '2021-05-04 22:36:58',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'LAPIZ',
                'id' => '56',
            ),
            56 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:37:37',
                'created_at' => '2021-05-04 22:37:37',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'TEMPERA',
                'id' => '57',
            ),
            57 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:38:21',
                'created_at' => '2021-05-04 22:38:21',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PINTUCARITA',
                'id' => '58',
            ),
            58 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:38:55',
                'created_at' => '2021-05-04 22:38:55',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'VINILO',
                'id' => '59',
            ),
            59 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:39:26',
                'created_at' => '2021-05-04 22:39:26',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PINCEL',
                'id' => '60',
            ),
            60 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:40:00',
                'created_at' => '2021-05-04 22:40:00',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'LAPIZ DE COLOR',
                'id' => '61',
            ),
            61 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:40:37',
                'created_at' => '2021-05-04 22:40:37',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'COPIA DE JUEGO DIDACTICO',
                'id' => '62',
            ),
            62 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:41:06',
                'created_at' => '2021-05-04 22:41:06',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'RESALTADOR',
                'id' => '63',
            ),
            63 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:41:53',
                'created_at' => '2021-05-04 22:41:53',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'CRAYOLA',
                'id' => '64',
            ),
            64 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:42:23',
                'created_at' => '2021-05-04 22:42:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'ESFERO',
                'id' => '65',
            ),
            65 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:42:59',
                'created_at' => '2021-05-04 22:42:59',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1766',
                's_recurso' => 'PAPEL BOND CARTA',
                'id' => '66',
            ),
            66 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:43:29',
                'created_at' => '2021-05-04 22:43:29',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PAPEL BOND OFICIO',
                'id' => '67',
            ),
            67 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:45:57',
                'created_at' => '2021-05-04 22:45:57',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'COLBON',
                'id' => '68',
            ),
            68 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:46:25',
                'created_at' => '2021-05-04 22:46:25',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PEGASTIC',
                'id' => '69',
            ),
            69 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:46:51',
                'created_at' => '2021-05-04 22:46:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'CLIP',
                'id' => '70',
            ),
            70 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:47:46',
                'created_at' => '2021-05-04 22:47:46',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'TIJERAS',
                'id' => '71',
            ),
            71 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:48:23',
                'created_at' => '2021-05-04 22:48:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'REGLA',
                'id' => '72',
            ),
            72 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:48:55',
                'created_at' => '2021-05-04 22:48:55',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'TAJALAPIZ',
                'id' => '73',
            ),
            73 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:49:26',
                'created_at' => '2021-05-04 22:49:26',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'BORRADOR NATA',
                'id' => '74',
            ),
            74 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:49:54',
                'created_at' => '2021-05-04 22:49:54',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'HOJA MANDALA',
                'id' => '75',
            ),
            75 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:50:28',
                'created_at' => '2021-05-04 22:50:28',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'HOJA IRIS',
                'id' => '76',
            ),
            76 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:50:31',
                'created_at' => '2021-05-04 22:50:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'HOJA IRIS',
                'id' => '77',
            ),
            77 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:51:10',
                'created_at' => '2021-05-04 22:51:10',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'TABLERO ACRÍLICO',
                'id' => '78',
            ),
            78 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:51:40',
                'created_at' => '2021-05-04 22:51:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'MARCADORES BORRABLES',
                'id' => '79',
            ),
            79 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-04 22:52:08',
                'created_at' => '2021-05-04 22:52:08',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'BORRADOR DE TABLERO',
                'id' => '80',
            ),
            80 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:41:51',
                'created_at' => '2021-05-18 21:41:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1769',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'CARTULINAS',
                'id' => '81',
            ),
            81 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:42:18',
                'created_at' => '2021-05-18 21:42:18',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1769',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PAPEL',
                'id' => '82',
            ),
            82 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:42:40',
                'created_at' => '2021-05-18 21:42:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1769',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PAPEL CRAFT',
                'id' => '83',
            ),
            83 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:42:59',
                'created_at' => '2021-05-18 21:42:59',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1769',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'FOMI',
                'id' => '84',
            ),
            84 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:44:04',
                'created_at' => '2021-05-18 21:44:04',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1769',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PAPEL CREPE',
                'id' => '85',
            ),
            85 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:44:30',
                'created_at' => '2021-05-18 21:44:30',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1769',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'PAPEL SEDA',
                'id' => '86',
            ),
            86 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:44:53',
                'created_at' => '2021-05-18 21:44:53',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2612',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'SPRAI',
                'id' => '87',
            ),
            87 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:45:19',
                'created_at' => '2021-05-18 21:45:19',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2615',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'CINTA ADHESIVA',
                'id' => '88',
            ),
            88 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:45:41',
                'created_at' => '2021-05-18 21:45:41',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2615',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'CINTA ENMASCARAR',
                'id' => '89',
            ),
            89 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:46:15',
                'created_at' => '2021-05-18 21:46:15',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2617',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'ICOPOR',
                'id' => '90',
            ),
            90 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:46:42',
                'created_at' => '2021-05-18 21:46:42',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1769',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'CARTULINA IRIS',
                'id' => '91',
            ),
            91 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:47:12',
                'created_at' => '2021-05-18 21:47:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2614',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'CARTULINA IRIS',
                'id' => '92',
            ),
            92 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:47:40',
                'created_at' => '2021-05-18 21:47:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'BROCHA',
                'id' => '93',
            ),
            93 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 21:48:10',
                'created_at' => '2021-05-18 21:48:10',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'RODILLO',
                'id' => '94',
            ),
            94 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:11:01',
                'created_at' => '2021-05-18 22:11:01',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2633',
                's_recurso' => 'BUS',
                'id' => '95',
            ),
            95 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:11:24',
                'created_at' => '2021-05-18 22:11:24',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2633',
                's_recurso' => 'CAMIONETA',
                'id' => '96',
            ),
            96 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:11:46',
                'created_at' => '2021-05-18 22:11:46',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2633',
                's_recurso' => 'VAN',
                'id' => '97',
            ),
            97 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:12:50',
                'created_at' => '2021-05-18 22:12:50',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2632',
                's_recurso' => 'LIRIOS',
                'id' => '98',
            ),
            98 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:13:37',
                'created_at' => '2021-05-18 22:13:37',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'GUITARRA',
                'id' => '99',
            ),
            99 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:14:02',
                'created_at' => '2021-05-18 22:14:02',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'GLOBO',
                'id' => '100',
            ),
            100 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:14:26',
                'created_at' => '2021-05-18 22:14:26',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'CINTAS',
                'id' => '101',
            ),
            101 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:14:53',
                'created_at' => '2021-05-18 22:14:53',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'SOMBRERO',
                'id' => '102',
            ),
            102 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:15:11',
                'created_at' => '2021-05-18 22:15:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO DE MESA',
                'id' => '103',
            ),
            103 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:15:32',
                'created_at' => '2021-05-18 22:15:32',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'FLAUTA',
                'id' => '104',
            ),
            104 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:15:55',
                'created_at' => '2021-05-18 22:15:55',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'MARACAS',
                'id' => '105',
            ),
            105 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:16:24',
                'created_at' => '2021-05-18 22:16:24',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'TAMBOR',
                'id' => '106',
            ),
            106 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:16:57',
                'created_at' => '2021-05-18 22:16:57',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'CARPAS',
                'id' => '107',
            ),
            107 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:17:19',
                'created_at' => '2021-05-18 22:17:19',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'SLEEPING',
                'id' => '108',
            ),
            108 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:17:44',
                'created_at' => '2021-05-18 22:17:44',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'COLCHONETA ALUMINIO',
                'id' => '109',
            ),
            109 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:18:07',
                'created_at' => '2021-05-18 22:18:07',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'COCINA CAMPING',
                'id' => '110',
            ),
            110 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:18:27',
                'created_at' => '2021-05-18 22:18:27',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'LINTERNA',
                'id' => '111',
            ),
            111 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:18:51',
                'created_at' => '2021-05-18 22:18:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'LAZOS',
                'id' => '112',
            ),
            112 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:19:12',
                'created_at' => '2021-05-18 22:19:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1681',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'CABUYA',
                'id' => '113',
            ),
            113 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:19:34',
                'created_at' => '2021-05-18 22:19:34',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'VESTUARIO',
                'id' => '114',
            ),
            114 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:19:53',
                'created_at' => '2021-05-18 22:19:53',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'TRAJES DE DANZA',
                'id' => '115',
            ),
            115 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:20:17',
                'created_at' => '2021-05-18 22:20:17',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1767',
                's_recurso' => 'BOMBAS R-12',
                'id' => '116',
            ),
            116 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:20:50',
                'created_at' => '2021-05-18 22:20:50',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'PELICULA',
                'id' => '117',
            ),
            117 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:21:11',
                'created_at' => '2021-05-18 22:21:11',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA AJEDREZ',
                'id' => '118',
            ),
            118 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:21:55',
                'created_at' => '2021-05-18 22:21:55',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA NAIPES O CARTAS',
                'id' => '119',
            ),
            119 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:22:33',
                'created_at' => '2021-05-18 22:22:33',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA MONOPOLY',
                'id' => '120',
            ),
            120 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:23:02',
                'created_at' => '2021-05-18 22:23:02',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA DOMINÓ',
                'id' => '121',
            ),
            121 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:23:26',
                'created_at' => '2021-05-18 22:23:26',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA ROMPECABEZAS',
                'id' => '122',
            ),
            122 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:23:47',
                'created_at' => '2021-05-18 22:23:47',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA BACKGAMMON',
                'id' => '123',
            ),
            123 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:24:10',
                'created_at' => '2021-05-18 22:24:10',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA DAMAS',
                'id' => '124',
            ),
            124 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:24:31',
                'created_at' => '2021-05-18 22:24:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA DAMAS CHINAS',
                'id' => '125',
            ),
            125 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:24:51',
                'created_at' => '2021-05-18 22:24:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA JENGA',
                'id' => '126',
            ),
            126 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:25:16',
                'created_at' => '2021-05-18 22:25:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2611',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'JUEGO MESA TWISTER',
                'id' => '127',
            ),
            127 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:27:18',
                'created_at' => '2021-05-18 22:27:18',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'BALONES',
                'id' => '128',
            ),
            128 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:27:38',
                'created_at' => '2021-05-18 22:27:38',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'BATES DE BASEBALL',
                'id' => '129',
            ),
            129 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:27:59',
                'created_at' => '2021-05-18 22:27:59',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'BALÓN DE FUTBOL',
                'id' => '130',
            ),
            130 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:28:18',
                'created_at' => '2021-05-18 22:28:18',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'BALÓN DE MICROFÙTBOL',
                'id' => '131',
            ),
            131 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:28:40',
                'created_at' => '2021-05-18 22:28:40',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'GORRO DE BAÑO',
                'id' => '132',
            ),
            132 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:29:02',
                'created_at' => '2021-05-18 22:29:02',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'PANTALONETA DE BAÑO',
                'id' => '133',
            ),
            133 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:30:13',
                'created_at' => '2021-05-18 22:30:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'BALÓN DE VOLEIBOL',
                'id' => '134',
            ),
            134 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:30:38',
                'created_at' => '2021-05-18 22:30:38',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'BALÓN DE BASQUETBALL',
                'id' => '135',
            ),
            135 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:30:57',
                'created_at' => '2021-05-18 22:30:57',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'FLOTADOR',
                'id' => '136',
            ),
            136 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:31:15',
                'created_at' => '2021-05-18 22:31:15',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'PETO',
                'id' => '137',
            ),
            137 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:31:38',
                'created_at' => '2021-05-18 22:31:38',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'CONO',
                'id' => '138',
            ),
            138 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:31:58',
                'created_at' => '2021-05-18 22:31:58',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'MALLA Y ARCO',
                'id' => '139',
            ),
            139 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:32:23',
                'created_at' => '2021-05-18 22:32:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'PITO',
                'id' => '140',
            ),
            140 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:32:41',
                'created_at' => '2021-05-18 22:32:41',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'TRAJE DE BAÑO',
                'id' => '141',
            ),
            141 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:33:02',
                'created_at' => '2021-05-18 22:33:02',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'ZAPATILLAS FUTBOL',
                'id' => '142',
            ),
            142 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:33:23',
                'created_at' => '2021-05-18 22:33:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'UNIFORME DEPORTIVO',
                'id' => '143',
            ),
            143 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:33:52',
                'created_at' => '2021-05-18 22:33:52',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1176',
                's_recurso' => 'AROS',
                'id' => '144',
            ),
            144 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:34:25',
                'created_at' => '2021-05-18 22:34:25',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2605',
                'i_prm_trecurso_id' => '1765',
                's_recurso' => 'BISUTERÍA',
                'id' => '145',
            ),
            145 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:35:17',
                'created_at' => '2021-05-18 22:35:17',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2605',
                'i_prm_trecurso_id' => '1765',
                's_recurso' => 'CHAQUIRAS',
                'id' => '146',
            ),
            146 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:35:48',
                'created_at' => '2021-05-18 22:35:48',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2616',
                'i_prm_trecurso_id' => '1765',
                's_recurso' => 'NAILON',
                'id' => '147',
            ),
            147 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:36:13',
                'created_at' => '2021-05-18 22:36:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2613',
                'i_prm_trecurso_id' => '1765',
                's_recurso' => 'LANA',
                'id' => '148',
            ),
            148 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:36:51',
                'created_at' => '2021-05-18 22:36:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '1765',
                's_recurso' => 'AGUJAS DE CROCHET',
                'id' => '149',
            ),
            149 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:37:20',
                'created_at' => '2021-05-18 22:37:20',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'PRESERVATIVOS',
                'id' => '150',
            ),
            150 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:37:41',
                'created_at' => '2021-05-18 22:37:41',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'MANTECA DE CACAO',
                'id' => '151',
            ),
            151 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:38:31',
                'created_at' => '2021-05-18 22:38:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'TAPABOCAS',
                'id' => '152',
            ),
            152 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:38:49',
                'created_at' => '2021-05-18 22:38:49',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'GUANTES',
                'id' => '153',
            ),
            153 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:39:19',
                'created_at' => '2021-05-18 22:39:19',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'PEINES',
                'id' => '154',
            ),
            154 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:39:43',
                'created_at' => '2021-05-18 22:39:43',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2618',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'SHAMPOO PARA PIOJOS',
                'id' => '155',
            ),
            155 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:40:03',
                'created_at' => '2021-05-18 22:40:03',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2619',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'SHAMPOO PARA PIOJOS',
                'id' => '156',
            ),
            156 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:40:26',
                'created_at' => '2021-05-18 22:40:26',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2620',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'SHAMPOO PARA PIOJOS',
                'id' => '157',
            ),
            157 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:40:51',
                'created_at' => '2021-05-18 22:40:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2621',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'SHAMPOO',
                'id' => '158',
            ),
            158 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:41:13',
                'created_at' => '2021-05-18 22:41:13',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2622',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'CREMA PARA MANOS',
                'id' => '159',
            ),
            159 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:41:34',
                'created_at' => '2021-05-18 22:41:34',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2621',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'CREMA PARA MANOS',
                'id' => '160',
            ),
            160 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:41:59',
                'created_at' => '2021-05-18 22:41:59',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2622',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'ANTIBACTERIAL',
                'id' => '161',
            ),
            161 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:42:23',
                'created_at' => '2021-05-18 22:42:23',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2623',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'JABON',
                'id' => '162',
            ),
            162 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:42:51',
                'created_at' => '2021-05-18 22:42:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2624',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'DOSIS FLÚOR',
                'id' => '163',
            ),
            163 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:43:17',
                'created_at' => '2021-05-18 22:43:17',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'CUBETAS PARA FLÚOR',
                'id' => '164',
            ),
            164 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:43:44',
                'created_at' => '2021-05-18 22:43:44',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2625',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'DOSIS CREMA DENTAL',
                'id' => '165',
            ),
            165 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:44:18',
                'created_at' => '2021-05-18 22:44:18',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2626',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'DOSIS SOLUCIÓN REVELADORA PLACA BACTERIANA',
                'id' => '166',
            ),
            166 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:44:39',
                'created_at' => '2021-05-18 22:44:39',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '1765',
                's_recurso' => 'ESPEJO FACIAL',
                'id' => '167',
            ),
            167 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:45:12',
                'created_at' => '2021-05-18 22:45:12',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'CEPILLOS DENTALES',
                'id' => '168',
            ),
            168 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:45:42',
                'created_at' => '2021-05-18 22:45:42',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2608',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'MACRO MODELO DENTAL CON SU CEPILLO',
                'id' => '169',
            ),
            169 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:46:22',
                'created_at' => '2021-05-18 22:46:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2604',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'AGUJAS',
                'id' => '170',
            ),
            170 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:46:47',
                'created_at' => '2021-05-18 22:46:47',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '1681',
                'i_prm_trecurso_id' => '2631',
                's_recurso' => 'HILOS DE COLORES',
                'id' => '171',
            ),
            171 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:47:16',
                'created_at' => '2021-05-18 22:47:16',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2627',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'VASELINA',
                'id' => '172',
            ),
            172 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:47:56',
                'created_at' => '2021-05-18 22:47:56',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2628',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'PROTECTOR SOLAR',
                'id' => '173',
            ),
            173 => 
            array (
                'deleted_at' => NULL,
                'updated_at' => '2021-05-18 22:48:21',
                'created_at' => '2021-05-18 22:48:21',
                'sis_esta_id' => '1',
                'user_edita_id' => '9',
                'user_crea_id' => '9',
                'i_prm_umedida_id' => '2629',
                'i_prm_trecurso_id' => '2630',
                's_recurso' => 'PROTECTOR SOLAR',
                'id' => '174',
            ),
        ));
        
        
    }
}