<?php

use App\Models\Sistema\SisTcampo;
use Illuminate\Database\Seeder;

class CamposAISeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //AI_REPORTE_EVASIONS
SisTcampo::create([ 's_campo' => 'CARGO_RECIBE', 's_descripcion' => 'CARGO_RECIBE', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//127
SisTcampo::create([ 's_campo' => 'CIRCUNSTANCIAS', 's_descripcion' => 'CIRCUNSTANCIAS', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//128
SisTcampo::create([ 's_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//129
SisTcampo::create([ 's_campo' => 'CUANTOS', 's_descripcion' => 'CUANTOS', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//130
SisTcampo::create([ 's_campo' => 'DEPARTAMENTO_ID', 's_descripcion' => 'DEPARTAMENTO_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//131
SisTcampo::create([ 's_campo' => 'FECHA_DENUNCIA', 's_descripcion' => 'FECHA_DENUNCIA', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//132
SisTcampo::create([ 's_campo' => 'FECHA_DILIGENCIAMIENTO', 's_descripcion' => 'FECHA_DILIGENCIAMIENTO', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//133
SisTcampo::create([ 's_campo' => 'FECHA_EVASION', 's_descripcion' => 'FECHA_EVASION', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//134
SisTcampo::create([ 's_campo' => 'HORA_DENUNCIA', 's_descripcion' => 'HORA_DENUNCIA', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//135
SisTcampo::create([ 's_campo' => 'HORA_EVASION', 's_descripcion' => 'HORA_EVASION', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//136
SisTcampo::create([ 's_campo' => 'INSTITUCION', 's_descripcion' => 'INSTITUCION', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//137
SisTcampo::create([ 's_campo' => 'LUGAR_EVASION', 's_descripcion' => 'LUGAR_EVASION', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//138
SisTcampo::create([ 's_campo' => 'MUNICIPIO_ID', 's_descripcion' => 'MUNICIPIO_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//139
SisTcampo::create([ 's_campo' => 'NNAJ_PESO', 's_descripcion' => 'NNAJ_PESO', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//140
SisTcampo::create([ 's_campo' => 'NNAJ_TALLA', 's_descripcion' => 'NNAJ_TALLA', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//141
SisTcampo::create([ 's_campo' => 'NOMBRE_RECIBE', 's_descripcion' => 'NOMBRE_RECIBE', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//142
SisTcampo::create([ 's_campo' => 'OBSERVACIONES_FAM', 's_descripcion' => 'OBSERVACIONES_FAM', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//143
SisTcampo::create([ 's_campo' => 'PLACA_RECIBE', 's_descripcion' => 'PLACA_RECIBE', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//144
SisTcampo::create([ 's_campo' => 'PRM_COLCABELLO_ID', 's_descripcion' => 'PRM_COLCABELLO_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param145', 's_idtarela'=> 'param145.id', 's_campsele'=> 'param145.nombre as nombre145', 'sis_esta_id' => 1 ]);//145
SisTcampo::create([ 's_campo' => 'PRM_CONTEXTURA_ID', 's_descripcion' => 'PRM_CONTEXTURA_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param146', 's_idtarela'=> 'param146.id', 's_campsele'=> 'param146.nombre as nombre146', 'sis_esta_id' => 1 ]);//146
SisTcampo::create([ 's_campo' => 'PRM_CORCABELLO_ID', 's_descripcion' => 'PRM_CORCABELLO_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param147', 's_idtarela'=> 'param147.id', 's_campsele'=> 'param147.nombre as nombre147', 'sis_esta_id' => 1 ]);//147
SisTcampo::create([ 's_campo' => 'PRM_HOR_DENUNCIA_ID', 's_descripcion' => 'PRM_HOR_DENUNCIA_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param148', 's_idtarela'=> 'param148.id', 's_campsele'=> 'param148.nombre as nombre148', 'sis_esta_id' => 1 ]);//148
SisTcampo::create([ 's_campo' => 'PRM_LLAMADA_ID', 's_descripcion' => 'PRM_LLAMADA_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param149', 's_idtarela'=> 'param149.id', 's_campsele'=> 'param149.nombre as nombre149', 'sis_esta_id' => 1 ]);//149
SisTcampo::create([ 's_campo' => 'PRM_NARIZ_ID', 's_descripcion' => 'PRM_NARIZ_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param150', 's_idtarela'=> 'param150.id', 's_campsele'=> 'param150.nombre as nombre150', 'sis_esta_id' => 1 ]);//150
SisTcampo::create([ 's_campo' => 'PRM_OJOS_ID', 's_descripcion' => 'PRM_OJOS_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param151', 's_idtarela'=> 'param151.id', 's_campsele'=> 'param151.nombre as nombre151', 'sis_esta_id' => 1 ]);//151
SisTcampo::create([ 's_campo' => 'PRM_PIEL_ID', 's_descripcion' => 'PRM_PIEL_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param152', 's_idtarela'=> 'param152.id', 's_campsele'=> 'param152.nombre as nombre152', 'sis_esta_id' => 1 ]);//152
SisTcampo::create([ 's_campo' => 'PRM_REPORTA_ID', 's_descripcion' => 'PRM_REPORTA_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param153', 's_idtarela'=> 'param153.id', 's_campsele'=> 'param153.nombre as nombre153', 'sis_esta_id' => 1 ]);//153
SisTcampo::create([ 's_campo' => 'PRM_ROSTRO_ID', 's_descripcion' => 'PRM_ROSTRO_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param154', 's_idtarela'=> 'param154.id', 's_campsele'=> 'param154.nombre as nombre154', 'sis_esta_id' => 1 ]);//154
SisTcampo::create([ 's_campo' => 'PRM_TAMLUNAR_ID', 's_descripcion' => 'PRM_TAMLUNAR_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param155', 's_idtarela'=> 'param155.id', 's_campsele'=> 'param155.nombre as nombre155', 'sis_esta_id' => 1 ]);//155
SisTcampo::create([ 's_campo' => 'PRM_TIENELUNAR_ID', 's_descripcion' => 'PRM_TIENELUNAR_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param156', 's_idtarela'=> 'param156.id', 's_campsele'=> 'param156.nombre as nombre156', 'sis_esta_id' => 1 ]);//156
SisTcampo::create([ 's_campo' => 'PRM_TINTURADO_ID', 's_descripcion' => 'PRM_TINTURADO_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param157', 's_idtarela'=> 'param157.id', 's_campsele'=> 'param157.nombre as nombre157', 'sis_esta_id' => 1 ]);//157
SisTcampo::create([ 's_campo' => 'PRM_TIPCABELLO_ID', 's_descripcion' => 'PRM_TIPCABELLO_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param158', 's_idtarela'=> 'param158.id', 's_campsele'=> 'param158.nombre as nombre158', 'sis_esta_id' => 1 ]);//158
SisTcampo::create([ 's_campo' => 'PRM_UPI_ID', 's_descripcion' => 'PRM_UPI_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param159', 's_idtarela'=> 'param159.id', 's_campsele'=> 'param159.nombre as nombre159', 'sis_esta_id' => 1 ]);//159
SisTcampo::create([ 's_campo' => 'RADICADO', 's_descripcion' => 'RADICADO', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//160
SisTcampo::create([ 's_campo' => 'RECIBE_DENUNCIA', 's_descripcion' => 'RECIBE_DENUNCIA', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//161
SisTcampo::create([ 's_campo' => 'RESPONSABLE', 's_descripcion' => 'RESPONSABLE', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//162
SisTcampo::create([ 's_campo' => 'SENIAS', 's_descripcion' => 'SENIAS', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//163
SisTcampo::create([ 's_campo' => 'sis_esta_id', 's_descripcion' => 'sis_esta_id', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//164
SisTcampo::create([ 's_campo' => 'SIS_NNAJ_ID', 's_descripcion' => 'SIS_NNAJ_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//165
SisTcampo::create([ 's_campo' => 'S_DOC_ADJUNTO', 's_descripcion' => 'S_DOC_ADJUNTO', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//166
SisTcampo::create([ 's_campo' => 'TINTURA', 's_descripcion' => 'TINTURA', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//167
SisTcampo::create([ 's_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//168
SisTcampo::create([ 's_campo' => 'user_crea_id', 's_descripcion' => 'user_crea_id', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//169
SisTcampo::create([ 's_campo' => 'USER_DOC1_ID', 's_descripcion' => 'USER_DOC1_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//170
SisTcampo::create([ 's_campo' => 'USER_DOC2_ID', 's_descripcion' => 'USER_DOC2_ID', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//171
SisTcampo::create([ 's_campo' => 'user_edita_id', 's_descripcion' => 'user_edita_id', 'sis_tabla_id' => 13, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//172
//AI_RETOSALIS
SisTcampo::create([ 's_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//173
SisTcampo::create([ 's_campo' => 'descripcion', 's_descripcion' => 'descripcion', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//174
SisTcampo::create([ 's_campo' => 'DOC_RETORNA', 's_descripcion' => 'DOC_RETORNA', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//175
SisTcampo::create([ 's_campo' => 'FECHA', 's_descripcion' => 'FECHA', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//176
SisTcampo::create([ 's_campo' => 'HORA_RETORNO', 's_descripcion' => 'HORA_RETORNO', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//177
SisTcampo::create([ 's_campo' => 'NOMBRES_RETORNA', 's_descripcion' => 'NOMBRES_RETORNA', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//178
SisTcampo::create([ 's_campo' => 'OBSERVACIONES', 's_descripcion' => 'OBSERVACIONES', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//179
SisTcampo::create([ 's_campo' => 'PRM_DOC_ID', 's_descripcion' => 'PRM_DOC_ID', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param180', 's_idtarela'=> 'param180.id', 's_campsele'=> 'param180.nombre as nombre180', 'sis_esta_id' => 1 ]);//180
SisTcampo::create([ 's_campo' => 'PRM_PARENTEZCO_ID', 's_descripcion' => 'PRM_PARENTEZCO_ID', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param181', 's_idtarela'=> 'param181.id', 's_campsele'=> 'param181.nombre as nombre181', 'sis_esta_id' => 1 ]);//181
SisTcampo::create([ 's_campo' => 'PRM_UPI_ID', 's_descripcion' => 'PRM_UPI_ID', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param182', 's_idtarela'=> 'param182.id', 's_campsele'=> 'param182.nombre as nombre182', 'sis_esta_id' => 1 ]);//182
SisTcampo::create([ 's_campo' => 'RESPONSABLE', 's_descripcion' => 'RESPONSABLE', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//183
SisTcampo::create([ 's_campo' => 'sis_esta_id', 's_descripcion' => 'sis_esta_id', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//184
SisTcampo::create([ 's_campo' => 'SIS_NNAJ_ID', 's_descripcion' => 'SIS_NNAJ_ID', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//185
SisTcampo::create([ 's_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//186
SisTcampo::create([ 's_campo' => 'user_crea_id', 's_descripcion' => 'user_crea_id', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//187
SisTcampo::create([ 's_campo' => 'USER_DOC1_ID', 's_descripcion' => 'USER_DOC1_ID', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//188
SisTcampo::create([ 's_campo' => 'user_edita_id', 's_descripcion' => 'user_edita_id', 'sis_tabla_id' => 14, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//189
//AI_RETSALCOS
SisTcampo::create([ 's_campo' => 'AI_RETORNO_SALIDA_ID', 's_descripcion' => 'AI_RETORNO_SALIDA_ID', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//190
SisTcampo::create([ 's_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//191
SisTcampo::create([ 's_campo' => 'PRM_BROTES_ID', 's_descripcion' => 'PRM_BROTES_ID', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param192', 's_idtarela'=> 'param192.id', 's_campsele'=> 'param192.nombre as nombre192', 'sis_esta_id' => 1 ]);//192
SisTcampo::create([ 's_campo' => 'PRM_CONDICION_ID', 's_descripcion' => 'PRM_CONDICION_ID', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param193', 's_idtarela'=> 'param193.id', 's_campsele'=> 'param193.nombre as nombre193', 'sis_esta_id' => 1 ]);//193
SisTcampo::create([ 's_campo' => 'PRM_ENFERMERD_ID', 's_descripcion' => 'PRM_ENFERMERD_ID', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param194', 's_idtarela'=> 'param194.id', 's_campsele'=> 'param194.nombre as nombre194', 'sis_esta_id' => 1 ]);//194
SisTcampo::create([ 's_campo' => 'PRM_LACERACIO_ID', 's_descripcion' => 'PRM_LACERACIO_ID', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param195', 's_idtarela'=> 'param195.id', 's_campsele'=> 'param195.nombre as nombre195', 'sis_esta_id' => 1 ]);//195
SisTcampo::create([ 's_campo' => 'PRM_ORIENTADO_ID', 's_descripcion' => 'PRM_ORIENTADO_ID', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param196', 's_idtarela'=> 'param196.id', 's_campsele'=> 'param196.nombre as nombre196', 'sis_esta_id' => 1 ]);//196
SisTcampo::create([ 's_campo' => 'sis_esta_id', 's_descripcion' => 'sis_esta_id', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//197
SisTcampo::create([ 's_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//198
SisTcampo::create([ 's_campo' => 'user_crea_id', 's_descripcion' => 'user_crea_id', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//199
SisTcampo::create([ 's_campo' => 'user_edita_id', 's_descripcion' => 'user_edita_id', 'sis_tabla_id' => 15, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//200
//AI_SALIDA_MAYORES
SisTcampo::create([ 's_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//201
SisTcampo::create([ 's_campo' => 'FECHA', 's_descripcion' => 'FECHA', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//202
SisTcampo::create([ 's_campo' => 'PRM_UPI_ID', 's_descripcion' => 'PRM_UPI_ID', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param203', 's_idtarela'=> 'param203.id', 's_campsele'=> 'param203.nombre as nombre203', 'sis_esta_id' => 1 ]);//203
SisTcampo::create([ 's_campo' => 'sis_esta_id', 's_descripcion' => 'sis_esta_id', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//204
SisTcampo::create([ 's_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//205
SisTcampo::create([ 's_campo' => 'user_crea_id', 's_descripcion' => 'user_crea_id', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//206
SisTcampo::create([ 's_campo' => 'USER_DOC1_ID', 's_descripcion' => 'USER_DOC1_ID', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//207
SisTcampo::create([ 's_campo' => 'USER_DOC2_ID', 's_descripcion' => 'USER_DOC2_ID', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//208
SisTcampo::create([ 's_campo' => 'user_edita_id', 's_descripcion' => 'user_edita_id', 'sis_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//209
//AI_SALIDA_MENORES
SisTcampo::create([ 's_campo' => 'APE1_AUTORIZADO', 's_descripcion' => 'APE1_AUTORIZADO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//210
SisTcampo::create([ 's_campo' => 'APE2_AUTORIZADO', 's_descripcion' => 'APE2_AUTORIZADO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//211
SisTcampo::create([ 's_campo' => 'CAUSA', 's_descripcion' => 'CAUSA', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//212
SisTcampo::create([ 's_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//213
SisTcampo::create([ 's_campo' => 'descripcion', 's_descripcion' => 'descripcion', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//214
SisTcampo::create([ 's_campo' => 'DIR_SALIDA', 's_descripcion' => 'DIR_SALIDA', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//215
SisTcampo::create([ 's_campo' => 'DOCUMENTO', 's_descripcion' => 'DOCUMENTO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//216
SisTcampo::create([ 's_campo' => 'DOC_AUTORIZADO', 's_descripcion' => 'DOC_AUTORIZADO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//217
SisTcampo::create([ 's_campo' => 'DOC_RECOGE', 's_descripcion' => 'DOC_RECOGE', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//218
SisTcampo::create([ 's_campo' => 'FECHA', 's_descripcion' => 'FECHA', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//219
SisTcampo::create([ 's_campo' => 'HORA_SALIDA', 's_descripcion' => 'HORA_SALIDA', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//220
SisTcampo::create([ 's_campo' => 'NOM1_AUTORIZADO', 's_descripcion' => 'NOM1_AUTORIZADO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//221
SisTcampo::create([ 's_campo' => 'NOM2_AUTORIZADO', 's_descripcion' => 'NOM2_AUTORIZADO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//222
SisTcampo::create([ 's_campo' => 'NOMBRES_RECOGE', 's_descripcion' => 'NOMBRES_RECOGE', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//223
SisTcampo::create([ 's_campo' => 'NOVEDAD', 's_descripcion' => 'NOVEDAD', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//224
SisTcampo::create([ 's_campo' => 'OBJETOS', 's_descripcion' => 'OBJETOS', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//225
SisTcampo::create([ 's_campo' => 'PRIMER_APELLIDO', 's_descripcion' => 'PRIMER_APELLIDO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//226
SisTcampo::create([ 's_campo' => 'PRIMER_NOMBRE', 's_descripcion' => 'PRIMER_NOMBRE', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//227
SisTcampo::create([ 's_campo' => 'PRM_AUTORIZADO_ID', 's_descripcion' => 'PRM_AUTORIZADO_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param228', 's_idtarela'=> 'param228.id', 's_campsele'=> 'param228.nombre as nombre228', 'sis_esta_id' => 1 ]);//228
SisTcampo::create([ 's_campo' => 'PRM_CARTA_ID', 's_descripcion' => 'PRM_CARTA_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param229', 's_idtarela'=> 'param229.id', 's_campsele'=> 'param229.nombre as nombre229', 'sis_esta_id' => 1 ]);//229
SisTcampo::create([ 's_campo' => 'PRM_COPIADOC2_ID', 's_descripcion' => 'PRM_COPIADOC2_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param230', 's_idtarela'=> 'param230.id', 's_campsele'=> 'param230.nombre as nombre230', 'sis_esta_id' => 1 ]);//230
SisTcampo::create([ 's_campo' => 'PRM_COPIADOC_ID', 's_descripcion' => 'PRM_COPIADOC_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param231', 's_idtarela'=> 'param231.id', 's_campsele'=> 'param231.nombre as nombre231', 'sis_esta_id' => 1 ]);//231
SisTcampo::create([ 's_campo' => 'PRM_DOC2_ID', 's_descripcion' => 'PRM_DOC2_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param232', 's_idtarela'=> 'param232.id', 's_campsele'=> 'param232.nombre as nombre232', 'sis_esta_id' => 1 ]);//232
SisTcampo::create([ 's_campo' => 'PRM_DOC_ID', 's_descripcion' => 'PRM_DOC_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param233', 's_idtarela'=> 'param233.id', 's_campsele'=> 'param233.nombre as nombre233', 'sis_esta_id' => 1 ]);//233
SisTcampo::create([ 's_campo' => 'PRM_PARENTEZCO2_ID', 's_descripcion' => 'PRM_PARENTEZCO2_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param234', 's_idtarela'=> 'param234.id', 's_campsele'=> 'param234.nombre as nombre234', 'sis_esta_id' => 1 ]);//234
SisTcampo::create([ 's_campo' => 'PRM_PARENTEZCO_ID', 's_descripcion' => 'PRM_PARENTEZCO_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param235', 's_idtarela'=> 'param235.id', 's_campsele'=> 'param235.nombre as nombre235', 'sis_esta_id' => 1 ]);//235
SisTcampo::create([ 's_campo' => 'PRM_UPI2_ID', 's_descripcion' => 'PRM_UPI2_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param236', 's_idtarela'=> 'param236.id', 's_campsele'=> 'param236.nombre as nombre236', 'sis_esta_id' => 1 ]);//236
SisTcampo::create([ 's_campo' => 'PRM_UPI_ID', 's_descripcion' => 'PRM_UPI_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param237', 's_idtarela'=> 'param237.id', 's_campsele'=> 'param237.nombre as nombre237', 'sis_esta_id' => 1 ]);//237
SisTcampo::create([ 's_campo' => 'RESPONSABLE', 's_descripcion' => 'RESPONSABLE', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//238
SisTcampo::create([ 's_campo' => 'SEGUNDO_APELLIDO', 's_descripcion' => 'SEGUNDO_APELLIDO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//239
SisTcampo::create([ 's_campo' => 'SEGUNDO_NOMBRE', 's_descripcion' => 'SEGUNDO_NOMBRE', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//240
SisTcampo::create([ 's_campo' => 'sis_esta_id', 's_descripcion' => 'sis_esta_id', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//241
SisTcampo::create([ 's_campo' => 'SIS_NNAJ_ID', 's_descripcion' => 'SIS_NNAJ_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//242
SisTcampo::create([ 's_campo' => 'TEL_CONTACTO', 's_descripcion' => 'TEL_CONTACTO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//243
SisTcampo::create([ 's_campo' => 'TIEMPO', 's_descripcion' => 'TIEMPO', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//244
SisTcampo::create([ 's_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//245
SisTcampo::create([ 's_campo' => 'user_crea_id', 's_descripcion' => 'user_crea_id', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//246
SisTcampo::create([ 's_campo' => 'USER_DOC1_ID', 's_descripcion' => 'USER_DOC1_ID', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//247
SisTcampo::create([ 's_campo' => 'user_edita_id', 's_descripcion' => 'user_edita_id', 'sis_tabla_id' => 17, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//248
//AI_SALIDA_MENORES_CON
SisTcampo::create([ 's_campo' => 'AI_SALIDA_MENORES_ID', 's_descripcion' => 'AI_SALIDA_MENORES_ID', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//249
SisTcampo::create([ 's_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//250
SisTcampo::create([ 's_campo' => 'PRM_BROTES_ID', 's_descripcion' => 'PRM_BROTES_ID', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param251', 's_idtarela'=> 'param251.id', 's_campsele'=> 'param251.nombre as nombre251', 'sis_esta_id' => 1 ]);//251
SisTcampo::create([ 's_campo' => 'PRM_CONDICION_ID', 's_descripcion' => 'PRM_CONDICION_ID', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param252', 's_idtarela'=> 'param252.id', 's_campsele'=> 'param252.nombre as nombre252', 'sis_esta_id' => 1 ]);//252
SisTcampo::create([ 's_campo' => 'PRM_ENFERMERD_ID', 's_descripcion' => 'PRM_ENFERMERD_ID', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param253', 's_idtarela'=> 'param253.id', 's_campsele'=> 'param253.nombre as nombre253', 'sis_esta_id' => 1 ]);//253
SisTcampo::create([ 's_campo' => 'PRM_LACERACIO_ID', 's_descripcion' => 'PRM_LACERACIO_ID', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param254', 's_idtarela'=> 'param254.id', 's_campsele'=> 'param254.nombre as nombre254', 'sis_esta_id' => 1 ]);//254
SisTcampo::create([ 's_campo' => 'PRM_ORIENTADO_ID', 's_descripcion' => 'PRM_ORIENTADO_ID', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> 'parametros as param255', 's_idtarela'=> 'param255.id', 's_campsele'=> 'param255.nombre as nombre255', 'sis_esta_id' => 1 ]);//255
SisTcampo::create([ 's_campo' => 'sis_esta_id', 's_descripcion' => 'sis_esta_id', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//256
SisTcampo::create([ 's_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//257
SisTcampo::create([ 's_campo' => 'user_crea_id', 's_descripcion' => 'user_crea_id', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//258
SisTcampo::create([ 's_campo' => 'user_edita_id', 's_descripcion' => 'user_edita_id', 'sis_tabla_id' => 18, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//259
//AI_SALIDA_MENORES_OBJ
SisTcampo::create([ 's_campo' => 'AI_SALIDA_MENORES_ID', 's_descripcion' => 'AI_SALIDA_MENORES_ID', 'sis_tabla_id' => 19, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//260
SisTcampo::create([ 's_campo' => 'PARAMETRO_ID', 's_descripcion' => 'PARAMETRO_ID', 'sis_tabla_id' => 19, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//261
SisTcampo::create([ 's_campo' => 'user_crea_id', 's_descripcion' => 'user_crea_id', 'sis_tabla_id' => 19, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//262
SisTcampo::create([ 's_campo' => 'user_edita_id', 's_descripcion' => 'user_edita_id', 'sis_tabla_id' => 19, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela'=> '', 's_idtarela'=> '', 's_campsele'=> '', 'sis_esta_id' => 1 ]);//263

    }
}
