<?php

use App\Models\Sistema\SisTcampo;
use Illuminate\Database\Seeder;

class CamposAgSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //AG_ACTIVIDADS
        SisTcampo::create(['s_campo' => 'AG_STTEMA_ID', 's_descripcion' => 'AG_STTEMA_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'AG_STTEMA_ID', 'sis_esta_id' => 1]); //1
        SisTcampo::create(['s_campo' => 'AG_TALLER_ID', 's_descripcion' => 'AG_TALLER_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'AG_TALLERS AS AG_TALLERS1', 's_idtarela' => 'AG_TALLERS1.ID', 's_campsele' => '', 'sis_esta_id' => 1]); //2
        SisTcampo::create(['s_campo' => 'AG_TEMA_ID', 's_descripcion' => 'AG_TEMA_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'AG_TEMAS AS AG_TEMAS1', 's_idtarela' => 'AG_TEMAS1.ID', 's_campsele' => '', 'sis_esta_id' => 1]); //3
        SisTcampo::create(['s_campo' => 'AREA_ID', 's_descripcion' => 'AREA_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'AREAS AS AREAS1', 's_idtarela' => 'AREAS1.ID', 's_campsele' => '', 'sis_esta_id' => 1]); //4
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT1', 'sis_esta_id' => 1]); //5
        SisTcampo::create(['s_campo' => 'DELETED_AT', 's_descripcion' => 'DELETED_AT', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'DELETED_AT AS DELETED_AT1', 'sis_esta_id' => 1]); //6
        SisTcampo::create(['s_campo' => 'D_REGISTRO', 's_descripcion' => 'D_REGISTRO', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'D_REGISTRO', 'sis_esta_id' => 1]); //7
        SisTcampo::create(['s_campo' => 'INCOMPLETO', 's_descripcion' => 'INCOMPLETO', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'INCOMPLETO', 'sis_esta_id' => 1]); //8
        SisTcampo::create(['s_campo' => 'I_PRM_DIRIG_ID', 's_descripcion' => 'I_PRM_DIRIG_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param9', 's_idtarela' => 'param9.id', 's_campsele' => 'param9.nombre as nombre9', 'sis_esta_id' => 1]); //9
        SisTcampo::create(['s_campo' => 'I_PRM_LUGAR_ID', 's_descripcion' => 'I_PRM_LUGAR_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param10', 's_idtarela' => 'param10.id', 's_campsele' => 'param10.nombre as nombre10', 'sis_esta_id' => 1]); //10
        SisTcampo::create(['s_campo' => 'SIS_DEPDESTINO_ID', 's_descripcion' => 'SIS_DEPDESTINO_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'SIS_DEPDESTINO_ID', 'sis_esta_id' => 1]); //11
        SisTcampo::create(['s_campo' => 'SIS_DEPORIGEN_ID', 's_descripcion' => 'SIS_DEPORIGEN_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'SIS_DEPORIGEN_ID', 'sis_esta_id' => 1]); //12
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'SIS_ESTAS AS SIS_ESTAS1', 's_idtarela' => 'SIS_ESTAS1.ID', 's_campsele' => '', 'sis_esta_id' => 1]); //13
        SisTcampo::create(['s_campo' => 'S_CATEGORI', 's_descripcion' => 'S_CATEGORI', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //14
        SisTcampo::create(['s_campo' => 'S_CONTENID', 's_descripcion' => 'S_CONTENID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //15
        SisTcampo::create(['s_campo' => 'S_ESTRATEG', 's_descripcion' => 'S_ESTRATEG', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //16
        SisTcampo::create(['s_campo' => 'S_EVALUACI', 's_descripcion' => 'S_EVALUACI', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //17
        SisTcampo::create(['s_campo' => 'S_INTRODUC', 's_descripcion' => 'S_INTRODUC', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //18
        SisTcampo::create(['s_campo' => 'S_JUSTIFIC', 's_descripcion' => 'S_JUSTIFIC', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //19
        SisTcampo::create(['s_campo' => 'S_METODOLO', 's_descripcion' => 'S_METODOLO', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //20
        SisTcampo::create(['s_campo' => 'S_OBJETIVO', 's_descripcion' => 'S_OBJETIVO', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //21
        SisTcampo::create(['s_campo' => 'S_OBSERVAC', 's_descripcion' => 'S_OBSERVAC', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //22
        SisTcampo::create(['s_campo' => 'S_PRM_ESPAC', 's_descripcion' => 'S_PRM_ESPAC', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param23', 's_idtarela' => 'param23.id', 's_campsele' => 'param23.nombre as nombre23', 'sis_esta_id' => 1]); //23
        SisTcampo::create(['s_campo' => 'S_RESULTAD', 's_descripcion' => 'S_RESULTAD', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //24
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //25
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //26
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //27
        //AG_ASISTENTES
        SisTcampo::create(['s_campo' => 'AG_ACTIVIDAD_ID', 's_descripcion' => 'AG_ACTIVIDAD_ID', 'sis_tabla_id' => 2, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //28
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 2, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT2', 'sis_esta_id' => 1]); //29
        SisTcampo::create(['s_campo' => 'FI_DATO_BASICO_ID', 's_descripcion' => 'FI_DATO_BASICO_ID', 'sis_tabla_id' => 2, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //30
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 2, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'SIS_ESTAS AS SIS_ESTAS2', 's_idtarela' => 'SIS_ESTAS2.ID', 's_campsele' => '', 'sis_esta_id' => 1]); //31
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 2, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //32
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 2, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //33
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 2, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //34
        //AG_CARGUEDOCS
        SisTcampo::create(['s_campo' => 'AG_ACTIVIDAD_ID', 's_descripcion' => 'AG_ACTIVIDAD_ID', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //35
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT3', 'sis_esta_id' => 1]); //36
        SisTcampo::create(['s_campo' => 'DELETED_AT', 's_descripcion' => 'DELETED_AT', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'DELETED_AT AS DELETED_AT2', 'sis_esta_id' => 1]); //37
        SisTcampo::create(['s_campo' => 'I_PRM_DOCUMENTO_ID', 's_descripcion' => 'I_PRM_DOCUMENTO_ID', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param38', 's_idtarela' => 'param38.id', 's_campsele' => 'param38.nombre as nombre38', 'sis_esta_id' => 1]); //38
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'SIS_ESTAS AS SIS_ESTAS3', 's_idtarela' => 'SIS_ESTAS3.ID', 's_campsele' => '', 'sis_esta_id' => 1]); //39
        SisTcampo::create(['s_campo' => 'S_RUTA', 's_descripcion' => 'S_RUTA', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //40
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //41
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //42
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 3, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //43
        //AG_CONTEXTOS
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 4, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT4', 'sis_esta_id' => 1]); //44
        SisTcampo::create(['s_campo' => 'ESTUSUARIO_ID', 's_descripcion' => 'ESTUSUARIO_ID', 'sis_tabla_id' => 4, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //45
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 4, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'SIS_ESTAS AS SIS_ESTAS4', 's_idtarela' => 'SIS_ESTAS4.ID', 's_campsele' => '', 'sis_esta_id' => 1]); //46
        SisTcampo::create(['s_campo' => 'S_CONTEXTO', 's_descripcion' => 'S_CONTEXTO', 'sis_tabla_id' => 4, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //47
        SisTcampo::create(['s_campo' => 'S_DESCRIPCION', 's_descripcion' => 'S_DESCRIPCION', 'sis_tabla_id' => 4, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //48
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 4, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //49
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 4, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //50
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 4, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //51
        //AG_CONVENIOS
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT5', 'sis_esta_id' => 1]); //52
        SisTcampo::create(['s_campo' => 'D_SUBSCRIP', 's_descripcion' => 'D_SUBSCRIP', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //53
        SisTcampo::create(['s_campo' => 'D_TERMINAC', 's_descripcion' => 'D_TERMINAC', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //54
        SisTcampo::create(['s_campo' => 'I_NCONVENIO', 's_descripcion' => 'I_NCONVENIO', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //55
        SisTcampo::create(['s_campo' => 'I_PRM_ENTIDAD_ID', 's_descripcion' => 'I_PRM_ENTIDAD_ID', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param56', 's_idtarela' => 'param56.id', 's_campsele' => 'param56.nombre as nombre56', 'sis_esta_id' => 1]); //56
        SisTcampo::create(['s_campo' => 'I_PRM_TCONVENIO_ID', 's_descripcion' => 'I_PRM_TCONVENIO_ID', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param57', 's_idtarela' => 'param57.id', 's_campsele' => 'param57.nombre as nombre57', 'sis_esta_id' => 1]); //57
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'SIS_ESTAS AS SIS_ESTAS4', 's_idtarela' => 'SIS_ESTAS4.ID', 's_campsele' => '', 'sis_esta_id' => 1]); //58
        SisTcampo::create(['s_campo' => 'S_CONVENIO', 's_descripcion' => 'S_CONVENIO', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //59
        SisTcampo::create(['s_campo' => 'S_DESCRIPCION', 's_descripcion' => 'S_DESCRIPCION', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //60
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //61
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //62
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 5, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //63
        //AG_RECURSOS
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT6', 'sis_esta_id' => 1]); //64
        SisTcampo::create(['s_campo' => 'DELETED_AT', 's_descripcion' => 'DELETED_AT', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'DELETED_AT AS DELETED_AT3', 'sis_esta_id' => 1]); //65
        SisTcampo::create(['s_campo' => 'I_PRM_TRECURSO_ID', 's_descripcion' => 'I_PRM_TRECURSO_ID', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param66', 's_idtarela' => 'param66.id', 's_campsele' => 'param66.nombre as nombre66', 'sis_esta_id' => 1]); //66
        SisTcampo::create(['s_campo' => 'I_PRM_UMEDIDA_ID', 's_descripcion' => 'I_PRM_UMEDIDA_ID', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param67', 's_idtarela' => 'param67.id', 's_campsele' => 'param67.nombre as nombre67', 'sis_esta_id' => 1]); //67
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //68
        SisTcampo::create(['s_campo' => 'S_RECURSO', 's_descripcion' => 'S_RECURSO', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //69
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //70
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //71
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 6, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //72
        //AG_RELACIONS
        SisTcampo::create(['s_campo' => 'AG_ACTIVIDAD_ID', 's_descripcion' => 'AG_ACTIVIDAD_ID', 'sis_tabla_id' => 7, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //73
        SisTcampo::create(['s_campo' => 'AG_RECURSO_ID', 's_descripcion' => 'AG_RECURSO_ID', 'sis_tabla_id' => 7, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //74
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 7, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT7', 'sis_esta_id' => 1]); //75
        SisTcampo::create(['s_campo' => 'I_CANTIDAD', 's_descripcion' => 'I_CANTIDAD', 'sis_tabla_id' => 7, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //76
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 7, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //77
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 7, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //78
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 7, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //79
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 7, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //80
        //AG_RESPONSABLES
        SisTcampo::create(['s_campo' => 'AG_ACTIVIDAD_ID', 's_descripcion' => 'AG_ACTIVIDAD_ID', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //81
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT8', 'sis_esta_id' => 1]); //82
        SisTcampo::create(['s_campo' => 'I_PRM_RESPONSABLE_ID', 's_descripcion' => 'I_PRM_RESPONSABLE_ID', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param83', 's_idtarela' => 'param83.id', 's_campsele' => 'param83.nombre as nombre83', 'sis_esta_id' => 1]); //83
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //84
        SisTcampo::create(['s_campo' => 'SIS_OBSE_ID', 's_descripcion' => 'SIS_OBSE_ID', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //85
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //86
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //87
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //88
        SisTcampo::create(['s_campo' => 'USER_ID', 's_descripcion' => 'USER_ID', 'sis_tabla_id' => 8, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //89
        //AG_SUBTEMAS
        SisTcampo::create(['s_campo' => 'AG_TALLER_ID', 's_descripcion' => 'AG_TALLER_ID', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => 'AG_TALLERS AS AG_TALLERS2', 's_campsele' => '', 'sis_esta_id' => 1]); //90
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT9', 'sis_esta_id' => 1]); //91
        SisTcampo::create(['s_campo' => 'DELETED_AT', 's_descripcion' => 'DELETED_AT', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'DELETED_AT AS DELETED_AT4', 'sis_esta_id' => 1]); //92
        SisTcampo::create(['s_campo' => 'ESTUSUARIO_ID', 's_descripcion' => 'ESTUSUARIO_ID', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //93
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //94
        SisTcampo::create(['s_campo' => 'S_DESCRIPCION', 's_descripcion' => 'S_DESCRIPCION', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //95
        SisTcampo::create(['s_campo' => 'S_SUBTEMA', 's_descripcion' => 'S_SUBTEMA', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //96
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //97
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //98
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 9, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //99
        //AG_TALLERS
        SisTcampo::create(['s_campo' => 'AG_TEMA_ID', 's_descripcion' => 'AG_TEMA_ID', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => 'AG_TEMAS AS AG_TEMAS2', 's_campsele' => '', 'sis_esta_id' => 1]); //100
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT10', 'sis_esta_id' => 1]); //101
        SisTcampo::create(['s_campo' => 'DELETED_AT', 's_descripcion' => 'DELETED_AT', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'DELETED_AT AS DELETED_AT5', 'sis_esta_id' => 1]); //102
        SisTcampo::create(['s_campo' => 'ESTUSUARIO_ID', 's_descripcion' => 'ESTUSUARIO_ID', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //103
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //104
        SisTcampo::create(['s_campo' => 'S_DESCRIPCION', 's_descripcion' => 'S_DESCRIPCION', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //105
        SisTcampo::create(['s_campo' => 'S_TALLER', 's_descripcion' => 'S_TALLER', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //106
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //107
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //108
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 10, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //109
        //AG_TALLER_AG_TEMA
        SisTcampo::create(['s_campo' => 'AG_TALLER_ID', 's_descripcion' => 'AG_TALLER_ID', 'sis_tabla_id' => 11, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => 'AG_TALLERS AS AG_TALLERS3', 's_campsele' => '', 'sis_esta_id' => 1]); //110
        SisTcampo::create(['s_campo' => 'AG_TEMA_ID', 's_descripcion' => 'AG_TEMA_ID', 'sis_tabla_id' => 11, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => 'AG_TEMAS AS AG_TEMAS3', 's_campsele' => '', 'sis_esta_id' => 1]); //111
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 11, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT11', 'sis_esta_id' => 1]); //112
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 11, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //113
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 11, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //114
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 11, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //115
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 11, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //116
        //AG_TEMAS
        SisTcampo::create(['s_campo' => 'AREA_ID', 's_descripcion' => 'AREA_ID', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => 'AREAS AS AREAS1', 's_campsele' => '', 'sis_esta_id' => 1]); //117
        SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'CREATED_AT AS CREATED_AT13', 'sis_esta_id' => 1]); //118
        SisTcampo::create(['s_campo' => 'DELETED_AT', 's_descripcion' => 'DELETED_AT', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => 'DELETED_AT AS DELETED_AT6', 'sis_esta_id' => 1]); //119
        SisTcampo::create(['s_campo' => 'ESTUSUARIO_ID', 's_descripcion' => 'ESTUSUARIO_ID', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //120
        SisTcampo::create(['s_campo' => 'SIS_ESTA_ID', 's_descripcion' => 'SIS_ESTA_ID', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //121
        SisTcampo::create(['s_campo' => 'S_DESCRIPCION', 's_descripcion' => 'S_DESCRIPCION', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //122
        SisTcampo::create(['s_campo' => 'S_TEMA', 's_descripcion' => 'S_TEMA', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //123
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //124
        SisTcampo::create(['s_campo' => 'USER_CREA_ID', 's_descripcion' => 'USER_CREA_ID', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //125
        SisTcampo::create(['s_campo' => 'USER_EDITA_ID', 's_descripcion' => 'USER_EDITA_ID', 'sis_tabla_id' => 12, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //126

    }
}
