<?php

use App\Models\Sistema\SisTcampo;
use Illuminate\Database\Seeder;

class CamposISSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //IS_DATOS_BASICOS
         SisTcampo::create(['s_campo' => 'CREATED_AT', 's_descripcion' => 'CREATED_AT', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1512
        SisTcampo::create(['s_campo' => 'D_FECHA_DILIGENCIA', 's_descripcion' => 'D_FECHA_DILIGENCIA', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1513
        SisTcampo::create(['s_campo' => 'D_FECHA_PROXIMA', 's_descripcion' => 'D_FECHA_PROXIMA', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1514
        SisTcampo::create(['s_campo' => 'I_PRIMER_RESPONSABLE', 's_descripcion' => 'I_PRIMER_RESPONSABLE', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1515
        SisTcampo::create(['s_campo' => 'I_PRM_AREA_ACADEMICA_ID', 's_descripcion' => 'I_PRM_AREA_ACADEMICA_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1516', 's_idtarela' => 'param1516.id', 's_campsele' => 'param1516.nombre as nombre1516', 'sis_esta_id' => 1]); //1516
        SisTcampo::create(['s_campo' => 'I_PRM_AREA_AJUSTE_ID', 's_descripcion' => 'I_PRM_AREA_AJUSTE_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1517', 's_idtarela' => 'param1517.id', 's_campsele' => 'param1517.nombre as nombre1517', 'sis_esta_id' => 1]); //1517
        SisTcampo::create(['s_campo' => 'I_PRM_AREA_COMPORTAM_ID', 's_descripcion' => 'I_PRM_AREA_COMPORTAM_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1518', 's_idtarela' => 'param1518.id', 's_campsele' => 'param1518.nombre as nombre1518', 'sis_esta_id' => 1]); //1518
        SisTcampo::create(['s_campo' => 'I_PRM_AREA_EMOCIONAL_ID', 's_descripcion' => 'I_PRM_AREA_EMOCIONAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1519', 's_idtarela' => 'param1519.id', 's_campsele' => 'param1519.nombre as nombre1519', 'sis_esta_id' => 1]); //1519
        SisTcampo::create(['s_campo' => 'I_PRM_AREA_FAMILIAR_ID', 's_descripcion' => 'I_PRM_AREA_FAMILIAR_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1520', 's_idtarela' => 'param1520.id', 's_campsele' => 'param1520.nombre as nombre1520', 'sis_esta_id' => 1]); //1520
        SisTcampo::create(['s_campo' => 'I_PRM_AREA_PROXIMA_ID', 's_descripcion' => 'I_PRM_AREA_PROXIMA_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1521', 's_idtarela' => 'param1521.id', 's_campsele' => 'param1521.nombre as nombre1521', 'sis_esta_id' => 1]); //1521
        SisTcampo::create(['s_campo' => 'I_PRM_AREA_SEXUAL_ID', 's_descripcion' => 'I_PRM_AREA_SEXUAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1522', 's_idtarela' => 'param1522.id', 's_campsele' => 'param1522.nombre as nombre1522', 'sis_esta_id' => 1]); //1522
        SisTcampo::create(['s_campo' => 'I_PRM_AREA_SOCIAL_ID', 's_descripcion' => 'I_PRM_AREA_SOCIAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1523', 's_idtarela' => 'param1523.id', 's_campsele' => 'param1523.nombre as nombre1523', 'sis_esta_id' => 1]); //1523
        SisTcampo::create(['s_campo' => 'I_PRM_AVANCE_ACADEM_ID', 's_descripcion' => 'I_PRM_AVANCE_ACADEM_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1524', 's_idtarela' => 'param1524.id', 's_campsele' => 'param1524.nombre as nombre1524', 'sis_esta_id' => 1]); //1524
        SisTcampo::create(['s_campo' => 'I_PRM_AVANCE_COMPOR_ID', 's_descripcion' => 'I_PRM_AVANCE_COMPOR_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1525', 's_idtarela' => 'param1525.id', 's_campsele' => 'param1525.nombre as nombre1525', 'sis_esta_id' => 1]); //1525
        SisTcampo::create(['s_campo' => 'I_PRM_AVANCE_EMOCIONAL_ID', 's_descripcion' => 'I_PRM_AVANCE_EMOCIONAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1526', 's_idtarela' => 'param1526.id', 's_campsele' => 'param1526.nombre as nombre1526', 'sis_esta_id' => 1]); //1526
        SisTcampo::create(['s_campo' => 'I_PRM_AVANCE_FAMILIAR_ID', 's_descripcion' => 'I_PRM_AVANCE_FAMILIAR_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1527', 's_idtarela' => 'param1527.id', 's_campsele' => 'param1527.nombre as nombre1527', 'sis_esta_id' => 1]); //1527
        SisTcampo::create(['s_campo' => 'I_PRM_AVANCE_SEXUAL_ID', 's_descripcion' => 'I_PRM_AVANCE_SEXUAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1528', 's_idtarela' => 'param1528.id', 's_campsele' => 'param1528.nombre as nombre1528', 'sis_esta_id' => 1]); //1528
        SisTcampo::create(['s_campo' => 'I_PRM_AVANCE_SOCIAL_ID', 's_descripcion' => 'I_PRM_AVANCE_SOCIAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1529', 's_idtarela' => 'param1529.id', 's_campsele' => 'param1529.nombre as nombre1529', 'sis_esta_id' => 1]); //1529
        SisTcampo::create(['s_campo' => 'I_PRM_SUBAREA_ACADEM_ID', 's_descripcion' => 'I_PRM_SUBAREA_ACADEM_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1530', 's_idtarela' => 'param1530.id', 's_campsele' => 'param1530.nombre as nombre1530', 'sis_esta_id' => 1]); //1530
        SisTcampo::create(['s_campo' => 'I_PRM_SUBAREA_AJUSTE_ID', 's_descripcion' => 'I_PRM_SUBAREA_AJUSTE_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1531', 's_idtarela' => 'param1531.id', 's_campsele' => 'param1531.nombre as nombre1531', 'sis_esta_id' => 1]); //1531
        SisTcampo::create(['s_campo' => 'I_PRM_SUBAREA_COMPOR_ID', 's_descripcion' => 'I_PRM_SUBAREA_COMPOR_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1532', 's_idtarela' => 'param1532.id', 's_campsele' => 'param1532.nombre as nombre1532', 'sis_esta_id' => 1]); //1532
        SisTcampo::create(['s_campo' => 'I_PRM_SUBAREA_EMOCIONAL_ID', 's_descripcion' => 'I_PRM_SUBAREA_EMOCIONAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1533', 's_idtarela' => 'param1533.id', 's_campsele' => 'param1533.nombre as nombre1533', 'sis_esta_id' => 1]); //1533
        SisTcampo::create(['s_campo' => 'I_PRM_SUBAREA_FAMILIAR_ID', 's_descripcion' => 'I_PRM_SUBAREA_FAMILIAR_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1534', 's_idtarela' => 'param1534.id', 's_campsele' => 'param1534.nombre as nombre1534', 'sis_esta_id' => 1]); //1534
        SisTcampo::create(['s_campo' => 'I_PRM_SUBAREA_SEXUAL_ID', 's_descripcion' => 'I_PRM_SUBAREA_SEXUAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1535', 's_idtarela' => 'param1535.id', 's_campsele' => 'param1535.nombre as nombre1535', 'sis_esta_id' => 1]); //1535
        SisTcampo::create(['s_campo' => 'I_PRM_SUBAREA_SOCIAL_ID', 's_descripcion' => 'I_PRM_SUBAREA_SOCIAL_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1536', 's_idtarela' => 'param1536.id', 's_campsele' => 'param1536.nombre as nombre1536', 'sis_esta_id' => 1]); //1536
        SisTcampo::create(['s_campo' => 'I_PRM_TIPO_ATENCION_ID', 's_descripcion' => 'I_PRM_TIPO_ATENCION_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => 'parametros as param1537', 's_idtarela' => 'param1537.id', 's_campsele' => 'param1537.nombre as nombre1537', 'sis_esta_id' => 1]); //1537
        SisTcampo::create(['s_campo' => 'I_SEGUNDO_RESPONSABLE', 's_descripcion' => 'I_SEGUNDO_RESPONSABLE', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1538
        SisTcampo::create(['s_campo' => 'SIS_DEPEN_ID', 's_descripcion' => 'SIS_DEPEN_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1539
        SisTcampo::create(['s_campo' => 'sis_esta_id', 's_descripcion' => 'sis_esta_id', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1540
        SisTcampo::create(['s_campo' => 'SIS_NNAJ_ID', 's_descripcion' => 'SIS_NNAJ_ID', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1541
        SisTcampo::create(['s_campo' => 'S_CONCLUSIONES_SESION', 's_descripcion' => 'S_CONCLUSIONES_SESION', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1542
        SisTcampo::create(['s_campo' => 'S_DESARROLLO_SESION', 's_descripcion' => 'S_DESARROLLO_SESION', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1543
        SisTcampo::create(['s_campo' => 'S_OBJETIVO_SESION', 's_descripcion' => 'S_OBJETIVO_SESION', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1544
        SisTcampo::create(['s_campo' => 'S_OBSERVACIONES', 's_descripcion' => 'S_OBSERVACIONES', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1545
        SisTcampo::create(['s_campo' => 'S_TAREAS', 's_descripcion' => 'S_TAREAS', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1546
        SisTcampo::create(['s_campo' => 'S_TEMA', 's_descripcion' => 'S_TEMA', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1547
        SisTcampo::create(['s_campo' => 'UPDATED_AT', 's_descripcion' => 'UPDATED_AT', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1548
        SisTcampo::create(['s_campo' => 'user_crea_id', 's_descripcion' => 'user_crea_id', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1549
        SisTcampo::create(['s_campo' => 'user_edita_id', 's_descripcion' => 'user_edita_id', 'sis_tabla_id' => 136, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_tablrela' => '', 's_idtarela' => '', 's_campsele' => '', 'sis_esta_id' => 1]); //1550
    }
}
