<?php

use App\Models\consulta\CsdAlimentacion;
use Illuminate\Database\Seeder;

class CsdAlimentacionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         CsdAlimentacion::create(['csd_id' => 78, 'cant_personas' => 4, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create(['csd_id' => 14, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create(['csd_id' => 19, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create(['csd_id' => 6, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create(['csd_id' => 16, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create(['csd_id' => 36, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create(['csd_id' => 70, 'cant_personas' => 8, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create(['csd_id' => 33, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create(['csd_id' => 66, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 32, 'cant_personas' => 4, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 83, 'cant_personas' => 2, 'prm_horario_id' => 227, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 25, 'cant_personas' => 4, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 28, 'cant_personas' => 2, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 29, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 85, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 87, 'cant_personas' => 8, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 48, 'cant_personas' => 5, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 84, 'cant_personas' => 0, 'prm_horario_id' => 770, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 9, 'cant_personas' => 0, 'prm_horario_id' => 771, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 3, 'cant_personas' => 0, 'prm_horario_id' => 794, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 50, 'cant_personas' => 0, 'prm_horario_id' => 771, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 4, 'cant_personas' => 0, 'prm_horario_id' => 771, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 35, 'cant_personas' => 0, 'prm_horario_id' => 771, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 54, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 3, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 10, 'cant_personas' => 6, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 8, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 13, 'cant_personas' => 5, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 51, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 15, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 67, 'cant_personas' => 6, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 7, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 12, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 11, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 43, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 80, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 73, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 63, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 40, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 53, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 41, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 30, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 52, 'cant_personas' => 8, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 49, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 13, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 2, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 18, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 86, 'cant_personas' => 8, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 20, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 72, 'cant_personas' => 2, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 39, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 26, 'cant_personas' => 2, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 55, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 12, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 88, 'cant_personas' => 8, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 71, 'cant_personas' => 5, 'prm_horario_id' => 227, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 57, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 90, 'cant_personas' => 10, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 75, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 23, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 31, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 7, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 69, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 82, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 5, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 17, 'cant_personas' => 2, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 79, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 42, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 22, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 68, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 47, 'cant_personas' => 3, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 37, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 81, 'cant_personas' => 9, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 1, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 56, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 89, 'cant_personas' => 2, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 21, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 91, 'cant_personas' => 4, 'prm_horario_id' => 227, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 77, 'cant_personas' => 4, 'prm_horario_id' => 227, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 62, 'cant_personas' => 6, 'prm_horario_id' => 227, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 45, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 59, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 44, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 65, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 61, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 76, 'cant_personas' => 2, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 60, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 34, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 58, 'cant_personas' => 5, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 64, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 38, 'cant_personas' => 8, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 46, 'cant_personas' => 6, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 24, 'cant_personas' => 8, 'prm_horario_id' => 228, 'prm_apoyo_id' => 227, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 74, 'cant_personas' => 4, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 92, 'cant_personas' => 2, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
        CsdAlimentacion::create([ 'csd_id' => 27, 'cant_personas' => 3, 'prm_horario_id' => 228, 'prm_apoyo_id' => 228, 'prm_entidad_id' => 1, 'prm_tipofuen_id' => 2316, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]);
    }
}
