<?php

use App\Models\consulta\CsdComfamob;
use Illuminate\Database\Seeder;

class CsdComfamobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         CsdComfamob::create(['csd_id' => 78, 'observaciones' => 'LA FAMILIA CUENTA CON COBERTURA EN SISTEMA DE SALUD BAJO SISTEMA SUBSIDIADO EL ADOLECENTE Y SU CUÑADO Y BAJO SISTEMA CONTRIBUTIVO LA HERMANA, EN RELACIÓN A EDUCACIÓN JOEL SE ENCUENTRA VINCULADO AL IDIPRON EN MODALIDAD EXTERNADO EN UPI MOLINOS; LA HERMANA ES BACHILLER Y SU CUÑADO SE ENCUENTRA ADSCRITO AL INSTITUTO. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 14, 'observaciones' => 'LA FAMILIA CUENTA CON COBERTURA EN SISTEMA DE SALUD BAJO SISTEMA CONTRIBUTIVO, EN RELACIÓN A EDUCACIÓN PAULA SE ENCUENTRA VINCULADA AL IDIPRON EN MODALIDAD EXTERNADO EN UPI MOLINOS, SE RECOMIENDA VALORACIÓN POR TERAPIA OCUPACIONAL TENIENDO EN CUENTA REPITENCIA ESCOLAR Y DIFICULTADES EN ADAPTACIÓN A NORMAS Y FIGURAS DE AUTORIDAD. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 19, 'observaciones' => 'LOS INTEGRANTES DE LA FAMILIA CUENTAN CON RÉGIMEN CONTRIBUTIVO A DIFERENCIA DE JADER QUE CUENTA CON RÉGIMEN SUBSIDIADO; EN RELACIÓN A EDUCACIÓN TODOS LOS MIEMBROS MENORES DEL HOGAR CUENTAN CON COBERTURA Y LA PROGENITORA ESTÁ A PUERTAS DE GRADUARSE COMO ENFERMERA. NINGUNO DE LOS MIEMBROS PRESENTA DISCAPACIDAD. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 6, 'observaciones' => 'LOS INTEGRANTES DE LA FAMILIA CUENTAN CON RÉGIMEN SUBSIDIADO; EN RELACIÓN A EDUCACIÓN TODOS LOS MIEMBROS MENORES DEL HOGAR CUENTAN CON COBERTURA SEGÚN ETAPA DE DESARROLLO. NINGUNO DE LOS MIEMBROS PRESENTA DISCAPACIDAD. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 16, 'observaciones' => 'LA FAMILIA CUENTA CON COBERTURA EN SISTEMA DE SALUD BAJO RÉGIMEN SUBSIDIADO, EN RELACIÓN A EDUCACIÓN ÁNGELA SE ENCUENTRA VINCULADA AL IDIPRON EN MODALIDAD EXTERNADO EN UPI MOLINOS, PRESENTANDO BAJA INASISTENCIA MOTIVOS POR LOS CUALES SE FIRMAN COMPROMISOS CON EL PROGENITOR.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 36, 'observaciones' => 'LA FAMILIA ES DE TIPOLOGIA RECONSTITUIDA POR LINEA MATERNA, EL GRUPO FAMILIAR ESTA COMPUESTO POR 3 PERSONAS CON RELACIONES DE RESPETO ENTRE ELLAS. TODOS LOS MIEMBROS DEL SISTEMA FAMILIAR SE ENCUENTRAN AFILIADOS AL SISTEMA DE SALUD REGIMEN SUBSIDIADO. NO HAY INTEGRANTES CON PROBLEMAS DE TALLA, PESO O DISCAPACIDAD. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 70, 'observaciones' => 'DOLESCENTE CON ANTECEDENTE DE ABANDONO, POR PARTE DE PROGENITORES, LA CUSTODIA LA POSEE ABUELA MATERNA DESDE EL AÑO 2012', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 33, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 66, 'observaciones' => 'EL PROGENITOR NO VIVE CON LOS MENORES DE EDAD, DESDE EL CONFLICTO FAMILIAR Y DEBIDO A LA VENTA DE LA CASA SIN AUTORIZACION DE LA PROGENITORA.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 32, 'observaciones' => 'VIVIENDA DE 1 PISO CON SERVICIOS DE AGUA LUS GAS NATURAL RECOLECCION DE BASURAS Y ALCANTARILLADO', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 83, 'observaciones' => 'CONVIVE LA PROGENITORA, SUS TRES HIJOS, LA SEÑORA SANDRA QUIEN ES LA PRIMA MATERNA, LLEGO A VIVIR CON ELLOS HACE QUINCE DIAS, LOS TRES NIÑOS SE ECNUENTRAN ESTUDIANDO, LA PROGENITORA RECIENTEMENTE SE FUA A TRABAJAR INTERNA EN EL MUNICIPIO DE LA MESA CUNDINAMARCA ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 25, 'observaciones' => 'CONVIVE LA PROGENITORA, SUS TRES HIJOS, LA SEÑORA SANDRA QUIEN ES LA PRIMA MATERNA, LLEGO A VIVIR CON ELLOS HACE QUINCE DIAS, LOS TRES NIÑOS SE ECNUENTRAN ESTUDIANDO, LA PROGENITORA RECIENTEMENTE SE FUA A TRABAJAR INTERNA EN EL MUNICIPIO DE LA MESA CUNDINAMARCA ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 28, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 29, 'observaciones' => 'LA FAMILIA SE ENCUENTRA AFILIADA AL REGIMEN DE SALUD SUBSIDIADA Y CUENTAN CON EL DOCUMENTO DE IDENTIDAD EN FISICO EL MENOR SE ENCUENTRAN DESESCOLARIZADOS ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 85, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 87, 'observaciones' => 'EL SISTEMA FAMILIAR DE TIPOLOGÍA RECONSTITUIDO SE ENCUENTRA CONFORMADO POR LA PROGENITORA, EL PADRASTRO Y 4 HIJOS MENORES DE EDAD. CUENTAN CON EL DOCUMENTO EN FÍSICO Y AFILIACIÓN AL SISTEMA DE SEGURIDAD SOCIAL, MEDIANTE EL REGIMEN SUBSIDIADO EN LA EPS COMPARTA EN ACEVEDO (HUILA) , POR LO CUAL SE ORIENTA A LA ACUDIENTE PARA REALIZAR LA PORTABILIDAD DEL SERVICIO A BOGOTÁ, CON EL FIN DE ACCEDER A LA ATENCIÓN EN ESTA CIUDAD. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 48, 'observaciones' => 'EN LA VIVIENDA HABITAN LA SEÑORA LUCILA, 2 HERMANOS DE MAICOL, UNA PRIMA Y SU HIJA, TODOS LOS MENORES DE EDAD SE ENCUENTRAN ESTUDIANDO Y LA PRIMA DE MAICOL TAMBIEN EN LA UPI MOLINOS. TODO EL GRUPO FAMILIAR CUENTA CON AFILIACION A SALUD REGIMEN SUBSIDIADO, LA SEÑORA LUCILA ACTUAMENTE PRESENTA BAJO PESO POR LA ENFERMEDAD QUE PADECE', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 84, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 9, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 3, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 50, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 4, 'observaciones' => 'FAMILIA MONOPARENTAL PATERNA, SE REFIERE TENCIÓN PRO ANTECEDENTE DE VIOLENCIA, SE REGISTRA REGISTROS EMOCIONALES PARA SUPERAR LA ADVERSIDAD.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 35, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 54, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 10, 'observaciones' => 'NINGUN MIEMBRO DEL NÚCLEO FAMILIAR SE IDENTIFICA CON NINGUN GRUPO ETNICO, ACTUALMENTE DE LA TIA MATERNA NO LABORA, SE ENCUENTRA EN LE HOGAR, SUPAREJA LABORA COMO INDEPENDIENTE. EL NUCLEO FAMILIAR SE ENCUENTRA AFILIADO EL REGIMEN DE SALUD CONTRIBUTIVO NO TINEN NINGUNA DISCAPACIDAD. TODOS LOS MIEMBROS DE LA FAMILIA SABEN LEER, ESCRIBIR Y OPERACIONES MATEMATICAS A EXCEPCION DE LOS 2 PRIMOS D LA ADOLESCENTE QUEINES SE ENCUENTRAN EN EDUCACION PREESCOLAR. LA TIA MATERNA, SU APREJA E HIJO SON BACHILLERES. LOS MENORES DE EDAD SE ENCUENTRA ESCOLARIZADOS. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 8, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 13, 'observaciones' => 'FAMILIA CONVIVIENTE PADRES, HIJOS, Y TIA ABUELA MATERNA, LA FAMILIA SE RESPONSABILIZA DE LA TÍA ABUELA YA QUE ELLA NO CUENTA CON MÁS FAMILIA QUE PUEDA HACERSE CARGO DE SUS GASTOS, LA SEÑORA ADELINA NO CUENTA CON NINGÚN APOYO ECONÓMICO.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 51, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 15, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 67, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 7, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 12, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 11, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 43, 'observaciones' => 'EL COMPAÑERO SENTIMENTAL DE JUANA PALACIOS ES RECOCLADOR DE RESIDUOS SOLIDOS, JUANA VA A LOS SEMAFOROS Y VENDE BOLSAS DE BASURAS', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 80, 'observaciones' => 'LA FAMILIA SE ENCUENTRA AFILIADA AO REGIMEN DE SALUD CONTRIBUTIBITIVO Y CUENTAN CON EL DOCUMENTO DE IDENTIDAD EN FISICO Y LAS MENORES SE ENCUENTRAN DESESCOLARIZADAS ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 73, 'observaciones' => 'LA SEÑORA MARIA DEL CARMEN CORDOBA ESCOBAR, REFIERE DESAPARICION DE HIJA JESSICA LEZCANO QUIEN ES PROGENITORA DE ALMER, LA FAMILIA TIENE ANTECEDENTES', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 63, 'observaciones' => 'LA FAMILIA SE ENCUENTRA AFILIADA AO REGIMEN DE SALUD SUBSIDIADA Y CUENTAN CON EL DOCUMENTO DE IDENTIDAD EN FISICO Y UNA DE LAS MENORES SE ENCUENTRA DESESCOLARIZADAS', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 40, 'observaciones' => 'HAY AUSENSIA', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 53, 'observaciones' => 'LA NIÑA PERMANECE EN CALLE DESD ELA 1:00 PM HASTA LAS 7:00PM "JUGANDO" PRESENTA PARES NEGATIVOS, QUE CONSUMEN SPA', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 41, 'observaciones' => 'SE LE IDENTIFICO QUE LOS 3 MENORES DE EDAD SON DE DIFERENTES PROGENITOR, PERO HAY NEGLIGENCIA POR PARTE DE TODOS EN EL CUIDADO DE LOS NIÑOS.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 30, 'observaciones' => 'LA FAMILIA SE ENCUENTRA AFILIADA AL REGIMEN DE SALUD SUBSIDIADA Y CUENTAN CON EL DOCUMENTO DE IDENTIDAD EN FISICO EL MENOR SE ENCUENTRAN DESESCOLARIZADOS ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 52, 'observaciones' => 'FAMILIA DE TIPOLOGÌA MONOPARENTAL MATERNA; EL NÚCLEO CONVIENTE SE ENCUENTRA CONFORMADO POR LA PROGENITORA, TRES HIJOS MENORES DE EDAD Y DOS MAYORES DE EDAD, LA NUERA Y NIETO DE 8 MESES. LOS MIEMBROS DE LA FAMILIA MAYORES DE EDAD SE ENCUENTRAN VINCULADOS LABORALMENTE, LOS MENORES DE EDAD SE ENCUENTRAN VINCULADOS ACADEMICAMENTE; CUENTAN CON ACCESO A SEGURIDAD SOCIAL POR MEDIO DEL REGIMEN SUBSIDIADO. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 49, 'observaciones' => 'FAMILIA DE TIPOLOGÌA MONOPARENTAL MATERNA A CARGO DE 3 ADOLESCENTES DE 17 AÑOS, 15 AÑOS Y 14 AÑOS RESPECTIVAMENTE, LA PROGENITORA CUENTA CON CONTRATO A TÈRMINO FIJO, LAS MENORES DE EDAD SE ENCUENTRAN ESCOLARIZADAS Y VINCULADAS AL SISTEMA DE SEGURIDAD SOCIAL EN EPS SANITAS EN REGIMEN CONTRIBUTIVO.LA PROGENITORA REALIZA REINTEGRO FAMILIAR DE SUS HIJAS MAYORES JUANA Y LEIDY, JENIFER CONTINUA PROCESO EN MODALIDAD DE INTERNADO EN EL INSTITUTO.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 2, 'observaciones' => 'ACTUALMENTE EL NÚCLEO CONVIVIENTE SE ENCUENTRA CONFORMADO POR LA PROGENITORA, EL PADRASTRO Y MARÌA ANGELICA; LAS HIJAS MENORES DE 12 Y 9 AÑOS RESIDEN EN VENEZUELA CON EL PROGENITOR. LA SEÑORA REFIERE QUE ELLA Y SU PAREJA CUENTAN CON ESTADIA LEGALIZADA EN BOGOTÀ, LA ADOLESCENTE NO CUENTA CON ESTA AUTORIZACIÒN . EL PADRASTRO LABORA DE MANERA INDEPENDIENTE COMO VENDEDOR INFORMAL , LA PROGENITORA SE DEDICA AL HOGAR Y LA BÚSQUEDA DE EMPLEO . LOS MIEMBROS DE LA FAMILIA NO CUENTAN CON VINCULACIÒN A SEGURIDAD SOCIAL.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 18, 'observaciones' => 'EL NÚCLEO CONVIVIENTE SE ENCUENTRA CONFORMADO POR EL PADRE DE CRIANZA, LA PROGENITORA Y LA ADOLESCENTE; EN LA MISMA VIVIENDA HABITA LA TÍA Y ABUELA MATERNA EN EL PRIMER NIVEL, PREPARAN LA ALIMENTACIÒN POR SEPARADO. LOS MIEMBROS DE LA FAMILIA EN ETAPA PRODUCTIVA CUENTAN CON VINCULACIÒN LABORAL, ASÍ MISMO LOS INTEGRANTES DEL GRUPO FAMILIAR SE ENCUENTRAN AFILIADOS AL SISTEMA DE SEGURIDAD SOCIAL, LA ADOLESCENTE SE ENCUENTRA ESCOLARIZADA EN LA ESCUAL PEDAGOGICA IDIPRON.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 86, 'observaciones' => 'FAMILIA DE TIPOLOGÌA MONOPARENTAL MATERNA A CARGO DE 7 HIJOS MENORES DE EDAD, LOS MIEMBROS DE LA FAMILIA CUENTAN CON EL DOCUMENTO DE IDENTIDAD EN FÌSICO , SE ENCUENTRAN VINCULADOS AL SISTEMA DE SEGURIDAD SOCIAL MEDIANTE EL REGIMEN SUBSIDIADO , 6 DE LOS MENORES DE EDAD SE ENCUENTRAN ESCOLARIZADOS, ESTEBAN DE 13 AÑOS DE EDAD NO CUENTA CON VINCULACIÓN ACADÉMICA , LA PROGENITORA REFIERE QUE SE DEBE A QUE ESTA GESTIONANDO VINCULACIÓN A MODALIDAD DE INTERNADO.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 20, 'observaciones' => 'FAMILIA DE TIPOLOGÍA NUCLEAR, CONFORMADA POR LOS PROGENITORES Y TRES HIJOS MENORES DE EDAD, CUENTAN CON DOCUMENTO DE IDENTIDAD EN FÍSICO, SE ENCUENTRAN VINCULADOS AL SISTEMA DE SEGURIDAD SOCIAL MEDIANTE EL RÉGIMEN SUBSIDIADO . EVELYN DE 16 AÑOS Y KAROL DE 13 AÑOS SE ENCUENTRAN EN MODALIDAD DE INTERNADO POR PROTECCIÓN DONDE CUENTAN CON VINCULACIÓN AL SISTEMA EDUCATIVO, BAYRON DE 12 AÑOS CURSA ACELERACIÓN 1 EN INSTITUCIÓN EDUCATIVA DEL SECTOR DE RESIDENCIA.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 72, 'observaciones' => 'EL NÚCLEO CONVIVIENTE SE ENCUENTRA CONFORMADO POR LA ABUELA MATERNA Y LA ADOLESCENTE, QUIENES CUENTAN CON SU DOCUMENTO DE IDENTIDAD EN FÍSICO Y VINCULACIÓN AL SISTEMA DE SEGURIDAD SOCIAL. LA FAMILIA NO CUENTA CON REDES DE APOYO QUE FAVOREZCAN LA CALIDAD DE VIDA DE LA ABUELA MATERNA Y LA ADOLESCENTE; PROGENITORES AUSENTES DEL CUIDADO Y CRIANZA DE ANGELY.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 39, 'observaciones' => 'EL NÚCLEO CONVIVIENTE SE ENCUENTRA CONFORMADO POR LA PROGENITORA, DANIEL DE 19 AÑOS Y DAYAN DE 15 AÑOS; EL HIJO MAYOR JEFERSON DE 24 AÑOS CONVIVE CON LA ABUELA MATERNA, MANTIENE RELACIÓN DISTANTE CONFLICTIVA A NIVEL MATERNO FILIAL Y FRATERNAL. LOS INTEGRANTES DEL GRUPO FAMILIAR CUENTA CON DOCUMENT0 DE IDENTIDAD EN FÍSICO, SE ENCUENTRAN VINCULADOS AL SISTEMA DE SEGURIDAD SOCIAL . LA MENOR DE EDAD ESTA MATRICULADA EN LA ESCUELA PEDAGOGICA DE IDIPRON EN EL AÑO EN CURSO. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 26, 'observaciones' => 'FAMILIA DE TIPOLOGÍA MONO PARENTAL MATERNA A CARGO DE UNA HIJA ADOLESCENTE DE 13 AÑOS DE EDAD, CUENTAN CON EL DOCUMENTO DE IDENTIDAD EN FÍSICO;AFILIACIÓN AL SISTEMA DE SEGURIDAD SOCIAL POR MEDIO DEL RÉGIMEN SUBSIDIADO. LA FAMILIA NO CUENTA CON REDES DE APOYO EN EL CUIDADO Y SUPERVISIÓN QUE LA ADOLESCENTE REQUIERE.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 55, 'observaciones' => 'EL GRUPO FAMILIAR LO CONFORMAN EL PROGENITOR, LA ABUELA PATERNA Y DIANA PATRICIA, LAS HIJAS MAYORES VIVEN DE MANERA INDEPENDIENTE, MANTIENEN RELACIÓN CERCANA Y DE COLABORACIÓN CON LA FAMILIA. LOS MIEMBROS DEL NÚCLEO CONVIVIENTE CUENTAN CON EL RESPECTIVO DOCUMENTO EN FÍSICO, SE ENCUENTRAN VINCULADOS AL SISTEMA DE SEGURIDAD SOCIAL, MEDIANTE EL REGIMEN SUBSIDIADO; LA MENOR DE EDAD SE ENCUENTRA VINCULADA A LA ESCUELA PEDAGOGICA IDIPRON.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 88, 'observaciones' => 'EL SISTEMA FAMILIAR DE TIPOLOGÍA RECONSTITUIDO SE ENCUENTRA CONFORMADO POR LA PROGENITORA, EL PADRASTRO Y 4 HIJOS MENORES DE EDAD. CUENTAN CON EL DOCUMENTO EN FÍSICO Y AFILIACIÓN AL SISTEMA DE SEGURIDAD SOCIAL, MEDIANTE EL REGIMEN SUBSIDIADO EN LA EPS COMPARTA EN ACEVEDO (HUILA) , POR LO CUAL SE ORIENTA A LA ACUDIENTE PARA REALIZAR LA PORTABILIDAD DEL SERVICIO A BOGOTÁ, CON EL FIN DE ACCEDER A LA ATENCIÓN EN ESTA CIUDAD. ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 71, 'observaciones' => 'FAMILIA COMPUESTA POR CINCO MIEMBROS , LA TÍA DE 38 AÑOS PRESENTA DISCAPACIDAD COGNITIVA LEVE/DEPENDE DEL CUIDADO DE LA ABUELA MATERNA; LA ABUELA SE DESEMPEÑA COMO VENDEDORA AMBULANTE . LAS MENORES DE EDAD SE ENCUENTRAN VINCULADAS A SALUD EN RÉGIMEN SUBSIDIADO Y SE ENCUENTRA VINCULADAS A EDUCACIÓN.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 57, 'observaciones' => 'LA FAMILIA CUENTA CON DOCUMENTO EN FISICO Y SE ENCUENTRA AFILIADA AL REGIMEN DE SALUD SUBSIDIADO ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 90, 'observaciones' => 'FAMILIA EXTENSA ESTAN AFILIADOS A REGIMEN DE SALUD SUBSIDIADO; KAREN YULIETH ESTA EN TRAMITE PARA SU AFILIACION A SALUD. LA INFANTE SOFIA DE 8 MESES PRESENTA DISCAPACIDAD FISICA MOTORA', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 75, 'observaciones' => 'LA FAMILIA CUENTA CON DOCUMENTO EN FISICO Y SE ENCUENTRA AFILIADA AL REGIMEN DE SALUD SUBSIDIADO ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 23, 'observaciones' => 'LA FAMILIA CUENTA CON DOCUMENTO EN FISICO Y SE ENCUENTRA AFILIADA AL REGIMEN DE SALUD SUBSIDIADO ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 31, 'observaciones' => 'LA FAMILIA CUENTA CCON DOCUMENTOS DE IDENTIDAD Y SE ENCUENTRAN REGISTRADOS AL REGIMEN DE SALUD SUBSIDIADO ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 69, 'observaciones' => ' GRUPO FAMILIAR AFILIADO A REGIMEN DE SALUD SUBSIDIADO Y NO REFIEREN DISCAPACIDAD', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 82, 'observaciones' => ' CASUSA DEL ALTO CONSUMO DE ALCOHOL DEL SEÑOR MARTIN. EN CUANTO A LAS RELACIONES CON LOS MENORES EL SEÑOR MARTIN EJERCE VIOLENCIA VERBAL CON LUISA DEBIDO A QUE ÉL ES EL PROVEEDOR ECONÓMICO DEL HOGAR, POR OTRO LADO CON SU HIJO BIOLÓGICO NO SE PRESENTAN HECHOS RELEVANTES', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 5, 'observaciones' => 'EN CUANTO A LAS RELACIONES EN EL HOGAR EL PADRASTRO DE NATALIA ES IDENTIFICADO COMO ROL PROTECTOR PARA LA FAMILIA, SIENDO EL MEDIADOR ENTRE LOS MIEMBROS DEL HOGAR, BRINDADO PROTECCIÓN Y ESTABILIDAD EN EL HOGAR.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 17, 'observaciones' => 'REFERENTE A LA RELACIÓN ENTRE MADRE E HIJA, COMENTAN QUE A PARTIR DEL PROCESO DE LA ADOLESCENTE EN LA UNIDAD, HAN OBTENIDO BENEFICIOS Y MEJORÍA EN ASPECTOS A NIVEL INDIVIDUAL Y FAMILIAR, FAVORECIENDO LAS DINÁMICAS DEL HOGAR, ENTRE ESOS AVANCES SE EVIDENCIA: UNA ADECUADA COMUNICACIÓN Y RELACIÓN, ESTABLECIMIENTO Y CUMPLIMIENTO DE LÍMITES Y NORMAS, USO DEL DIALOGO PARA LA RESOLUCIÓN DE CONFLICTOS, FORTALECIMIENTO DEL RESPETO Y LA CONFIANZA, UNIÓN FAMILIAR, ADECUADOS ESTILOS DE CRIANZA Y MANEJO DE CONTINGENCIAS', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 79, 'observaciones' => 'CON SU RED FAMILIAR SE DEBE TRABAJAR COMUNICACIÓN ASERTIVA, PAUTAS DE CRIANZA, USO ADECUADO DE CANALES DE COMUNICACIÓN, ES EVIDENTE QUE TANTO EN LO FAMILIAR COMO EN LO INDIVIDUAL LES HA CONSTADO ACCEDER A ESTOS ESPACIOS Y SOBRE TODO TENER ACCESO A ESCENARIOS REFLEXIVOS', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 42, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 22, 'observaciones' => 'ULTIMO GRADO CURSADO DE DARLIN 5° DE PRIMARIA JM EN EL COLEGIO ANTONIO JOSE URIBE. ULTIMO GRADO CURSADO DE DANNA 1° JM EN EL COLEGIO ANTONIO JOSE URIBE', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 68, 'observaciones' => 'EL PROGENITOR NO VIVE CON LOS NIÑOS POR LA VIOLENCIA INTRAFAMILIAR EJERCIDA HACIA LA PROGENITORA, COMO TAMBIEN POR CONDUCTAS DELECTIVAS Y CONSUMO DE SPA.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 47, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 37, 'observaciones' => 'LA FAMILIA SE ENCUENTRA AFILIADA AL REGIMEN DE SALUD SUBSIDIADA Y CUENTAN CON EL DOCUMENTO DE IDENTIDAD EN FISICO EL MENOR SE ENCUENTRA DESESCOLARIZADO ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 81, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 1, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 56, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 89, 'observaciones' => 'GRUPO FAMILIAR QUE NO PRESENTAN DISCAPACIDAD, ESTAN AFILIADOS A REGIMEN DE ALUD CONTRIBUTIVO Y SON DESPLAZADOS DEL HUILA', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 21, 'observaciones' => 'GRUPO FAMILIAR EN REGIMEN DE SALUD SUBSIDIADO, SEBASTIAN PRESENTA DISCAPACIDAD MOTRIZ Y LOS DEMAS NO PRESENTAN DISCAPACIDAD', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 91, 'observaciones' => 'GRUPO FAMILIAR EN REGIMEN DE SALUD SUBSIDIADO Y NO REPORTAN DISCAPACIDAD', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 77, 'observaciones' => 'GRUPO FAMILIAR QUE NO REPORTA DISCAPACIDAD. KAREN NO TIENE EPS, PORQUE NECESITA PAPELES FIRMADOS DE SU PROGENITORA', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 62, 'observaciones' => 'GRUPO FAMILIAR AFILIADO A REGIMEN DE SALUD SUBSIDIADO EXCEPTO EL PADRASTRO QUE NO TIENE AFILIACION A REGIMEN DE SALUD, NO REPORTAN DISCAPACIDAD', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 45, 'observaciones' => 'GRUPO FAMILIAR QUE NO PRESENTA DISCAPACIDAD, AFILIADOS A SALUD, JEAN PAUL SE ENCUENTRA DESESCOLARIZADO', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 59, 'observaciones' => 'SE ENCUENTRA QUE TODOS LOS MENORES DE EDAD ESTAN ESTUDIANDO, AFILIADOS ASEGUIRIDAD SOCIAL CAPITAL SALUD . SE ENCUENTRAN BUSCANDO CUOS ACADEMICOS CERCA A SU CASA. NO CONDICION DE DISCAPACIDAD EN NINGUN MIEMBRO.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 44, 'observaciones' => 'EL COMPAÑERO SENTIMENTAL DE JUANA PALACIOS ES RECOCLADOR DE RESIDUOS SOLIDOS, JUANA VA A LOS SEMAFOROS Y VENDE BOLSAS DE BASURAS', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 65, 'observaciones' => 'SE OBSERVO QUE LOS NIÑOS PERMANECEN TODO EL TIEMPO FUERA DE LA VIVIENDA POR LA PERMISIVIDAD DE LA PROGENITORA. LA PROGENITORA REFIERE QUE LOS NIÑOS CONOCEN MUCHAS COSAS QUE HAN VISTO EN EL CONTEXTO BARRIAL A PESAR DE LA CORTA EDAD', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 61, 'observaciones' => 'EL NUCLEO FAMILIAR PROVENIENTE DEL DEPARTAMENTO DEL CHOCO POR DESPLAZAMIENRO GENERADO POR LA GUERRILLA DEBIDO A LA EXPLOTACION DE MINAS DE ORO.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 76, 'observaciones' => 'JESUS DAVID ESTUDIABA EN EL 2019 EN EL COLEGIO SEDE TANQUE LAGUNA HASTA EL MES DE MARZO SEDESMOTIVO ACADEMICAMENTE Y NO HA VUELTO AL COLEGIO', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 60, 'observaciones' => 'LA FAMILIA SE ENCUENTRA AFILIADA AO REGIMEN DE SALUD SUBSIDIADO Y CUENTAN CON EL DOCUMENTO DE IDENTIDAD EN FISICO ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 34, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 58, 'observaciones' => 'LA FAMILIA CUENTA CON DOCUMENTO EN FISICO Y SE ENCUENTRA AFILIADA AL REGIMEN DE SALUD SUBSIDIADO ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 64, 'observaciones' => 'TODOS LOS MIEMBROS SE ENCUENTRAN AFILIADOS AL REGIMEN SUBSIDIADO. EL PROGENITOR TIENE UNA DISCPACIDAD DE TIPO FISICA EN UNA DE SUS MANOS, LA CUAL ESTA DIAGNOSTICADA.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 38, 'observaciones' => 'GRUPO FAMILIAR AFILIADO A REGIMEN DE SALUD CONTRIBUTIVO, LA ABUELA PRESENTA DISCAPACIDAD', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 46, 'observaciones' => ' ', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 24, 'observaciones' => 'FAMILIA EXTENSA, TODOS AFILIADOS AL REGIMEN SUBSIDIADO, LA MAYORIA DE LOS INTEGRANTES NO CONCLUYERON SUS ESTUDIOS.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 74, 'observaciones' => 'SE ENCUENTRA QUE EL SISTEMA FAMILIAR SE ENCUENTRA AFILIADO AL REGIMEN CONTRIBUTIVO DE SEGURIDAD SOCIAL', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 92, 'observaciones' => 'SE ENCUENTRA QUE LOS MIEMBROS ESTAN AFILIADOS A SISTEMA DE SALUD.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
        CsdComfamob::create(['csd_id' => 27, 'observaciones' => 'TODOS LOS MIEMBROS AFILIADOS AL REGIMEN SUBSIDIADO, NO PRESENTAN PROBLEMAS DE PESO O TALLA, NO PRESENTAN CONDICION DE DISCAPACIDAD.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1, 'prm_tipofuen_id' => 2316]);
    }
}
