<?php
use App\Models\consulta\CsdGenIngreso;
use Illuminate\Database\Seeder;

class CsdGenIngresoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CsdGenIngreso::create(['id'=>1,'csd_id'=>1, 'observacion'=>'', 'trabaja'=>'EMPACADORA ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'367','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'LA HERMANA IDENTIFICA DIFICULTADES ECONÓMICAS POR LA FALTA DE EMPLEOS FORMALES LO QUE SE CONSIDERA UN RIESGO LATENTE YA QUE SE ENCUENTRAN EN LA CONSTRUCCIÓN DE LA VIVIENDA Y MANUTENCIÓN DE JOEL. ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>2,'csd_id'=>2, 'observacion'=>'', 'trabaja'=>'SERVICIOS GENERALES','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'613','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'LA ABUELA PATERNA REFIERE DIFICULTADES ECONÓMICAS YA QUE LOS PROGENITORES DE LA MENOR NO APORTAN DE MANERA REGULAR CON CUOTA DE MANUTENCIÓN. ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>3,'csd_id'=>3, 'observacion'=>'', 'trabaja'=>'NIGUNA','prm_actividad_id'=>627, 'prm_informal_id'=>811,'prm_otra_id'=>259, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'613','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'LOS CÓNYUGES IDENTIFICAN DIFICULTADES ECONÓMICAS, DEBIDO A LA INFORMALIDAD DE LOS EMPLEOS Y EL TIPO DE CONTRATO QUE GENERAN RIEGOS LATENTES EN LA FAMILIA AL CULMINAR LA RELACIÓN LABORAL. ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>4,'csd_id'=>4, 'observacion'=>'', 'trabaja'=>'CAJERA ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'367','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'LA PROGENITORA IDENTIFICA DIFICULTADES ECONÓMICAS, DEBIDO A LA INFORMALIDAD DE SU EMPLEO YA QUE POR SU EDAD SE GENERAN BARRERAS DE ACCESO AL MUNDO LABORAL TENIENDO QUE ACUDIR A LABORES COMO EL RECICLAJE. ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>5,'csd_id'=>5, 'observacion'=>'', 'trabaja'=>'ORNAMENTADOR','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'367','intensidad'=>'8', 'prm_dificultad_id'=>'228','razon'=>'LOS CÓNYUGES NO IDENTIFICAN DIFICULTADES ECONÓMICAS, SIN EMBARGO LA INFORMALIDAD DEL EMPLEOS Y EL TIPO DE CONTRATO GENERAN RIEGOS LATENTES EN LA FAMILIA YA QUE AL CULMINAR LA RELACIÓN LABORAL SE GENERARÍAN RIESGOS LATENTES ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>6,'csd_id'=>6, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'9', 'prm_dificultad_id'=>'227','razon'=>'LA SEÑORA LILIANA REFIERE QUE LA FAMILIA DE SU PAREJA SENTIMENTAL NO PRESENTA DIFICULTADES ECONOMICAS YA QUE LOGRAN GARANTIZAR LAS NECESIDADES BASICAS DE ALIMENTACION Y VIVIENDA. SIM EMBARGO ES IMPORTANTE MENCIONAR QUE LA SEÑORA LILIANA SI CUENTA CON DIFICULTADES ECONOMICAS DADO QUE HA ESTADO DESEMPLEADA. ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>7,'csd_id'=>7, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LA SEÑORA MARIA CAMACHO NO POSEE PENSIÓN Y EN ESTE MOMENTO EL ABUELASTRO SE ENCUENTRA DESEMPLEADO, CUENTAN CON EL APORTE DE $150,000 DE TIO MATERNO Y TRABAJO OCASIOONAL DE COMPAÑERO.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>8,'csd_id'=>8, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>627, 'prm_informal_id'=>632,'prm_otra_id'=>259, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'SE PRESENTA INESTABILIDAD ECONOMICA POR DESEMPLEO DE LA PROGENITORA E INGRESOS INSUFICIENTES DEL PADRASTRO, SEGÚN REFIERE LA SEÑORA SANDRA NO TIENE CONOCIMIENTO EXACTO DE LOS INGRESOS ECONOMICOS DE SU PAREJA REFIERE UN PROMEDIO DE 600000, LOS CUALES SON INSUFICIENTES PARA EL SUSTENTO DEL SISTEMA FAMILIAR. ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>9,'csd_id'=>9, 'observacion'=>'', 'trabaja'=>'OFICIOS DOMESTICOS Y PLAZA DE MERCADO','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LO CONSEGUIDO ECONOMICAMENTE NO ALCANZA PARA CUBRIR LAS NECECIDADES BASICAS DEL CONJUNTO FAMILIAR.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>10,'csd_id'=>10, 'observacion'=>'', 'trabaja'=>'VENDEDORA INFORMAL ','prm_actividad_id'=>627, 'prm_informal_id'=>632,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'259','intensidad'=>'9', 'prm_dificultad_id'=>'227','razon'=>'BAIRON ESTUBO INTERNADO EN IDIPRON DESDE EL 2016 HASTA EL 2018 SE RETIRO EN ENERO DE 2019 NO QUISO CONTINUAR EN IDIPRON SIN EMBARGO BAIRON TIENE GRAN INTERES DE INGRESAR AL INTERNADO. ACTUALMENTE S EENCUENTRA DESECOLARIZADO YEISON ANDRES CAMARGO-HERMANO DE BAIRON- SE ENCUENTRA INTERNO EN LA FLORIDA POR CONSUMO DE SUSTANCIA PSICOACTIVAS Y PERMANENCIA EN CALLE ACTIVIDADES DELICTIVAS Y RIESGO DE MUERTE DURANTE DOS NOCHES NO LLEGARON A LA CASA.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>11,'csd_id'=>11, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LOS INGRESOS RECIBIDOS SON VARIABLES MENSUALMENTE POR LO QUE EN OCASIONES NO ALCANZA PARA CUBRIR LOS GASTOS ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>12,'csd_id'=>12, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LA UNICA PROVEEDORA ES LA SEÑORA BLANCA Y LOS INGRESOS NO SON SUFICIENTES PARA CUBRIR TODOS LOS GASTOS ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>13,'csd_id'=>13, 'observacion'=>'', 'trabaja'=>'VENTA DE TINTO ','prm_actividad_id'=>627, 'prm_informal_id'=>632,'prm_otra_id'=>259, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>' ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>14,'csd_id'=>14, 'observacion'=>'', 'trabaja'=>'RESTAURANTE ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'5', 'prm_dificultad_id'=>'227','razon'=>'LA FAMILIA NO TIENE DIFICULTADES YA QUE LOS INGRESOS SON SUFICIENTES PARA CUBRIR TODAS LAS NECESIDADES DEL HOGAR ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>15,'csd_id'=>15, 'observacion'=>'', 'trabaja'=>'VENDE BOLSAS Y ROSAS','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'SE OBSERVAN DIFICULTADES ECONOMICAS YA QUE SI LA SEÑORA LUZ AIDA GUTIERREZ HERNANDEZ NO SALE A TRABAJAR NO OBTIENE EL DINERO DE LA ALIMENTACION DIARIA', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>16,'csd_id'=>16, 'observacion'=>'', 'trabaja'=>'JEFE DE COCINA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'614','intensidad'=>'10', 'prm_dificultad_id'=>'228','razon'=>'SEGÚN LA PROGENITORA Y SU PAREJA ACTUAL, LA FAMILIA ACTUALMENTE NO PRESENTA DIFICULTADES DE TIPO ECONÓMICO, PUESTO QUE LOS INGRESOS GENERADOS POR ELLOS, LES PERMITE CUBRIR A CABALIDAD LAS DEMANDAS DE LOS INTEGRANTES DEL NÚCLEO CONVIVIENTE.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>17,'csd_id'=>17, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'EL UNICO INGRESO ES EL DEL BONO DE ADULTO MAYOR QUE SON $120000, CON ESTO DEBE COSTEAR ALIMENTACIÓN DE ELLA Y SUS 4 NIETOS, TAMBIEN DEBE CUBRIR OTROS GASTOS', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>18,'csd_id'=>18, 'observacion'=>'', 'trabaja'=>'OTRA ACTIVIDAD','prm_actividad_id'=>635, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'643','prm_frecuencia_id'=>'613','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'EL PROGENITOR REFIERE PRESETNAR DIFICULTADES PAEA SUPLIR LOS GASTOS DE TRANSPORTE PARA EL DESPLAZAMIENTI DEL ADOLESCENTE A LA UNIDAD .', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>19,'csd_id'=>19, 'observacion'=>'', 'trabaja'=>'OTRA ACTIVIDAD','prm_actividad_id'=>635, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'SOLO SE CUENTRA TRABAJANDO UNA PERSONA LABORANDO Y NO ES SUFICIENTE PARA EL SUSTENTO FAMILIAR', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>20,'csd_id'=>20, 'observacion'=>'', 'trabaja'=>'OFICIOS VARIOS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'SE REPORTA FRAGILIDAD ECONÓMICA POR ESCACES', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>21,'csd_id'=>21, 'observacion'=>'', 'trabaja'=>'VENTA AMBULANTE','prm_actividad_id'=>627, 'prm_informal_id'=>1800,'prm_otra_id'=>259, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'SE PRESENTA FRAGILIDAD ECONOMICA Y SOCIAL', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>22,'csd_id'=>22, 'observacion'=>'', 'trabaja'=>'OFICIOS VARIOS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'367','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'EL PADRE ES EL UNICO APORTANTE.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>23,'csd_id'=>23, 'observacion'=>'', 'trabaja'=>'OTRA ACTIVIDAD','prm_actividad_id'=>635, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'ACTUALMENTE QUIEN GENERA UN INGRESO FIJO ES EL PADRE DE L ADOLESCENTE SU PROGENITORA VARIA LOS INGRESOS YA QUE REALIZO ACTIVIDADES DE TIPO INFORMAL', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>24,'csd_id'=>24, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'SE IDENTIFICA DIFICUTLADES ECONÓMICAS YA QUE LAS CONDICIONES SON LIMITADAS ASI COMO LOS RECURSOS. ADICIONALMENTE LA JOVEN NO GENERA INGRESOS EN LA ACTUALIDAD Y SU RED DE APOYO NO LE COLABORA EN ESTE ASPECTO. TAN SOLO RECIBE AYUDA DE SU PROGENITORA, YA QUE LOS PRGOENITORES DE SUS HIJOS (EX- PAREJA) NO HAN SIDO CORRESPONSABLES ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>25,'csd_id'=>25, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'228','razon'=>'EL NÚCLEO FAMILIAR REFIERE QUE ACTUALMENTE NO PRESENTA DIFICUTLADES ECONÓMICAS Y NO SE IDENTIFICA ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>26,'csd_id'=>26, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'ACTUALMENTE EL PROGENITOR ES EL UNICO QUE APORTA EL SUSENTO ECONÓMICO DEL HOGAR ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>27,'csd_id'=>27, 'observacion'=>'', 'trabaja'=>'VIGILANCIA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'367','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'LOS RECURSOS ECONOMICOS ACTUALES DE LA FAMILIA NO ALCANZAN PARA LOS GASTOS DE LA FAMILIA, PADRE TIENE LA MAYOR RESPONSABILIDAD ECONÓMICA Y LA MADRE APORTA', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>28,'csd_id'=>28, 'observacion'=>'', 'trabaja'=>'COMERCIANTE','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'259','intensidad'=>'6', 'prm_dificultad_id'=>'227','razon'=>'LA SEÑORA MARÍA REFIERE NO TIENE INGRESOS FIJOS POR LOCAL SE LE DIFICULTA PROYECTARSE Y CAMBIR DE LUGAR DE RESIDENCIA', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>29,'csd_id'=>29, 'observacion'=>'', 'trabaja'=>'OPERARIO','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'613','intensidad'=>'8', 'prm_dificultad_id'=>'228','razon'=>'NO SE EVIDENCIA DIFICUTLADES ECONÓMICAS EN EL HOGAR POR LOS INGRESOS DE LA FAMILIA ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>30,'csd_id'=>30, 'observacion'=>'', 'trabaja'=>'SERVICIOS GENERALES','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'644','prm_frecuencia_id'=>'613','intensidad'=>'8', 'prm_dificultad_id'=>'228','razon'=>'LA FAMILIA PRESENTA DIFICUTLADES ECONÓMICAS POR LOS POCOS INGRESOS DE LA FAMILIA ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>31,'csd_id'=>31, 'observacion'=>'', 'trabaja'=>'OFICIOS VARIOS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'367','intensidad'=>'9', 'prm_dificultad_id'=>'227','razon'=>'LOS RECURSOS ECONOMICOS NO ALCANZAN', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>32,'csd_id'=>32, 'observacion'=>'', 'trabaja'=>'OPERARIA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'643','prm_frecuencia_id'=>'367','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'ACTUALMENTE LOS RECURSOS SON POCOS EN LA FAMILIA, DEBIDO A QUE LA PROGENITORA ES LA UNICA PROVEEDORA', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>33,'csd_id'=>33, 'observacion'=>'', 'trabaja'=>'MAQUILLADORA DE MUEBLES','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'367','intensidad'=>'16', 'prm_dificultad_id'=>'227','razon'=>'SE EVIDENCIAN DIFICULTADES AL INTERIOR DEL HOGAR PUESTO QUE EL INGRESO PROVIENE SOLO DE LA PROGENITORA.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>34,'csd_id'=>34, 'observacion'=>'', 'trabaja'=>'VENDER BOLSAS DE BASURA','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'HABITABILIDAD PRECARIA, LA VIVIENDA NO CUENTA CON INODORO, SE BAÑAN CON BALDE, LA VIVIENDA SE ENCUENTRA EN CONDICIONES INSALUBRES', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>35,'csd_id'=>35, 'observacion'=>'', 'trabaja'=>'SEGURIDAD ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'643','prm_frecuencia_id'=>'367','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'SY PRESENTAN DIFICULTADES ECONOMICAS YA QUE EL PROGENITOR TIENE QUE PGAR ARRIENDO SERVICIOS Y TRANSPORTES ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>36,'csd_id'=>36, 'observacion'=>'', 'trabaja'=>'VENDER BOLSAS DE BASURA','prm_actividad_id'=>627, 'prm_informal_id'=>632,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'4', 'prm_dificultad_id'=>'227','razon'=>'LA PROGENITORA REFIERE QUE HAN PASADO SITUACION ECONOMICA PRECARIA YA QUE NO POSEE EMPLEO, EL INGRESO DEL HOGAR PROVIENE DE LA VENTA DE BOLSAS DE BASURA', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>37,'csd_id'=>37, 'observacion'=>'', 'trabaja'=>'RECICLAJE ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'10', 'prm_dificultad_id'=>'227','razon'=>'SY PRESENTAN DIFICULTADES ECONOMICAS YA QUELOS INGRESOS NO SON SUFICIENTES CARA CUBRIR LAS NECESIDADS DEL HOGAR', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>38,'csd_id'=>38, 'observacion'=>'', 'trabaja'=>'GUARDA DE SEGURIDAD','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'228','razon'=>' ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>39,'csd_id'=>39, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'SE OBSERVA DESEMPLEO EN EL NUCLEO FAMILIA', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>40,'csd_id'=>40, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>627, 'prm_informal_id'=>634,'prm_otra_id'=>259, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'NO EXISTE LA MAS MINIMA GARANTIA DE BIENESTAR EN EL GRUPO FAMILIAR POR LAS DIFICULTADES ECONOMICAS.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>41,'csd_id'=>41, 'observacion'=>'', 'trabaja'=>'RESTAURANTE ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'5', 'prm_dificultad_id'=>'227','razon'=>'LA FAMILIA NO TIENE DIFICULTADES YA QUE LOS INGRESOS SON SUFICIENTES PARA CUBRIR TODAS LAS NECESIDADES DEL HOGAR ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>42,'csd_id'=>42, 'observacion'=>'', 'trabaja'=>'VENTA AMBULANTE','prm_actividad_id'=>627, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'7', 'prm_dificultad_id'=>'227','razon'=>'TOMANDO COMO PUNTO DE REFERENCIA LA INFORMACIÒN SUMINISTRADA POR LA PROGENITORA,SE CONSIDERA QUE EL SISTEMA FAMILIAR PRESENTA DIFICULTADES DE TIPO ECONÓMICO, PUESTO QUE LOS INGRESOS SON INSUFICIENTES PARA CUBRIR LAS DEMANDAS DE LOS INTEGRANTES DE LA FAMILIA, POR LO CUAL PRIORIZAN SUS GASTOS Y NECESIDADES.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>43,'csd_id'=>43, 'observacion'=>'', 'trabaja'=>'OFICIAL DE CONSTRUCCIÒN','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'367','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'DE ACUERDO A LA INFORMACIÒN SUMINISTRADA POR LA PROGENITORA, LA FAMILIA PRESENTA DIFICULTADES PARA CUBRIR LAS DEMANDAS DE LOS INTEGRANTES DEL NÙCLEO CONVIVIENTE, TENIENDO EN CUENTA QUE JUANA Y LEIDY SE REINTEGRARON A MEDIO FAMILIAR ASPECTO QUE INCREMENTO LOS GASTOS.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>44,'csd_id'=>44, 'observacion'=>'', 'trabaja'=>'LA PROGENITORA SE DEDICA AL HOGAR.','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'16', 'prm_dificultad_id'=>'227','razon'=>'DE ACUERDO A LO OBSERVADO EN LA CONSULTA SOCIAL EN DOMICILIO Y LOS INGRESOS REFERIDOS POR LA PROGENITORA, SE IDENTIFICA QUE LA FAMILIA PRESENTA DIFICULTADES DE TIPO ECONÓMICO, PUESTO QUE LOS INGRESOS GENERADOS POR EL PADRASTRO SON INSUFICIENTES PARA SUPLIR LAS DEMANDAS DE LOS MIEMBROS DEL NÚCLEO CONVIVIENTE.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>45,'csd_id'=>45, 'observacion'=>'', 'trabaja'=>'TRANSPORTE DE PASAJEROS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'228','razon'=>'TENIENDO EN CUENTA LOS INGRESOS FAMILIARES REPORTADOS POR EL ACUDIENTE, SE CONSIDERA QUE LA FAMILIA NO PRESENTA DIFICULTADES ECONÓMICAS, PUESTO QUE LOGRAN CUBRIR A CABALIDAD LAS DEMANDAS DE LOS INTEGRANTES DEL NÚCLEO CONVIVIENTE.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>46,'csd_id'=>46, 'observacion'=>'', 'trabaja'=>'VENTA AMBULANTE Y ACTIVIDADES DE TIPO DOMÉSTICO.','prm_actividad_id'=>627, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'TENIENDO EN CUENTA LOS INGRESOS ECONÓMICOS REPORTADOS POR LA ACUDIENTE Y LO OBSERVADO EN LA CONSULTA SOCIAL EN DOMICILIO SE CONSIDERA QUE UNA DE LAS PRINCIPALES PROBLEMÁTICAS DE LA FAMILIA, SON LAS DIFICULTADES DE TIPO ECONÓMICO , PUESTO QUE NO LOGRAN SUPLIR A CABALIDAD LAS NECESIDADES BÁSICAS.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>47,'csd_id'=>47, 'observacion'=>'', 'trabaja'=>'OFICIOS VARIOS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'DE ACUERDO A LO EVIDENCIADO EN LA CONSULTA SOCIAL Y LOS INGRESOS ECONÓMICOS REFERIDOS POR LOS PROGENITORE, SE CONSIDERA QUE LA FAMILIA PRESENTA SITUACIÓN ECONÓMICA PRECARIA, PUESTO QUE NO LOGRAN SUPLIR NECESIDADES BÁSICAS DE LOS MIEMBROS DEL NÚCLEO CONVIVIENTE.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>48,'csd_id'=>48, 'observacion'=>'', 'trabaja'=>'AYUDANTE DE COCINA Y ACTIVIDAD DE RECICLAJE','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'612','intensidad'=>'9', 'prm_dificultad_id'=>'227','razon'=>'SEGÚN LOS INGRESOS REPORTADOS POR LA ACUDIENTE, SE CONSIDERA QUE LA FAMILIA PRESENTA DIFICULTADES DE TIPO ECONÓMICO PUESTO QUE ESTOS INGRESOS RESULTAN INSUFICIENTES PARA CUBRIR LAS DEMANDAS DE LOS INTEGRANTES DE LA FAMILIA; AUNADO A RECIENTE SEPARACIÓN DE LA SEÑORA CONSUELO DE SU EX PAREJA QUIÉN LE BRINDABA APOYO ECONÓMICO.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>49,'csd_id'=>49, 'observacion'=>'', 'trabaja'=>'OPERARIA DE LAVADO','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'613','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'SEGÚN LA INFORMACIÓN SUMINISTRADA POR LA PROGENITORA, LOS INGRESOS ECONÓMICOS DE LA FAMILIA SON INSUFIENTES PARA CUBRIR LAS DEMANDAS DE LOS INTEGRANTES DEL NÚCLEO CONVIVIENTE, POR LO CUAL DEBE ORGANIZAR Y PRIORIZAR GASTOS MES A MES.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>50,'csd_id'=>50, 'observacion'=>'', 'trabaja'=>'VENTA AMBULANTE','prm_actividad_id'=>627, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'228','razon'=>'LA PROGENITORA MENCIONA QUE SUS INGRESOS ECONÓMICOS SON SUFICIENTES PARA SUPLIR LAS DEMANDAS DE SU HIJA Y LAS PROPIAS. LA FAMILIA NO PRESENTA DIFICULTADES DE TIPO ECONÒMICO.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>51,'csd_id'=>51, 'observacion'=>'', 'trabaja'=>'REPARTIDOR DE CARNES','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'614','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'EL PROGENITOR REFIERE QUE LOS INGRESOS FAMILIARES, SON INSUFICIENTES PARA CUBRIR LAS DEMANDAS DE LOS INTEGRANTES DEL NÚCLEO CONVIVIENTE , POR LO CUAL ES NECESARIO PRIORIZAR GASTOS; SIN EMBARGO LOGRAN COBERTURA DE NECESIDADES BÁSICAS.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>52,'csd_id'=>52, 'observacion'=>'', 'trabaja'=>'JEFE DE COCINA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'614','intensidad'=>'10', 'prm_dificultad_id'=>'228','razon'=>'SEGÚN LA PROGENITORA Y SU PAREJA ACTUAL, LA FAMILIA ACTUALMENTE NO PRESENTA DIFICULTADES DE TIPO ECONÓMICO, PUESTO QUE LOS INGRESOS GENERADOS POR ELLOS, LES PERMITE CUBRIR A CABALIDAD LAS DEMANDAS DE LOS INTEGRANTES DEL NÚCLEO CONVIVIENTE.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>53,'csd_id'=>53, 'observacion'=>'', 'trabaja'=>'EMPLEADA DOMESTICA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'367','intensidad'=>'5', 'prm_dificultad_id'=>'227','razon'=>'LA PROGENITORA MANIFIESTA QUE DADO QUE SE VINCULÓ RECIENTEMENTE AL TRABAJO ACTUAL, ESTÁ PASANDO POR DIFICULTADES ECONÓMICAS YA QUE SE ESTÁ VOLVIENDO A ESTABILIZAS Y A ASUMIR SUS RESPONSABILIDADES.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>54,'csd_id'=>54, 'observacion'=>'', 'trabaja'=>'VENTA DE BEBIDAS','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'SE EVIDENCIA DIFICULTADES ECONOMICAS YA QUE LA SEÑORAES QUIEN RESPONDE POR SUS TRES NIETOS', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>55,'csd_id'=>55, 'observacion'=>'', 'trabaja'=>'VENTA DE TINTOS','prm_actividad_id'=>627, 'prm_informal_id'=>632,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'LA SEÑORA CLARA ES CABEZA DE HOGAR, EL INGRESO ECONOMICO ES DIARIO Y NO ALCANZA PARA CUBRIR LAS NECESIDADES DEL HOGAR. LA SEÑORA CLARA REFIERE QUE SUS HIJOS MAYORES NO CONSIGUEN TRABAJO', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>56,'csd_id'=>56, 'observacion'=>'', 'trabaja'=>'AUXILIAR DE COCINA ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'SE EVIDENCIA DIFICULTADES ECONOMICAS YA QUE LA SEÑORA O CUENTA CON UN TRABAJO ESTABLE', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>57,'csd_id'=>57, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'SE EVIDENCIA DIFICULTADES ECONOMICAS YA QUE LAS SEÑORAASNO CUENTAN CON UN TRABAJO ESTBLE ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>58,'csd_id'=>58, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'8', 'prm_dificultad_id'=>'228','razon'=>'PORQUE LA POGENITORA SUPLE LAS NECESIDADES DE LA FAMILIA JUNTO AL PADRASTRO QUIEN ES EL PROPIETARIO DE LA VIVIENDA Y PROPORCIONA ALIMENTO A TODOS LOS MIEMBROS DE LA FAMILIA.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>59,'csd_id'=>59, 'observacion'=>'', 'trabaja'=>'EMPLEADO EN LA CENTRAL DE MERCADO EN CORABASTOS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'QUIEN GENERA LOS INGRESOS ES LA MADRASTRA QUIEN TRABAJA MANEJANDO UN CARRO Y EL HERMANASTRO TRABAJA COMO EMPLEADO EN CORABASTOS, EN PLAZA .', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>60,'csd_id'=>60, 'observacion'=>'', 'trabaja'=>'RECICLAJE','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'4', 'prm_dificultad_id'=>'227','razon'=>'LOS INGRESOS ECONOMICOS DEL HOGAR NO SON FIJOS, RAZON POR LA QUE EXISTE AUSENCIA DE ALGUNAS NECESIDADES BASICAS. LO QUE APORTA EL PADRASTROD E LUISA ES INCIERTTO DEBIDO A SU ALTO CONSUMO DE ALCOHOL', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>61,'csd_id'=>61, 'observacion'=>'', 'trabaja'=>'OFICIOS VARIOS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'614','intensidad'=>'5', 'prm_dificultad_id'=>'228','razon'=>'LOS INGRESOS ECONÓMICOS DEL HOGAR ESTÁN A CARGO DE LA PROGENITORA QUIEN SE DESEMPEÑA EN OFICIOS VARIOS, Y EL PADRASTRO SE DESEMPEÑA COMO CONTRATISTA EN CONSTRUCCIÓN Y TRANSPORTADOR, POR OTRO LADO EL PROGENITOR LABORA COMO CONDUCTOR DE UNA EMPRESA DE ALIMENTOS, DONDE SUS INGRESOS PROVIENEN DE DICHAS ACTIVIDADES LAS CUALES GENERAN ESTABILIDAD ECONÓMICA.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>62,'csd_id'=>62, 'observacion'=>'', 'trabaja'=>'GUARDA DE SEGURIDAD','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'367','intensidad'=>'7', 'prm_dificultad_id'=>'228','razon'=>'LOS INGRESOS ECONÓMICOS DEL HOGAR ESTÁN A CARGO DE LA PROGENITORA QUIEN SE DESEMPEÑA COMO VIGILANTE Y EL PADRASTRO SE DESEMPEÑA COMO VIGILANTE, DICHAS ACTIVIDADES LAS CUALES GENERAN ESTABILIDAD ECONÓMICA.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>63,'csd_id'=>63, 'observacion'=>'', 'trabaja'=>'OFICIOS VARIOS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'614','intensidad'=>'5', 'prm_dificultad_id'=>'228','razon'=>'LOS INGRESOS ECONÓMICOS DEL HOGAR ESTÁN A CARGO DE LOS PROGENITORES QUIENES SE DESEMPEÑAN COMO AYUDANTE DE CONSTRUCCIÓN Y OFICIOS VARIOS, DONDE SUS INGRESOS PROVIENEN DE DICHAS ACTIVIDADES LAS CUALES GENERAN DE ALGUNA MANERA ESTABILIDAD ECONÓMICA. ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>64,'csd_id'=>64, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>635, 'prm_informal_id'=>635,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'613','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LA SEÑORA LUZ MERYS ES VOLUNTARIA DE LA FUNDACION "MUJERES POR LA PAZ"', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>65,'csd_id'=>65, 'observacion'=>'', 'trabaja'=>'TURNOS EN RESTAURANTES','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'SE OBSERVA DESEMPLEO POR PARTE DE LA PROGENITORA, LOS RECURSOS ECONOMICOS PROVIENEN DE TURNOS EN RESTAURANTE DE MANERA EVENTUAL', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>66,'csd_id'=>66, 'observacion'=>'', 'trabaja'=>'OFICIOS VARIOS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LAS CONDICONES ECONOMICAS DEL GRUPO FAMILIAR SON LAMENTABLES DEBIDO A LA FALTA DE TRABAJO DE LA PROGENITORA Y FALTA DE REDES DE APOYO.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>67,'csd_id'=>67, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'l aprogenitora es madre cabeza de hogar, paga de arriendo 450000', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>68,'csd_id'=>68, 'observacion'=>'', 'trabaja'=>'MANTENIMIENTO ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'643','prm_frecuencia_id'=>'259','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'LA FAMILIA TIENE DIFICULTADES YA QUE ES UNA FAMILIA EXTENSA QUE GENERA MUCHOS GASTOS Y LOS RECIBIDOS NO SON SUFICIENTES ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>69,'csd_id'=>69, 'observacion'=>'', 'trabaja'=>'OPERARIA DE ASEO ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'613','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LOS RECURSOS ECONOMICOS NO SON SUFICIENTES PARA CUBRIR NECECIDADES DEL GRUPO FAMILIAR.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>70,'csd_id'=>70, 'observacion'=>'', 'trabaja'=>'HOGAR MADRES COMUNITARIAS','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>' ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>71,'csd_id'=>71, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>853, 'prm_informal_id'=>259,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>' ', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>72,'csd_id'=>72, 'observacion'=>'', 'trabaja'=>'TAXISTA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'612','intensidad'=>'16', 'prm_dificultad_id'=>'227','razon'=>'PORQUE EL PROGENITOR TIENE QUE SOLVENTAR LOS GASTOS PERSONALES Y DE SUS DOS HIJOS. ACTUALMETE SE ENCUENTRA PREOCUPADO PORQUE NO PUEDE ESTAR TIEMPO NECESARIO CON SU HIJO PARA SUPERVISARLO, YA QUE EL NIÑO SE VADE DE CASA.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>73,'csd_id'=>73, 'observacion'=>'', 'trabaja'=>'HOGAR','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'PORQUE LA PROGENITORA DE JULIAN ES MADRE CABEZA DE FAMILIA Y ES QUIEN APORTA EN LOS GASTOS DEL HOGAR. (ARRIENDO, ALIMENTACION Y OTRAS)', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>74,'csd_id'=>74, 'observacion'=>'', 'trabaja'=>'CASAS DE FAMILIA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'PORQUE EL INGRESO NO ALCANZA PARA CUBRIR TODAS LAS NECESIDDES DE LOS NIÑOS', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>75,'csd_id'=>75, 'observacion'=>'', 'trabaja'=>'HOGAR','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'228','razon'=>'LA ABUELASTRA NO REFIERE DIFICULTADES ECONOMICAS, EXPRESA QUE EL SUELDO ALCANZA PARA LOS GASTOS', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>76,'csd_id'=>76, 'observacion'=>'', 'trabaja'=>'HOGAR','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'228','razon'=>'NO REFIERE', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>77,'csd_id'=>77, 'observacion'=>'', 'trabaja'=>'CONSTRUCCION ','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'645','prm_frecuencia_id'=>'259','intensidad'=>'12', 'prm_dificultad_id'=>'227','razon'=>'PORQUE LA TIA (BRIGITH) TIENE DEUDAS PERSONALES Y JHON EL PROGENITOR TIENE QUE DAR CUOTA ALIMENTARIA A DOS HIJOS QUE TIENE POR APARTE, LA ABUELA PAGA CREDITOS.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>78,'csd_id'=>78, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>635, 'prm_informal_id'=>259,'prm_otra_id'=>1800, 'prm_laboral_id'=>'1561','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LOS INGRESOS NO SON FIJOS , Y SU ACTIVIDAD ECONOMICA IMPLICA RIESGOS PARA SU INTEGRIDAD SEGÚN REFIEREN.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>79,'csd_id'=>79, 'observacion'=>'', 'trabaja'=>'VENDER BOLSAS DE BASURA','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'HABITABILIDAD PRECARIA, LA VIVIENDA NO CUENTA CON INODORO, SE BAÑAN CON BALDE, LA VIVIENDA SE ENCUENTRA EN CONDICIONES INSALUBRES', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>80,'csd_id'=>80, 'observacion'=>'', 'trabaja'=>'NO LABORA POR SU CONDICION DE DISCAPACIDAD','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'EL INGRESO DE LA FAMILIA ES DE $10000 A $15000 DIARIOS Y NO ES SUFICIENTE PARA EL ALTO NUMERO DE NECESIDADES DEL GRUPO FAMILIAR.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>81,'csd_id'=>81, 'observacion'=>'', 'trabaja'=>'EMPRESA DE ASEO','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'642','prm_frecuencia_id'=>'613','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LOS INGRESOS NO SON SUFICIENTES PARA CUBRIR TODAS LAS NECESIDADES DEL GRUPO FAMILIAR.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>82,'csd_id'=>82, 'observacion'=>'', 'trabaja'=>'TURNOS EVENTUALES COMO VIGILANTE','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'EL PROGENITOR REFIERE NO CONTAR CON DINERO PARA DESAYUNAR ES ASÍ QUE EL MENOR DE EDAD SALE DE LA CASA A LAS 10:00 AMALMUERZA EN OCASIONES EN LA VIVIENDA DE LA PROGENITORA SALE A LA CALLE Y RETORNA AL HOGAR A LAS 6:00 PM.DICHA SITUACIÓN ES RIESGOSA YA QUE DESDE MARZO DEL 2019 EL NIÑO NO S EENCUENTRA ESCOLARIZADO.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>83,'csd_id'=>83, 'observacion'=>'', 'trabaja'=>'VENTA AMBULANTE ENSALADAS ','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'LA FAMILIA PRESENTA DIFICULTADES ECONOMICAS YA QUE LO QUE GANA EL PROGENITOR NO LE ALCANZZA PARA PAGAR LOS GASTOS QUE SE GENERAN EN LA VIVIENDA', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>84,'csd_id'=>84, 'observacion'=>'', 'trabaja'=>'OFICIOS VARIOS EN UN RESTAURANTE','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'EL FACTOR ECONOMICO DE LA FAMILIA ES QUIZAS LA DIFICULTAD MAS ENORME POR LA QUE ATRAVIESA LA FAMILIA, NO HAY CONDICIONES PARA EL BIENESTAR Y DESARROLLO DE LOS MENORES DE EDAD.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>85,'csd_id'=>85, 'observacion'=>'', 'trabaja'=>'VENTA DE BEBIDAS','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'646','prm_frecuencia_id'=>'612','intensidad'=>'8', 'prm_dificultad_id'=>'227','razon'=>'SE EVIDENCIA DIFICULTADES ECONOMICAS YA QUE LA SEÑORAES QUIEN RESPONDE POR SUS TRES NIETOS', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>86,'csd_id'=>86, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>627, 'prm_informal_id'=>632,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'NO TIENEN UN TRABAJO ESTABLE, NI APOYO DE RED FAMILIAR, IN INSTITUCIONAL A PARTE DE IDIPRON.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>87,'csd_id'=>87, 'observacion'=>'', 'trabaja'=>'SERVICIOS GENERALES EN EMPRESA PRIVADA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'643','prm_frecuencia_id'=>'613','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'PORQUE LA PROGENITORA ES CABEZA DE FAMILIA, SU SUELDO ES PARA SUSTENTAR EL ARRIENDO, LA COMIDA, LOS SERVICIOS Y LOS GASTOS DE SUS HIJOS.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>88,'csd_id'=>88, 'observacion'=>'', 'trabaja'=>'TRABAJO INFORMAL','prm_actividad_id'=>627, 'prm_informal_id'=>631,'prm_otra_id'=>633, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'1561','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'SE EVIDENCIA DIFICULTADES ECONOMICAS Y LOS INGRESOS CONSEGUIDOS NO SON SUFICIENTES PARA CUBRIR LAS NECESIDADES BASICAS.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>89,'csd_id'=>89, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>627, 'prm_informal_id'=>632,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'228','razon'=>'TODOS LOS MIEMBROS APORTAN AL HOGAR, LOGRAN CUBRIR LOS GASTOS.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>90,'csd_id'=>90, 'observacion'=>'', 'trabaja'=>'HOGAR','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'EL HIJO MAYOR DE LA ABUELA MATERNA YA NO PUEDE APOYARLOS POR UNA INCAPACIDAD DEBIDA A UNA ENFERMEDAD.', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>91,'csd_id'=>91, 'observacion'=>'', 'trabaja'=>'NA','prm_actividad_id'=>627, 'prm_informal_id'=>1578,'prm_otra_id'=>259, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'REFIERE NO TENER APOYO DE NINGUN TIPO', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        CsdGenIngreso::create(['id'=>92,'csd_id'=>92, 'observacion'=>'', 'trabaja'=>'MESERA','prm_actividad_id'=>626, 'prm_informal_id'=>626,'prm_otra_id'=>626, 'prm_laboral_id'=>'259','prm_frecuencia_id'=>'259','intensidad'=>'0', 'prm_dificultad_id'=>'227','razon'=>'REFIERE QUE DISTRIBUYE LOS GASTOS PARA CUBRIR TODO Y NO RECIBE EL APOYO DEL PROGENITOR DE LOS NIÑOS', 'user_crea_id'=>1,'user_edita_id'=>1,'sis_esta_id'=>1,'prm_tipofuen_id'=>2316]);
        
    }
}
