<?php

use App\Models\fichaobservacion\FosStse;
use Illuminate\Database\Seeder;

class FosStsesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        FosStse::create(['codigo' => '', 'nombre' => 'NO APLICA', 'descripcion' => 'NA', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-06-25T21:28:48.000000Z',]); // 1
        FosStse::create(['codigo' => '', 'nombre' => 'SALUD (GISA)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON ENTIDADES PRESTADORAS DEL SISTEMA DE SALUD (EPS O RED HOSPITALARIA).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 2
        FosStse::create(['codigo' => '', 'nombre' => 'SDIS (GISD)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN Y/O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON LA SECRETARIA SOCIAL (SDIS).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 3
        FosStse::create(['codigo' => '', 'nombre' => 'ICBF (GIIC)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN Y/O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON EL INSTITUTO COLOMBIANO DE BIENESTAR FAMILIAR.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 4
        FosStse::create(['codigo' => '', 'nombre' => 'EDUCACIÓN (GIED)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN Y/O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON LA SECRETARIA DE EDUCACIÓN (DIRECCIÓN LOCAL DE EDUCACIÓN- DILE).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 5
        FosStse::create(['codigo' => '', 'nombre' => 'SECRETARIA DE LA MUJER (GISM)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN Y/O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON LA SECRETARIA DE LA MUJER.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 6
        FosStse::create(['codigo' => '', 'nombre' => 'COMISARIA DE FAMILIA (GICF)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN Y/O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON LA COMISARIA DE FAMILIA.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 7
        FosStse::create(['codigo' => '', 'nombre' => 'REGISTRADURIA (GIRE)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN Y/O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON LA REGISTRADURIA NACIONAL.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 8
        FosStse::create(['codigo' => '', 'nombre' => 'ONG (GONG)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN Y/O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON LAS ONG (ORGANIZACIONES NO GUBERNAMENTALES). REFERENCIAR EN LA DESCRIPCIÓN LA ORGANIZACIÓN Y SERVICIO.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 9
        FosStse::create(['codigo' => '', 'nombre' => 'SALUD (AISA)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ A OTRAS INSTITUCIONES DEL SISTEMA DE SALUD SIN QUE EL PROFESIONAL REALICE ALGÚN TIPO DE ARTICULACIÓN O VINCULACIÓN.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 10
        FosStse::create(['codigo' => '', 'nombre' => 'SDIS (AISD)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ CON LA SECRETARIA DE INTEGRACIÓN SOCIAL, SIN QUE EL PROFESIONAL REALICE ALGÚN TIPO DE ARTICULACIÓN O VINCULACIÓN.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 11
        FosStse::create(['codigo' => '', 'nombre' => 'ICBF (AIIC)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ CON EL INSTITUTO COLOMBIANO DE BIENESTAR FAMILIAR (ICBF), SIN QUE EL PROFESIONAL REALICE ALGÚN TIPO DE ARTICULACIÓN O VINCULACIÓN.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 12
        FosStse::create(['codigo' => '', 'nombre' => 'EDUCACION (AIED)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ A LA SECRETARIA DE EDUCACIÓN, SIN QUE EL PROFESIONAL REALICE ALGÚN TIPO DE ARTICULACIÓN O VINCULACIÓN.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 13
        FosStse::create(['codigo' => '', 'nombre' => 'SECRETRÍA DE LA MUJER (AISM)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ A LA SECRETARIA DE LA MUJER, SIN QUE EL PROFESIONAL REALICE ALGÚN TIPO DE ARTICULACIÓN O VINCULACIÓN.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 14
        FosStse::create(['codigo' => '', 'nombre' => 'COMISARIA DE FAMILIA (AICF)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ A LA COMISARIA DE FAMILIA, SIN QUE EL PROFESIONAL REALICE ALGÚN TIPO DE ARTICULACIÓN O VINCULACIÓN.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 15
        FosStse::create(['codigo' => '', 'nombre' => 'REGISTRADURIA (AIRE)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ A LA REGISTRADURIA NACIONAL, SIN QUE EL PROFESIONAL REALICE ALGÚN TIPO DE ARTICULACIÓN O VINCULACIÓN.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 16
        FosStse::create(['codigo' => '', 'nombre' => 'ONG (AONG)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ A (ORGANIZACIONES NO GUBERNAMENTALES) ONG, SIN QUE EL PROFESIONAL REALICE ALGÚN TIPO DE ARTICULACIÓN O VINCULACIÓN.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 17
        FosStse::create(['codigo' => '', 'nombre' => 'DE TRABAJO SOCIAL A NNAJ (AANJ)', 'descripcion' => 'SE CREA EL CRITERIO DE CARGUE PARA QUE EL PROFESIONAL EN TRABAJO SOCIAL REGISTE ATENCIÓN REALIZADA A EL/LA NNAJ RESPECTO A INFORMACIÓN, ORIENTACIÓN Y SEGUIMIENTO INMEDIATO.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 18
        FosStse::create(['codigo' => '', 'nombre' => 'PSICOLÓGICAS A NNAJ (APNJ)', 'descripcion' => 'SE CREA EL CRITERIO DE CARGUE PARA QUE EL PROFESIONAL EN PSICOLOGÍA REGISTE ATENCIÓN REALIZADA CON EL NNAJ RESPECTO A INFORMACIÓN, ORIENTACIÓN Y SEGUIMIENTO INMEDIATO.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 19
        FosStse::create(['codigo' => '', 'nombre' => 'PSICOLÓGICAS (AAPF)', 'descripcion' => 'SE CREA EL CRITERIO DE CARGUE PARA QUE EL PROFESIONAL EN PSICOLOGÍA REGISTE ATENCIÓN REALIZADA CON LA FAMILIA O REDES DE APOYO DEL NNAJ RESPECTO A INFORMACIÓN, ORIENTACIÓN Y SEGUIMIENTO INMEDIATO.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 20
        FosStse::create(['codigo' => '', 'nombre' => 'DE TRABAJO SOCIAL FAMILIA (ATSF)', 'descripcion' => 'SE CREA EL CRITERIO DE CARGUE PARA QUE EL PROFESIONAL EN TRABAJO SOCIAL REGISTE ATENCIÓN REALIZADA CON LA FAMILIA Y/O REDES DE APOYO NNAJ RESPECTO A INFORMACIÓN, ORIENTACIÓN Y SEGUIMIENTO INMEDIATO.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 21
        FosStse::create(['codigo' => '', 'nombre' => 'PROCESO TERAPÉUTICO (CTPT)', 'descripcion' => 'SE CREA CRITERIO DE REGISTRO, APLICA PARA NNA QUE CUENTAN CON PROCESO ADMINISTRATIVO DE RESTABLECIMIENTO DE DERECHOS (PARD), LA ACCIÓN HACE REFERENCIA A LA PARTICIPACIÓN DEL EQUIPO SICOSOCIAL DEL IDIPRON EN EL COMITÉ TÉCNICO CONVOCADO Y EJECUTADO POR EL DEFENSOR DE FAMILIA Y EQUIPO INTERDISCIPLINAR DEL ICBF, AQUÍ SE DEFINE SI EL NNA REQUIERE ACTIVACIÓN DE REDES EN PROCESO TERAPÉUTICO SIGUIENDO LOS LINEAMIENTOS QUE ESTABLEZCA EL ICBF.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 22
        FosStse::create(['codigo' => '', 'nombre' => 'REINTEGRO FAMILIAR (CTRF)', 'descripcion' => 'SE CREA CRITERIO DE REGISTRO DE ACCIONES QUE APLICAN PARA NNA QUE CUENTAN CON PROCESO ADMINISTRATIVO DE RESTABLECIMIENTO DE DERECHOS (PARD), EL EQUIPO PSICOSOCIAL DE LA UNIDAD PARTICIPA JUNTO AL EQUIPO DE LA DEFENSORÍA Y DEFENSOR DE FAMILIA DE ICBF, EN LA EVALUACIÓN DEL PROCESO Y SEGUIMIENTO A LOS NNA RESPECTO A REINTEGRO FAMILIAR DEL NNA, SE OBTIENE COMO EVIDENCIA LA BOLETA DE EGRESO DEL ICBF PARA DAR REINTEGRO FAMILIAR.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 23
        FosStse::create(['codigo' => '', 'nombre' => 'CAMBIO DE INSTITUCIÓN (CTCI)', 'descripcion' => 'SE CREA CRITERIO DE REGISTRAR ACCIONES QUE APLICAN PARA NNA QUE CUENTAN CON PROCESO ADMINISTRATIVO DE RESTABLECIMIENTO DE DERECHOS (PARD), EL EQUIPO PSICOSOCIAL DE LA UNIDAD PARTICIPA JUNTO AL EQUIPO DE LA DEFENSORÍA Y DEFENSOR DE FAMILIA DE ICBF, EN LA EVALUACIÓN DE CAMBIO DE INSTITUCIÓN, ES DECIR QUE NO CONTINÚE CON LA VINCULACIÓN EN EL IDIPRON.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 24
        FosStse::create(['codigo' => '', 'nombre' => 'SEGUIMIENTO PROCESOS (CTSP)', 'descripcion' => 'APLICA PARA NNA QUE CUENTAN CON PROCESO ADMINISTRATIVO DE RESTABLECIMIENTO DE DERECHOS (PARD), EL EQUIPO PSICOSOCIAL DE LA UNIDAD PARTICIPA JUNTO AL EQUIPO DE LA DEFENSORÍA Y DEFENSOR DE FAMILIA DE ICBF, EN LA EVALUACIÓN DEL PROCESO Y SEGUIMIENTO A LOS NNA RESPECTO A CONTINUIDAD EN EL IDIPRON, DE ACUERDO A LAS NECESIDADES DE LOS MISMOS.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 25
        FosStse::create(['codigo' => '', 'nombre' => 'SALUD (AITS)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ AL ÁREA DE DERECHOS DEL IDIPRON (SALUD-COMPONENTE MITIGACIÓN).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 26
        FosStse::create(['codigo' => '', 'nombre' => 'SOCIO LEGAL (ACSO)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ AL ÁREA DE DERECHOS DEL IDIPRON (SOCIOLEGAL).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 27
        FosStse::create(['codigo' => '', 'nombre' => 'EDUCACION (AITE)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ AL ÁREA DE DERECHOS DEL IDIPRON (EDUCACIÓN).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 28
        FosStse::create(['codigo' => '', 'nombre' => 'EMPRENDER (ACEM)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ AL ÁREA DE DERECHOS DEL IDIPRON (EMPREDER).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 29
        FosStse::create(['codigo' => '', 'nombre' => 'ESPIRITUALIDAD (ACES)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ AL ÁREA DE DERECHOS DEL IDIPRON (ESPIRITUALIDAD).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 30
        FosStse::create(['codigo' => '', 'nombre' => 'SALUD (GIAS)', 'descripcion' => 'SON TODAS LAS GESTIONES Y ARTICULACIONES QUE REALIZA EL EQUIPO PSICOSOCIAL CON EL ÁREA DE DERECHOS DEL IDIPRON (SALUD-COMPONENTE MITIGACIÓN).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 31
        FosStse::create(['codigo' => '', 'nombre' => 'SOCIO LEGAL (GISL)', 'descripcion' => 'SON TODAS LAS GESTIONES Y ARTICULACIONES QUE REALIZA EL EQUIPO PSICOSOCIAL CON EL ÁREA DE DERECHOS DEL IDIPRON (SALUD-COMPONENTE MITIGACIÓN).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 32
        FosStse::create(['codigo' => '', 'nombre' => 'EDUCACION (GIAE)', 'descripcion' => 'SON TODAS LAS GESTIONES Y ARTICULACIONES QUE REALIZA EL EQUIPO PSICOSOCIAL CON EL ÁREA DE DERECHOS DEL IDIPRON (EDUCACIÓN).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 33
        FosStse::create(['codigo' => '', 'nombre' => 'EMPRENDER (GIEM)', 'descripcion' => 'SON TODAS LAS GESTIONES Y ARTICULACIONES QUE REALIZA EL EQUIPO PSICOSOCIAL CON EL ÁREA DE DERECHOS DEL IDIPRON (EMPRENDER).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 34
        FosStse::create(['codigo' => '', 'nombre' => 'ESPIRITUALIDAD (GIES)', 'descripcion' => 'SON TODAS LAS GESTIONES Y ARTICULACIONES QUE REALIZA EL EQUIPO PSICOSOCIAL CON EL ÁREA DE DERECHOS DEL IDIPRON (ESPIRITUALIDAD).', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 35
        FosStse::create(['codigo' => '', 'nombre' => 'JUDICIALES (GIJU)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGIA O TRABAJO SOCIAL) CON ENTIDADES JUDICIALES TALES COMO SE MENCIONA EN LA \'ESTRUCTURA GENERAL DE LA ADMINISTRACION DE JUSTICIA\' DE 2018: 1. CONSEJO DE ESTADO, 2. TRIBUNALES ADMINISTRATIVOS, 3. JUZGADOS ADMINISTRATIVOS, C) DE LA JURISDICCIÓN CONSTITUCIONAL: 1. CORTE CONSTITUCIONAL; D) DE LA JURISDICCIÓN DE PAZ: JUECES DE PAZ. 2. LA FISCALÍA GENERAL DE LA NACIÓN. 3. EL CONSEJO SUPERIOR DE LA JUDICATURA.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 36
        FosStse::create(['codigo' => '', 'nombre' => 'OTRAS INSTITUCIONES (GIOI)', 'descripcion' => 'HACE REFERENCIA A LA GESTIÓN INTERINSTITUCIONAL (REFERENCIACIÓN, ORIENTACIÓN O VINCULACIÓN) QUE REALIZA EL PROFESIONAL PSICOSOCIAL (EN PSICOLOGÍA O TRABAJO SOCIAL) CON SISBEN, MOVILIDAD, DEFENSORÍA DEL PUEBLO, IDIGER, IPES, ALCALDÍAS LOCALES, SECRETARIAS DISTRITALES DEL HÁBITAT, HACIENDA, DESARROLLO ECONÓMICA, DE SEGURIDAD, CONVIVENCIA Y JUSTICIA, DE CULTURA, RECREACIÓN Y DEPORTE (IDRD), DEFENSORÍA DEL ESPACIO PÚBLICO, PERSONERÍA, SECRETARIA DE GOBIERNO, HACIENDA, PLANEACIÓN Y/O CATASTRO.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 37
        FosStse::create(['codigo' => '', 'nombre' => 'JUDICIALES (AIJU)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ A ENTIDADES JUDICIALES TALES COMO SE MENCIONA EN LA \'ESTRUCTURA GENERAL DE LA ADMINISTRACION DE JUSTICIA\' DE 2018: 1. CONSEJO DE ESTADO, 2. TRIBUNALES ADMINISTRATIVOS, 3. JUZGADOS ADMINISTRATIVOS, C) DE LA JURISDICCIÓN CONSTITUCIONAL: 1. CORTE CONSTITUCIONAL; D) DE LA JURISDICCIÓN DE PAZ: JUECES DE PAZ. 2. LA FISCALÍA GENERAL DE LA NACIÓN. 3. EL CONSEJO SUPERIOR DE LA JUDICATURA.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 38
        FosStse::create(['codigo' => '', 'nombre' => 'OTRAS INSTITUCIONES (AIOI)', 'descripcion' => 'HACE REFERENCIA AL ACOMPAÑAMIENTO Y/O DESPLAZAMIENTO QUE REALIZA EL PROFESIONAL EN PSICOLOGÍA O TRABAJO SOCIAL CON EL NNAJ AL: SISBEN, MOVILIDAD, DEFENSORÍA DEL PUEBLO, IDIGER, IPES, ALCALDÍAS LOCALES, SECRETARIAS DISTRITALES DEL HÁBITAT, HACIENDA, DESARROLLO ECONÓMICA, DE SEGURIDAD, CONVIVENCIA Y JUSTICIA, DE CULTURA, RECREACIÓN Y DEPORTE (IDRD), DEFENSORÍA DEL ESPACIO PÚBLICO, PERSONERÍA, SECRETARIA DE GOBIERNO, HACIENDA, PLANEACIÓN Y/O CATASTRO.', 'estusuario_id' => '49', 'user_crea_id' => '2', 'user_edita_id' => '2', 'sis_esta_id' => '1', 'created_at' => '2021-04-27T17:01:18.000000Z', 'updated_at' => '2021-04-27T17:01:18.000000Z',]); // 39
        FosStse::create(['codigo' => '', 'nombre' => 'INASISTENCIA (SGIN)', 'descripcion' => 'LO CONSTITUYEN CADA UNA DE LAS ACCIONES QUE SE REALIZAN UNA VEZ PRESENTADA LA NO ASISTENCIA DEL NNAJ POR UN PERIODO MENOR O IGUAL A UN (1) MES A LA UPI MODALIDAD INTERNADO, MENOR O IGUAL A 45 DÍAS A LA UPI MODALIDAD EXTERNADO Y NO MAYOR A 1 SEMANA A LA UPI RIESGO ESCNNA MODALIDAD EXTERNADO, BUSCANDO ESTABLECER CONDICIONES DE LOS NNAJ ASÍ COMO LA POSIBILIDAD DE RETORNO A LAS UNIDADES O LA PERTINENCIA DE TRÁMITE DE EGRESO CON LAS GESTIONES INTRA E INTER INSTITUCIONALES A QUE HUBIERE LUGAR PARA GARANTIZAR SU GOCE DE DERECHOS (CONSULTADO EN MANUAL DE PROCESOS Y PROCEDIMIENTOS: M-MSL-PR-001, M-MSL-PR-002 Y M-SEG-IN-001).', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-05-05T04:22:23.000000Z', 'updated_at' => '2021-05-05T04:22:23.000000Z',]); // 40
        FosStse::create(['codigo' => '', 'nombre' => 'TELEFÓNICO (TAST)', 'descripcion' => 'CUANDO SE ESTABLECE CONTACTO TELEFÓNICO CON LA FAMILIA Y/O EL NNAJ PARA DAR INFORMACIÓN DEL PROCESO, REALIZAR CONVOCATORIA A EVENTOS, ENCUENTROS FAMILIARES; ASÍ COMO LA COMUNICACIÓN QUE EL NNAJ ESTABLECE CON SU RED DE APOYO FAMILIAR CON EL FIN DE FORTALECIMIENTO DEL VÍNCULO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-05-05T04:25:47.000000Z', 'updated_at' => '2021-05-05T04:25:47.000000Z',]); // 41
        FosStse::create(['codigo' => '', 'nombre' => 'CPS (ACCC)', 'descripcion' => 'DEFINICIÓN DE LA PERMANENCIA O CONTINUIDAD DE EL/LA JOVEN A LA AC MODALIDAD CPS. SE CONSIGNA LA REALIZACIÓN DEL COMITÉ MISIONAL CORRESPONDIENTE.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T01:38:15.000000Z', 'updated_at' => '2021-07-09T23:39:05.000000Z',]); // 42
        FosStse::create(['codigo' => '', 'nombre' => 'ESTÍMULO (ACEE)', 'descripcion' => 'DEFINICIÓN DE LA PERMANENCIA O CONTINUIDAD DE EL/LA JOVEN A LA AC MODALIDAD ESTÍMULO. SE CONSIGNA LA REALIZACIÓN DEL COMITÉ MISIONAL CORRESPONDIENTE.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T01:39:09.000000Z', 'updated_at' => '2021-07-09T23:44:38.000000Z',]); // 43
        FosStse::create(['codigo' => '', 'nombre' => 'SITUACIÓN LEGAL (ACFL)', 'descripcion' => 'FINALIZACIÓN DE LA VINCULACIÓN DE EL/LA JOVEN A LA AC POR PRESENTAR SITUACIÓN LEGAL QUE IMPIDE LA PARTICIPACIÓN DETERMINADA EN COMITÉ MISIONAL. ', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T01:56:59.000000Z', 'updated_at' => '2021-06-24T01:56:59.000000Z',]); // 44
        FosStse::create(['codigo' => '', 'nombre' => 'CESION CPS (ACFE )', 'descripcion' => 'SE EMPLEA CUANDO EL/LA JOVEN DECIDE CEDER SU CONTRATO Y FINALIZA SU VINCULACIÓN EN LA AC MODALIDAD CPS.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:16:17.000000Z', 'updated_at' => '2021-06-24T02:16:17.000000Z',]); // 45
        FosStse::create(['codigo' => '', 'nombre' => 'CULMINACIÓN AC (ACCL)', 'descripcion' => 'FINALIZACIÓN DE LA  AC DEBIDO A LA CULMINACIÓN DEL CONVENIO RELACIONADO CON DICHA ACTIVIDAD. SE CONSIGNA EL COMITÉ MISIONAL CORRESPONDIENTE.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:20:30.000000Z', 'updated_at' => '2021-07-29T14:29:02.000000Z',]); // 46
        FosStse::create(['codigo' => '', 'nombre' => 'DECESO (ACFD)', 'descripcion' => 'ES LA FINALIZACIÓN DE LA VINCULACIÓN DE EL/LA JOVEN A LA ACTIVIDAD DE CORRESPONSABILIDAD POR DECESO. SE CONSIGNA EL COMITÉ MISIONAL CORRESPONDIENTE.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:24:55.000000Z', 'updated_at' => '2021-07-29T23:47:37.000000Z',]); // 47
        FosStse::create(['codigo' => '', 'nombre' => 'DESAFILIACIÓN SALUD (ACFS)', 'descripcion' => 'ES LA FINALIZACIÓN DE LA VINCULACIÓN DE LA AC POR NO ENCONTRARSE ACTIVO EN EL SISTEMA DE SALUD Y NO SUBSANAR ESTA SITUACIÓN (ACUERDO DE CONVIVENCIA).', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:29:51.000000Z', 'updated_at' => '2021-07-29T14:29:25.000000Z',]); // 48
        FosStse::create(['codigo' => '', 'nombre' => 'INASISTENCIA (ACFI)', 'descripcion' => 'ES LA FINALIZACIÓN DE LA VINCULACIÓN DE EL/LA JOVEN A AC MODALIDAD ESTÍMULO POR INASISTENCIA.  SE CONSIGNA LA REALIZACIÓN DEL COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:31:55.000000Z', 'updated_at' => '2021-07-29T14:30:16.000000Z',]); // 49
        FosStse::create(['codigo' => '', 'nombre' => 'INASISTENCIA ACADÉMICA (ACIA)', 'descripcion' => 'FINALIZACIÓN DE LA VINCULACIÓN A LA AC MODALIDAD ESTIMULO POR INASISTENCIA A LA AC Y ESPACIOS FORMACIÓN PROPUESTO, SE CONSIGNA EL COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:34:36.000000Z', 'updated_at' => '2021-07-29T14:29:41.000000Z',]); // 50
        FosStse::create(['codigo' => '', 'nombre' => 'INCUMPLIMIENTO CPS (ACFG)', 'descripcion' => 'CUANDO NO SE EJECUTA LAS OBLIGACIONES CONTRACTUALES EL ÁREA DE JURÍDICA O SUPERVISIÓN DE CONTRATO DECLARAN OFICIALMENTE EL INCUMPLIMIENTO (CPS).', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:36:56.000000Z', 'updated_at' => '2021-07-22T21:27:11.000000Z',]); // 51
        FosStse::create(['codigo' => '', 'nombre' => 'NO TRÁMITE DOCUMENTO IDENTIDAD (ACFT)', 'descripcion' => 'FINALIZACIÓN DE LA VINCULACIÓN DE LA AC POR NO REALIZAR EL TRÁMITE DEL DOCUMENTO DE IDENTIDAD CÉDULA DE CIUDADANÍA. SE CONSIGNA COMITÉ MISIONAL ', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:39:39.000000Z', 'updated_at' => '2021-07-29T14:55:37.000000Z',]); // 52
        FosStse::create(['codigo' => '', 'nombre' => 'PARTICIPACIÓN HURTO (ACFH)', 'descripcion' => 'SEGUIMIENTO PROFESIONAL REALIZADO CON EL/LA JOVEN AL VERSE IMPLICADO EN SITUACIONES DE HURTO DURANTE LAS AC. SE CONSIGNA EN COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:41:51.000000Z', 'updated_at' => '2021-07-29T15:13:34.000000Z',]); // 53
        FosStse::create(['codigo' => '', 'nombre' => 'RETIRO VOLUNTARIO (ACRV)', 'descripcion' => 'ES LA FINALIZACIÓN DE LA VINCULACIÓN A LA AC (ESTÍMULO) POR DECISIÓN VOLUNTARIA DE EL/LA JOVEN. SE CONSIGNA LA REALIZACIÓN DEL COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:45:35.000000Z', 'updated_at' => '2021-07-29T15:16:21.000000Z',]); // 54
        FosStse::create(['codigo' => '', 'nombre' => 'RIESGO SALUD (ACFU )', 'descripcion' => 'FINALIZACIÓN DE EL/LA JOVEN EN AC ESTIMULO POR SITUACIONES DE SALUD QUE IMPIDEN LA REALIZACIÓN DE LAS ACTIVIDADES. SE CONSIGNA EL COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:46:53.000000Z', 'updated_at' => '2021-07-29T15:18:51.000000Z',]); // 55
        FosStse::create(['codigo' => '', 'nombre' => 'SUPERACIÓN TIEMPO EN AC (ACFM)', 'descripcion' => 'FINALIZACIÓN DE EL/LA JOVEN EN AC (ESTÍMULO) POR SUPERACIÓN DEL TIEMPO MÁXIMO DE PERMANENCIA EN MODALIDAD. SE CONSIGNA EL COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:49:43.000000Z', 'updated_at' => '2021-07-10T00:48:03.000000Z',]); // 56
        FosStse::create(['codigo' => '', 'nombre' => 'AGOTAMIENTO OBJ, CPS (ACFO)', 'descripcion' => 'SE EMPLEA CUANDO EL/LA JOVEN TERMINA SU VINCULACIÓN EN LA FECHA DE FINALIZACIÓN DE SU CONTRATO, APLICA PARA AC MODALIDAD CPS.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:52:18.000000Z', 'updated_at' => '2021-06-24T02:52:18.000000Z',]); // 57
        FosStse::create(['codigo' => '', 'nombre' => 'COMPORTAMIENTO INDEBIDO (ACFC)', 'descripcion' => 'FINALIZACIÓN VINCULACION (ESTIMULO) POR COMPORTAMIENTO CONTRARIO AL ACUERDO CORRESPONSABILIDAD Y ACUERDO DE CONVIVENCIA. REGISTRAR COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:54:03.000000Z', 'updated_at' => '2021-07-29T23:50:10.000000Z',]); // 58
        FosStse::create(['codigo' => '', 'nombre' => 'PRÁCTICA PRODUCTIVA SENA (ACFP)', 'descripcion' => 'HACE REFERENCIA A LA FINALIZACIÓN DE LA VINCULACIÓN DE EL/ LA JOVEN A LAS AC DEBIDO A VINCULACIÓN A  PRÁCTICA PRODUCTIVA SENA.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T02:56:36.000000Z', 'updated_at' => '2021-07-29T23:53:00.000000Z',]); // 59
        FosStse::create(['codigo' => '', 'nombre' => 'ANTICIPADA CPS (ACFA)', 'descripcion' => 'SE EMPLEA CUANDO EL/LA JOVEN TERMINA SU VINCULACIÓN ANTES DE LA FECHA DE FINALIZACIÓN DE SU CONTRATO, APLICA PARA AC MODALIDAD CPS.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:16:25.000000Z', 'updated_at' => '2021-06-24T03:16:25.000000Z',]); // 60
        FosStse::create(['codigo' => '', 'nombre' => 'FIRMA DE ACUERDO (ACFR)', 'descripcion' => 'SE REFIERE A LA FIRMA DEL ACUERDO DE CORRESPONSABILIDAD PARA AC (ESTÍMULO Y CPS) SE EFECTÚAN CON LA  VINCULACIÓN DEL JOVEN A LAS DOS MODALIDADES AC.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:20:00.000000Z', 'updated_at' => '2021-06-24T03:20:00.000000Z',]); // 61
        FosStse::create(['codigo' => '', 'nombre' => 'ACADÉMICO (ACSA)', 'descripcion' => 'INDAGACIÓN Y ARTICULACIÓN PERIÓDICA, FRENTE AL AVANCE O DIFICULTADES PRESENTADAS POR EL/LA JOVEN EN LOS PROCESOS DE FORMACIÓN EN LAS UPI.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:37:14.000000Z', 'updated_at' => '2021-06-24T03:37:14.000000Z',]); // 62
        FosStse::create(['codigo' => '', 'nombre' => 'AGRESIÓN (ACAG )', 'descripcion' => 'SEGUIMIENTO A EL/LA JOVEN QUE PRESENTA INTENTO O AGRESIÓN FÍSICA A OTRA PERSONA EL EJERCICIO DE SUS AC. SE CONSIGNA EL COMITÉ MISIONAL .', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:39:07.000000Z', 'updated_at' => '2021-06-24T03:39:07.000000Z',]); // 63
        FosStse::create(['codigo' => '', 'nombre' => 'PRESUNTO HURTO (ACPH)', 'descripcion' => 'SEGUIMIENTO A EL/LA JOVEN SI SE ENCUENTRA IMPLICADO SITUACIONES DE HURTO DURANTE LA AC (ACUERDO DE CONVIVENCIA- ESTIMULO). SE REGISTRA COMITÉ MISIONAL', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:43:04.000000Z', 'updated_at' => '2021-07-30T00:16:53.000000Z',]); // 64
        FosStse::create(['codigo' => '', 'nombre' => 'SALUD (ACSS)', 'descripcion' => 'SEGUIMIENTO CUANDO PRESENTA QUEBRANTOS DE SALUD QUE AFECTAN SU PARTICIPACIÓN EN LAS AC Y/O FORMATIVAS. SE CONSIGNA LA REALIZACIÓN COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:46:34.000000Z', 'updated_at' => '2021-06-24T03:46:34.000000Z',]); // 65
        FosStse::create(['codigo' => '', 'nombre' => 'PRESUNTO SPA (ACSP)', 'descripcion' => 'SEGUIMIENTO CON EL/LA JOVEN POR PRESENTARSE EN BAJO EL EFECTO DE SPA CONSUMIR O EXPENDER DURANTE VINCULACION AC, APLICA PARA LAS DOS MODALIDADES.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:48:39.000000Z', 'updated_at' => '2021-06-24T03:48:39.000000Z',]); // 66
        FosStse::create(['codigo' => '', 'nombre' => 'TRIMESTRAL DESEMPEÑO (ACTD)', 'descripcion' => 'RESULTADOS DEL SEGUIMIENTO PEDAGÓGICO TRIMESTRAL MODALIDAD ESTIMULO, INCLUYENDO INFORMACIÓN CUALITATIVA Y NIVEL COMPETENCIA LABORAL A LOS/LAS JÓVENES.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:50:50.000000Z', 'updated_at' => '2021-06-24T03:50:50.000000Z',]); // 67
        FosStse::create(['codigo' => '', 'nombre' => 'DETERIORO IMPLEMENTOS Y/O EQUIPOS (ACSE)', 'descripcion' => 'SEGUIMIENTO QUE SE EFECTÚA CON EL/LA JOVEN QUE DAÑA O DETERIORA LOS EQUIPOS O IMPLEMENTOS ASIGNADOS O UTILIZADOS PARA EL DESARROLLO DE LAS AC. ', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:53:01.000000Z', 'updated_at' => '2021-06-24T03:53:01.000000Z',]); // 68
        FosStse::create(['codigo' => '', 'nombre' => 'LENGUAJE INDEBIDO (ACSL)', 'descripcion' => 'SEGUIMIENTO AL EL/LA JOVEN POR USO DE PALABRAS SOECES DESPECTIVAS U OFENSIVAS O EL USO DE LENGUAJE CON CONTENIDO SEXUAL EN EL EJERCICIO DE SUS AC.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:54:48.000000Z', 'updated_at' => '2021-06-24T03:54:48.000000Z',]); // 69
        FosStse::create(['codigo' => '', 'nombre' => 'NO PORTE EPP (ACSO)', 'descripcion' => 'SEGUIMIENTO AL EL/LA  JOVEN POR NO PORTAR LA DOTACIÓN IDENTIFICACIÓN VISUAL Y/O ELEMENTOS DE PROTECCIÓN PERSONAL EN LAS ACTIVIDADES EN CAMPO. ', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T03:58:45.000000Z', 'updated_at' => '2021-06-24T03:58:45.000000Z',]); // 70
        FosStse::create(['codigo' => '', 'nombre' => 'NO PORTE IDENTIFICACIÓN (ACSF)', 'descripcion' => 'SEGUIMIENTO SE EFECTÚA CON EL/LA JOVEN POR NO PORTAR LA DOCUMENTACIÓN REQUERIDA (CÉDULA, VINCULACIÓN EPS) PARA EL EJERCICIO DE SUS AC (ESTIMULO).', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T04:00:41.000000Z', 'updated_at' => '2021-06-24T04:00:41.000000Z',]); // 71
        FosStse::create(['codigo' => '', 'nombre' => 'SITUACIÓN MILITAR (ACSM)', 'descripcion' => 'SE REFIERE AL SEGUIMIENTO QUE SE EFECTÚA CON EL/LA JOVEN VINCULADO A AC MODALIDAD ESTIMULO O CPS RELACIONADO CON LA DEFINICIÓN DE SU SITUACIÓN MILITAR.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T04:03:30.000000Z', 'updated_at' => '2021-06-24T04:03:30.000000Z',]); // 72
        FosStse::create(['codigo' => '', 'nombre' => 'SOLICITAR DINERO O EN ESPECIE (ACSD)', 'descripcion' => 'HACE REFERENCIA AL SEGUIMIENTO PROFESIONAL  A EL/LA JOVEN POR SOLICITAR AYUDA MONETARIA O EN ESPECIE A PARTICULARES, EN EL EJERCICIO DE SUS AC.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T04:04:49.000000Z', 'updated_at' => '2021-06-24T04:04:49.000000Z',]); // 73
        FosStse::create(['codigo' => '', 'nombre' => 'COMPORTAMIENTO INDEBIDO (ACCI)', 'descripcion' => 'SEGUIMIENTO QUE SE REALIZA A EL/LA JOVEN QUE PRESENTA COMPORTAMIENTO INDEBIDO EL EJERCICIO DE SUS AC. SE CONSIGNA EL COMITÉ MISIONAL, SI APLICA.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T04:15:27.000000Z', 'updated_at' => '2021-06-24T04:15:27.000000Z',]); // 74
        FosStse::create(['codigo' => '', 'nombre' => 'EDAD (ACFÑ)', 'descripcion' => 'FINALIZACIÓN DE EL/LA JOVEN EN AC POR SUPERACIÓN DE EDAD MISIONAL Y ORIENTACIONES GENERADAS DESDE EL ÁREA ENCARGADA. SE CONSIGNA EL COMITÉ MISIONAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T04:21:14.000000Z', 'updated_at' => '2021-07-10T00:52:07.000000Z',]); // 75
        FosStse::create(['codigo' => '', 'nombre' => 'BAJO RENDIMIENTO AC (ACSR)', 'descripcion' => ' SEGUIMIENTO QUE SE REALIZA A EL/LA JOVEN QUE PRESENTA BAJO RENDIMIENTO EL EJERCICIO DE SUS AC. SE CONSIGNA EL COMITÉ MISIONAL, SI APLICA.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T04:23:27.000000Z', 'updated_at' => '2021-06-24T04:23:27.000000Z',]); // 76
        FosStse::create(['codigo' => '', 'nombre' => 'VERIFICACIÓN CUMPLIMIENTO TIEMPO Y EDAD (ACTE)', 'descripcion' => 'VERIFICAR A PARTIR DE LA INFORMACIÓN GENERADA POR SIMI, EL CUMPLIMIENTO DE LOS CRITERIOS DE PERMANENCIA DE EDAD Y TIEMPO ESTABLECIDO EN AC.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-24T04:25:10.000000Z', 'updated_at' => '2021-06-24T04:25:10.000000Z',]); // 77
        FosStse::create(['codigo' => '', 'nombre' => 'NO APLICA', 'descripcion' => 'NO APLICA', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-06-25T19:37:22.000000Z', 'updated_at' => '2021-07-30T00:15:20.000000Z',]); // 78
        FosStse::create(['codigo' => '', 'nombre' => 'VOLUNTARIO(RPSV)', 'descripcion' => 'SOCIALIZACIÓN VERBAL DEL/LA JOVEN DE CULMINAR EL PROCESO PRE- SEMÁFORO DE MANERA ANTICIPADA.', 'estusuario_id' => '49', 'user_crea_id' => '1', 'user_edita_id' => '1', 'sis_esta_id' => '1', 'created_at' => '2021-09-20T13:31:00.000000Z', 'updated_at' => '2021-09-20T13:36:09.000000Z',]); // 79
        FosStse::create(['codigo' => '', 'nombre' => 'INCUMPLIMIENTO AL PROCESO (RPIP)', 'descripcion' => 'INCLUMPLIMIENTO AL PROCESO PRE-SEMAFORO', 'estusuario_id' => '49', 'user_crea_id' => '1', 'user_edita_id' => '1', 'sis_esta_id' => '1', 'created_at' => '2021-09-20T13:33:36.000000Z', 'updated_at' => '2021-09-20T13:36:59.000000Z',]); // 80
        FosStse::create(['codigo' => '', 'nombre' => 'DESNATURALIZACIÓN PATRONES DE CALLE (PPDP)', 'descripcion' => 'RETROALIMENTACIÓN DEL/LA JOVEN AL REDUCIR PATRONES DE CALLE, EN SU PROCESO FORMATIVO EN PROMOCION DE SU GARANTIA DE DERECHOS EN PRO DE DEJAR LA CALLE SU LUGAR DE VIVIENDA.', 'estusuario_id' => '49', 'user_crea_id' => '1', 'user_edita_id' => '1', 'sis_esta_id' => '1', 'created_at' => '2021-09-20T13:39:28.000000Z', 'updated_at' => '2021-09-20T13:39:28.000000Z',]); // 81
        FosStse::create(['codigo' => '', 'nombre' => 'PROMOCIÓN HABITOS DE AUTOCUIDADO CHC (PPHA)', 'descripcion' => 'CORRESPONDE A LA RETROALIMENTACIÓN DEL/LA JOVEN QUE ADQUIERE HABITOS DE AUTOCIDADO PARA ADQUIRIR HABITOS DE VIDA SALUDABLE.', 'estusuario_id' => '49', 'user_crea_id' => '1', 'user_edita_id' => '1', 'sis_esta_id' => '1', 'created_at' => '2021-09-20T13:40:06.000000Z', 'updated_at' => '2021-09-20T13:40:06.000000Z',]); // 82
        FosStse::create(['codigo' => '', 'nombre' => 'RECONOCIMIENTO AL PROCESO (PPRP)', 'descripcion' => 'RECURSO LO QUE SE UTILIZA PARA RESALTAR EL APRENDIZALE DE CONDUCTAS Y/O COMPARTAMIENTO DESEADOS QUE SE DESARROLLAN EN EL PROCESO PRE- SEMÁFORO', 'estusuario_id' => '49', 'user_crea_id' => '1', 'user_edita_id' => '1', 'sis_esta_id' => '1', 'created_at' => '2021-09-20T13:41:25.000000Z', 'updated_at' => '2021-09-20T13:41:32.000000Z',]); // 83
        FosStse::create(['codigo' => '', 'nombre' => 'INCUMPLIMIENTO DE NORMAS Y PACTO DE CONVIVENCIA (PPIN)', 'descripcion' => 'OBSERVACIÓN QUE SE REALIZA CUANDO EL/LA JOVEN CHC INCUMPLE LAS NORMAS Y PACTO CONVIVENCIA ESTABLECIDAS EN LA UNIDAD DE PROTECCIÓN INTEGRAL PROCESO PRE-SEMÁFORO', 'estusuario_id' => '49', 'user_crea_id' => '1', 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-09-20T13:42:54.000000Z', 'updated_at' => '2021-12-09T22:28:47.000000Z',]); // 84
        FosStse::create(['codigo' => '', 'nombre' => 'PSICOLOGICAS MITIGACIÓN (AAPM)', 'descripcion' => 'ACOMPAÑAMIENTO PSICOLÓGICO DESDE EL ENFOQUE DE LA REDUCCIÓN DE RIESGOS Y DAÑOS POR CONSUMO DE SUSTANCIAS PSICOATIVAS LEGALES E ILEGALES Y SU RELACIÓN CON LAS MISMAS EN EL MARCO DE LA SALUD MENTAL.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-10-01T01:28:17.000000Z', 'updated_at' => '2021-10-01T01:28:17.000000Z',]); // 85
        FosStse::create(['codigo' => '', 'nombre' => 'TRABAJO SOCIAL MITIGACIÓN (AATM)', 'descripcion' => 'ACOMPAÑAMIENTO DESDE TRABAJO SOCIAL A PARTIR DEL ENFOQUE DE LA REDUCCIÓN DE RIESGOS Y DAÑOS POR CONSUMO DE SUSTANCIAS PSICOATIVAS LEGALES E ILEGALES Y SU RELACIÓN CON LAS MISMAS EN LOS ENTORNOS DE NIÑOS, NIÑAS, ADOLESCENTES Y JÓVENES.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-10-01T01:34:57.000000Z', 'updated_at' => '2021-10-01T01:34:57.000000Z',]); // 86
        FosStse::create(['codigo' => '', 'nombre' => 'INSCRIPCIÓN PROCESO PRE-SEMÁFORO (INPP)', 'descripcion' => 'CORRESPONDE A LA ACCIÓN DE REALIZAR PREINSCIPCIÓN AL PROCESO PRE-SEMÁFORO DE LOS/AS JOVENES EN SITUACIÓN DE VIDA EN CALLE, EN ESTE PROCESO INICIAL SU FORMACIÓN DE DESABITUACIÓN DE LA CALLE EN PROCESO INTERNADO', 'estusuario_id' => '49', 'user_crea_id' => '1', 'user_edita_id' => '1', 'sis_esta_id' => '1', 'created_at' => '2021-10-21T16:31:56.000000Z', 'updated_at' => '2021-10-21T16:41:36.000000Z',]); // 87
        FosStse::create(['codigo' => '', 'nombre' => 'INSCRIPCIÓN PROCESO SEMÁFORO (ISF)', 'descripcion' => 'CORRESPONDE A LA ACCIÓN DE REALIZAR PREINSCIPCIÓN AL PROCESO SEMÁFORO DE LOS/AS JOVENES EN SITUACIÓN DE VIDA EN CALLE, EN ESTE PROCESO INICIAL SU FORMACIÓN DE DESABITUACIÓN DE LA CALLE EN PROCESO INTERNADO', 'estusuario_id' => '49', 'user_crea_id' => '1', 'user_edita_id' => '1', 'sis_esta_id' => '1', 'created_at' => '2021-10-21T16:38:16.000000Z', 'updated_at' => '2021-10-21T16:42:07.000000Z',]); // 88
        FosStse::create(['codigo' => '', 'nombre' => 'SUSPENSIÓN CONTRATO CPS (ACSC)', 'descripcion' => 'E EMPLEA CUANDO EL/LA JOVEN VINCULADA EN AC/CPS REALIZA LA SUSPENSIÓN DEL CONTRATO. SE CONSIGNA EL MOTIVO Y TIEMPO DE LA SUSPENSIÓN.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T20:05:56.000000Z', 'updated_at' => '2021-12-09T18:47:47.000000Z',]); // 89
        FosStse::create(['codigo' => '', 'nombre' => 'PRIMER SEGUIMIENTO TRIMESTRAL AL DESEMPEÑO (PSTD)', 'descripcion' => 'RESULTADO DEL (1) SEGUIMIENTO PEDAGÓGICO TRIMESTRAL, INCLUYENDO INFORMACIÓN CUALITATIVA Y NIVEL COMPETENCIA LABORAL DE EL/LA JOVEN MODALIDAD ESTIMULO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T20:20:14.000000Z', 'updated_at' => '2021-12-07T20:20:14.000000Z',]); // 90
        FosStse::create(['codigo' => '', 'nombre' => 'SEGUNDO SEGUIMIENTO TRIMESTRAL AL DESEMPEÑO (SSTD)', 'descripcion' => 'RESULTADO DEL (2) SEGUIMIENTO PEDAGÓGICO TRIMESTRAL, INCLUYENDO INFORMACIÓN CUALITATIVA Y NIVEL COMPETENCIA LABORAL DE EL/LA JOVEN MODALIDAD ESTIMULO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T20:26:27.000000Z', 'updated_at' => '2021-12-07T20:26:42.000000Z',]); // 91
        FosStse::create(['codigo' => '', 'nombre' => 'TERCER SEGUIMIENTO TRIMESTRAL AL DESEMPEÑO ( TSTD)', 'descripcion' => 'RESULTADO DEL (3) SEGUIMIENTO PEDAGÓGICO TRIMESTRAL, INCLUYENDO INFORMACIÓN CUALITATIVA Y NIVEL COMPETENCIA LABORAL DE EL/LA JOVEN MODALIDAD ESTIMULO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T20:38:59.000000Z', 'updated_at' => '2021-12-07T20:38:59.000000Z',]); // 92
        FosStse::create(['codigo' => '', 'nombre' => 'CUARTO SEGUIMIENTO TRIMESTRAL AL DESEMPEÑO (CSTD)', 'descripcion' => 'ESULTADO DEL (4) SEGUIMIENTO PEDAGÓGICO TRIMESTRAL, INCLUYENDO INFORMACIÓN CUALITATIVA Y NIVEL COMPETENCIA LABORAL DE EL/LA JOVEN MODALIDAD ESTIMULO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T20:40:10.000000Z', 'updated_at' => '2021-12-07T20:40:10.000000Z',]); // 93
        FosStse::create(['codigo' => '', 'nombre' => 'QUINTO SEGUIMIENTO TRIMESTRAL AL DESEMPEÑO (QSTD)', 'descripcion' => 'ESULTADO DEL (5) SEGUIMIENTO PEDAGÓGICO TRIMESTRAL, INCLUYENDO INFORMACIÓN CUALITATIVA Y NIVEL COMPETENCIA LABORAL DE EL/LA JOVEN MODALIDAD ESTIMULO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T20:41:17.000000Z', 'updated_at' => '2021-12-07T20:41:17.000000Z',]); // 94
        FosStse::create(['codigo' => '', 'nombre' => 'SEXTO SEGUIMIENTO TRIMESTRAL AL DESEMPEÑO (SETD)', 'descripcion' => 'RESULTADO DEL (6) SEGUIMIENTO PEDAGÓGICO TRIMESTRAL, INCLUYENDO INFORMACIÓN CUALITATIVA Y NIVEL COMPETENCIA LABORAL DE EL/LA JOVEN MODALIDAD ESTIMULO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T20:42:13.000000Z', 'updated_at' => '2021-12-07T20:42:28.000000Z',]); // 95
        FosStse::create(['codigo' => '', 'nombre' => 'SEGUIMIENTO AC (CMAC)', 'descripcion' => 'REGISTRO COMITÉ MISIONAL CON LA SOCIALIZACIÓN DEL DESEMPEÑO Y DESARROLLO DE COMPETENCIAS GENERALES DE EL/LA JOVEN DURANTE LA PERMANENCIA EN LA AC.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T20:59:41.000000Z', 'updated_at' => '2021-12-07T20:59:41.000000Z',]); // 96
        FosStse::create(['codigo' => '', 'nombre' => 'PRE-SEMAFORÒ FINALIZACIÒN SATISFACTORIA (EPFS)', 'descripcion' => 'CULMINACIÓN SATISFACTORIA DEL PROCESO SEMÁFORO, DONDE EL/LA JOVEN ADQUIEREN HERRAMIENTAS PARA CONTINUAR CON EL PROCESO SEMÁFORO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T21:40:24.000000Z', 'updated_at' => '2021-12-07T21:40:24.000000Z',]); // 97
        FosStse::create(['codigo' => '', 'nombre' => 'SEMAFORÒ FINALIZACIÒN SATISFACTORIA (ESFS)', 'descripcion' => 'CULMINACIÓN SATISFACTORIA DEL PROCESO SEMÁFORO, DONDE EL/LA JOVEN ADQUIEREN HERRAMIENTAS PARA CONTINUAR CON EL PROCESO SEMÁFORO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T21:41:11.000000Z', 'updated_at' => '2021-12-07T21:41:11.000000Z',]); // 98
        FosStse::create(['codigo' => '', 'nombre' => 'PRE-SEMAFORO VOLUNTARIO (RPSV)', 'descripcion' => 'MANIFESTACIÓN VOLUNTARIO DEL JOVEN DE REALIZAR INTERRUPCIÓN DEL PROCESO PRESEMAFORO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T21:46:07.000000Z', 'updated_at' => '2021-12-07T21:46:07.000000Z',]); // 99
        FosStse::create(['codigo' => '', 'nombre' => 'PRE-SEMAFORO INCUMPLIMIENTO AL PROCESO (RPIP)', 'descripcion' => 'RETIRO AL PROCESO PRESEMAFORO DEBIDO AL INCUMPLIMIENTO DEL PROCESO CHC.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T21:46:49.000000Z', 'updated_at' => '2021-12-07T21:46:49.000000Z',]); // 100
        FosStse::create(['codigo' => '', 'nombre' => 'VOLUNTARIO SEMAFORO (RVSF)', 'descripcion' => 'MANIFESTACIÓN VOLUNTARIO DEL JOVEN DE REALIZAR INTERRUPCIÓN DEL PROCESO SEMAFORO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T21:47:57.000000Z', 'updated_at' => '2021-12-07T21:47:57.000000Z',]); // 101
        FosStse::create(['codigo' => '', 'nombre' => 'INCUMPLIMIENTO AL PROCESO SEMAFORO ( RIPS)', 'descripcion' => 'RETIRO AL PROCESO SEMAFORO DEBIDO AL INCUMPLIMIENTO DEL PROCESO CHC.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-07T21:48:55.000000Z', 'updated_at' => '2021-12-07T21:48:55.000000Z',]); // 102
        FosStse::create(['codigo' => '', 'nombre' => 'SEMAFORO (CPSM)', 'descripcion' => 'CULMINACIÓN SATISFACTORIA DE LA ETAPA SEMAFORO, DONDE SE ALCANZAN LOS OBJETIVOS PROPUESTOS PARA EL PROCESO DEL JOVEN Y SU CONTINUIDAD A LA SIGUIENTE ETAPA DE ACUERDO A SUS EXPECTATIVAS Y LOS AVANCES EVIDENCIADOS DESDE CADA UNA DE LAS ÁREAS.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-09T20:46:11.000000Z', 'updated_at' => '2021-12-09T20:53:30.000000Z',]); // 103
        FosStse::create(['codigo' => '', 'nombre' => 'PROCESO SEMAFORO (CMPS)', 'descripcion' => 'CONCEPTO DE LA EJECUCIÓN DEL COMITÉ MISIONAL DE UPI REFERENET AL PROCESO SEMAFORO.', 'estusuario_id' => '49', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => '1', 'created_at' => '2021-12-09T20:56:59.000000Z', 'updated_at' => '2021-12-09T20:56:59.000000Z',]); // 104
        // 5333
    }
}
