<?php

use App\Models\Indicadores\InDocPregunta;
use Illuminate\Database\Seeder;

class InDocPreguntasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        InDocPregunta::create(['in_ligru_id' => 1, 'in_pregunta_id' => 40, 'sis_tabla_id' => 102, 'sis_campo_tabla_id' => 278, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //1
        InDocPregunta::create(['in_ligru_id' => 2, 'in_pregunta_id' => 41, 'sis_tabla_id' => 97, 'sis_campo_tabla_id' => 272, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //2
        InDocPregunta::create(['in_ligru_id' => 3, 'in_pregunta_id' => 49, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 218, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //3
        InDocPregunta::create(['in_ligru_id' => 4, 'in_pregunta_id' => 10, 'sis_tabla_id' => 30, 'sis_campo_tabla_id' => 91, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //4
        InDocPregunta::create(['in_ligru_id' => 4, 'in_pregunta_id' => 11, 'sis_tabla_id' => 30, 'sis_campo_tabla_id' => 92, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //5
        InDocPregunta::create(['in_ligru_id' => 4, 'in_pregunta_id' => 79, 'sis_tabla_id' => 29, 'sis_campo_tabla_id' => 89, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //6
        InDocPregunta::create(['in_ligru_id' => 5, 'in_pregunta_id' => 80, 'sis_tabla_id' => 28, 'sis_campo_tabla_id' => 88, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //7
        InDocPregunta::create(['in_ligru_id' => 6, 'in_pregunta_id' => 62, 'sis_tabla_id' => 91, 'sis_campo_tabla_id' => 252, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //8
        InDocPregunta::create(['in_ligru_id' => 6, 'in_pregunta_id' => 66, 'sis_tabla_id' => 91, 'sis_campo_tabla_id' => 254, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //9
        InDocPregunta::create(['in_ligru_id' => 7, 'in_pregunta_id' => 62, 'sis_tabla_id' => 91, 'sis_campo_tabla_id' => 252, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //10
        InDocPregunta::create(['in_ligru_id' => 7, 'in_pregunta_id' => 68, 'sis_tabla_id' => 91, 'sis_campo_tabla_id' => 253, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //11
        InDocPregunta::create(['in_ligru_id' => 8, 'in_pregunta_id' => 47, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 70, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //12
        InDocPregunta::create(['in_ligru_id' => 8, 'in_pregunta_id' => 48, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 73, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //13
        InDocPregunta::create(['in_ligru_id' => 9, 'in_pregunta_id' => 72, 'sis_tabla_id' => 26, 'sis_campo_tabla_id' => 86, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //14
        InDocPregunta::create(['in_ligru_id' => 10, 'in_pregunta_id' => 70, 'sis_tabla_id' => 104, 'sis_campo_tabla_id' => 288, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //15
        InDocPregunta::create(['in_ligru_id' => 11, 'in_pregunta_id' => 45, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 70, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //16
        InDocPregunta::create(['in_ligru_id' => 11, 'in_pregunta_id' => 48, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 73, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //17
        InDocPregunta::create(['in_ligru_id' => 12, 'in_pregunta_id' => 42, 'sis_tabla_id' => 79, 'sis_campo_tabla_id' => 233, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //18
        InDocPregunta::create(['in_ligru_id' => 13, 'in_pregunta_id' => 67, 'sis_tabla_id' => 38, 'sis_campo_tabla_id' => 133, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //19
        InDocPregunta::create(['in_ligru_id' => 14, 'in_pregunta_id' => 73, 'sis_tabla_id' => 25, 'sis_campo_tabla_id' => 85, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //20
        InDocPregunta::create(['in_ligru_id' => 15, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //21
        InDocPregunta::create(['in_ligru_id' => 16, 'in_pregunta_id' => 70, 'sis_tabla_id' => 104, 'sis_campo_tabla_id' => 288, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //22
        InDocPregunta::create(['in_ligru_id' => 17, 'in_pregunta_id' => 50, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 219, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //23
        InDocPregunta::create(['in_ligru_id' => 18, 'in_pregunta_id' => 63, 'sis_tabla_id' => 66, 'sis_campo_tabla_id' => 66, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //24
        InDocPregunta::create(['in_ligru_id' => 19, 'in_pregunta_id' => 17, 'sis_tabla_id' => 118, 'sis_campo_tabla_id' => 329, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //25
        InDocPregunta::create(['in_ligru_id' => 20, 'in_pregunta_id' => 51, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 222, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //26
        InDocPregunta::create(['in_ligru_id' => 20, 'in_pregunta_id' => 82, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 221, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //27
        InDocPregunta::create(['in_ligru_id' => 20, 'in_pregunta_id' => 83, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 223, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //28
        InDocPregunta::create(['in_ligru_id' => 20, 'in_pregunta_id' => 52, 'sis_tabla_id' => 72, 'sis_campo_tabla_id' => 225, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //29
        InDocPregunta::create(['in_ligru_id' => 21, 'in_pregunta_id' => 69, 'sis_tabla_id' => 105, 'sis_campo_tabla_id' => 289, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //30
        InDocPregunta::create(['in_ligru_id' => 22, 'in_pregunta_id' => 14, 'sis_tabla_id' => 6, 'sis_campo_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //31
        InDocPregunta::create(['in_ligru_id' => 22, 'in_pregunta_id' => 64, 'sis_tabla_id' => 135, 'sis_campo_tabla_id' => 407, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //32
        InDocPregunta::create(['in_ligru_id' => 23, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //33
        InDocPregunta::create(['in_ligru_id' => 24, 'in_pregunta_id' => 65, 'sis_tabla_id' => 66, 'sis_campo_tabla_id' => 66, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //34
        InDocPregunta::create(['in_ligru_id' => 25, 'in_pregunta_id' => 11, 'sis_tabla_id' => 30, 'sis_campo_tabla_id' => 92, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //35
        InDocPregunta::create(['in_ligru_id' => 25, 'in_pregunta_id' => 15, 'sis_tabla_id' => 66, 'sis_campo_tabla_id' => 66, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //36
        InDocPregunta::create(['in_ligru_id' => 26, 'in_pregunta_id' => 13, 'sis_tabla_id' => 6, 'sis_campo_tabla_id' => 16, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //37
        InDocPregunta::create(['in_ligru_id' => 27, 'in_pregunta_id' => 16, 'sis_tabla_id' => 124, 'sis_campo_tabla_id' => 384, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //38
        InDocPregunta::create(['in_ligru_id' => 28, 'in_pregunta_id' => 71, 'sis_tabla_id' => 31, 'sis_campo_tabla_id' => 105, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //39
        InDocPregunta::create(['in_ligru_id' => 29, 'in_pregunta_id' => 65, 'sis_tabla_id' => 66, 'sis_campo_tabla_id' => 66, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //40
        InDocPregunta::create(['in_ligru_id' => 30, 'in_pregunta_id' => 45, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 70, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //41
        InDocPregunta::create(['in_ligru_id' => 30, 'in_pregunta_id' => 48, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 73, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //42
        InDocPregunta::create(['in_ligru_id' => 31, 'in_pregunta_id' => 54, 'sis_tabla_id' => 39, 'sis_campo_tabla_id' => 134, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //43
        InDocPregunta::create(['in_ligru_id' => 32, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //44
        InDocPregunta::create(['in_ligru_id' => 33, 'in_pregunta_id' => 53, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 150, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //45
        InDocPregunta::create(['in_ligru_id' => 33, 'in_pregunta_id' => 56, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 161, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //46
        InDocPregunta::create(['in_ligru_id' => 34, 'in_pregunta_id' => 57, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 165, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //47
        InDocPregunta::create(['in_ligru_id' => 34, 'in_pregunta_id' => 58, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 166, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //48
        InDocPregunta::create(['in_ligru_id' => 35, 'in_pregunta_id' => 60, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 169, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //49
        InDocPregunta::create(['in_ligru_id' => 36, 'in_pregunta_id' => 17, 'sis_tabla_id' => 118, 'sis_campo_tabla_id' => 329, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //50
        InDocPregunta::create(['in_ligru_id' => 37, 'in_pregunta_id' => 19, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 381, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //51
        InDocPregunta::create(['in_ligru_id' => 38, 'in_pregunta_id' => 54, 'sis_tabla_id' => 39, 'sis_campo_tabla_id' => 134, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //52
        InDocPregunta::create(['in_ligru_id' => 39, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //53
        InDocPregunta::create(['in_ligru_id' => 40, 'in_pregunta_id' => 50, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 219, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //54
        InDocPregunta::create(['in_ligru_id' => 41, 'in_pregunta_id' => 53, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 150, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //55
        InDocPregunta::create(['in_ligru_id' => 41, 'in_pregunta_id' => 56, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 161, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //56
        InDocPregunta::create(['in_ligru_id' => 42, 'in_pregunta_id' => 59, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 168, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //57
        InDocPregunta::create(['in_ligru_id' => 43, 'in_pregunta_id' => 60, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 169, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //58
        InDocPregunta::create(['in_ligru_id' => 43, 'in_pregunta_id' => 61, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 170, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //59
        InDocPregunta::create(['in_ligru_id' => 44, 'in_pregunta_id' => 17, 'sis_tabla_id' => 118, 'sis_campo_tabla_id' => 329, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //60
        InDocPregunta::create(['in_ligru_id' => 45, 'in_pregunta_id' => 19, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 381, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //61
        InDocPregunta::create(['in_ligru_id' => 46, 'in_pregunta_id' => 54, 'sis_tabla_id' => 39, 'sis_campo_tabla_id' => 134, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //62
        InDocPregunta::create(['in_ligru_id' => 47, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //63
        InDocPregunta::create(['in_ligru_id' => 48, 'in_pregunta_id' => 43, 'sis_tabla_id' => 103, 'sis_campo_tabla_id' => 279, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //64
        InDocPregunta::create(['in_ligru_id' => 49, 'in_pregunta_id' => 53, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 150, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //65
        InDocPregunta::create(['in_ligru_id' => 49, 'in_pregunta_id' => 56, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 161, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //66
        InDocPregunta::create(['in_ligru_id' => 50, 'in_pregunta_id' => 60, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 169, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //67
        InDocPregunta::create(['in_ligru_id' => 51, 'in_pregunta_id' => 61, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 170, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //68
        InDocPregunta::create(['in_ligru_id' => 51, 'in_pregunta_id' => 84, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 171, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //69
        InDocPregunta::create(['in_ligru_id' => 52, 'in_pregunta_id' => 43, 'sis_tabla_id' => 103, 'sis_campo_tabla_id' => 279, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //70
        InDocPregunta::create(['in_ligru_id' => 52, 'in_pregunta_id' => 44, 'sis_tabla_id' => 103, 'sis_campo_tabla_id' => 280, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //71
        InDocPregunta::create(['in_ligru_id' => 53, 'in_pregunta_id' => 17, 'sis_tabla_id' => 118, 'sis_campo_tabla_id' => 329, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //72
        InDocPregunta::create(['in_ligru_id' => 54, 'in_pregunta_id' => 19, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 381, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //73
        InDocPregunta::create(['in_ligru_id' => 55, 'in_pregunta_id' => 2, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 25, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //74
        InDocPregunta::create(['in_ligru_id' => 55, 'in_pregunta_id' => 3, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 32, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //75
        InDocPregunta::create(['in_ligru_id' => 55, 'in_pregunta_id' => 4, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 33, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //76
        InDocPregunta::create(['in_ligru_id' => 56, 'in_pregunta_id' => 54, 'sis_tabla_id' => 39, 'sis_campo_tabla_id' => 134, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //77
        InDocPregunta::create(['in_ligru_id' => 56, 'in_pregunta_id' => 55, 'sis_tabla_id' => 66, 'sis_campo_tabla_id' => 66, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //78
        InDocPregunta::create(['in_ligru_id' => 57, 'in_pregunta_id' => 8, 'sis_tabla_id' => 109, 'sis_campo_tabla_id' => 293, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //79
        InDocPregunta::create(['in_ligru_id' => 57, 'in_pregunta_id' => 85, 'sis_tabla_id' => 74, 'sis_campo_tabla_id' => 230, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //80
        InDocPregunta::create(['in_ligru_id' => 58, 'in_pregunta_id' => 82, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 221, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //81
        InDocPregunta::create(['in_ligru_id' => 58, 'in_pregunta_id' => 51, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 222, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //82
        InDocPregunta::create(['in_ligru_id' => 58, 'in_pregunta_id' => 83, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 223, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //83
        InDocPregunta::create(['in_ligru_id' => 59, 'in_pregunta_id' => 1, 'sis_tabla_id' => 66, 'sis_campo_tabla_id' => 66, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //84
        InDocPregunta::create(['in_ligru_id' => 60, 'in_pregunta_id' => 5, 'sis_tabla_id' => 110, 'sis_campo_tabla_id' => 319, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //85
        InDocPregunta::create(['in_ligru_id' => 60, 'in_pregunta_id' => 6, 'sis_tabla_id' => 110, 'sis_campo_tabla_id' => 319, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //86
        InDocPregunta::create(['in_ligru_id' => 60, 'in_pregunta_id' => 7, 'sis_tabla_id' => 108, 'sis_campo_tabla_id' => 292, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //87
        InDocPregunta::create(['in_ligru_id' => 60, 'in_pregunta_id' => 8, 'sis_tabla_id' => 109, 'sis_campo_tabla_id' => 293, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //88
        InDocPregunta::create(['in_ligru_id' => 61, 'in_pregunta_id' => 64, 'sis_tabla_id' => 135, 'sis_campo_tabla_id' => 407, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //89
        InDocPregunta::create(['in_ligru_id' => 61, 'in_pregunta_id' => 85, 'sis_tabla_id' => 74, 'sis_campo_tabla_id' => 230, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //90
        InDocPregunta::create(['in_ligru_id' => 62, 'in_pregunta_id' => 77, 'sis_tabla_id' => 91, 'sis_campo_tabla_id' => 256, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //91
        InDocPregunta::create(['in_ligru_id' => 62, 'in_pregunta_id' => 78, 'sis_tabla_id' => 91, 'sis_campo_tabla_id' => 257, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //92
        InDocPregunta::create(['in_ligru_id' => 63, 'in_pregunta_id' => 2, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 25, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //93
        InDocPregunta::create(['in_ligru_id' => 63, 'in_pregunta_id' => 3, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 32, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //94
        InDocPregunta::create(['in_ligru_id' => 63, 'in_pregunta_id' => 4, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 33, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //95
        InDocPregunta::create(['in_ligru_id' => 64, 'in_pregunta_id' => 5, 'sis_tabla_id' => 110, 'sis_campo_tabla_id' => 319, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //96
        InDocPregunta::create(['in_ligru_id' => 65, 'in_pregunta_id' => 4, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 33, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //97
        InDocPregunta::create(['in_ligru_id' => 66, 'in_pregunta_id' => 7, 'sis_tabla_id' => 108, 'sis_campo_tabla_id' => 292, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //98
        InDocPregunta::create(['in_ligru_id' => 66, 'in_pregunta_id' => 75, 'sis_tabla_id' => 69, 'sis_campo_tabla_id' => 212, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //99
        InDocPregunta::create(['in_ligru_id' => 66, 'in_pregunta_id' => 76, 'sis_tabla_id' => 94, 'sis_campo_tabla_id' => 262, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //100
        InDocPregunta::create(['in_ligru_id' => 67, 'in_pregunta_id' => 45, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 70, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //101
        InDocPregunta::create(['in_ligru_id' => 67, 'in_pregunta_id' => 48, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 73, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //102
        InDocPregunta::create(['in_ligru_id' => 68, 'in_pregunta_id' => 74, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 22, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //103
        InDocPregunta::create(['in_ligru_id' => 68, 'in_pregunta_id' => 64, 'sis_tabla_id' => 135, 'sis_campo_tabla_id' => 407, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //104
        InDocPregunta::create(['in_ligru_id' => 69, 'in_pregunta_id' => 72, 'sis_tabla_id' => 26, 'sis_campo_tabla_id' => 86, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //105
        InDocPregunta::create(['in_ligru_id' => 70, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //106
        InDocPregunta::create(['in_ligru_id' => 70, 'in_pregunta_id' => 12, 'sis_tabla_id' => 107, 'sis_campo_tabla_id' => 291, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //107
        InDocPregunta::create(['in_ligru_id' => 71, 'in_pregunta_id' => 64, 'sis_tabla_id' => 135, 'sis_campo_tabla_id' => 407, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //108
        InDocPregunta::create(['in_ligru_id' => 72, 'in_pregunta_id' => 16, 'sis_tabla_id' => 124, 'sis_campo_tabla_id' => 384, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //109
        InDocPregunta::create(['in_ligru_id' => 73, 'in_pregunta_id' => 17, 'sis_tabla_id' => 118, 'sis_campo_tabla_id' => 329, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //110
        InDocPregunta::create(['in_ligru_id' => 74, 'in_pregunta_id' => 19, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 381, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //111
        InDocPregunta::create(['in_ligru_id' => 75, 'in_pregunta_id' => 74, 'sis_tabla_id' => 9, 'sis_campo_tabla_id' => 22, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //112
        InDocPregunta::create(['in_ligru_id' => 75, 'in_pregunta_id' => 64, 'sis_tabla_id' => 135, 'sis_campo_tabla_id' => 407, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //113
        InDocPregunta::create(['in_ligru_id' => 76, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //114
        InDocPregunta::create(['in_ligru_id' => 76, 'in_pregunta_id' => 12, 'sis_tabla_id' => 107, 'sis_campo_tabla_id' => 291, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //115
        InDocPregunta::create(['in_ligru_id' => 77, 'in_pregunta_id' => 18, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 373, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //116
        InDocPregunta::create(['in_ligru_id' => 77, 'in_pregunta_id' => 39, 'sis_tabla_id' => 54, 'sis_campo_tabla_id' => 192, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //117
        InDocPregunta::create(['in_ligru_id' => 78, 'in_pregunta_id' => 18, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 373, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //118
        InDocPregunta::create(['in_ligru_id' => 78, 'in_pregunta_id' => 35, 'sis_tabla_id' => 119, 'sis_campo_tabla_id' => 338, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //119
        InDocPregunta::create(['in_ligru_id' => 79, 'in_pregunta_id' => 18, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 373, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //120
        InDocPregunta::create(['in_ligru_id' => 80, 'in_pregunta_id' => 16, 'sis_tabla_id' => 124, 'sis_campo_tabla_id' => 384, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //121
        InDocPregunta::create(['in_ligru_id' => 81, 'in_pregunta_id' => 18, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 373, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //122
        InDocPregunta::create(['in_ligru_id' => 81, 'in_pregunta_id' => 35, 'sis_tabla_id' => 119, 'sis_campo_tabla_id' => 338, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //123
        InDocPregunta::create(['in_ligru_id' => 82, 'in_pregunta_id' => 72, 'sis_tabla_id' => 26, 'sis_campo_tabla_id' => 86, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //124
        InDocPregunta::create(['in_ligru_id' => 83, 'in_pregunta_id' => 73, 'sis_tabla_id' => 25, 'sis_campo_tabla_id' => 85, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //125
        InDocPregunta::create(['in_ligru_id' => 84, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //126
        InDocPregunta::create(['in_ligru_id' => 85, 'in_pregunta_id' => 30, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 265, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //127
        InDocPregunta::create(['in_ligru_id' => 85, 'in_pregunta_id' => 31, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 266, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //128
        InDocPregunta::create(['in_ligru_id' => 86, 'in_pregunta_id' => 32, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 269, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //129
        InDocPregunta::create(['in_ligru_id' => 86, 'in_pregunta_id' => 33, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 270, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //130
        InDocPregunta::create(['in_ligru_id' => 87, 'in_pregunta_id' => 40, 'sis_tabla_id' => 102, 'sis_campo_tabla_id' => 278, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //131
        InDocPregunta::create(['in_ligru_id' => 87, 'in_pregunta_id' => 41, 'sis_tabla_id' => 97, 'sis_campo_tabla_id' => 272, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //132
        InDocPregunta::create(['in_ligru_id' => 88, 'in_pregunta_id' => 64, 'sis_tabla_id' => 135, 'sis_campo_tabla_id' => 407, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //133
        InDocPregunta::create(['in_ligru_id' => 89, 'in_pregunta_id' => 16, 'sis_tabla_id' => 124, 'sis_campo_tabla_id' => 384, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //134
        InDocPregunta::create(['in_ligru_id' => 90, 'in_pregunta_id' => 72, 'sis_tabla_id' => 26, 'sis_campo_tabla_id' => 86, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //135
        InDocPregunta::create(['in_ligru_id' => 91, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //136
        InDocPregunta::create(['in_ligru_id' => 92, 'in_pregunta_id' => 28, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 264, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //137
        InDocPregunta::create(['in_ligru_id' => 92, 'in_pregunta_id' => 29, 'sis_tabla_id' => 100, 'sis_campo_tabla_id' => 276, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //138
        InDocPregunta::create(['in_ligru_id' => 93, 'in_pregunta_id' => 30, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 265, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //139
        InDocPregunta::create(['in_ligru_id' => 93, 'in_pregunta_id' => 31, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 266, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //140
        InDocPregunta::create(['in_ligru_id' => 94, 'in_pregunta_id' => 32, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 269, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //141
        InDocPregunta::create(['in_ligru_id' => 94, 'in_pregunta_id' => 33, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 270, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //142
        InDocPregunta::create(['in_ligru_id' => 95, 'in_pregunta_id' => 27, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 382, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //143
        InDocPregunta::create(['in_ligru_id' => 96, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //144
        InDocPregunta::create(['in_ligru_id' => 97, 'in_pregunta_id' => 28, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 264, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //145
        InDocPregunta::create(['in_ligru_id' => 97, 'in_pregunta_id' => 29, 'sis_tabla_id' => 100, 'sis_campo_tabla_id' => 276, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //146
        InDocPregunta::create(['in_ligru_id' => 98, 'in_pregunta_id' => 33, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 270, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //147
        InDocPregunta::create(['in_ligru_id' => 99, 'in_pregunta_id' => 40, 'sis_tabla_id' => 102, 'sis_campo_tabla_id' => 278, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //148
        InDocPregunta::create(['in_ligru_id' => 99, 'in_pregunta_id' => 41, 'sis_tabla_id' => 97, 'sis_campo_tabla_id' => 272, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //149
        InDocPregunta::create(['in_ligru_id' => 100, 'in_pregunta_id' => 19, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 381, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //150
        InDocPregunta::create(['in_ligru_id' => 101, 'in_pregunta_id' => 25, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 300, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //151
        InDocPregunta::create(['in_ligru_id' => 102, 'in_pregunta_id' => 26, 'sis_tabla_id' => 126, 'sis_campo_tabla_id' => 386, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //152
        InDocPregunta::create(['in_ligru_id' => 103, 'in_pregunta_id' => 9, 'sis_tabla_id' => 52, 'sis_campo_tabla_id' => 187, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //153
        InDocPregunta::create(['in_ligru_id' => 104, 'in_pregunta_id' => 28, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 264, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //154
        InDocPregunta::create(['in_ligru_id' => 104, 'in_pregunta_id' => 29, 'sis_tabla_id' => 100, 'sis_campo_tabla_id' => 276, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //155
        InDocPregunta::create(['in_ligru_id' => 105, 'in_pregunta_id' => 38, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 376, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //156
        InDocPregunta::create(['in_ligru_id' => 105, 'in_pregunta_id' => 19, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 381, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //157
        InDocPregunta::create(['in_ligru_id' => 106, 'in_pregunta_id' => 20, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 377, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //158
        InDocPregunta::create(['in_ligru_id' => 106, 'in_pregunta_id' => 23, 'sis_tabla_id' => 125, 'sis_campo_tabla_id' => 385, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //159
        InDocPregunta::create(['in_ligru_id' => 107, 'in_pregunta_id' => 26, 'sis_tabla_id' => 126, 'sis_campo_tabla_id' => 386, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //160
        InDocPregunta::create(['in_ligru_id' => 108, 'in_pregunta_id' => 28, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 264, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //161
        InDocPregunta::create(['in_ligru_id' => 108, 'in_pregunta_id' => 29, 'sis_tabla_id' => 100, 'sis_campo_tabla_id' => 276, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //162
        InDocPregunta::create(['in_ligru_id' => 109, 'in_pregunta_id' => 19, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 381, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //163
        InDocPregunta::create(['in_ligru_id' => 109, 'in_pregunta_id' => 38, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 376, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //164
        InDocPregunta::create(['in_ligru_id' => 110, 'in_pregunta_id' => 20, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 377, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //165
        InDocPregunta::create(['in_ligru_id' => 110, 'in_pregunta_id' => 21, 'sis_tabla_id' => 33, 'sis_campo_tabla_id' => 119, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //166
        InDocPregunta::create(['in_ligru_id' => 111, 'in_pregunta_id' => 24, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 379, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //167
        InDocPregunta::create(['in_ligru_id' => 112, 'in_pregunta_id' => 22, 'sis_tabla_id' => 128, 'sis_campo_tabla_id' => 389, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //168
        InDocPregunta::create(['in_ligru_id' => 112, 'in_pregunta_id' => 23, 'sis_tabla_id' => 125, 'sis_campo_tabla_id' => 385, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //169
        InDocPregunta::create(['in_ligru_id' => 113, 'in_pregunta_id' => 25, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 300, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //170
        InDocPregunta::create(['in_ligru_id' => 114, 'in_pregunta_id' => 45, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 70, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //171
        InDocPregunta::create(['in_ligru_id' => 114, 'in_pregunta_id' => 48, 'sis_tabla_id' => 22, 'sis_campo_tabla_id' => 73, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //172
        InDocPregunta::create(['in_ligru_id' => 115, 'in_pregunta_id' => 54, 'sis_tabla_id' => 39, 'sis_campo_tabla_id' => 134, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //173
        InDocPregunta::create(['in_ligru_id' => 116, 'in_pregunta_id' => 72, 'sis_tabla_id' => 26, 'sis_campo_tabla_id' => 86, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //174
        InDocPregunta::create(['in_ligru_id' => 117, 'in_pregunta_id' => 28, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 264, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //175
        InDocPregunta::create(['in_ligru_id' => 117, 'in_pregunta_id' => 29, 'sis_tabla_id' => 100, 'sis_campo_tabla_id' => 276, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //176
        InDocPregunta::create(['in_ligru_id' => 118, 'in_pregunta_id' => 30, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 265, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //177
        InDocPregunta::create(['in_ligru_id' => 118, 'in_pregunta_id' => 31, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 266, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //178
        InDocPregunta::create(['in_ligru_id' => 119, 'in_pregunta_id' => 32, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 269, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //179
        InDocPregunta::create(['in_ligru_id' => 119, 'in_pregunta_id' => 33, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 270, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //180
        InDocPregunta::create(['in_ligru_id' => 120, 'in_pregunta_id' => 34, 'sis_tabla_id' => 69, 'sis_campo_tabla_id' => 212, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //181
        InDocPregunta::create(['in_ligru_id' => 120, 'in_pregunta_id' => 37, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 169, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //182
        InDocPregunta::create(['in_ligru_id' => 121, 'in_pregunta_id' => 50, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 219, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //183
        InDocPregunta::create(['in_ligru_id' => 122, 'in_pregunta_id' => 25, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 300, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //184
        InDocPregunta::create(['in_ligru_id' => 123, 'in_pregunta_id' => 26, 'sis_tabla_id' => 126, 'sis_campo_tabla_id' => 386, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //185
        InDocPregunta::create(['in_ligru_id' => 124, 'in_pregunta_id' => 54, 'sis_tabla_id' => 39, 'sis_campo_tabla_id' => 134, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //186
        InDocPregunta::create(['in_ligru_id' => 125, 'in_pregunta_id' => 28, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 264, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //187
        InDocPregunta::create(['in_ligru_id' => 125, 'in_pregunta_id' => 29, 'sis_tabla_id' => 100, 'sis_campo_tabla_id' => 276, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //188
        InDocPregunta::create(['in_ligru_id' => 126, 'in_pregunta_id' => 30, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 265, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //189
        InDocPregunta::create(['in_ligru_id' => 126, 'in_pregunta_id' => 31, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 266, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //190
        InDocPregunta::create(['in_ligru_id' => 127, 'in_pregunta_id' => 32, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 269, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //191
        InDocPregunta::create(['in_ligru_id' => 127, 'in_pregunta_id' => 33, 'sis_tabla_id' => 96, 'sis_campo_tabla_id' => 270, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //192
        InDocPregunta::create(['in_ligru_id' => 128, 'in_pregunta_id' => 34, 'sis_tabla_id' => 69, 'sis_campo_tabla_id' => 212, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //193
        InDocPregunta::create(['in_ligru_id' => 128, 'in_pregunta_id' => 37, 'sis_tabla_id' => 40, 'sis_campo_tabla_id' => 169, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //194
        InDocPregunta::create(['in_ligru_id' => 129, 'in_pregunta_id' => 40, 'sis_tabla_id' => 102, 'sis_campo_tabla_id' => 278, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //195
        InDocPregunta::create(['in_ligru_id' => 130, 'in_pregunta_id' => 50, 'sis_tabla_id' => 71, 'sis_campo_tabla_id' => 219, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //196
        InDocPregunta::create(['in_ligru_id' => 131, 'in_pregunta_id' => 16, 'sis_tabla_id' => 124, 'sis_campo_tabla_id' => 384, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //197
        InDocPregunta::create(['in_ligru_id' => 132, 'in_pregunta_id' => 25, 'sis_tabla_id' => 123, 'sis_campo_tabla_id' => 300, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //198
        InDocPregunta::create(['in_ligru_id' => 133, 'in_pregunta_id' => 26, 'sis_tabla_id' => 126, 'sis_campo_tabla_id' => 386, 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //199
    }
}
