<?php

use App\Models\sistema\ParametroArea;
use App\Models\sistema\ParametroSubarea;
use App\Models\Tema;
use App\Models\Temacombo;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

use Spatie\Permission\Models\Permission;

class IntervencionAdminSeeder extends Seeder
{
     /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

      

         $areaxxxx = array(
            [
                "prm_atencion_id" => 1062,
                "prm_area_id" => 282,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1062,
                "prm_area_id" => 1059,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1062,
                "prm_area_id" => 1058,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1062,
                "prm_area_id" => 448,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1062,
                "prm_area_id" => 525,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1062,
                "prm_area_id" => 449,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1062,
                "prm_area_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1063,
                "prm_area_id" => 282,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1063,
                "prm_area_id" => 1059,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1063,
                "prm_area_id" => 1058,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1063,
                "prm_area_id" => 448,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1063,
                "prm_area_id" => 525,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1063,
                "prm_area_id" => 449,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1063,
                "prm_area_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1064,
                "prm_area_id" => 282,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1064,
                "prm_area_id" => 1059,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1064,
                "prm_area_id" => 1058,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1064,
                "prm_area_id" => 448,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1064,
                "prm_area_id" => 525,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1064,
                "prm_area_id" => 449,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1064,
                "prm_area_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1065,
                "prm_area_id" => 282,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1065,
                "prm_area_id" => 1059,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1065,
                "prm_area_id" => 1058,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1065,
                "prm_area_id" => 448,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1065,
                "prm_area_id" => 525,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1065,
                "prm_area_id" => 449,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1065,
                "prm_area_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "prm_atencion_id" => 1067,
                "prm_area_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ]
        );

        ParametroArea::insert($areaxxxx);

        $subarea = array(
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 895,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 899,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 894,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 897,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 900,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 898,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 893,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 576,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 890,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 892,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 339,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 889,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 891,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 896,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 1,
                "prm_subajuste_id" => 663,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 2,
                "prm_subajuste_id" => 882,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 2,
                "prm_subajuste_id" => 879,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 2,
                "prm_subajuste_id" => 881,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 2,
                "prm_subajuste_id" => 880,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 3,
                "prm_subajuste_id" => 875,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 3,
                "prm_subajuste_id" => 1632,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 3,
                "prm_subajuste_id" => 878,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 3,
                "prm_subajuste_id" => 877,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 3,
                "prm_subajuste_id" => 876,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 4,
                "prm_subajuste_id" => 869,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 4,
                "prm_subajuste_id" => 868,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 4,
                "prm_subajuste_id" => 867,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 4,
                "prm_subajuste_id" => 870,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 4,
                "prm_subajuste_id" => 865,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 4,
                "prm_subajuste_id" => 871,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 4,
                "prm_subajuste_id" => 866,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 5,
                "prm_subajuste_id" => 872,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 5,
                "prm_subajuste_id" => 874,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 5,
                "prm_subajuste_id" => 873,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 5,
                "prm_subajuste_id" => 581,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 5,
                "prm_subajuste_id" => 563,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 6,
                "prm_subajuste_id" => 888,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 6,
                "prm_subajuste_id" => 887,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 6,
                "prm_subajuste_id" => 883,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 6,
                "prm_subajuste_id" => 885,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 6,
                "prm_subajuste_id" => 2137,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 6,
                "prm_subajuste_id" => 886,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 6,
                "prm_subajuste_id" => 884,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 6,
                "prm_subajuste_id" => 1633,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 7,
                "prm_subajuste_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 895,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 899,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 894,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 897,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 900,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 898,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 893,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 576,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 890,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 892,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 339,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 889,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 891,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 896,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 8,
                "prm_subajuste_id" => 663,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 9,
                "prm_subajuste_id" => 882,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 9,
                "prm_subajuste_id" => 880,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 9,
                "prm_subajuste_id" => 879,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 9,
                "prm_subajuste_id" => 881,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 10,
                "prm_subajuste_id" => 878,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 10,
                "prm_subajuste_id" => 877,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 10,
                "prm_subajuste_id" => 875,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 10,
                "prm_subajuste_id" => 1632,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 10,
                "prm_subajuste_id" => 876,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 11,
                "prm_subajuste_id" => 866,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 11,
                "prm_subajuste_id" => 865,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 11,
                "prm_subajuste_id" => 871,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 11,
                "prm_subajuste_id" => 869,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 11,
                "prm_subajuste_id" => 868,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 11,
                "prm_subajuste_id" => 867,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 11,
                "prm_subajuste_id" => 870,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 12,
                "prm_subajuste_id" => 872,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 12,
                "prm_subajuste_id" => 874,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 12,
                "prm_subajuste_id" => 873,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 12,
                "prm_subajuste_id" => 581,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 12,
                "prm_subajuste_id" => 563,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 13,
                "prm_subajuste_id" => 884,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 13,
                "prm_subajuste_id" => 1633,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 13,
                "prm_subajuste_id" => 888,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 13,
                "prm_subajuste_id" => 887,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 13,
                "prm_subajuste_id" => 883,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 13,
                "prm_subajuste_id" => 885,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 13,
                "prm_subajuste_id" => 2137,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 13,
                "prm_subajuste_id" => 886,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 14,
                "prm_subajuste_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 895,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 899,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 894,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 897,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 900,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 898,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 893,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 576,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 890,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 892,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 339,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 889,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 891,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 896,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 15,
                "prm_subajuste_id" => 663,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 16,
                "prm_subajuste_id" => 882,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 16,
                "prm_subajuste_id" => 880,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 16,
                "prm_subajuste_id" => 879,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 16,
                "prm_subajuste_id" => 881,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 17,
                "prm_subajuste_id" => 875,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 17,
                "prm_subajuste_id" => 1632,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 17,
                "prm_subajuste_id" => 878,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 17,
                "prm_subajuste_id" => 877,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 17,
                "prm_subajuste_id" => 876,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 18,
                "prm_subajuste_id" => 869,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 18,
                "prm_subajuste_id" => 870,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 18,
                "prm_subajuste_id" => 865,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 18,
                "prm_subajuste_id" => 871,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 18,
                "prm_subajuste_id" => 866,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 18,
                "prm_subajuste_id" => 868,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 18,
                "prm_subajuste_id" => 867,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 19,
                "prm_subajuste_id" => 872,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 19,
                "prm_subajuste_id" => 873,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 19,
                "prm_subajuste_id" => 581,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 19,
                "prm_subajuste_id" => 563,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 19,
                "prm_subajuste_id" => 874,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 20,
                "prm_subajuste_id" => 884,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 20,
                "prm_subajuste_id" => 1633,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 20,
                "prm_subajuste_id" => 888,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 20,
                "prm_subajuste_id" => 887,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 20,
                "prm_subajuste_id" => 883,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 20,
                "prm_subajuste_id" => 885,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 20,
                "prm_subajuste_id" => 2137,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 20,
                "prm_subajuste_id" => 886,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 21,
                "prm_subajuste_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 895,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 892,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 899,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 894,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 897,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 900,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 898,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 893,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 576,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 890,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 339,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 889,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 891,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 896,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 22,
                "prm_subajuste_id" => 663,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 23,
                "prm_subajuste_id" => 882,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 23,
                "prm_subajuste_id" => 880,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 23,
                "prm_subajuste_id" => 879,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 23,
                "prm_subajuste_id" => 881,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 24,
                "prm_subajuste_id" => 878,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 24,
                "prm_subajuste_id" => 875,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 24,
                "prm_subajuste_id" => 1632,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 24,
                "prm_subajuste_id" => 877,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 24,
                "prm_subajuste_id" => 876,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 25,
                "prm_subajuste_id" => 869,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 25,
                "prm_subajuste_id" => 868,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 25,
                "prm_subajuste_id" => 867,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 25,
                "prm_subajuste_id" => 870,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 25,
                "prm_subajuste_id" => 865,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 25,
                "prm_subajuste_id" => 871,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 25,
                "prm_subajuste_id" => 866,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 26,
                "prm_subajuste_id" => 872,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 26,
                "prm_subajuste_id" => 874,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 26,
                "prm_subajuste_id" => 873,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 26,
                "prm_subajuste_id" => 581,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 26,
                "prm_subajuste_id" => 563,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 27,
                "prm_subajuste_id" => 884,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 27,
                "prm_subajuste_id" => 1633,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 27,
                "prm_subajuste_id" => 888,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 27,
                "prm_subajuste_id" => 887,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 27,
                "prm_subajuste_id" => 883,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 27,
                "prm_subajuste_id" => 885,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 27,
                "prm_subajuste_id" => 2137,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 27,
                "prm_subajuste_id" => 886,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 28,
                "prm_subajuste_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ],
            [
                "area_parametro_id" => 29,
                "prm_subajuste_id" => 235,
                "user_crea_id" => 1,
                "user_edita_id" => 1,
                "sis_esta_id" => 1,
                'created_at' => new Datetime,
                'updated_at' => new Datetime,
            ]
        );

        ParametroSubarea::insert($subarea);

        // Limpia cache de permisos
        app()['cache']->forget('spatie.permission.cache');
        // Permisos de tipo atencion
        Permission::create([
            'name' => 'tipoatencion-modulo',
            'descripcion' => 'Permiso que permite ver el menu de: Gestion tipoatencion - intervenciones',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'tipoatencion-crear',
            'descripcion' => 'Permiso que permite crear una pagina de tipoatencion',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'tipoatencion-editar',
            'descripcion' => 'Permiso que permite editar una pagina de tipoatencion',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'tipoatencion-leer',
            'descripcion' => 'Permiso que permite leer una pagina de tipoatencion',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'tipoatencion-cambiar',
            'descripcion' => 'Permiso que permite cambiar la visibilidad de una pagina de tipoatencion',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);

        // Permisos Area de Ajuste
        Permission::create([
            'name' => 'intarea-modulo',
            'descripcion' => 'Permiso que permite ver el menu de: Gestion intarea - intervenciones',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'intarea-crear',
            'descripcion' => 'Permiso que permite crear una pagina de intarea',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'intarea-editar',
            'descripcion' => 'Permiso que permite editar una pagina de intarea',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'intarea-leer',
            'descripcion' => 'Permiso que permite leer una pagina de intarea',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'intarea-cambiar',
            'descripcion' => 'Permiso que permite cambiar la visibilidad de una pagina de intarea',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);

        // Permisos Subarea de Ajuste
        Permission::create([
            'name' => 'intsubarea-modulo',
            'descripcion' => 'Permiso que permite ver el menu de: Gestion intsubarea - intervenciones',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'intsubarea-crear',
            'descripcion' => 'Permiso que permite crear una pagina de intsubarea',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'intsubarea-editar',
            'descripcion' => 'Permiso que permite editar una pagina de intsubarea',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'intsubarea-leer',
            'descripcion' => 'Permiso que permite leer una pagina de intsubarea',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);
        Permission::create([
            'name' => 'intsubarea-cambiar',
            'descripcion' => 'Permiso que permite cambiar la visibilidad de una pagina de intsubarea',
            'sis_pestania_id' => 1,
            'user_crea_id' => 1,
            'user_edita_id' => 1,
            'sis_esta_id' => 1
        ]);

        $role = Role::find(1);
        $role ->givePermissionTo([
            'tipoatencion-modulo', 'tipoatencion-crear', 'tipoatencion-editar', 'tipoatencion-leer', 'tipoatencion-cambiar', 'intarea-modulo', 'intarea-crear', 'intarea-editar', 'intarea-leer', 'intarea-cambiar', 'intsubarea-modulo', 'intsubarea-crear', 'intsubarea-editar', 'intsubarea-leer', 'intsubarea-cambiar',
        ]);

        $role_dos = Role::find(2);
        $role_dos->givePermissionTo([
            'tipoatencion-crear', 'tipoatencion-editar', 'tipoatencion-leer', 'tipoatencion-cambiar', 'intarea-modulo', 'intarea-crear', 'intarea-editar', 'intarea-leer', 'intarea-cambiar', 'intsubarea-modulo', 'intsubarea-crear', 'intsubarea-editar', 'intsubarea-leer', 'intsubarea-cambiar',
        ]);

     }
}

