<?php

use App\Models\Acciones\Grupales\Traslado\MotivoEgresoSecu;
use Illuminate\Database\Seeder;

class MotivoEgresoSecusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 1, 'nombre' => 'CUMPLIMIENTO DE OBJETIVOS (CO):', 'descripcion' => 'Superación del motivo de ingreso al IDIPRON, garantizando el goce efectivo de derechos del NNAJ.', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //1
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 2, 'nombre' => 'RETIRO VOLUNTARIO SATISFACTORIO (RVS):',  'descripcion' => 'Se presenta cuando el Niño, Niña, Adolescente o Joven (NNAJ) o el representante legal de toda persona menor de edad, decide el retiro de la UPI y se garantiza el goce efectivo de los derechos', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //2
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 3, 'nombre' => 'CAMBIO DE MEDIDA:',  'descripcion' => 'Reintegro a medio familiar (ordenado por la autoridad administrativa). (CMRF): Se presenta en el momento que la autoridad administrativa competente decide reintegro a medio familiar de un NNA institucionalizado en el IDIPRON.', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //3
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 4, 'nombre' => 'VINCULACIÓN LABORAL DEL/LA JOVEN (VLJ):',  'descripcion' => 'Se presenta cuando un/a joven se retira del IDIPRON por vinculación laboral.  ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //4
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 5, 'nombre' => 'INCORPORACIÓN DEL JOVEN AL EJÉRCITO (IJA):', 'descripcion' => 'Terminación de proceso en el IDIPRON por vinculación del joven al ejercito.  ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //5
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 6, 'nombre' => 'RETORNO DEL O LA JOVEN A SU NÚCLEO FAMILIAR (RNF):', 'descripcion' => 'Se presenta cuando un/a joven en proceso con las UPI que atienden a población a CHC retorna a su núcleo familiar.  ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //6
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 7, 'nombre' => 'UBICACIÓN EN ALOJAMIENTO FIJO (UAF):', 'descripcion' => 'Se presenta cuando un/a joven en proceso con UPI que atienden a población a CHC se ubica en un alojamiento permanente.  ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //7
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 8, 'nombre' => 'FINALIZACIÓN PROYECTO MADRES PARA LA VIDA (FPM):', 'descripcion' => 'Egreso por finalización del proceso realizado en el Proyecto "Madres para la vida". ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //8
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 9, 'nombre' => 'INCUMPLIMIENTO DEL PACTO CONVIVENCIAL (IPC):', 'descripcion' => 'Retiro de la Unidad de Protección Integral o remisión definitiva a otra entidad por incumplimiento del Pacto Convivencial frente a la realización de faltas muy graves determinado por la UPI, con copia al representante legal y al Archivo Misional (Pacto Convivencial cód.: M-RDE-MA-001, acciones pedagógicas).  ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //9
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 10, 'nombre' => 'PRIVACIÓN DE LA LIBERTAD EN CENTROS DE ATENCIÓN ESPECIALIZADO, MENORES (PL):', 'descripcion' => 'Se presenta cuando un/a adolescente en proceso con el IDIPRON es trasladado a institución por proceso con SRPA.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //10
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 11, 'nombre' => 'PRIVACIÓN DE LA LIBERTAD EN CENTROS PENITENCIARIOS Y/O CARCELARIOS (PL):', 'descripcion' => 'Se presenta cuando un/a joven en proceso con el IDIPRON es trasladado a institución carcelaria.', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //11
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 12, 'nombre' => 'REMISIÓN A OTRAS INSTITUCIONES (ROI):', 'descripcion' => 'Se presenta cuando se realiza traslado de un NNAJ a otra institución por solicitud de atención en alguna especialidad: médica, terapéutica, protección, etc. ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //12
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 13, 'nombre' => 'CAMBIO DE MEDIDA: CAMBIO DE INSTITUCIÓN (ORDENADO POR LA AUTORIDAD ADMINISTRATIVA). (CMI):', 'descripcion' => 'Se presenta cuando la Autoridad Administrativa Competente ordena traslado de institución de Protección. ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //13
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 14, 'nombre' => 'RETIRO VOLUNTARIO NO SATISFACTORIO (RVNS) SEGÚN LAS SITUACIONES: -', 'descripcion' => 'Cuando el NNA y/o su representante legal decide el retiro de la UPI y no se garantiza el goce efectivo de los derechos por parte del sistema familiar. - Retiro manifiesto del Joven sin garantía del goce efectivo de sus derechos. ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //14
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 15, 'nombre' => 'DESERCIÓN (DS):', 'descripcion' => 'No regreso a la UPI o falta de voluntad del NNA, su sistema familiar o del/la joven por continuar el proceso con Territorio 1.  ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //15
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 16, 'nombre' => 'EVASIÓN (EV):', 'descripcion' => 'Salidas sin permiso de la UPI o de las actividades pedagógicas dentro y fuera de la Unidad (sólo aplica para UPI Internado).  ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //16
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 17, 'nombre' => 'CUALQUIER SITUACIÓN FAMILIAR QUE IMPIDA LA CONTINUIDAD DEL PROCESO. (CSF):', 'descripcion' => 'Situaciones familiares que impiden que un NNAJ continúe su proceso con el IDIPRON: Calamidad doméstica, viaje, trámites médicos o personales o cualquier otra situación familiar que se pueda presentar.  ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //17
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 18, 'nombre' => 'INGRESO A PROCESO DE INSTITUCIONALIZACIÓN CON AUTORIDAD ADMINISTRATIVA (IPI):', 'descripcion' => 'Se presenta cuando un NNA con proceso en Territorio 1 o vinculado UPI Contexto pedagógico Externado inicia proceso de Institucionalización de Autoridad Administrativa competente. ', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //18
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 19, 'nombre' => 'REMISIÓN INTERINSTITUCIONAL SIN RESPUESTA DE LA ENTIDAD (RISR):', 'descripcion' => 'Se presenta cuando Territorio 1 realiza solicitud para activación de redes y no recibe respuesta institucional (se da egreso para iniciar seguimiento a la respuesta institucional por parte del área Sociolegal y Justicia Restaurativa).', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //19
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 20, 'nombre' => 'PÉRDIDA DE CONTACTO CON EL NNAJ (PC)', 'descripcion' => 'Se presenta cuando se pierde contacto con un NNAJ vinculado en Territorio 1.', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //20
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 21, 'nombre' => 'DECESO (DC).', 'descripcion' => 'Deceso', 'user_crea_id' => 1, 'user_edita_id' => 1, 'sis_esta_id' => 1]); //21
        MotivoEgresoSecu::create(['estusuario_id'=>15,'id' => 22, 'nombre' => 'SIN INFORMACIÓN', 'descripcion' => 'SIN INFORMACIÓN', 'user_crea_id' => 1,  'user_edita_id' => 1, 'sis_esta_id' => 1]); //22
       }
}
