<?php

use App\Models\fichaIngreso\NnajSexo;
use Illuminate\Database\Seeder;

class NnajSexoNueveMilSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        NnajSexo::create(['id' => '8242', 'fi_datos_basico_id' => 9312, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8001
        NnajSexo::create(['id' => '8243', 'fi_datos_basico_id' => 9313, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 2086, 'user_edita_id' => 2086, 'sis_docfuen_id' => 2,]); // 8002
        NnajSexo::create(['id' => '8244', 'fi_datos_basico_id' => 9314, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 2086, 'user_edita_id' => 2086, 'sis_docfuen_id' => 2,]); // 8003
        NnajSexo::create(['id' => '8245', 'fi_datos_basico_id' => 9315, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8004
        NnajSexo::create(['id' => '8246', 'fi_datos_basico_id' => 9316, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8005
        NnajSexo::create(['id' => '8247', 'fi_datos_basico_id' => 9317, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 2065, 'user_edita_id' => 2065, 'sis_docfuen_id' => 2,]); // 8006
        NnajSexo::create(['id' => '8248', 'fi_datos_basico_id' => 9318, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 2065, 'user_edita_id' => 2065, 'sis_docfuen_id' => 2,]); // 8007
        NnajSexo::create(['id' => '8249', 'fi_datos_basico_id' => 9319, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 2065, 'user_edita_id' => 2065, 'sis_docfuen_id' => 2,]); // 8008
        NnajSexo::create(['id' => '8250', 'fi_datos_basico_id' => 9320, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 2086, 'user_edita_id' => 2086, 'sis_docfuen_id' => 2,]); // 8009
        NnajSexo::create(['id' => '8251', 'fi_datos_basico_id' => 9321, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 235, 'prm_orientacion_sexual_id' => 235, 'sis_esta_id' => 1, 'user_crea_id' => 1436, 'user_edita_id' => 1436, 'sis_docfuen_id' => 2,]); // 8010
        NnajSexo::create(['id' => '8252', 'fi_datos_basico_id' => 9322, 's_nombre_identitario' => '', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8011
        NnajSexo::create(['id' => '8253', 'fi_datos_basico_id' => 9323, 's_nombre_identitario' => 'NINGUNO', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8012
        NnajSexo::create(['id' => '8254', 'fi_datos_basico_id' => 9324, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8013
        NnajSexo::create(['id' => '8255', 'fi_datos_basico_id' => 9325, 's_nombre_identitario' => '', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8014
        NnajSexo::create(['id' => '8256', 'fi_datos_basico_id' => 9326, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8015
        NnajSexo::create(['id' => '8257', 'fi_datos_basico_id' => 9327, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8016
        NnajSexo::create(['id' => '8258', 'fi_datos_basico_id' => 9328, 's_nombre_identitario' => '', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8017
        NnajSexo::create(['id' => '8259', 'fi_datos_basico_id' => 9329, 's_nombre_identitario' => '', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8018
        NnajSexo::create(['id' => '8260', 'fi_datos_basico_id' => 9330, 's_nombre_identitario' => '', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 235, 'prm_orientacion_sexual_id' => 235, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8019
        NnajSexo::create(['id' => '8261', 'fi_datos_basico_id' => 9331, 's_nombre_identitario' => '', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8020
        NnajSexo::create(['id' => '8262', 'fi_datos_basico_id' => 9332, 's_nombre_identitario' => '', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8021
        NnajSexo::create(['id' => '8263', 'fi_datos_basico_id' => 9333, 's_nombre_identitario' => '', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8022
        NnajSexo::create(['id' => '8264', 'fi_datos_basico_id' => 9335, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8023
        NnajSexo::create(['id' => '8265', 'fi_datos_basico_id' => 9336, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 662, 'user_edita_id' => 662, 'sis_docfuen_id' => 2,]); // 8024
        NnajSexo::create(['id' => '8266', 'fi_datos_basico_id' => 9337, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8025
        NnajSexo::create(['id' => '8267', 'fi_datos_basico_id' => 9338, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8026
        NnajSexo::create(['id' => '8268', 'fi_datos_basico_id' => 9339, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8027
        NnajSexo::create(['id' => '8269', 'fi_datos_basico_id' => 9340, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8028
        NnajSexo::create(['id' => '8270', 'fi_datos_basico_id' => 9341, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8029
        NnajSexo::create(['id' => '8271', 'fi_datos_basico_id' => 9342, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8030
        NnajSexo::create(['id' => '8272', 'fi_datos_basico_id' => 9343, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8031
        NnajSexo::create(['id' => '8273', 'fi_datos_basico_id' => 9344, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8032
        NnajSexo::create(['id' => '8274', 'fi_datos_basico_id' => 9345, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 21, 'prm_identidad_genero_id' => 23, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8033
        NnajSexo::create(['id' => '8275', 'fi_datos_basico_id' => 9346, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 133, 'user_edita_id' => 133, 'sis_docfuen_id' => 2,]); // 8034
        NnajSexo::create(['id' => '8276', 'fi_datos_basico_id' => 9348, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 1632, 'user_edita_id' => 1632, 'sis_docfuen_id' => 2,]); // 8035
        NnajSexo::create(['id' => '8277', 'fi_datos_basico_id' => 9349, 's_nombre_identitario' => 'NO TIENE', 'prm_sexo_id' => 20, 'prm_identidad_genero_id' => 24, 'prm_orientacion_sexual_id' => 29, 'sis_esta_id' => 1, 'user_crea_id' => 1632, 'user_edita_id' => 1632, 'sis_docfuen_id' => 2,]); // 8036
    }
}
