<?php

use App\Models\Sistema\SisBarrio;
use Illuminate\Database\Seeder;

class SisBarriosSeeder extends Seeder
{
    public function getR($dataxxxx)
    {
        foreach ($dataxxxx as $key => $value) {
            SisBarrio::create(['sis_esta_id' => 1, 'user_crea_id' => 1, 'user_edita_id' => 1, 's_barrio' => strtoupper($value['nombrexx']) ]);
        }
    }
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataxxxx = [
            ['nombrexx' => 'CANAIMA'], // 1
            ['nombrexx' => 'LA FLORESTA DE LA SABANA'], // 2
            ['nombrexx' => 'TORCA'], // 3
            ['nombrexx' => 'ALTOS DE SERREZUELA'], // 4
            ['nombrexx' => 'BALCONES DE VISTA HERMOSA'], // 5
            ['nombrexx' => 'BALMORAL NORTE'], // 6
            ['nombrexx' => 'BUENAVISTA'], // 7
            ['nombrexx' => 'CHAPARRAL'], // 8
            ['nombrexx' => 'EL CODITO'], // 9
            ['nombrexx' => 'EL REFUGIO DE SAN ANTONIO'], // 10
            ['nombrexx' => 'EL VERBENAL'], // 11
            ['nombrexx' => 'HORIZONTES'], // 12
            ['nombrexx' => 'LA ESTRELLITA'], // 13
            ['nombrexx' => 'LA FRONTERA'], // 14
            ['nombrexx' => 'LA LLANURITA'], // 15
            ['nombrexx' => 'LOS CONSUELOS'], // 16
            ['nombrexx' => 'MARANTÁ'], // 17
            ['nombrexx' => 'MATURÍN'], // 18
            ['nombrexx' => 'MEDELLÍN'], // 19
            ['nombrexx' => 'MIRADOR DEL NORTE'], // 20
            ['nombrexx' => 'NUEVO HORIZONTE'], // 21
            ['nombrexx' => 'SAN ANTONIO NORTE'], // 22
            ['nombrexx' => 'SANTANDERSITO'], // 23
            ['nombrexx' => 'TIBABITA'], // 24
            ['nombrexx' => 'VIÑA DEL MAR'], // 25
            ['nombrexx' => 'BOSQUE DE SAN ANTONIO'], // 26
            ['nombrexx' => 'CONJUNTO CAMINO DEL PALMAR'], // 27
            ['nombrexx' => 'EL PITE'], // 28
            ['nombrexx' => 'EL REDIL'], // 29
            ['nombrexx' => 'LA CITA'], // 30
            ['nombrexx' => 'LA GRANJA NORTE'], // 31
            ['nombrexx' => 'LA URIBE'], // 32
            ['nombrexx' => 'LOS NARANJOS'], // 33
            ['nombrexx' => 'SAN JUAN BOSCO'], // 34
            ['nombrexx' => 'URBANIZACIÓN LOS LAURELES'], // 35
            ['nombrexx' => 'AINSUCA'], // 36
            ['nombrexx' => 'ALTABLANCA'], // 37
            ['nombrexx' => 'BARRANCAS'], // 38
            ['nombrexx' => 'CALIFORNIA'], // 39
            ['nombrexx' => 'CERRO NORTE'], // 40
            ['nombrexx' => 'DANUBIO'], // 41
            ['nombrexx' => 'DON BOSCO'], // 42
            ['nombrexx' => 'LA PERLA ORIENTAL'], // 43
            ['nombrexx' => 'LAS ARENERAS'], // 44
            ['nombrexx' => 'MILÁN (BARRANCAS)'], // 45
            ['nombrexx' => 'PRADERA NORTE'], // 46
            ['nombrexx' => 'SAN CRISTÓBAL NORTE'], // 47
            ['nombrexx' => 'SAN CRISTÓBAL NORTE PARTE ALTA'], // 48
            ['nombrexx' => 'SAN CRISTÓBAL NORTE PARTE BAJA'], // 49
            ['nombrexx' => 'SANTA TERESA'], // 50
            ['nombrexx' => 'SORATAMA'], // 51
            ['nombrexx' => 'TORCOROMA'], // 52
            ['nombrexx' => 'VILLA NYDIA'], // 53
            ['nombrexx' => 'VILLA OLIVA'], // 54
            ['nombrexx' => 'EL TOBERÍN'], // 55
            ['nombrexx' => 'BABILONIA'], // 56
            ['nombrexx' => 'DARANDELOS'], // 57
            ['nombrexx' => 'ESTRELLA DEL NORTE'], // 58
            ['nombrexx' => 'GUANOA'], // 59
            ['nombrexx' => 'JARDÍN NORTE'], // 60
            ['nombrexx' => 'LA LIBERIA'], // 61
            ['nombrexx' => 'LA PRADERA NORTE'], // 62
            ['nombrexx' => 'LAS ORQUÍDEAS'], // 63
            ['nombrexx' => 'PANTANITO'], // 64
            ['nombrexx' => 'SANTA MÓNICA'], // 65
            ['nombrexx' => 'VILLA MAGDALA'], // 66
            ['nombrexx' => 'VILLAS DE ARANJUEZ'], // 67
            ['nombrexx' => 'VILLAS DEL MEDITERRÁNEO'], // 68
            ['nombrexx' => 'ZARAGOZA'], // 69
            ['nombrexx' => 'ACACIAS'], // 70
            ['nombrexx' => 'ANTIGUA'], // 71
            ['nombrexx' => 'BELMIRA'], // 72
            ['nombrexx' => 'BOSQUE DE PINOS'], // 73
            ['nombrexx' => 'CAOBOS SALAZAR'], // 74
            ['nombrexx' => 'CAPRI'], // 75
            ['nombrexx' => 'CEDRITOS'], // 76
            ['nombrexx' => 'CEDRO BOLÍVAR'], // 77
            ['nombrexx' => 'CEDRO GOLF'], // 78
            ['nombrexx' => 'CEDRO MADEIRA'], // 79
            ['nombrexx' => 'CEDRO NARVÁEZ'], // 80
            ['nombrexx' => 'CEDRO SALAZAR'], // 81
            ['nombrexx' => 'EL CONTADOR'], // 82
            ['nombrexx' => 'EL RINCÓN DE LAS MARGARITAS'], // 83
            ['nombrexx' => 'LA SONORA'], // 84
            ['nombrexx' => 'LAS MARGARITAS'], // 85
            ['nombrexx' => 'LISBOA'], // 86
            ['nombrexx' => 'LOS CEDROS'], // 87
            ['nombrexx' => 'LOS CEDROS ORIENTAL'], // 88
            ['nombrexx' => 'MONTEARROYO'], // 89
            ['nombrexx' => 'NUEVA AUTOPISTA'], // 90
            ['nombrexx' => 'NUEVO COUNTRY'], // 91
            ['nombrexx' => 'SIERRAS DEL MORAL EL NOGAL'], // 92
            ['nombrexx' => 'BELLA SUIZA'], // 93
            ['nombrexx' => 'BELLAVISTA'], // 94
            ['nombrexx' => 'BOSQUE MEDINA'], // 95
            ['nombrexx' => 'EL PAÑUELITO'], // 96
            ['nombrexx' => 'EL PEDREGAL'], // 97
            ['nombrexx' => 'ESCUELA DE CABALLERÍA I'], // 98
            ['nombrexx' => 'ESCUELA DE INFANTERÍA'], // 99
            ['nombrexx' => 'FRANCISCO MIRANDA'], // 100
            ['nombrexx' => 'GINEBRA'], // 101
            ['nombrexx' => 'LA ESPERANZA'], // 102
            ['nombrexx' => 'LA GLORIETA'], // 103
            ['nombrexx' => 'LAS DELICIAS DEL CARMEN'], // 104
            ['nombrexx' => 'SAGRADO CORAZÓN'], // 105
            ['nombrexx' => 'SAN GABRIEL'], // 106
            ['nombrexx' => 'SANTA ANA'], // 107
            ['nombrexx' => 'SANTA ANA OCCIDENTAL'], // 108
            ['nombrexx' => 'SANTA BÁRBARA'], // 109
            ['nombrexx' => 'SANTA BÁRBARA ALTA'], // 110
            ['nombrexx' => 'SANTA BÁRBARA ORIENTAL'], // 111
            ['nombrexx' => 'UNICERROS'], // 112
            ['nombrexx' => 'USAQUÉN'], // 113
            ['nombrexx' => 'COUNTRY CLUB'], // 114
            ['nombrexx' => 'LA CALLEJA'], // 115
            ['nombrexx' => 'LA CAROLINA'], // 116
            ['nombrexx' => 'LA CRISTALINA'], // 117
            ['nombrexx' => 'PRADOS DEL COUNTRY'], // 118
            ['nombrexx' => 'RECODO DEL COUNTRY'], // 119
            ['nombrexx' => 'SANTA COLOMA'], // 120
            ['nombrexx' => 'SOATAMA'], // 121
            ['nombrexx' => 'TOLEDO'], // 122
            ['nombrexx' => 'TORRES DEL COUNTRY'], // 123
            ['nombrexx' => 'VERGEL DEL COUNTRY'], // 124
            ['nombrexx' => 'SANTA BÁRBARA OCCIDENTAL'], // 125
            ['nombrexx' => 'CAMPO ALEGRE'], // 126
            ['nombrexx' => 'MOLINOS DEL NORTE'], // 127
            ['nombrexx' => 'MULTICENTRO'], // 128
            ['nombrexx' => 'NAVARRA'], // 129
            ['nombrexx' => 'RINCÓN DEL CHICÓ'], // 130
            ['nombrexx' => 'SAN PATRICIO'], // 131
            ['nombrexx' => 'SANTA BÁRBARA CENTRAL'], // 132
            ['nombrexx' => 'SANTA BIBIANA'], // 133
            ['nombrexx' => 'SANTA PAULA'], // 134
            ['nombrexx' => 'CHICÓ RESERVADO'], // 135
            ['nombrexx' => 'CHICÓ ALTO'], // 136
            ['nombrexx' => 'EL NOGAL'], // 137
            ['nombrexx' => 'EL REFUGIO'], // 138
            ['nombrexx' => 'LA CABRERA'], // 139
            ['nombrexx' => 'LOS ROSALES'], // 140
            ['nombrexx' => 'SEMINARIO'], // 141
            ['nombrexx' => 'TOSCANA'], // 142
            ['nombrexx' => 'LA ESPERANZA NORORIENTAL'], // 143
            ['nombrexx' => 'LA SUREÑA'], // 144
            ['nombrexx' => 'SAN ISIDRO'], // 145
            ['nombrexx' => 'SAN LUIS ALTOS DEL CABO'], // 146
            ['nombrexx' => 'BOSQUE CALDERÓN'], // 147
            ['nombrexx' => 'BOSQUE CALDERÓN TEJADA'], // 148
            ['nombrexx' => 'CHAPINERO ALTO'], // 149
            ['nombrexx' => 'EL CASTILLO'], // 150
            ['nombrexx' => 'EL PARAÍSO'], // 151
            ['nombrexx' => 'EMAUS'], // 152
            ['nombrexx' => 'GRANADA'], // 153
            ['nombrexx' => 'INGEMAR'], // 154
            ['nombrexx' => 'JUAN XXIII'], // 155
            ['nombrexx' => 'LA SALLE'], // 156
            ['nombrexx' => 'LAS ACACIAS'], // 157
            ['nombrexx' => 'LOS OLIVOS'], // 158
            ['nombrexx' => 'MARÍA CRISTINA'], // 159
            ['nombrexx' => 'MARISCAL SUCRE'], // 160
            ['nombrexx' => 'NUEVA GRANADA'], // 161
            ['nombrexx' => 'PALOMAR'], // 162
            ['nombrexx' => 'PARDO RUBIO'], // 163
            ['nombrexx' => 'SAN MARTÍN DE PORRES'], // 164
            ['nombrexx' => 'VILLA ANITA'], // 165
            ['nombrexx' => 'VILLA DEL CERRO'], // 166
            ['nombrexx' => 'ANTIGUO COUNTRY'], // 167
            ['nombrexx' => 'CHICÓ NORTE'], // 168
            ['nombrexx' => 'CHICÓ NORTE II'], // 169
            ['nombrexx' => 'CHICÓ NORTE III'], // 170
            ['nombrexx' => 'CHICÓ OCCIDENTAL'], // 171
            ['nombrexx' => 'EL CHICÓ'], // 172
            ['nombrexx' => 'EL RETIRO'], // 173
            ['nombrexx' => 'ESPARTILLAL'], // 174
            ['nombrexx' => 'LAGO GAITÁN'], // 175
            ['nombrexx' => 'PORCIÚNCULA'], // 176
            ['nombrexx' => 'QUINTA CAMACHO'], // 177
            ['nombrexx' => 'CATALUÑA'], // 178
            ['nombrexx' => 'CHAPINERO CENTRAL'], // 179
            ['nombrexx' => 'CHAPINERO NORTE'], // 180
            ['nombrexx' => 'MARLY'], // 181
            ['nombrexx' => 'SUCRE'], // 182
            ['nombrexx' => 'LA MERCED'], // 183
            ['nombrexx' => 'PARQUE CENTRAL BAVARIA'], // 184
            ['nombrexx' => 'SAN DIEGO'], // 185
            ['nombrexx' => 'SAMPER'], // 186
            ['nombrexx' => 'SAN MARTÍN'], // 187
            ['nombrexx' => 'BOSQUE IZQUIERDO'], // 188
            ['nombrexx' => 'GERMANIA'], // 189
            ['nombrexx' => 'LA MACARENA'], // 190
            ['nombrexx' => 'LA PAZ CENTRO'], // 191
            ['nombrexx' => 'LA PERSEVERANCIA'], // 192
            ['nombrexx' => 'LA ALAMEDA'], // 193
            ['nombrexx' => 'LA CAPUCHINA'], // 194
            ['nombrexx' => 'VERACRUZ'], // 195
            ['nombrexx' => 'LAS NIEVES'], // 196
            ['nombrexx' => 'SAN VICTORINO'], // 197
            ['nombrexx' => 'SANTA INÉS'], // 198
            ['nombrexx' => 'LAS CRUCES'], // 199
            ['nombrexx' => 'SAN BERNARDO'], // 200
            ['nombrexx' => 'ATANASIO GIRARDOT'], // 201
            ['nombrexx' => 'CARTAGENA'], // 202
            ['nombrexx' => 'EL BALCÓN'], // 203
            ['nombrexx' => 'EL CONSUELO'], // 204
            ['nombrexx' => 'EL DORADO'], // 205
            ['nombrexx' => 'EL GUAVIO'], // 206
            ['nombrexx' => 'EL MIRADOR'], // 207
            ['nombrexx' => 'EL ROCÍO'], // 208
            ['nombrexx' => 'EL TRIUNFO'], // 209
            ['nombrexx' => 'FABRICA DE LOZA'], // 210
            ['nombrexx' => 'GRAN COLOMBIA'], // 211
            ['nombrexx' => 'LA PEÑA'], // 212
            ['nombrexx' => 'LOS LACHES'], // 213
            ['nombrexx' => 'LOURDES'], // 214
            ['nombrexx' => 'RAMÍREZ'], // 215
            ['nombrexx' => 'SAN DIONISIO'], // 216
            ['nombrexx' => 'SANTA ROSA DE LIMA'], // 217
            ['nombrexx' => 'VITELMA'], // 218
            ['nombrexx' => 'AGUAS CLARAS'], // 219
            ['nombrexx' => 'ALTOS DEL ZIPA'], // 220
            ['nombrexx' => 'AMAPOLAS'], // 221
            ['nombrexx' => 'AMAPOLAS II'], // 222
            ['nombrexx' => 'BALCÓN DE LA CASTAÑA'], // 223
            ['nombrexx' => 'BELLA VISTA SECTOR LUCERO'], // 224
            ['nombrexx' => 'BELLAVISTA PARTE BAJA'], // 225
            ['nombrexx' => 'BELLAVISTA SUR'], // 226
            ['nombrexx' => 'BOSQUE DE LOS ALPES'], // 227
            ['nombrexx' => 'BUENAVISTA SURORIENTAL'], // 228
            ['nombrexx' => 'CAMINO VIEJO SAN CRISTÓBAL'], // 229
            ['nombrexx' => 'CERROS DE SAN VICENTE'], // 230
            ['nombrexx' => 'CIUDAD DE LONDRES'], // 231
            ['nombrexx' => 'CORINTO'], // 232
            ['nombrexx' => 'EL BALCÓN DE LA CASTAÑA'], // 233
            ['nombrexx' => 'EL FUTURO'], // 234
            ['nombrexx' => 'EL RAMAJAL'], // 235
            ['nombrexx' => 'EL RAMAJAL (SAN PEDRO)'], // 236
            ['nombrexx' => 'GRAN COLOMBIA (MOLINOS DE ORIENTE)'], // 237
            ['nombrexx' => 'HORACIO ORJUELA'], // 238
            ['nombrexx' => 'LA CASTAÑA'], // 239
            ['nombrexx' => 'LA CECILIA'], // 240
            ['nombrexx' => 'LA GRAN COLOMBIA'], // 241
            ['nombrexx' => 'LA HERRADURA'], // 242
            ['nombrexx' => 'LA JOYITA CENTRO (BELLO HORIZONTE)'], // 243
            ['nombrexx' => 'LA PLAYA'], // 244
            ['nombrexx' => 'LA ROCA'], // 245
            ['nombrexx' => 'LA SAGRADA FAMILIA'], // 246
            ['nombrexx' => 'LAS COLUMNAS'], // 247
            ['nombrexx' => 'LAS MERCEDES'], // 248
            ['nombrexx' => 'LAURELES SUR ORIENTAL II SECTOR'], // 249
            ['nombrexx' => 'LOS ALPES'], // 250
            ['nombrexx' => 'LOS ALPES FUTURO'], // 251
            ['nombrexx' => 'LOS ARRAYANES SECTOR SANTA INÉS'], // 252
            ['nombrexx' => 'LOS LAURELES SUR ORIENTAL I SECTOR'], // 253
            ['nombrexx' => 'MACARENA LOS ALPES'], // 254
            ['nombrexx' => 'MANANTIAL'], // 255
            ['nombrexx' => 'MANILA'], // 256
            ['nombrexx' => 'MIRAFLORES'], // 257
            ['nombrexx' => 'MOLINOS DE ORIENTE'], // 258
            ['nombrexx' => 'MONTECARLO'], // 259
            ['nombrexx' => 'NUEVA ESPAÑA'], // 260
            ['nombrexx' => 'NUEVA ESPAÑA PARTE ALTA'], // 261
            ['nombrexx' => 'RAMAJAL'], // 262
            ['nombrexx' => 'RINCÓN DE LA VICTORIA-BELLAVISTA'], // 263
            ['nombrexx' => 'SAGRADA FAMILIA'], // 264
            ['nombrexx' => 'SAN BLAS'], // 265
            ['nombrexx' => 'SAN BLAS (PARCELAS)'], // 266
            ['nombrexx' => 'SAN BLAS II SECTOR'], // 267
            ['nombrexx' => 'SAN CRISTÓBAL ALTO'], // 268
            ['nombrexx' => 'SAN CRISTÓBAL VIEJO'], // 269
            ['nombrexx' => 'SAN PEDRO SUR ORIENTAL'], // 270
            ['nombrexx' => 'SAN VICENTE'], // 271
            ['nombrexx' => 'SAN VICENTE ALTO'], // 272
            ['nombrexx' => 'SAN VICENTE BAJO'], // 273
            ['nombrexx' => 'SAN VICENTE SUR ORIENTAL'], // 274
            ['nombrexx' => 'SANTA INÉS SUR'], // 275
            ['nombrexx' => 'TERRAZAS DE ORIENTE'], // 276
            ['nombrexx' => 'TRIÁNGULO'], // 277
            ['nombrexx' => 'TRIÁNGULO ALTO'], // 278
            ['nombrexx' => 'TRIÁNGULO BAJO'], // 279
            ['nombrexx' => 'VEREDA ALTOS DE SAN BLAS'], // 280
            ['nombrexx' => 'GOLCONDA'], // 281
            ['nombrexx' => 'PRIMERO DE MAYO'], // 282
            ['nombrexx' => 'BUENOS AIRES'], // 283
            ['nombrexx' => 'CALVO SUR'], // 284
            ['nombrexx' => 'LA MARÍA'], // 285
            ['nombrexx' => 'LAS BRISAS'], // 286
            ['nombrexx' => 'LOS DOS LEONES'], // 287
            ['nombrexx' => 'MODELO SUR'], // 288
            ['nombrexx' => 'NARIÑO SUR'], // 289
            ['nombrexx' => 'QUINTA RAMOS'], // 290
            ['nombrexx' => 'REPÚBLICA DE VENEZUELA'], // 291
            ['nombrexx' => 'SAN CRISTÓBAL SUR'], // 292
            ['nombrexx' => 'SAN JAVIER'], // 293
            ['nombrexx' => 'SANTA ANA SUR'], // 294
            ['nombrexx' => 'SOSIEGO'], // 295
            ['nombrexx' => 'VELÓDROMO'], // 296
            ['nombrexx' => 'VILLA ALBANIA'], // 297
            ['nombrexx' => 'VILLA JAVIER'], // 298
            ['nombrexx' => 'ATENAS'], // 299
            ['nombrexx' => '20 DE JULIO'], // 300
            ['nombrexx' => 'ATENAS I'], // 301
            ['nombrexx' => 'AYACUCHO'], // 302
            ['nombrexx' => 'BARCELONA'], // 303
            ['nombrexx' => 'BARCELONA SUR'], // 304
            ['nombrexx' => 'BARCELONA SUR ORIENTAL'], // 305
            ['nombrexx' => 'BELLO HORIZONTE'], // 306
            ['nombrexx' => 'BELLO HORIZONTE III SECTOR'], // 307
            ['nombrexx' => 'CÓRDOBA'], // 308
            ['nombrexx' => 'EL ÁNGULO'], // 309
            ['nombrexx' => 'EL ENCANTO'], // 310
            ['nombrexx' => 'GRANADA SUR'], // 311
            ['nombrexx' => 'GRANADA SUR III SECTOR'], // 312
            ['nombrexx' => 'LA JOYITA'], // 313
            ['nombrexx' => 'LA SERAFINA'], // 314
            ['nombrexx' => 'MANAGUA'], // 315
            ['nombrexx' => 'MONTEBELLO'], // 316
            ['nombrexx' => 'SAN ISIDRO I Y II'], // 317
            ['nombrexx' => 'SAN ISIDRO SUR'], // 318
            ['nombrexx' => 'SAN LUIS'], // 319
            ['nombrexx' => 'SUR AMÉRICA'], // 320
            ['nombrexx' => 'VILLA DE LOS ALPES'], // 321
            ['nombrexx' => 'VILLA DE LOS ALPES I'], // 322
            ['nombrexx' => 'VILLA NATALY'], // 323
            ['nombrexx' => 'ALTAMIRA'], // 324
            ['nombrexx' => 'ALTAMIRA CHIQUITA'], // 325
            ['nombrexx' => 'ALTOS DEL POBLADO'], // 326
            ['nombrexx' => 'ALTOS DEL VIRREY'], // 327
            ['nombrexx' => 'ALTOS DEL ZUQUE'], // 328
            ['nombrexx' => 'BELLAVISTA PARTE ALTA'], // 329
            ['nombrexx' => 'EL PILAR'], // 330
            ['nombrexx' => 'BELLAVISTA SUR ORIENTAL'], // 331
            ['nombrexx' => 'CIUDADELA SANTA ROSA'], // 332
            ['nombrexx' => 'EL QUINDÍO'], // 333
            ['nombrexx' => 'EL RECODO-REPÚBLICA DE CANADÁ'], // 334
            ['nombrexx' => 'EL RODEO'], // 335
            ['nombrexx' => 'LA COLMENA'], // 336
            ['nombrexx' => 'LA GLORIA'], // 337
            ['nombrexx' => 'LA GLORIA BAJA'], // 338
            ['nombrexx' => 'LA GLORIA MZ 11'], // 339
            ['nombrexx' => 'LA GLORIA OCCIDENTAL'], // 340
            ['nombrexx' => 'LA GLORIA ORIENTAL'], // 341
            ['nombrexx' => 'LA GLORIA SAN MIGUEL'], // 342
            ['nombrexx' => 'LA GROVANA'], // 343
            ['nombrexx' => 'LA VICTORIA'], // 344
            ['nombrexx' => 'LA VICTORIA II SECTOR'], // 345
            ['nombrexx' => 'LA VICTORIA III SECTOR'], // 346
            ['nombrexx' => 'LA YE'], // 347
            ['nombrexx' => 'LAS GAVIOTAS'], // 348
            ['nombrexx' => 'LAS GUACAMAYAS'], // 349
            ['nombrexx' => 'LAS GUACAMAYAS I'], // 350
            ['nombrexx' => 'II Y III'], // 351
            ['nombrexx' => 'MALVINAS'], // 352
            ['nombrexx' => 'MORALBA'], // 353
            ['nombrexx' => 'PANORAMA'], // 354
            ['nombrexx' => 'PASEITO III'], // 355
            ['nombrexx' => 'PUENTE COLORADO'], // 356
            ['nombrexx' => 'QUINDÍO'], // 357
            ['nombrexx' => 'QUINDÍO I Y II'], // 358
            ['nombrexx' => 'SAN JOSÉ'], // 359
            ['nombrexx' => 'SAN JOSÉ ORIENTAL'], // 360
            ['nombrexx' => 'SAN JOSÉ SUR ORIENTAL'], // 361
            ['nombrexx' => 'SAN MARTÍN DE LOBA I Y II'], // 362
            ['nombrexx' => 'SAN MARTÍN SUR'], // 363
            ['nombrexx' => 'SAN MIGUEL'], // 364
            ['nombrexx' => 'ANTIOQUIA'], // 365
            ['nombrexx' => 'CANADÁ LA GUIRÁ'], // 366
            ['nombrexx' => 'CANADÁ LA GUIRÁ II SECTOR'], // 367
            ['nombrexx' => 'CANADÁ-SAN LUIS'], // 368
            ['nombrexx' => 'CHIGUAZA'], // 369
            ['nombrexx' => 'EL PINAR (REPÚBLICA DEL CANADÁ II)'], // 370
            ['nombrexx' => 'JUAN REY (LA PAZ)'], // 371
            ['nombrexx' => 'LA BELLEZA'], // 372
            ['nombrexx' => 'LA NUEVA GLORIA'], // 373
            ['nombrexx' => 'LA NUEVA GLORIA II SECTOR'], // 374
            ['nombrexx' => 'LA PENÍNSULA'], // 375
            ['nombrexx' => 'LA SIERRA'], // 376
            ['nombrexx' => 'LOS LIBERTADORES'], // 377
            ['nombrexx' => 'LOS LIBERTADORES SECTOR EL TESORO'], // 378
            ['nombrexx' => 'LOS LIBERTADORES SECTOR LA COLINA'], // 379
            ['nombrexx' => 'LOS LIBERTADORES SECTOR SAN IGNACIO'], // 380
            ['nombrexx' => 'LOS LIBERTADORES SECTOR SAN ISIDRO'], // 381
            ['nombrexx' => 'LOS LIBERTADORES SECTOR SAN JOSÉ'], // 382
            ['nombrexx' => 'LOS LIBERTADORES SECTOR SAN LUIS'], // 383
            ['nombrexx' => 'LOS LIBERTADORES SECTOR SAN MIGUEL'], // 384
            ['nombrexx' => 'LOS LIBERTADORES BOSQUE DIAMANTE TRIÁNGULO'], // 385
            ['nombrexx' => 'LOS PINARES'], // 386
            ['nombrexx' => 'LOS PINOS'], // 387
            ['nombrexx' => 'LOS PUENTES'], // 388
            ['nombrexx' => 'NUEVA DELHI'], // 389
            ['nombrexx' => 'NUEVA GLORIA'], // 390
            ['nombrexx' => 'NUEVA ROMA'], // 391
            ['nombrexx' => 'NUEVAS MALVINAS (EL TRIUNFO)'], // 392
            ['nombrexx' => 'REPÚBLICA DEL CANADÁ'], // 393
            ['nombrexx' => 'REPÚBLICA DEL CANADÁ-EL PINAR'], // 394
            ['nombrexx' => 'SAN JACINTO'], // 395
            ['nombrexx' => 'SAN MANUEL'], // 396
            ['nombrexx' => 'SAN RAFAEL SUR ORIENTAL'], // 397
            ['nombrexx' => 'SAN RAFAEL USME'], // 398
            ['nombrexx' => 'SANTA RITA I'], // 399
            ['nombrexx' => 'SANTA RITA SUR ORIENTAL'], // 400
            ['nombrexx' => 'VALPARAÍSO'], // 401
            ['nombrexx' => 'VILLA ANGÉLICA-CANADÁ-LA GUIRÁ'], // 402
            ['nombrexx' => 'VILLA AURORA'], // 403
            ['nombrexx' => 'VILLABELL'], // 404
            ['nombrexx' => 'YOMASA'], // 405
            ['nombrexx' => 'VILLA ANGÉLICA'], // 406
            ['nombrexx' => 'EL PARAÍSO SUR ORIENTAL I SECTOR'], // 407
            ['nombrexx' => 'JUAN REY I Y II'], // 408
            ['nombrexx' => 'VILLA BEGONIA'], // 409
            ['nombrexx' => 'COSTA RICA'], // 410
            ['nombrexx' => 'DOÑA LILIANA'], // 411
            ['nombrexx' => 'EL BOSQUE KM. 11'], // 412
            ['nombrexx' => 'JUAN JOSÉ RONDÓN'], // 413
            ['nombrexx' => 'JUAN JOSÉ RONDÓN II SECTOR'], // 414
            ['nombrexx' => 'LA CABAÑA'], // 415
            ['nombrexx' => 'LA FLORA-PARCELACIÓN SAN PEDRO'], // 416
            ['nombrexx' => 'LAS VIOLETAS'], // 417
            ['nombrexx' => 'LOS ARRAYANES'], // 418
            ['nombrexx' => 'LOS SOCHES'], // 419
            ['nombrexx' => 'TIHUAQUE'], // 420
            ['nombrexx' => 'UNIÓN'], // 421
            ['nombrexx' => 'VILLA DIANA'], // 422
            ['nombrexx' => 'VILLA ROSITA'], // 423
            ['nombrexx' => 'ALASKA'], // 424
            ['nombrexx' => 'ARRAYANES'], // 425
            ['nombrexx' => 'DANUBIO AZUL'], // 426
            ['nombrexx' => 'DAZA SECTOR II'], // 427
            ['nombrexx' => 'DUITAMA'], // 428
            ['nombrexx' => 'EL PORVENIR'], // 429
            ['nombrexx' => 'EL PORVENIR II SECTOR'], // 430
            ['nombrexx' => 'FISCALA II LA FORTUNA'], // 431
            ['nombrexx' => 'FISCALA SECTOR CENTRO'], // 432
            ['nombrexx' => 'LA FISCALA-LOS TRES LAURELES'], // 433
            ['nombrexx' => 'LA FISCALA-LOTE 16'], // 434
            ['nombrexx' => 'LA FISCALA-LOTE 16A'], // 435
            ['nombrexx' => 'LA FISCALA SECTOR DAZA'], // 436
            ['nombrexx' => 'LA FISCALA SECTOR NORTE'], // 437
            ['nombrexx' => 'LA FISCALA SECTOR RODRÍGUEZ'], // 438
            ['nombrexx' => 'LA MORENA I'], // 439
            ['nombrexx' => 'LA MORENA II'], // 440
            ['nombrexx' => 'LA MORENA II (SECTOR VILLA SANDRA)'], // 441
            ['nombrexx' => 'NUEVA ESPERANZA'], // 442
            ['nombrexx' => 'VILLA NEIZA'], // 443
            ['nombrexx' => 'PICOTA SUR'], // 444
            ['nombrexx' => 'PORVENIR'], // 445
            ['nombrexx' => 'ALMIRANTE PADILLA'], // 446
            ['nombrexx' => 'ALTOS DEL PINO'], // 447
            ['nombrexx' => 'ARIZONA'], // 448
            ['nombrexx' => 'BARRANQUILLITA'], // 449
            ['nombrexx' => 'BENJAMIN URIBE'], // 450
            ['nombrexx' => 'BETANIA'], // 451
            ['nombrexx' => 'BETANIA II'], // 452
            ['nombrexx' => 'BOLONIA'], // 453
            ['nombrexx' => 'BULEVAR DEL SUR'], // 454
            ['nombrexx' => 'CASA LOMA II'], // 455
            ['nombrexx' => 'CASA REY'], // 456
            ['nombrexx' => 'CASALOMA'], // 457
            ['nombrexx' => 'COMPOSTELA I'], // 458
            ['nombrexx' => 'COMPOSTELA II'], // 459
            ['nombrexx' => 'COMPOSTELA III'], // 460
            ['nombrexx' => 'EL BOSQUE'], // 461
            ['nombrexx' => 'EL CORTIJO'], // 462
            ['nombrexx' => 'EL CURUBO'], // 463
            ['nombrexx' => 'EL JORDÁN'], // 464
            ['nombrexx' => 'EL NEVADO'], // 465
            ['nombrexx' => 'EL RECUERDO SUR'], // 466
            ['nombrexx' => 'EL REFUGIO SECTOR SANTA LIBRADA'], // 467
            ['nombrexx' => 'EL ROSAL-MIRADOR'], // 468
            ['nombrexx' => 'EL RUBÍ II SECTOR'], // 469
            ['nombrexx' => 'GRAN YOMASA I'], // 470
            ['nombrexx' => 'GRAN YOMASA II'], // 471
            ['nombrexx' => 'LA ANDREA'], // 472
            ['nombrexx' => 'LA AURORA'], // 473
            ['nombrexx' => 'LA FORTALEZA'], // 474
            ['nombrexx' => 'LA REGADERA KM. 11'], // 475
            ['nombrexx' => 'LA REGADERA SUR'], // 476
            ['nombrexx' => 'LAS GRANJAS DE SAN PEDRO (SANTA LIBRADA)'], // 477
            ['nombrexx' => 'LAS VIVIENDAS'], // 478
            ['nombrexx' => 'LOS TEJARES SUR II SECTOR'], // 479
            ['nombrexx' => 'NUEVO SAN ANDRÉS DE LOS ALTOS'], // 480
            ['nombrexx' => 'OLIVARES'], // 481
            ['nombrexx' => 'SALAZAR SALAZAR'], // 482
            ['nombrexx' => 'SAN ANDRÉS ALTO'], // 483
            ['nombrexx' => 'SAN FELIPE'], // 484
            ['nombrexx' => 'SAN JUAN BAUTISTA'], // 485
            ['nombrexx' => 'SAN JUAN I'], // 486
            ['nombrexx' => 'SAN JUAN II'], // 487
            ['nombrexx' => 'SAN JUAN II Y III'], // 488
            ['nombrexx' => 'SAN PABLO'], // 489
            ['nombrexx' => 'SANTA LIBRADA'], // 490
            ['nombrexx' => 'SANTA LIBRADA-LA ESPERANZA'], // 491
            ['nombrexx' => 'SANTA LIBRADA-LA SUREÑA'], // 492
            ['nombrexx' => 'SANTA LIBRADA-LOS TEJARES (GRAN YOMASA)'], // 493
            ['nombrexx' => 'SANTA LIBRADA NORTE'], // 494
            ['nombrexx' => 'SANTA LIBRADA-SAN BERNARDINO'], // 495
            ['nombrexx' => 'SANTA LIBRADA-SAN FRANCISCO'], // 496
            ['nombrexx' => 'SANTA LIBRADA-SALAZAR SALAZAR'], // 497
            ['nombrexx' => 'SANTA LIBRADA SECTOR LA PEÑA'], // 498
            ['nombrexx' => 'SANTA MARTA II'], // 499
            ['nombrexx' => 'SANTA MARTHA'], // 500
            ['nombrexx' => 'SIERRA MORENA'], // 501
            ['nombrexx' => 'TENERIFE II SECTOR'], // 502
            ['nombrexx' => 'URBANIZACIÓN COSTA RICA-SAN ANDRÉS DE LOS ALTOS'], // 503
            ['nombrexx' => 'URBANIZACIÓN BRASILIA II SECTOR'], // 504
            ['nombrexx' => 'URBANIZACIÓN BRASILIA SUR'], // 505
            ['nombrexx' => 'URBANIZACIÓN CARTAGENA'], // 506
            ['nombrexx' => 'URBANIZACIÓN LA ANDREA'], // 507
            ['nombrexx' => 'URBANIZACIÓN LA AURORA II'], // 508
            ['nombrexx' => 'URBANIZACIÓN MIRAVALLE'], // 509
            ['nombrexx' => 'URBANIZACIÓN TEQUENDAMA'], // 510
            ['nombrexx' => 'VALLES DE CAFAM'], // 511
            ['nombrexx' => 'VIANEY'], // 512
            ['nombrexx' => 'VILLA ALEJANDRÍA'], // 513
            ['nombrexx' => 'VILLA NELLY'], // 514
            ['nombrexx' => 'VILLAS DE SANTA ISABEL (PARQUE ENTRENUBES)'], // 515
            ['nombrexx' => 'VILLAS DEL EDÉN'], // 516
            ['nombrexx' => 'YOMASITA'], // 517
            ['nombrexx' => 'ALFONSO LÓPEZ SECTOR CHARALÁ'], // 518
            ['nombrexx' => 'ANTONIO JOSÉ DE SUCRE I'], // 519
            ['nombrexx' => 'BELLAVISTA ALTA'], // 520
            ['nombrexx' => 'BELLAVISTA II SECTOR'], // 521
            ['nombrexx' => 'BOSQUE EL LIMONAR'], // 522
            ['nombrexx' => 'BOSQUE EL LIMONAR II SECTOR'], // 523
            ['nombrexx' => 'BRAZUELOS'], // 524
            ['nombrexx' => 'BRAZUELOS OCCIDENTAL'], // 525
            ['nombrexx' => 'BRAZUELOS-EL PARAÍSO'], // 526
            ['nombrexx' => 'BRAZUELOS-LA ESMERALDA'], // 527
            ['nombrexx' => 'CENTRO EDUCATIVO SAN JOSÉ'], // 528
            ['nombrexx' => 'CHAPINERITO'], // 529
            ['nombrexx' => 'CHICÓ SUR'], // 530
            ['nombrexx' => 'CHICÓ SUR II'], // 531
            ['nombrexx' => 'CIUDADELA CANTARRANA I'], // 532
            ['nombrexx' => 'II Y III SECTOR'], // 533
            ['nombrexx' => 'COMUNEROS'], // 534
            ['nombrexx' => 'EL BRILLANTE'], // 535
            ['nombrexx' => 'EL ESPINO'], // 536
            ['nombrexx' => 'EL MORTIÑO'], // 537
            ['nombrexx' => 'EL RUBÍ'], // 538
            ['nombrexx' => 'EL TUNO'], // 539
            ['nombrexx' => 'EL UVAL'], // 540
            ['nombrexx' => 'EL VIRREY ÊLTIMA ETAPA'], // 541
            ['nombrexx' => 'FINCA LA ESPERANZA'], // 542
            ['nombrexx' => 'LA ESMERALDA-EL RECUERDO'], // 543
            ['nombrexx' => 'LA ESPERANZA KM. 10'], // 544
            ['nombrexx' => 'LAS FLORES'], // 545
            ['nombrexx' => 'LORENZO ALCANTUZ I'], // 546
            ['nombrexx' => 'LORENZO ALCANTUZ II'], // 547
            ['nombrexx' => 'LOS ALTOS DEL BRAZUELO'], // 548
            ['nombrexx' => 'MARICHUELA III'], // 549
            ['nombrexx' => 'MONTEBLANCO'], // 550
            ['nombrexx' => 'MONTEVÍDEO'], // 551
            ['nombrexx' => 'NUEVO SAN LUIS'], // 552
            ['nombrexx' => 'SAN JOAQUÍN-EL UVAL'], // 553
            ['nombrexx' => 'SECTOR GRANJAS DE SAN PEDRO'], // 554
            ['nombrexx' => 'TENERIFE'], // 555
            ['nombrexx' => 'URBANIZACIÓN CHUNIZA I'], // 556
            ['nombrexx' => 'URBANIZACIÓN JARÓN MONTE RUBIO'], // 557
            ['nombrexx' => 'URBANIZACIÓN LÍBANO'], // 558
            ['nombrexx' => 'URBANIZACIÓN MARICHUELA'], // 559
            ['nombrexx' => 'USMINIA'], // 560
            ['nombrexx' => 'VILLA ALEMANIA'], // 561
            ['nombrexx' => 'VILLA ALEMANIA II SECTOR'], // 562
            ['nombrexx' => 'VILLA ANITA SUR'], // 563
            ['nombrexx' => 'VILLA ISRAEL'], // 564
            ['nombrexx' => 'VILLA ISRAEL II'], // 565
            ['nombrexx' => 'ALFONSO LÓPEZ SECTOR BUENOS AIRES'], // 566
            ['nombrexx' => 'ALFONSO LÓPEZ SECTOR EL PROGRESO'], // 567
            ['nombrexx' => 'BRISAS DEL LLANO'], // 568
            ['nombrexx' => 'EL NUEVO PORTAL'], // 569
            ['nombrexx' => 'EL PORTAL II ETAPA'], // 570
            ['nombrexx' => 'EL PROGRESO USME'], // 571
            ['nombrexx' => 'EL REFUGIO I Y II'], // 572
            ['nombrexx' => 'EL TRIÁNGULO'], // 573
            ['nombrexx' => 'EL UVAL II SECTOR'], // 574
            ['nombrexx' => 'LA HUERTA'], // 575
            ['nombrexx' => 'LA ORQUÍDEA USME'], // 576
            ['nombrexx' => 'LA REFORMA'], // 577
            ['nombrexx' => 'NUEVO PORVENIR'], // 578
            ['nombrexx' => 'NUEVO PROGRESO-EL PROGRESO II SECTOR'], // 579
            ['nombrexx' => 'PORTAL DE LA VEGA'], // 580
            ['nombrexx' => 'PORTAL DE ORIENTE'], // 581
            ['nombrexx' => 'PORTAL DEL DIVINO'], // 582
            ['nombrexx' => 'PUERTA AL LLANO'], // 583
            ['nombrexx' => 'PUERTA AL LLANO II'], // 584
            ['nombrexx' => 'REFUGIO I'], // 585
            ['nombrexx' => 'VILLA HERMOSA'], // 586
            ['nombrexx' => 'EL BOSQUE CENTRAL'], // 587
            ['nombrexx' => 'EL NUEVO PORTAL II'], // 588
            ['nombrexx' => 'EL REFUGIO I'], // 589
            ['nombrexx' => 'LA ESPERANZA SUR'], // 590
            ['nombrexx' => 'LOS OLIVARES'], // 591
            ['nombrexx' => 'PEPINITOS'], // 592
            ['nombrexx' => 'TOCAIMITA ORIENTAL'], // 593
            ['nombrexx' => 'TOCAIMITA SUR'], // 594
            ['nombrexx' => 'CIUDADELA EL OASIS'], // 595
            ['nombrexx' => 'USME-CENTRO'], // 596
            ['nombrexx' => 'EL PEDREGAL-LA LIRA'], // 597
            ['nombrexx' => 'EL SALTEADOR'], // 598
            ['nombrexx' => 'FÁTIMA'], // 599
            ['nombrexx' => 'ISLA DEL SOL'], // 600
            ['nombrexx' => 'LAGUNETA'], // 601
            ['nombrexx' => 'NUEVO MUZÚ'], // 602
            ['nombrexx' => 'RINCÓN DE MUZÚ'], // 603
            ['nombrexx' => 'RINCÓN DE VENECIA'], // 604
            ['nombrexx' => 'SAMORE'], // 605
            ['nombrexx' => 'SAN VICENTE FERRER'], // 606
            ['nombrexx' => 'TEJAR DE ONTARIO'], // 607
            ['nombrexx' => 'VENECIA'], // 608
            ['nombrexx' => 'CIUDAD TUNAL'], // 609
            ['nombrexx' => 'ABRAHAM LINCOLN'], // 610
            ['nombrexx' => 'SAN BENITO'], // 611
            ['nombrexx' => 'SAN CARLOS'], // 612
            ['nombrexx' => 'TUNJUELITO'], // 613
            ['nombrexx' => 'JARDINES DEL APOGEO'], // 614
            ['nombrexx' => 'EL MOTORISTA'], // 615
            ['nombrexx' => 'INDUSTRIAL'], // 616
            ['nombrexx' => 'LA ILUSIÓN'], // 617
            ['nombrexx' => 'NUEVO CHILE'], // 618
            ['nombrexx' => 'OLARTE'], // 619
            ['nombrexx' => 'VILLA DEL RÍO'], // 620
            ['nombrexx' => 'AMARU'], // 621
            ['nombrexx' => 'BERLÍN'], // 622
            ['nombrexx' => 'BERLÍN DE BOSA LA LIBERTAD III'], // 623
            ['nombrexx' => 'BOSA NOVA'], // 624
            ['nombrexx' => 'BOSA NOVA II SECTOR'], // 625
            ['nombrexx' => 'BOSALINDA (HOLDEBRANDO OLARTE)'], // 626
            ['nombrexx' => 'BRASIL'], // 627
            ['nombrexx' => 'BRASILIA'], // 628
            ['nombrexx' => 'CAMPO HERMOSO'], // 629
            ['nombrexx' => 'CASA NUEVA'], // 630
            ['nombrexx' => 'CHICALA'], // 631
            ['nombrexx' => 'CIUDADELA LA LIBERTAD'], // 632
            ['nombrexx' => 'EL BOSQUE DE BOSA'], // 633
            ['nombrexx' => 'EL CAUCE'], // 634
            ['nombrexx' => 'EL DIAMANTE'], // 635
            ['nombrexx' => 'EL LIBERTADOR'], // 636
            ['nombrexx' => 'EL PARADERO'], // 637
            ['nombrexx' => 'EL PORTAL DE LA LIBERTAD'], // 638
            ['nombrexx' => 'EL PROGRESO'], // 639
            ['nombrexx' => 'EL RECUERDO'], // 640
            ['nombrexx' => 'EL RINCÓN DE BOSA'], // 641
            ['nombrexx' => 'EL SAUCE'], // 642
            ['nombrexx' => 'ESCOCIA'], // 643
            ['nombrexx' => 'HOLANDA'], // 644
            ['nombrexx' => 'HORTELANOS DE ESCOCIA'], // 645
            ['nombrexx' => 'JORGE URIBE BOTERO'], // 646
            ['nombrexx' => 'LA CONCEPCIÓN'], // 647
            ['nombrexx' => 'LA DULCINEA'], // 648
            ['nombrexx' => 'LA ESMERALDA'], // 649
            ['nombrexx' => 'LA ESTANZUELA I Y II'], // 650
            ['nombrexx' => 'LA FLORIDA'], // 651
            ['nombrexx' => 'LA FONTANA DE BOSA-LA LIBERTAD'], // 652
            ['nombrexx' => 'LA INDEPENDENCIA'], // 653
            ['nombrexx' => 'LA LIBERTAD I'], // 654
            ['nombrexx' => 'II'], // 655
            ['nombrexx' => 'III'], // 656
            ['nombrexx' => 'IV'], // 657
            ['nombrexx' => 'LA MAGNOLIA'], // 658
            ['nombrexx' => 'LA PALMA'], // 659
            ['nombrexx' => 'LA PAZ'], // 660
            ['nombrexx' => 'LA PORTADA'], // 661
            ['nombrexx' => 'LA PORTADITA'], // 662
            ['nombrexx' => 'LA VEGUITA'], // 663
            ['nombrexx' => 'LAS VEGAS'], // 664
            ['nombrexx' => 'LOS OCALES'], // 665
            ['nombrexx' => 'LOS SAUCES'], // 666
            ['nombrexx' => 'MIAMI'], // 667
            ['nombrexx' => 'NEW JERSEY'], // 668
            ['nombrexx' => 'NUESTRA SEÑORA DE LA PAZ'], // 669
            ['nombrexx' => 'NUEVA ESCOCIA'], // 670
            ['nombrexx' => 'POTRERITOS'], // 671
            ['nombrexx' => 'SAN ANTONIO'], // 672
            ['nombrexx' => 'SAN ANTONIO DE BOSA'], // 673
            ['nombrexx' => 'SAN ANTONIO DE ESCOCIA'], // 674
            ['nombrexx' => 'SAN BERNARDINO'], // 675
            ['nombrexx' => 'SAN JORGE'], // 676
            ['nombrexx' => 'SAN JUANITO'], // 677
            ['nombrexx' => 'SAN PEDRO'], // 678
            ['nombrexx' => 'SAUCES'], // 679
            ['nombrexx' => 'SIRACUZA'], // 680
            ['nombrexx' => 'TOKIO'], // 681
            ['nombrexx' => 'VEGAS DE SANTANA'], // 682
            ['nombrexx' => 'VILLA CAROLINA'], // 683
            ['nombrexx' => 'VILLA CLEMENCIA'], // 684
            ['nombrexx' => 'VILLA COLOMBIA'], // 685
            ['nombrexx' => 'VILLA DE LOS COMUNEROS'], // 686
            ['nombrexx' => 'VILLA DE SUAITA'], // 687
            ['nombrexx' => 'VILLA MAGNOLIA'], // 688
            ['nombrexx' => 'VILLA NATALIA'], // 689
            ['nombrexx' => 'VILLA NOHORA'], // 690
            ['nombrexx' => 'VILLA SONIA I Y II'], // 691
            ['nombrexx' => 'VILLAS DEL PROGRESO'], // 692
            ['nombrexx' => 'VILLAS DEL VELERO'], // 693
            ['nombrexx' => 'CAMPO VERDE'], // 694
            ['nombrexx' => 'ANDALUCÍA I Y II'], // 695
            ['nombrexx' => 'ANTONIA SANTOS'], // 696
            ['nombrexx' => 'ARGELIA'], // 697
            ['nombrexx' => 'BOSA'], // 698
            ['nombrexx' => 'BOSQUES DE MERYLAND'], // 699
            ['nombrexx' => 'BRASILIA-LA ESTACIÓN'], // 700
            ['nombrexx' => 'CARLOS ALBÁN'], // 701
            ['nombrexx' => 'CHARLES DE GAULLE'], // 702
            ['nombrexx' => 'CLARETIANO'], // 703
            ['nombrexx' => 'EL JARDÍN'], // 704
            ['nombrexx' => 'EL LLANO'], // 705
            ['nombrexx' => 'EL PALMAR'], // 706
            ['nombrexx' => 'EL PORTAL DE BOSA'], // 707
            ['nombrexx' => 'EL POVENIR'], // 708
            ['nombrexx' => 'EL RETAZO'], // 709
            ['nombrexx' => 'EL TOCHE'], // 710
            ['nombrexx' => 'GETSEMANÍ'], // 711
            ['nombrexx' => 'GRANCOLOMBIANO I Y II'], // 712
            ['nombrexx' => 'GUALOCHE'], // 713
            ['nombrexx' => 'HERMANOS BARRAGÁN'], // 714
            ['nombrexx' => 'HUMBERTO VALENCIA'], // 715
            ['nombrexx' => 'ISLANDIA'], // 716
            ['nombrexx' => 'ISRAELITA'], // 717
            ['nombrexx' => 'JIMÉNEZ DE QUESADA'], // 718
            ['nombrexx' => 'JOSÉ ANTONIO GALÁN'], // 719
            ['nombrexx' => 'JOSÉ MARÍA CARBONEL'], // 720
            ['nombrexx' => 'LA AMISTAD'], // 721
            ['nombrexx' => 'LA AZUCENA'], // 722
            ['nombrexx' => 'LA ESTACIÓN'], // 723
            ['nombrexx' => 'LA RIVIERA'], // 724
            ['nombrexx' => 'LAURELES'], // 725
            ['nombrexx' => 'LLANO ORIENTAL'], // 726
            ['nombrexx' => 'LLANOS DE BOSA'], // 727
            ['nombrexx' => 'MANZANARES'], // 728
            ['nombrexx' => 'MITRANI'], // 729
            ['nombrexx' => 'NARANJOS'], // 730
            ['nombrexx' => 'BOSA PALESTINA'], // 731
            ['nombrexx' => 'PASO ANCHO'], // 732
            ['nombrexx' => 'PIAMONTE'], // 733
            ['nombrexx' => 'PRIMAVERA SUR'], // 734
            ['nombrexx' => 'SAN EUGENIO'], // 735
            ['nombrexx' => 'SAN PABLO I SECTOR Y SAN PABLO II SECTOR'], // 736
            ['nombrexx' => 'SANTA LUCÍA'], // 737
            ['nombrexx' => 'URBANIZACIÓN ACUARELA'], // 738
            ['nombrexx' => 'VEREDA SAN JOSÉ'], // 739
            ['nombrexx' => 'VILLA ANNY'], // 740
            ['nombrexx' => 'VILLA BOSA'], // 741
            ['nombrexx' => 'XOCHIMILCO'], // 742
            ['nombrexx' => 'CALDAS'], // 743
            ['nombrexx' => 'ANTONIO NARIÑO'], // 744
            ['nombrexx' => 'CAÑAVERALEJO'], // 745
            ['nombrexx' => 'EL ANHELO'], // 746
            ['nombrexx' => 'EL CORZO'], // 747
            ['nombrexx' => 'EL RECUERDO DE SANTA FE'], // 748
            ['nombrexx' => 'EL REGALO'], // 749
            ['nombrexx' => 'LA ARBOLEDA'], // 750
            ['nombrexx' => 'LA GRANJITA'], // 751
            ['nombrexx' => 'LA SUERTE'], // 752
            ['nombrexx' => 'LA UNIÓN'], // 753
            ['nombrexx' => 'LOS CENTAUROS'], // 754
            ['nombrexx' => 'OSORIO X'], // 755
            ['nombrexx' => 'OSORIO XIII'], // 756
            ['nombrexx' => 'PARCELA EL PORVENIR'], // 757
            ['nombrexx' => 'SAN BERNARDINO II'], // 758
            ['nombrexx' => 'SANTA FE I, II Y III'], // 759
            ['nombrexx' => 'SANTA FE DE BOSA'], // 760
            ['nombrexx' => 'VILLA ALEGRE'], // 761
            ['nombrexx' => 'VILLA ALEGRÍA'], // 762
            ['nombrexx' => 'VILLA ESMERALDA'], // 763
            ['nombrexx' => 'VILLA KAREN'], // 764
            ['nombrexx' => 'EL MATORRAL'], // 765
            ['nombrexx' => 'EL MATORRAL DE SAN BERNARDINO'], // 766
            ['nombrexx' => 'EL TRIUNFO DE SAN BERNARDINO'], // 767
            ['nombrexx' => 'LA VEGA DE SAN BERNARDINO BAJO'], // 768
            ['nombrexx' => 'SAN BERNARDINO SECTOR POTRERITO'], // 769
            ['nombrexx' => 'SAN BERNARDINO XIX, XVI, XVII, XVIII, XXII Y XXV'], // 770
            ['nombrexx' => 'CIUDADELA EL RECREO'], // 771
            ['nombrexx' => 'AGRUPACIÓN PÍO X'], // 772
            ['nombrexx' => 'AGRUPACIÓN MULTIFAMILIAR VILLA EMILIA'], // 773
            ['nombrexx' => 'ALFÉREZ REAL'], // 774
            ['nombrexx' => 'AMÉRICAS CENTRAL'], // 775
            ['nombrexx' => 'AMÉRICAS OCCIDENTAL I'], // 776
            ['nombrexx' => 'II Y III ETAPA'], // 777
            ['nombrexx' => 'ANTIGUO HIPÓDROMO DE TECHO II ETAPA'], // 778
            ['nombrexx' => 'BANDERAS'], // 779
            ['nombrexx' => 'CARVAJAL II SECTOR'], // 780
            ['nombrexx' => 'CENTROAMÉRICAS'], // 781
            ['nombrexx' => 'CIUDAD KENNEDY'], // 782
            ['nombrexx' => 'EL RINCÓN DE MANDALAY'], // 783
            ['nombrexx' => 'FLORESTA SUR'], // 784
            ['nombrexx' => 'FUNDADORES'], // 785
            ['nombrexx' => 'GLORIETA DE LAS AMÉRICAS'], // 786
            ['nombrexx' => 'HIPOTECHO'], // 787
            ['nombrexx' => 'IGUALDAD I Y II'], // 788
            ['nombrexx' => 'LA LLANURA'], // 789
            ['nombrexx' => 'LAS AMÉRICAS'], // 790
            ['nombrexx' => 'MANDALAY'], // 791
            ['nombrexx' => 'MARSELLA III'], // 792
            ['nombrexx' => 'NUEVA MARSELLA I'], // 793
            ['nombrexx' => 'PROVIVIENDA ORIENTAL'], // 794
            ['nombrexx' => 'SANTA ROSA DE CARVAJAL'], // 795
            ['nombrexx' => 'VILLA ADRIANA'], // 796
            ['nombrexx' => 'VILLA CLAUDIA'], // 797
            ['nombrexx' => 'ALQUERÍA DE LA FRAGUA'], // 798
            ['nombrexx' => 'BOMBAY'], // 799
            ['nombrexx' => 'CARIMAGUA I'], // 800
            ['nombrexx' => 'CARVAJAL'], // 801
            ['nombrexx' => 'CARVAJAL OSORIO'], // 802
            ['nombrexx' => 'CARVAJAL TECHO'], // 803
            ['nombrexx' => 'CONDADO EL REY'], // 804
            ['nombrexx' => 'DELICIAS'], // 805
            ['nombrexx' => 'DESARROLLO NUEVA YORK'], // 806
            ['nombrexx' => 'EL PENCIL'], // 807
            ['nombrexx' => 'EL PROGRESO I Y II'], // 808
            ['nombrexx' => 'FLORALIA I Y II'], // 809
            ['nombrexx' => 'GERONA'], // 810
            ['nombrexx' => 'GUADALUPE'], // 811
            ['nombrexx' => 'LA CHUCUA'], // 812
            ['nombrexx' => 'LAS TORRES'], // 813
            ['nombrexx' => 'LOS CRISTALES'], // 814
            ['nombrexx' => 'LUCERNA'], // 815
            ['nombrexx' => 'MILENTA'], // 816
            ['nombrexx' => 'NUEVA YORK'], // 817
            ['nombrexx' => 'PROVIVIENDA'], // 818
            ['nombrexx' => 'PROVIVIENDA OCCIDENTAL'], // 819
            ['nombrexx' => 'SALVADOR ALLENDE'], // 820
            ['nombrexx' => 'SAN ANDRÉS I Y II'], // 821
            ['nombrexx' => 'TALAVERA DE LA REINA'], // 822
            ['nombrexx' => 'TAYRONA COMERCIAL'], // 823
            ['nombrexx' => 'VALENCIA-LA CHUCUA'], // 824
            ['nombrexx' => 'VILLA NUEVA'], // 825
            ['nombrexx' => 'ALOHA NORTE'], // 826
            ['nombrexx' => 'AGRUPACIÓN DE VIVIENDA PIO XII'], // 827
            ['nombrexx' => 'BAVARIA TECHO II'], // 828
            ['nombrexx' => 'BOSQUES DE CASTILLA'], // 829
            ['nombrexx' => 'CASTILLA LA NUEVA'], // 830
            ['nombrexx' => 'CASTILLA LOS MANDRILES'], // 831
            ['nombrexx' => 'CASTILLA REAL'], // 832
            ['nombrexx' => 'CASTILLA RESERVADO'], // 833
            ['nombrexx' => 'CATANIA'], // 834
            ['nombrexx' => 'CATANIA-CASTILLA'], // 835
            ['nombrexx' => 'CIUDAD DON BOSCO'], // 836
            ['nombrexx' => 'CIUDAD FAVIDI'], // 837
            ['nombrexx' => 'CIUDAD TECHO'], // 838
            ['nombrexx' => 'EL CONDADO'], // 839
            ['nombrexx' => 'EL PORTAL DE LAS AMÉRICAS'], // 840
            ['nombrexx' => 'EL RINCÓN DE CASTILLA'], // 841
            ['nombrexx' => 'EL RINCÓN DE LOS ÁNGELES'], // 842
            ['nombrexx' => 'EL TINTAL'], // 843
            ['nombrexx' => 'EL VERGEL'], // 844
            ['nombrexx' => 'LAGOS DE CASTILLA'], // 845
            ['nombrexx' => 'LAS DOS AVENIDAS I Y II ETAPA'], // 846
            ['nombrexx' => 'MONTERREY'], // 847
            ['nombrexx' => 'MULTIFAMILIARES EL FERROL'], // 848
            ['nombrexx' => 'OSORIO'], // 849
            ['nombrexx' => 'OVIEDO'], // 850
            ['nombrexx' => 'PIO XII'], // 851
            ['nombrexx' => 'SAN JOSÉ OCCIDENTAL'], // 852
            ['nombrexx' => 'SANTA CATALINA I Y II'], // 853
            ['nombrexx' => 'VALLADOLID'], // 854
            ['nombrexx' => 'VILLA ALSACIA'], // 855
            ['nombrexx' => 'VILLA CASTILLA'], // 856
            ['nombrexx' => 'VILLA GALANTE'], // 857
            ['nombrexx' => 'VILLA LILIANA'], // 858
            ['nombrexx' => 'VILLA MARIANA'], // 859
            ['nombrexx' => 'VISIÓN DE COLOMBIA'], // 860
            ['nombrexx' => 'CASABLANCA I, II, III Y IV'], // 861
            ['nombrexx' => 'CASABLANCA 32 Y 33'], // 862
            ['nombrexx' => 'CIUDAD KENNEDY CENTRAL'], // 863
            ['nombrexx' => 'CIUDAD KENNEDY NORTE'], // 864
            ['nombrexx' => 'CIUDAD KENNEDY OCCIDENTAL'], // 865
            ['nombrexx' => 'CIUDAD KENNEDY ORIENTAL'], // 866
            ['nombrexx' => 'CIUDAD KENNEDY SUR'], // 867
            ['nombrexx' => 'EL DESCANSO'], // 868
            ['nombrexx' => 'LA GIRALDILLA'], // 869
            ['nombrexx' => 'MIRAFLORES KENNEDY'], // 870
            ['nombrexx' => 'MULTIFAMILIAR TECHO'], // 871
            ['nombrexx' => 'NUEVO KENNEDY'], // 872
            ['nombrexx' => 'PASTRANA'], // 873
            ['nombrexx' => 'TECHO'], // 874
            ['nombrexx' => 'PUERTO JOSÉ DE CALDAS'], // 875
            ['nombrexx' => 'ALAMEDA DE TIMIZA'], // 876
            ['nombrexx' => 'ALFONSO MONTAÑA'], // 877
            ['nombrexx' => 'BOITÁ I Y II'], // 878
            ['nombrexx' => 'CASA LOMA'], // 879
            ['nombrexx' => 'CATALINA'], // 880
            ['nombrexx' => 'CATALINA II'], // 881
            ['nombrexx' => 'EL COMITÉ'], // 882
            ['nombrexx' => 'EL PALENQUE'], // 883
            ['nombrexx' => 'JACQUELINE'], // 884
            ['nombrexx' => 'JUAN PABLO I'], // 885
            ['nombrexx' => 'LA UNIDAD'], // 886
            ['nombrexx' => 'LAGO TIMIZA I Y II ETAPA'], // 887
            ['nombrexx' => 'LAS LUCES'], // 888
            ['nombrexx' => 'MORAVIA II'], // 889
            ['nombrexx' => 'NUEVO TIMIZA'], // 890
            ['nombrexx' => 'ONASIS'], // 891
            ['nombrexx' => 'PASTRANITA II'], // 892
            ['nombrexx' => 'PERPETUO SOCORRO'], // 893
            ['nombrexx' => 'PRADOS DE KENNEDY'], // 894
            ['nombrexx' => 'ROMA'], // 895
            ['nombrexx' => 'ROMA II'], // 896
            ['nombrexx' => 'SANTA CATALINA'], // 897
            ['nombrexx' => 'TIMIZA'], // 898
            ['nombrexx' => 'TONOLI'], // 899
            ['nombrexx' => 'TOCAREMA'], // 900
            ['nombrexx' => 'TUNDAMA'], // 901
            ['nombrexx' => 'VASCONIA II'], // 902
            ['nombrexx' => 'VILLA DE LOS SAUCES'], // 903
            ['nombrexx' => 'VILLA RICA'], // 904
            ['nombrexx' => 'SANTA PAZ-SANTA ELVIRA'], // 905
            ['nombrexx' => 'VEREDA EL TINTAL Y LA PARTE OCCIDENTAL DEL SECTOR TINTAL COMO LO ES CIUDAD TINTAL'], // 906
            ['nombrexx' => 'URBANIZACIÓN UNIR UNO (PREDIO CALANDAIMA)'], // 907
            ['nombrexx' => 'CALANDAIMA'], // 908
            ['nombrexx' => 'CONJUNTO RESIDENCIAL PRADOS DE CASTILLA I, II Y III'], // 909
            ['nombrexx' => 'CONJUNTO RESIDENCIAL GERONA DEL TINTAL'], // 910
            ['nombrexx' => 'GALÁN'], // 911
            ['nombrexx' => 'SANTA FE DEL TINTAL'], // 912
            ['nombrexx' => 'TINTALA'], // 913
            ['nombrexx' => 'CIUDADELA TIERRA BUENA'], // 914
            ['nombrexx' => 'CIUDADELA PRIMAVERA'], // 915
            ['nombrexx' => 'CAYETANO CAÑIZARES'], // 916
            ['nombrexx' => 'CHUCUA DE LA VACA'], // 917
            ['nombrexx' => 'EL AMPARO'], // 918
            ['nombrexx' => 'EL LLANTITO'], // 919
            ['nombrexx' => 'EL OLIVO'], // 920
            ['nombrexx' => 'EL SAUCEDAL'], // 921
            ['nombrexx' => 'LA CONCORDIA'], // 922
            ['nombrexx' => 'LLANO GRANDE'], // 923
            ['nombrexx' => 'MARÍA PAZ'], // 924
            ['nombrexx' => 'PINAR DEL RÍO'], // 925
            ['nombrexx' => 'VILLA DE LA LOMA'], // 926
            ['nombrexx' => 'VILLA DE LA TORRE'], // 927
            ['nombrexx' => 'VILLA EMILIA'], // 928
            ['nombrexx' => 'VISTA HERMOSA'], // 929
            ['nombrexx' => 'ALFONSO LÓPEZ MICHELSEN'], // 930
            ['nombrexx' => 'BRITALITA'], // 931
            ['nombrexx' => 'CALARCÁ I Y II'], // 932
            ['nombrexx' => 'CASABLANCA SUR'], // 933
            ['nombrexx' => 'CLASS'], // 934
            ['nombrexx' => 'EL ALMENAR'], // 935
            ['nombrexx' => 'EL CARMELO'], // 936
            ['nombrexx' => 'GRAN BRITALIA'], // 937
            ['nombrexx' => 'PASTRANITA'], // 938
            ['nombrexx' => 'SANTA MARÍA DE KENNEDY'], // 939
            ['nombrexx' => 'VEGAS DE SANTA ANA'], // 940
            ['nombrexx' => 'VILLA ANDREA'], // 941
            ['nombrexx' => 'VILLA ZARZAMORA'], // 942
            ['nombrexx' => 'VILLAS DE KENNEDY'], // 943
            ['nombrexx' => 'ALTAMAR'], // 944
            ['nombrexx' => 'AVENIDA CUNDINAMARCA'], // 945
            ['nombrexx' => 'CIUDAD DE CALI'], // 946
            ['nombrexx' => 'CIUDAD GALÁN'], // 947
            ['nombrexx' => 'CIUDAD GRANADA'], // 948
            ['nombrexx' => 'DINDALITO'], // 949
            ['nombrexx' => 'EL PATIO'], // 950
            ['nombrexx' => 'EL ROSARIO'], // 951
            ['nombrexx' => 'HORIZONTE OCCIDENTE'], // 952
            ['nombrexx' => 'JAZMÍN OCCIDENTAL'], // 953
            ['nombrexx' => 'LA RIVERA'], // 954
            ['nombrexx' => 'LAS PALMERAS'], // 955
            ['nombrexx' => 'LOS ALMENDROS'], // 956
            ['nombrexx' => 'PALMITAS'], // 957
            ['nombrexx' => 'PATIO BONITO I, II Y III'], // 958
            ['nombrexx' => 'PUENTE LA VEGA'], // 959
            ['nombrexx' => 'SAN MARINO'], // 960
            ['nombrexx' => 'SUMAPAZ'], // 961
            ['nombrexx' => 'TAYRONA'], // 962
            ['nombrexx' => 'TIERRA BUENA. TINTALITO I Y II'], // 963
            ['nombrexx' => 'VILLA ALEXANDRA'], // 964
            ['nombrexx' => 'VILLA ANDRÉS'], // 965
            ['nombrexx' => 'VILLA MENDOZA'], // 966
            ['nombrexx' => 'OSORIO XI Y XII'], // 967
            ['nombrexx' => 'PORTAL AMÉRICAS'], // 968
            ['nombrexx' => 'ALOHA'], // 969
            ['nombrexx' => 'ALSACIA'], // 970
            ['nombrexx' => 'ÁTICOS DE LAS AMÉRICAS'], // 971
            ['nombrexx' => 'COOPERATIVA DE SUBOFICIALES'], // 972
            ['nombrexx' => 'EL CONDADO DE LA PAZ'], // 973
            ['nombrexx' => 'LOS PINOS DE MARSELLA'], // 974
            ['nombrexx' => 'LUSITANIA'], // 975
            ['nombrexx' => 'MARSELLA'], // 976
            ['nombrexx' => 'UNIDAD OVIEDO'], // 977
            ['nombrexx' => 'URBANIZACIÓN BAVARIA'], // 978
            ['nombrexx' => 'CIUDAD ALSACIA'], // 979
            ['nombrexx' => 'ARABIA'], // 980
            ['nombrexx' => 'ATAHUALPA'], // 981
            ['nombrexx' => 'BAHÍA SOLANO'], // 982
            ['nombrexx' => 'SANTIAGO BATAVIA'], // 983
            ['nombrexx' => 'BELÉN'], // 984
            ['nombrexx' => 'BOSTON'], // 985
            ['nombrexx' => 'CENTENARIO'], // 986
            ['nombrexx' => 'CENTRO A'], // 987
            ['nombrexx' => 'EL CARMEN'], // 988
            ['nombrexx' => 'EL CUCO'], // 989
            ['nombrexx' => 'EL GUADUAL'], // 990
            ['nombrexx' => 'EL RUBY'], // 991
            ['nombrexx' => 'EL TAPETE'], // 992
            ['nombrexx' => 'FERROCAJA'], // 993
            ['nombrexx' => 'FLANDES'], // 994
            ['nombrexx' => 'FONTIBÓN CENTRO'], // 995
            ['nombrexx' => 'LA GIRALDA'], // 996
            ['nombrexx' => 'LA LAGUNA'], // 997
            ['nombrexx' => 'PALESTINA'], // 998
            ['nombrexx' => 'RINCÓN SANTO'], // 999
            ['nombrexx' => 'SANTANDER'], // 1000
            ['nombrexx' => 'SALAMANCA'], // 1001
            ['nombrexx' => 'SAN PEDRO-LOS ROBLES'], // 1002
            ['nombrexx' => 'UNIDAD RESIDENCIAL MONTECARLO'], // 1003
            ['nombrexx' => 'VALLE VERDE'], // 1004
            ['nombrexx' => 'VERSALLES'], // 1005
            ['nombrexx' => 'VILLA BEATRIZ'], // 1006
            ['nombrexx' => 'VILLA CARMENZA'], // 1007
            ['nombrexx' => 'VILLEMAR'], // 1008
            ['nombrexx' => 'AMBALEMA'], // 1009
            ['nombrexx' => 'BOHÍOS'], // 1010
            ['nombrexx' => 'EL PORTAL'], // 1011
            ['nombrexx' => 'FLORENCIA'], // 1012
            ['nombrexx' => 'JERICÓ'], // 1013
            ['nombrexx' => 'LA ALDEA'], // 1014
            ['nombrexx' => 'LA PERLA'], // 1015
            ['nombrexx' => 'LA ZELFITA'], // 1016
            ['nombrexx' => 'PRADOS DE LA ALAMEDA'], // 1017
            ['nombrexx' => 'PUENTE GRANDE'], // 1018
            ['nombrexx' => 'SELVA DORADA'], // 1019
            ['nombrexx' => 'HB'], // 1020
            ['nombrexx' => 'RECODO'], // 1021
            ['nombrexx' => 'PUEBLO NUEVO'], // 1022
            ['nombrexx' => 'MORAVIA'], // 1023
            ['nombrexx' => 'KASANDRA'], // 1024
            ['nombrexx' => 'SABANA GRANDE'], // 1025
            ['nombrexx' => 'CARLOS LLERAS'], // 1026
            ['nombrexx' => 'LA ESPERANZA NORTE'], // 1027
            ['nombrexx' => 'SALITRE NOR-OCCIDENTAL'], // 1028
            ['nombrexx' => 'SAUZALITO'], // 1029
            ['nombrexx' => 'EL FRANCO'], // 1030
            ['nombrexx' => 'GRANJAS DE TECHO'], // 1031
            ['nombrexx' => 'PARAÍSO BAVARIA'], // 1032
            ['nombrexx' => 'VISIÓN SEMIINDUSTRIAL'], // 1033
            ['nombrexx' => 'BOSQUE DE MODELIA'], // 1034
            ['nombrexx' => 'BALEARES'], // 1035
            ['nombrexx' => 'CAPELLANIA'], // 1036
            ['nombrexx' => 'EL RINCÓN DE MODELIA'], // 1037
            ['nombrexx' => 'FUENTES DEL DORADO'], // 1038
            ['nombrexx' => 'HAYUELOS'], // 1039
            ['nombrexx' => 'COFRADÍA'], // 1040
            ['nombrexx' => 'LA FELICIDAD'], // 1041
            ['nombrexx' => 'MALLORCA'], // 1042
            ['nombrexx' => 'MODELIA'], // 1043
            ['nombrexx' => 'MODELIA OCCIDENTAL'], // 1044
            ['nombrexx' => 'SANTA CECILIA'], // 1045
            ['nombrexx' => 'TARRAGONA'], // 1046
            ['nombrexx' => 'LA ROSITA'], // 1047
            ['nombrexx' => 'PUERTA DE TEJA'], // 1048
            ['nombrexx' => 'EL BOGOTANO'], // 1049
            ['nombrexx' => 'ACAPULCO'], // 1050
            ['nombrexx' => 'BELLAVISTA OCCIDENTAL'], // 1051
            ['nombrexx' => 'LA BONANZA'], // 1052
            ['nombrexx' => 'BOSQUE POPULAR'], // 1053
            ['nombrexx' => 'CIUDAD DE HONDA'], // 1054
            ['nombrexx' => 'EL DORADO-SAN JOAQUÍN'], // 1055
            ['nombrexx' => 'EL GUALI'], // 1056
            ['nombrexx' => 'EL LAUREL'], // 1057
            ['nombrexx' => 'EL PASEO'], // 1058
            ['nombrexx' => 'ESTRADA'], // 1059
            ['nombrexx' => 'LA ESTRADITA'], // 1060
            ['nombrexx' => 'LA EUROPA'], // 1061
            ['nombrexx' => 'LA MARCELA'], // 1062
            ['nombrexx' => 'LA RELIQUIA'], // 1063
            ['nombrexx' => 'LAS FERIAS'], // 1064
            ['nombrexx' => 'METRÓPOLIS'], // 1065
            ['nombrexx' => 'PALO BLANCO'], // 1066
            ['nombrexx' => 'SANTO DOMINGO'], // 1067
            ['nombrexx' => 'ANDALUCÍA'], // 1068
            ['nombrexx' => 'CIUDAD BACHUÉ'], // 1069
            ['nombrexx' => 'COPETROCO LA TROPICAL'], // 1070
            ['nombrexx' => 'EL PORTAL DEL RÍO'], // 1071
            ['nombrexx' => 'LA PALESTINA'], // 1072
            ['nombrexx' => 'TISQUESUSA'], // 1073
            ['nombrexx' => 'LA ESPAÑOLA'], // 1074
            ['nombrexx' => 'LA SERENA'], // 1075
            ['nombrexx' => 'LOS CEREZOS'], // 1076
            ['nombrexx' => 'LUIS CARLOS GALÁN'], // 1077
            ['nombrexx' => 'MEISSEN-SIDAUTO'], // 1078
            ['nombrexx' => 'MINUTO DE DIOS'], // 1079
            ['nombrexx' => 'MORISCO'], // 1080
            ['nombrexx' => 'PARÍS GAITÁN'], // 1081
            ['nombrexx' => 'PRIMAVERA NORTE'], // 1082
            ['nombrexx' => 'QUIRIGUA'], // 1083
            ['nombrexx' => 'BOYACÁ'], // 1084
            ['nombrexx' => 'FLORIDA BLANCA'], // 1085
            ['nombrexx' => 'LA ALMERÍA'], // 1086
            ['nombrexx' => 'LA GRANJA'], // 1087
            ['nombrexx' => 'LA SOLEDAD NORTE'], // 1088
            ['nombrexx' => 'LA SALINA'], // 1089
            ['nombrexx' => 'LOS PINOS FLORENCIA'], // 1090
            ['nombrexx' => 'MARATU'], // 1091
            ['nombrexx' => 'PARÍS'], // 1092
            ['nombrexx' => 'SANTA HELENITA'], // 1093
            ['nombrexx' => 'SANTA MARÍA DEL LAGO'], // 1094
            ['nombrexx' => 'SANTA ROSITA'], // 1095
            ['nombrexx' => 'TABORA'], // 1096
            ['nombrexx' => 'ZARZAMORA'], // 1097
            ['nombrexx' => 'EL LUJAN'], // 1098
            ['nombrexx' => 'EL REAL'], // 1099
            ['nombrexx' => 'LOS MONJES'], // 1100
            ['nombrexx' => 'NORMANDÍA'], // 1101
            ['nombrexx' => 'NORMANDÍA OCCIDENTAL'], // 1102
            ['nombrexx' => 'SAN IGNACIO'], // 1103
            ['nombrexx' => 'SAN MARCOS'], // 1104
            ['nombrexx' => 'VILLA LUZ'], // 1105
            ['nombrexx' => 'BOCHICA'], // 1106
            ['nombrexx' => 'BOCHICA COMPARTIR'], // 1107
            ['nombrexx' => 'BOLIVIA'], // 1108
            ['nombrexx' => 'CIUDADELA COLSUBSIDIO'], // 1109
            ['nombrexx' => 'CORTIJO'], // 1110
            ['nombrexx' => 'GARCÉS NAVAS'], // 1111
            ['nombrexx' => 'ÁLAMOS'], // 1112
            ['nombrexx' => 'ÁLAMOS NORTE'], // 1113
            ['nombrexx' => 'BOSQUES DE MARIANA'], // 1114
            ['nombrexx' => 'EL CEDRO'], // 1115
            ['nombrexx' => 'LOS ÁNGELES'], // 1116
            ['nombrexx' => 'MOLINOS DE VIENTO'], // 1117
            ['nombrexx' => 'PLAZUELAS DEL VIRREY'], // 1118
            ['nombrexx' => 'SAN BASILIO'], // 1119
            ['nombrexx' => 'VILLA AMALIA'], // 1120
            ['nombrexx' => 'VILLA SAGRARIO'], // 1121
            ['nombrexx' => 'VILLAS DE GRANADA'], // 1122
            ['nombrexx' => 'VILLAS DEL MADRIGAL'], // 1123
            ['nombrexx' => 'VILLAS DEL DORADO-SAN ANTONIO'], // 1124
            ['nombrexx' => 'BOSQUES DE GRANADA'], // 1125
            ['nombrexx' => 'PARQUES DE GRANADA'], // 1126
            ['nombrexx' => 'ANDALUCÍA PARQUES DE GRANADA'], // 1127
            ['nombrexx' => 'PORTAL DE GRANADA'], // 1128
            ['nombrexx' => 'RINCÓN DE GRANADA'], // 1129
            ['nombrexx' => 'GRANADA CLUB RESIDENCIAL'], // 1130
            ['nombrexx' => 'LA ROTANA'], // 1131
            ['nombrexx' => 'MIRADOR DE LOS CEREZOS'], // 1132
            ['nombrexx' => 'ALAMEDA'], // 1133
            ['nombrexx' => 'CENTAUROS DEL DANUBIO'], // 1134
            ['nombrexx' => 'EL MUELLE'], // 1135
            ['nombrexx' => 'EL VERDÚN'], // 1136
            ['nombrexx' => 'ENGATIVÁ-CENTRO'], // 1137
            ['nombrexx' => 'GRANJAS EL DORADO'], // 1138
            ['nombrexx' => 'LA FAENA'], // 1139
            ['nombrexx' => 'LA TORQUIGUA'], // 1140
            ['nombrexx' => 'SANTA LUCÍA NORTE'], // 1141
            ['nombrexx' => 'LAS PALMAS'], // 1142
            ['nombrexx' => 'LINTERAMA'], // 1143
            ['nombrexx' => 'LOS LAURELES'], // 1144
            ['nombrexx' => 'LOS LAURELES-SABANAS EL DORADO'], // 1145
            ['nombrexx' => 'MARANDÚ'], // 1146
            ['nombrexx' => 'PUERTO AMOR-PLAYAS DEL JABOQUE'], // 1147
            ['nombrexx' => 'SAN JOSÉ OBRERO'], // 1148
            ['nombrexx' => 'VILLA CLAVER I Y II'], // 1149
            ['nombrexx' => 'VILLA CONSTANZA'], // 1150
            ['nombrexx' => 'VILLAS DEL DORADO NORTE'], // 1151
            ['nombrexx' => 'VILLA GLADYS'], // 1152
            ['nombrexx' => 'VILLA MARY'], // 1153
            ['nombrexx' => 'VILLA SANDRA'], // 1154
            ['nombrexx' => 'VILLA TERESITA'], // 1155
            ['nombrexx' => 'EL SALITRE-LUIS MARÍA FERNÁNDEZ'], // 1156
            ['nombrexx' => 'SAN IGNACIO-LOS ÁLAMOS'], // 1157
            ['nombrexx' => 'LA ACADEMIA'], // 1158
            ['nombrexx' => 'GUAYMARAL'], // 1159
            ['nombrexx' => 'CONEJERA'], // 1160
            ['nombrexx' => 'GIBRALTAR'], // 1161
            ['nombrexx' => 'GUICANI'], // 1162
            ['nombrexx' => 'MIRANDELA'], // 1163
            ['nombrexx' => 'NUEVA ZELANDIA'], // 1164
            ['nombrexx' => 'OIKOS'], // 1165
            ['nombrexx' => 'SAN JOSÉ DE BAVARIA'], // 1166
            ['nombrexx' => 'TEJARES DEL NORTE'], // 1167
            ['nombrexx' => 'VILLANOVA'], // 1168
            ['nombrexx' => 'VILLA DEL PRADO'], // 1169
            ['nombrexx' => 'VILLA LUCY'], // 1170
            ['nombrexx' => 'BRITALIA'], // 1171
            ['nombrexx' => 'BRITALIA SAN DIEGO'], // 1172
            ['nombrexx' => 'CALIMA NORTE'], // 1173
            ['nombrexx' => 'CANTAGALLO'], // 1174
            ['nombrexx' => 'CANTALEJO'], // 1175
            ['nombrexx' => 'EL PARAÍSO DE LOS 12 APÓSTOLES'], // 1176
            ['nombrexx' => 'GILMAR'], // 1177
            ['nombrexx' => 'GRANADA NORTE'], // 1178
            ['nombrexx' => 'GRANJAS DE NAMUR'], // 1179
            ['nombrexx' => 'LA CHOCITA'], // 1180
            ['nombrexx' => 'LOS ELISEOS'], // 1181
            ['nombrexx' => 'PIJAO DE ORO'], // 1182
            ['nombrexx' => 'PORTALES DEL NORTE'], // 1183
            ['nombrexx' => 'SAN CIPRIANO'], // 1184
            ['nombrexx' => 'VILLA DELIA'], // 1185
            ['nombrexx' => 'VISTA BELLA'], // 1186
            ['nombrexx' => 'ALCALÁ'], // 1187
            ['nombrexx' => 'ATABANZA'], // 1188
            ['nombrexx' => 'BERNAL Y FORERO'], // 1189
            ['nombrexx' => 'CACIHIA'], // 1190
            ['nombrexx' => 'CANODROMO'], // 1191
            ['nombrexx' => 'LA SULTANA'], // 1192
            ['nombrexx' => 'LIBERTADORES'], // 1193
            ['nombrexx' => 'LOS PRADOS DE LA SULTANA'], // 1194
            ['nombrexx' => 'MADEIRA'], // 1195
            ['nombrexx' => 'MANUELA ARLUZ'], // 1196
            ['nombrexx' => 'MAZURÉN'], // 1197
            ['nombrexx' => 'NIZA IX'], // 1198
            ['nombrexx' => 'PRADO PINZÓN'], // 1199
            ['nombrexx' => 'PRADO SUR'], // 1200
            ['nombrexx' => 'PRADO VERANIEGO'], // 1201
            ['nombrexx' => 'PRADO VERANIEGO NORTE'], // 1202
            ['nombrexx' => 'PRADO VERANIEGO SUR'], // 1203
            ['nombrexx' => 'SAN JOSÉ DEL SPRING'], // 1204
            ['nombrexx' => 'SAN JOSÉ DEL PRADO'], // 1205
            ['nombrexx' => 'SANTA HELENA'], // 1206
            ['nombrexx' => 'TIERRA LINDA'], // 1207
            ['nombrexx' => 'VICTORIA NORTE'], // 1208
            ['nombrexx' => 'VILLA MORENA'], // 1209
            ['nombrexx' => 'ALHAMBRA'], // 1210
            ['nombrexx' => 'BATÁN'], // 1211
            ['nombrexx' => 'EL RECREO DE LOS FRAILES'], // 1212
            ['nombrexx' => 'ESTORIL'], // 1213
            ['nombrexx' => 'ILARCO'], // 1214
            ['nombrexx' => 'MALIBÚ'], // 1215
            ['nombrexx' => 'MÓNACO'], // 1216
            ['nombrexx' => 'PASADENA'], // 1217
            ['nombrexx' => 'PUENTE LARGO'], // 1218
            ['nombrexx' => 'CATALAYUD'], // 1219
            ['nombrexx' => 'CASA BLANCA I Y II'], // 1220
            ['nombrexx' => 'CASABLANCA NORTE SUBA'], // 1221
            ['nombrexx' => 'DEL MONTE'], // 1222
            ['nombrexx' => 'EL VELERO'], // 1223
            ['nombrexx' => 'ESCUELA DE CARABINEROS'], // 1224
            ['nombrexx' => 'CALATRAVA'], // 1225
            ['nombrexx' => 'CAMPANIA'], // 1226
            ['nombrexx' => 'CIUDAD JARDÍN NORTE'], // 1227
            ['nombrexx' => 'COLINA CAMPESTRE'], // 1228
            ['nombrexx' => 'COLINAS DE SUBA'], // 1229
            ['nombrexx' => 'COVADONGA'], // 1230
            ['nombrexx' => 'GRATAMIRA'], // 1231
            ['nombrexx' => 'IBERIA'], // 1232
            ['nombrexx' => 'LAGOS DE CÓRDOBA'], // 1233
            ['nombrexx' => 'LAS VILLAS'], // 1234
            ['nombrexx' => 'LINDARAJA'], // 1235
            ['nombrexx' => 'NIZA'], // 1236
            ['nombrexx' => 'NIZA NORTE'], // 1237
            ['nombrexx' => 'NIZA SUBA'], // 1238
            ['nombrexx' => 'NIZA VIII'], // 1239
            ['nombrexx' => 'PRADO JARDÍN'], // 1240
            ['nombrexx' => 'PROVENZA'], // 1241
            ['nombrexx' => 'RINCÓN DE IBERIA'], // 1242
            ['nombrexx' => 'SOTILEZA'], // 1243
            ['nombrexx' => 'ANDES NORTE'], // 1244
            ['nombrexx' => 'CLUB LOS LAGARTOS'], // 1245
            ['nombrexx' => 'COASMEDAS'], // 1246
            ['nombrexx' => 'JULIO FLOREZ'], // 1247
            ['nombrexx' => 'LA ALBORADA'], // 1248
            ['nombrexx' => 'LA FLORESTA NORTE'], // 1249
            ['nombrexx' => 'MORATO'], // 1250
            ['nombrexx' => 'NUEVO MONTERREY'], // 1251
            ['nombrexx' => 'PONTEVEDRA'], // 1252
            ['nombrexx' => 'POTOSÍ'], // 1253
            ['nombrexx' => 'SANTA ROSA'], // 1254
            ['nombrexx' => 'SAN NICOLÁS'], // 1255
            ['nombrexx' => 'TEUSACÁ'], // 1256
            ['nombrexx' => 'ALCÁZAR DE SUBA'], // 1257
            ['nombrexx' => 'ALMENDROS NORTE'], // 1258
            ['nombrexx' => 'ALTO DE LA TOMA'], // 1259
            ['nombrexx' => 'BOSQUES DE SAN JORGE'], // 1260
            ['nombrexx' => 'CAMPANELA'], // 1261
            ['nombrexx' => 'COSTA AZUL'], // 1262
            ['nombrexx' => 'SUBA COMPARTIR'], // 1263
            ['nombrexx' => 'EL PINAR'], // 1264
            ['nombrexx' => 'LOS LAGOS'], // 1265
            ['nombrexx' => 'EL PÓRTICO'], // 1266
            ['nombrexx' => 'EL SALITRE'], // 1267
            ['nombrexx' => 'JAVA'], // 1268
            ['nombrexx' => 'LA CAMPIÑA'], // 1269
            ['nombrexx' => 'LA FONTANA'], // 1270
            ['nombrexx' => 'GLORIA LARA'], // 1271
            ['nombrexx' => 'LONDRES'], // 1272
            ['nombrexx' => 'MONARCAS'], // 1273
            ['nombrexx' => 'NAVETAS'], // 1274
            ['nombrexx' => 'PRADOS DE SUBA'], // 1275
            ['nombrexx' => 'PORTAL DE LAS MERCEDES'], // 1276
            ['nombrexx' => 'ALMENDROS DE SUBA'], // 1277
            ['nombrexx' => 'PRADERA DE SUBA'], // 1278
            ['nombrexx' => 'RINCÓN DE SANTA INÉS'], // 1279
            ['nombrexx' => 'SAN FRANCISCO'], // 1280
            ['nombrexx' => 'SANTA ISABEL'], // 1281
            ['nombrexx' => 'SUBA CENTRO'], // 1282
            ['nombrexx' => 'TUNA ALTA'], // 1283
            ['nombrexx' => 'TUNA BAJA'], // 1284
            ['nombrexx' => 'TURINGIA'], // 1285
            ['nombrexx' => 'VEREDA SUBA CERROS'], // 1286
            ['nombrexx' => 'VILLA DEL CAMPO'], // 1287
            ['nombrexx' => 'VILLA ESPERANZA'], // 1288
            ['nombrexx' => 'VILLA SUSANA'], // 1289
            ['nombrexx' => 'ALCAPARROS'], // 1290
            ['nombrexx' => 'ALMIRANTE COLÓN'], // 1291
            ['nombrexx' => 'ALMONACID'], // 1292
            ['nombrexx' => 'ALTOS DE CHOZICA'], // 1293
            ['nombrexx' => 'ALTOS DE LA ESPERANZA'], // 1294
            ['nombrexx' => 'AMBERES'], // 1295
            ['nombrexx' => 'ANTONIO GRANADOS'], // 1296
            ['nombrexx' => 'AURES I Y II'], // 1297
            ['nombrexx' => 'BOCHALEMA'], // 1298
            ['nombrexx' => 'CIUDAD HUNZA'], // 1299
            ['nombrexx' => 'CIUDADELA CAFAM'], // 1300
            ['nombrexx' => 'EL AGUINALDO'], // 1301
            ['nombrexx' => 'EL ARENAL'], // 1302
            ['nombrexx' => 'EL CEREZO'], // 1303
            ['nombrexx' => 'EL CÓNDOR'], // 1304
            ['nombrexx' => 'EL JORDAN-LA ESPERANZA'], // 1305
            ['nombrexx' => 'EL POA'], // 1306
            ['nombrexx' => 'EL NARANJAL'], // 1307
            ['nombrexx' => 'EL OCAL'], // 1308
            ['nombrexx' => 'EL REFUGIO DE SUBA'], // 1309
            ['nombrexx' => 'EL TABOR'], // 1310
            ['nombrexx' => 'GLORIA LARA DE ECHEVERRI'], // 1311
            ['nombrexx' => 'GUILLERMO NÚÑEZ'], // 1312
            ['nombrexx' => 'JAIME BERMEO'], // 1313
            ['nombrexx' => 'JAPÓN'], // 1314
            ['nombrexx' => 'JAVA II SECTOR'], // 1315
            ['nombrexx' => 'LA AGUADITA'], // 1316
            ['nombrexx' => 'LA ESPERANZA (CALLE 131 A)'], // 1317
            ['nombrexx' => 'LA ESTANZUELA'], // 1318
            ['nombrexx' => 'LA FLOR'], // 1319
            ['nombrexx' => 'LA FLORA'], // 1320
            ['nombrexx' => 'LA MANUELITA'], // 1321
            ['nombrexx' => 'LAGOS DE SUBA'], // 1322
            ['nombrexx' => 'LOMBARDÍA/COMUNEROS'], // 1323
            ['nombrexx' => 'LOS NOGALES'], // 1324
            ['nombrexx' => 'NARANJOS ALTOS'], // 1325
            ['nombrexx' => 'PALMA ALDEA'], // 1326
            ['nombrexx' => 'PORTERRILLO'], // 1327
            ['nombrexx' => 'PRADOS DE SANTA BÁRBARA'], // 1328
            ['nombrexx' => 'PUERTA DEL SOL'], // 1329
            ['nombrexx' => 'RINCÓN DE SUBA'], // 1330
            ['nombrexx' => 'RINCÓN EL CÓNDOR'], // 1331
            ['nombrexx' => 'RINCÓN-ESCUELA'], // 1332
            ['nombrexx' => 'RIOBAMBA'], // 1333
            ['nombrexx' => 'RODRIGO LARA BONILLA'], // 1334
            ['nombrexx' => 'SAN CAYETANO'], // 1335
            ['nombrexx' => 'SAN ISIDRO NORTE'], // 1336
            ['nombrexx' => 'SANTA ANA DE SUBA'], // 1337
            ['nombrexx' => 'TABERÍN'], // 1338
            ['nombrexx' => 'TELECOM ARRAYANES'], // 1339
            ['nombrexx' => 'TEUSAQUILLO DE SUBA'], // 1340
            ['nombrexx' => 'TIBABUYES'], // 1341
            ['nombrexx' => 'TRINITARIA'], // 1342
            ['nombrexx' => 'VILLA CATALINA'], // 1343
            ['nombrexx' => 'VILLA ELISA'], // 1344
            ['nombrexx' => 'VILLA MARÍA'], // 1345
            ['nombrexx' => 'VILLAS DEL RINCÓN'], // 1346
            ['nombrexx' => 'BILBAO'], // 1347
            ['nombrexx' => 'CAÑIZA I'], // 1348
            ['nombrexx' => 'CAROLINA II Y III'], // 1349
            ['nombrexx' => 'COMPARTIR'], // 1350
            ['nombrexx' => 'FONTANAR DEL RÍO'], // 1351
            ['nombrexx' => 'LA GAITANA'], // 1352
            ['nombrexx' => 'LA ISABELA'], // 1353
            ['nombrexx' => 'LOS NOGALES DE TIBABUYES'], // 1354
            ['nombrexx' => 'MIRAMAR'], // 1355
            ['nombrexx' => 'NUEVA TIBABUYES'], // 1356
            ['nombrexx' => 'NUEVO CORINTO'], // 1357
            ['nombrexx' => 'RINCÓN DE BOYACÁ'], // 1358
            ['nombrexx' => 'SABANA DE TIBABUYES'], // 1359
            ['nombrexx' => 'SAN CARLOS DE SUBA'], // 1360
            ['nombrexx' => 'SAN CARLOS DE TIBABUYES'], // 1361
            ['nombrexx' => 'SAN PEDRO DE TIBABUYES'], // 1362
            ['nombrexx' => 'SANTA RITA'], // 1363
            ['nombrexx' => 'TIBABUYES UNIVERSAL'], // 1364
            ['nombrexx' => 'VEREDA SUBA-RINCÓN'], // 1365
            ['nombrexx' => 'VEREDA TIBABUYES'], // 1366
            ['nombrexx' => 'VERONA'], // 1367
            ['nombrexx' => 'VILLA CINDY'], // 1368
            ['nombrexx' => 'VILLA DE LAS FLORES'], // 1369
            ['nombrexx' => 'VILLA GLORIA'], // 1370
            ['nombrexx' => 'VILLA CALASANZ'], // 1371
            ['nombrexx' => 'ENTRE RÍOS'], // 1372
            ['nombrexx' => 'LA CASTELLANA'], // 1373
            ['nombrexx' => 'LA PATRIA'], // 1374
            ['nombrexx' => 'LOS ANDES'], // 1375
            ['nombrexx' => 'RIONEGRO'], // 1376
            ['nombrexx' => 'URBANIZACIÓN SAN MARTÍN'], // 1377
            ['nombrexx' => 'VIZCAYA'], // 1378
            ['nombrexx' => 'DOCE DE OCTUBRE'], // 1379
            ['nombrexx' => 'JORGE ELIÉCER GAITÁN'], // 1380
            ['nombrexx' => 'JOSÉ JOAQUÍN VARGAS'], // 1381
            ['nombrexx' => 'LA LIBERTAD'], // 1382
            ['nombrexx' => 'RINCÓN DEL SALITRE'], // 1383
            ['nombrexx' => 'EL LABRADOR'], // 1384
            ['nombrexx' => 'MODELO NORTE'], // 1385
            ['nombrexx' => 'SAN FERNANDO'], // 1386
            ['nombrexx' => 'SIMÓN BOLÍVAR'], // 1387
            ['nombrexx' => '1 DE NOVIEMBRE'], // 1388
            ['nombrexx' => 'ALCÁZARES NORTE'], // 1389
            ['nombrexx' => 'BAQUERO'], // 1390
            ['nombrexx' => 'BENJAMÍN HERRERA'], // 1391
            ['nombrexx' => 'CHAPINERO NOROCCIDENTAL'], // 1392
            ['nombrexx' => 'COLOMBIA'], // 1393
            ['nombrexx' => 'CONCEPCIÓN NORTE'], // 1394
            ['nombrexx' => 'JUAN XXIII NORTE'], // 1395
            ['nombrexx' => 'LA MERCED NORTE'], // 1396
            ['nombrexx' => 'LOS ALCÁZARES'], // 1397
            ['nombrexx' => 'MUEQUETÁ'], // 1398
            ['nombrexx' => 'POLO CLUB'], // 1399
            ['nombrexx' => 'QUINTA MUTIS'], // 1400
            ['nombrexx' => 'RAFAEL URIBE URIBE'], // 1401
            ['nombrexx' => 'SANTA SOFÍA'], // 1402
            ['nombrexx' => 'SIETE DE AGOSTO'], // 1403
            ['nombrexx' => 'EL CAMPÍN'], // 1404
            ['nombrexx' => 'CHAPINERO OCCIDENTAL'], // 1405
            ['nombrexx' => 'GALERÍAS'], // 1406
            ['nombrexx' => 'BANCO CENTRAL'], // 1407
            ['nombrexx' => 'QUESADA'], // 1408
            ['nombrexx' => 'BELALCÁZAR'], // 1409
            ['nombrexx' => 'ALFONSO LÓPEZ NORTE'], // 1410
            ['nombrexx' => 'PALERMO'], // 1411
            ['nombrexx' => 'LA SOLEDAD'], // 1412
            ['nombrexx' => 'SANTA TERESITA'], // 1413
            ['nombrexx' => 'LA MAGDALENA'], // 1414
            ['nombrexx' => 'TEUSAQUILLO'], // 1415
            ['nombrexx' => 'LA ESTRELLA'], // 1416
            ['nombrexx' => 'ARMENIA'], // 1417
            ['nombrexx' => 'PARQUE METROPOLITANO SIMÓN BOLÍVAR'], // 1418
            ['nombrexx' => 'PABLO VI'], // 1419
            ['nombrexx' => 'NICOLÁS DE FEDERMÁN'], // 1420
            ['nombrexx' => 'CAMPIN OCCIDENTAL'], // 1421
            ['nombrexx' => 'RAFAEL NÚÑEZ'], // 1422
            ['nombrexx' => 'ACEVEDO TEJADA'], // 1423
            ['nombrexx' => 'GRAN AMÉRICA'], // 1424
            ['nombrexx' => 'CENTRO NARIÑO'], // 1425
            ['nombrexx' => 'QUINTA PAREDES'], // 1426
            ['nombrexx' => 'ORTEZAL'], // 1427
            ['nombrexx' => 'CIUDAD SALITRE SU-ORIENTAL'], // 1428
            ['nombrexx' => 'CIUDAD SALITRE NOR-ORIENTAL'], // 1429
            ['nombrexx' => 'EDUARDO SANTOS'], // 1430
            ['nombrexx' => 'VERAGUAS'], // 1431
            ['nombrexx' => 'EL LISTÓN'], // 1432
            ['nombrexx' => 'ESTACIÓN DE LA SABANA'], // 1433
            ['nombrexx' => 'LA FAVORITA'], // 1434
            ['nombrexx' => 'LA PEPITA'], // 1435
            ['nombrexx' => 'PALOQUEMAO'], // 1436
            ['nombrexx' => 'PANAMERICANO - LA FLORIDA'], // 1437
            ['nombrexx' => 'RICAURTE'], // 1438
            ['nombrexx' => 'SAMPER MENDOZA'], // 1439
            ['nombrexx' => 'SANTA FE'], // 1440
            ['nombrexx' => 'VOTO NACIONAL'], // 1441
            ['nombrexx' => 'EL CONJUNTO RESIDENCIAL USATAMA'], // 1442
            ['nombrexx' => 'UNIDAD RESIDENCIAL COLSEGUROS'], // 1443
            ['nombrexx' => 'LA UNIDAD RESIDENCIAL SANS FAçON'], // 1444
            ['nombrexx' => 'BULEVAR DE SANS FAçON'], // 1445
            ['nombrexx' => 'POLICARPA'], // 1446
            ['nombrexx' => 'CARACAS'], // 1447
            ['nombrexx' => 'CIUDAD BERNA'], // 1448
            ['nombrexx' => 'CIUDAD JARDÍN'], // 1449
            ['nombrexx' => 'SEVILLA'], // 1450
            ['nombrexx' => 'LUNA PARK'], // 1451
            ['nombrexx' => 'LA HORTÚA'], // 1452
            ['nombrexx' => 'RESTREPO'], // 1453
            ['nombrexx' => 'VILLA MAYOR'], // 1454
            ['nombrexx' => 'SAN JORGE CENTRAL'], // 1455
            ['nombrexx' => 'CINCO DE NOVIEMBRE'], // 1456
            ['nombrexx' => 'EDUARDO FREÍ'], // 1457
            ['nombrexx' => 'LA FRAGUA'], // 1458
            ['nombrexx' => 'LA FRAGUITA'], // 1459
            ['nombrexx' => 'LA GUACA'], // 1460
            ['nombrexx' => 'CARABELAS'], // 1461
            ['nombrexx' => 'CIUDAD MONTES'], // 1462
            ['nombrexx' => 'EL SOL'], // 1463
            ['nombrexx' => 'JAZMÍN'], // 1464
            ['nombrexx' => 'JORGE GAITÁN CORTÉS'], // 1465
            ['nombrexx' => 'VILLA INÉS'], // 1466
            ['nombrexx' => 'LA ASUNCIÓN'], // 1467
            ['nombrexx' => 'LA CAMELIA'], // 1468
            ['nombrexx' => 'LOS COMUNEROS'], // 1469
            ['nombrexx' => 'PONDEROSA'], // 1470
            ['nombrexx' => 'PRIMAVERA'], // 1471
            ['nombrexx' => 'REMANSO'], // 1472
            ['nombrexx' => 'SAN EUSEBIO'], // 1473
            ['nombrexx' => 'SANTA MATILDE'], // 1474
            ['nombrexx' => 'TIBANÁ'], // 1475
            ['nombrexx' => 'TORREMOLINOS'], // 1476
            ['nombrexx' => 'ALQUERÍA'], // 1477
            ['nombrexx' => 'AUTOPISTA SUR'], // 1478
            ['nombrexx' => 'LA CORUÑA'], // 1479
            ['nombrexx' => 'MUZÚ'], // 1480
            ['nombrexx' => 'OSPINA PÉREZ'], // 1481
            ['nombrexx' => 'TEJAR'], // 1482
            ['nombrexx' => 'VILLA DEL ROSARIO'], // 1483
            ['nombrexx' => 'VILLA SONIA'], // 1484
            ['nombrexx' => 'BISAS DEL GALÁN'], // 1485
            ['nombrexx' => 'CAMELIA SUR'], // 1486
            ['nombrexx' => 'COLÓN'], // 1487
            ['nombrexx' => 'LA PRADERA'], // 1488
            ['nombrexx' => 'LA TRINIDAD'], // 1489
            ['nombrexx' => 'EL ARPAY LA LIRA'], // 1490
            ['nombrexx' => 'SAN RAFAEL'], // 1491
            ['nombrexx' => 'SAN RAFAEL INDUSTRIAL'], // 1492
            ['nombrexx' => 'SALAZAR GOMEZ'], // 1493
            ['nombrexx' => 'CUNDINAMARCA'], // 1494
            ['nombrexx' => 'EL EJIDO'], // 1495
            ['nombrexx' => 'GORGONZOLA'], // 1496
            ['nombrexx' => 'INDUSTRIAL CENTENARIO'], // 1497
            ['nombrexx' => 'LA FLORIDA OCCIDENTAL'], // 1498
            ['nombrexx' => 'LOS EJIDOS'], // 1499
            ['nombrexx' => 'PENSILVANIA'], // 1500
            ['nombrexx' => 'BATALLÓN CALDAS'], // 1501
            ['nombrexx' => 'CENTRO INDUSTRIAL'], // 1502
            ['nombrexx' => 'PUENTE ARANDA'], // 1503
            ['nombrexx' => 'LA CATEDRAL'], // 1504
            ['nombrexx' => 'LAS AGUAS'], // 1505
            ['nombrexx' => 'CENTRO ADMINISTRATIVO'], // 1506
            ['nombrexx' => 'EGIPTO'], // 1507
            ['nombrexx' => 'NUEVA SANTA FE Y SANTA BÁRBARA'], // 1508
            ['nombrexx' => 'BOSQUE DE SAN CARLOS'], // 1509
            ['nombrexx' => 'COUNTRY SUR'], // 1510
            ['nombrexx' => 'GUSTAVO RESTREPO'], // 1511
            ['nombrexx' => 'PIJAOS'], // 1512
            ['nombrexx' => 'SAN JOSÉ SUR'], // 1513
            ['nombrexx' => 'SAN LUIS SUR'], // 1514
            ['nombrexx' => 'SOSIEGO SUR'], // 1515
            ['nombrexx' => 'CLARET'], // 1516
            ['nombrexx' => 'BRAVO PÁEZ'], // 1517
            ['nombrexx' => 'MATATIGRES'], // 1518
            ['nombrexx' => 'MURILLO TORO'], // 1519
            ['nombrexx' => 'OLAYA'], // 1520
            ['nombrexx' => 'QUIROGA'], // 1521
            ['nombrexx' => 'SANTIAGO PÉREZ'], // 1522
            ['nombrexx' => 'EL INGLÉS'], // 1523
            ['nombrexx' => 'VILLA MAYOR OCCIDENTAL'], // 1524
            ['nombrexx' => 'COLINAS'], // 1525
            ['nombrexx' => 'EL PESEBRE'], // 1526
            ['nombrexx' => 'GRANJAS DE SAN PABLO'], // 1527
            ['nombrexx' => 'GRANJAS DE SANTA SOFÍA'], // 1528
            ['nombrexx' => 'JORGE CAVELIER LA RESURECCIÓN'], // 1529
            ['nombrexx' => 'LAS LOMAS'], // 1530
            ['nombrexx' => 'LUIS LÓPEZ DE MESA'], // 1531
            ['nombrexx' => 'MARCO FIDEL SUÁREZ'], // 1532
            ['nombrexx' => 'RÍO DE JANEIRO'], // 1533
            ['nombrexx' => 'ARBOLEDA SUR'], // 1534
            ['nombrexx' => 'CALLEJÓN SANTA BÁRBARA'], // 1535
            ['nombrexx' => 'CERROS DE ORIENTE'], // 1536
            ['nombrexx' => 'CHIRCALES'], // 1537
            ['nombrexx' => 'DANUBIO SUR'], // 1538
            ['nombrexx' => 'EL ROSAL'], // 1539
            ['nombrexx' => 'EL SOCORRO'], // 1540
            ['nombrexx' => 'GAVAROBA'], // 1541
            ['nombrexx' => 'GUIPARMA'], // 1542
            ['nombrexx' => 'LA MERCED DEL SUR'], // 1543
            ['nombrexx' => 'LA PICOTA OCCIDENTAL'], // 1544
            ['nombrexx' => 'MARRUECOS'], // 1545
            ['nombrexx' => 'MIRADOR DEL SUR'], // 1546
            ['nombrexx' => 'MOLINOS'], // 1547
            ['nombrexx' => 'NUEVA PENSILVANIA SUR'], // 1548
            ['nombrexx' => 'PRADERA SUR'], // 1549
            ['nombrexx' => 'PUERTO RICO'], // 1550
            ['nombrexx' => 'SARASOTA'], // 1551
            ['nombrexx' => 'VILLA MORALES'], // 1552
            ['nombrexx' => 'SAN AGUSTÍN'], // 1553
            ['nombrexx' => 'DIANA TURBAY'], // 1554
            ['nombrexx' => 'LA ESPERANZA ALTA'], // 1555
            ['nombrexx' => 'LA PICOTA ORIENTAL'], // 1556
            ['nombrexx' => 'PALERMO SUR'], // 1557
            ['nombrexx' => 'LA LIRA'], // 1558
            ['nombrexx' => 'VILLA JACKY'], // 1559
            ['nombrexx' => 'LAS MANAS'], // 1560
            ['nombrexx' => 'MOCHUELO ORIENTAL'], // 1561
            ['nombrexx' => 'EL MOCHUELO II'], // 1562
            ['nombrexx' => 'BRAZUELOS DE SANTO DOMINGO'], // 1563
            ['nombrexx' => 'ESMERALDA'], // 1564
            ['nombrexx' => 'LAGUNITAS'], // 1565
            ['nombrexx' => 'PATICOS'], // 1566
            ['nombrexx' => 'BARRANQUITOS'], // 1567
            ['nombrexx' => 'ARBORIZADORA BAJA'], // 1568
            ['nombrexx' => 'ATLANTA'], // 1569
            ['nombrexx' => 'MADELENA'], // 1570
            ['nombrexx' => 'RAFAEL ESCAMILLA'], // 1571
            ['nombrexx' => 'SANTA ROSA SUR'], // 1572
            ['nombrexx' => 'VILLA HELENA'], // 1573
            ['nombrexx' => 'CASA LINDA'], // 1574
            ['nombrexx' => 'PROTECHO'], // 1575
            ['nombrexx' => 'CANDELARIA LA NUEVA'], // 1576
            ['nombrexx' => 'COLMENA'], // 1577
            ['nombrexx' => 'LA CASONA'], // 1578
            ['nombrexx' => 'SAN FERNANDO SUR'], // 1579
            ['nombrexx' => 'SANTA INÉS DE LA ACACIA'], // 1580
            ['nombrexx' => 'MILLAN LOS SAUCES'], // 1581
            ['nombrexx' => 'PUERTA DEL LLANO'], // 1582
            ['nombrexx' => 'HORTALIZAS'], // 1583
            ['nombrexx' => 'ÁLVARO BERNAL SEGURA'], // 1584
            ['nombrexx' => 'LUCERO ALTO'], // 1585
            ['nombrexx' => 'LUCERO MEDIO'], // 1586
            ['nombrexx' => 'LUCERO BAJO'], // 1587
            ['nombrexx' => 'DOMINGO LAÍN'], // 1588
            ['nombrexx' => 'EL PARAÍSO MIRADOR'], // 1589
            ['nombrexx' => 'BELLA FLOR'], // 1590
            ['nombrexx' => 'LA TORRE'], // 1591
            ['nombrexx' => 'ESTRELLA DEL SUR'], // 1592
            ['nombrexx' => 'GIBRALTAR SUR'], // 1593
            ['nombrexx' => 'JUAN PABLO II'], // 1594
            ['nombrexx' => 'LA ESCALA'], // 1595
            ['nombrexx' => 'LAS MANITAS'], // 1596
            ['nombrexx' => 'EL SATÉLITE'], // 1597
            ['nombrexx' => 'LOS ANDES DE NUTIBARA'], // 1598
            ['nombrexx' => 'LA ESTRELLA DE LAGOS'], // 1599
            ['nombrexx' => 'CIUDAD MILAGROS'], // 1600
            ['nombrexx' => 'MEISSEN'], // 1601
            ['nombrexx' => 'BRISAS DEL VOLADOR'], // 1602
            ['nombrexx' => 'MÉXICO'], // 1603
            ['nombrexx' => 'NUEVA COLOMBIA'], // 1604
            ['nombrexx' => 'NACIONES UNIDAS'], // 1605
            ['nombrexx' => 'RINCÓN DEL DIAMANTE VILLA GLORIA'], // 1606
            ['nombrexx' => 'BOGOTÁ SUR'], // 1607
            ['nombrexx' => 'DIVINO NIÑO'], // 1608
            ['nombrexx' => 'CASA DE TEJA'], // 1609
            ['nombrexx' => 'EL TESORO'], // 1610
            ['nombrexx' => 'TESORITO'], // 1611
            ['nombrexx' => 'EL MOCHUELO I'], // 1612
            ['nombrexx' => 'EL REFLEJO'], // 1613
            ['nombrexx' => 'LA CUMBRE'], // 1614
            ['nombrexx' => 'LOS DUQUES'], // 1615
            ['nombrexx' => 'INÉS ELVIRA'], // 1616
            ['nombrexx' => 'MONTEREY'], // 1617
            ['nombrexx' => 'MINUTO DE MARÍA'], // 1618
            ['nombrexx' => 'OCHO DE DICIEMBRE'], // 1619
            ['nombrexx' => 'QUIBA'], // 1620
            ['nombrexx' => 'REPÚBLICA DE CANADÁ'], // 1621
            ['nombrexx' => 'SAN RAFAEL SUR'], // 1622
            ['nombrexx' => 'SAN JOAQUÍN DEL VATICANO'], // 1623
            ['nombrexx' => 'SOTAVENTO'], // 1624
            ['nombrexx' => 'VILLA DIANA LÓPEZ'], // 1625
            ['nombrexx' => 'BELLA ESTANCIA'], // 1626
            ['nombrexx' => 'BARLOVENTO'], // 1627
            ['nombrexx' => 'CARACOLÍ'], // 1628
            ['nombrexx' => 'BONANZA SUR'], // 1629
            ['nombrexx' => 'CASA LOMA CASAVIANCA'], // 1630
            ['nombrexx' => 'CERRO DEL DIAMANTE'], // 1631
            ['nombrexx' => 'ISMAEL PERDOMO'], // 1632
            ['nombrexx' => 'EL RINCÓN DEL PORVENIR'], // 1633
            ['nombrexx' => 'GALICIA'], // 1634
            ['nombrexx' => 'LA CARBONERA'], // 1635
            ['nombrexx' => 'MIRADOR DE LA ESTANCIA'], // 1636
            ['nombrexx' => 'MIRADOR DE PRIMAVERA'], // 1637
            ['nombrexx' => 'PERDOMO ALTO'], // 1638
            ['nombrexx' => 'RINCÓN DE GALICIA'], // 1639
            ['nombrexx' => 'RINCÓN DE LA ESTANCIA'], // 1640
            ['nombrexx' => 'RINCÓN DE LA VALVANERA'], // 1641
            ['nombrexx' => 'SAN ANTONIO DEL MIRADOR'], // 1642
            ['nombrexx' => 'MARÍA CANO'], // 1643
            ['nombrexx' => 'SAN RAFAEL DE LA ESTANCIA'], // 1644
            ['nombrexx' => 'SANTA VIVIANA'], // 1645
            ['nombrexx' => 'ARBORIZADORA ALTA'], // 1646
            ['nombrexx' => 'BELLA VISTA'], // 1647
            ['nombrexx' => 'FLORIDA DEL SUR'], // 1648
            ['nombrexx' => 'JERUSALÉN'], // 1649
            ['nombrexx' => 'LAS VEGAS DE POTOSÍ'], // 1650
            ['nombrexx' => 'VILLAS DE BOLÍVAR'], // 1651
            ['nombrexx' => 'BARRIO INCORRECTO EN LA BASE PLANA'], // 1652
            ['nombrexx' => 'N/A'], // 1653
            ['nombrexx' => 'BRISAS DEL TINTAL'], // 1654
            ['nombrexx' => 'BARRIO NO IDENTIFICADO EN EL NUEVO DESARROLLO'], // 1655
            ['nombrexx' => 'DISTRITAL'], // 1656
            ['nombrexx' => 'SOACHA'],//1657
        ];
        $this->getR($dataxxxx);
    }
}
