INSERT IGNORE INTO `sis_fos_sub_tipo_seguimientos` (`id`, `area_id`, `seg_id`, `codigo`, `nombre`, `descripcion`, `activo`, `user_crea_id`, `user_edita_id`, `created_at`, `updated_at`) VALUES
	(1, 1, 1, 'AMAI', 'INICIAL', '0', 0, 1, 1, NULL, NULL),
	(2, 1, 2, 'CD48', 'ACADÉMICOS Y ADMINISTRATIVOS', '0', 1, 1, 1, NULL, NULL),
	(3, 1, 3, 'ASN6', 'ASPECTOS A NIVELAR', 'Este multivalor lo usan los docentes para registrar el diagnóstico realizado a los beneficiarios al ingresar a los procesos académicos, respecto a las nivelaciones a realizar luego del diagnóstico académico.', 1, 1, 1, NULL, NULL),
	(4, 1, 3, 'PRES', 'PRESABERES', '0', 0, 1, 1, NULL, NULL),
	(5, 1, 4, 'APCO', 'APRENDER A CONOCER', '0', 0, 1, 1, NULL, NULL),
	(6, 1, 4, 'APHA', 'APRENDER A HACER', '0', 0, 1, 1, NULL, NULL),
	(7, 1, 4, 'APSR', 'APRENDER A SER', '0', 0, 1, 1, NULL, NULL),
	(8, 1, 4, 'APVJ', 'APRENDER A VIVIR JUNTOS', '0', 0, 1, 1, NULL, NULL),
	(9, 1, 5, 'BA19', 'MODELO PEDAGÓGICO-FORMACIÓN TÉCNICA', 'Se crea este criterio de cargue para poder evidenciar el proceso de acogida e inducción de los AJ a los Programas de Formación para el Trabajo y el desarrollo Huamano, en procesos de ingreso inferiores o igual a 20 AJ', 1, 1, 1, NULL, NULL),
	(10, 1, 6, 'MS1', 'MODULO 1 SESIÓN 1', 'Este parámetro permite evidenciar novedades durante esta actividad, la cual hace parte de los Módulos de competencias transversales, proceso introductorio de convenios de formación técnica. Adicionalmente permite evidenciar el inicio de los módulos de competenciar transversales por parte de beneficiario.', 1, 1, 1, NULL, NULL),
	(11, 1, 6, 'MS2', 'MODULO 1 SESIÓN 2', 'Este parámetro permite evidenciar novedades durante esta actividad, la cual hace parte de los Módulos de competencias transversales, proceso introductorio de convenios de formación técnica.', 1, 1, 1, NULL, NULL),
	(12, 1, 6, 'M1S3', 'MODULO 1 SESIÓN 3', '0', 0, 1, 1, NULL, NULL),
	(13, 1, 6, 'M1S4', 'MODULO 1 SESIÓN 4', '0', 0, 1, 1, NULL, NULL),
	(14, 1, 6, 'M2S1', 'MODULO 2 SESIÓN 1', 'Este parámetro permite evidenciar novedades durante esta actividad, la cual hace parte de los Módulos de competencias transversales, proceso introductorio de convenios de formación técnica.', 1, 1, 1, NULL, NULL),
	(15, 1, 6, 'M2S2', 'MODULO 2 SESIÓN 2', 'Este parámetro permite evidenciar novedades durante esta actividad, la cual hace parte de los Módulos de competencias transversales, proceso introductorio de convenios de formación técnica.', 1, 1, 1, NULL, NULL),
	(16, 1, 6, 'M2S3', 'MODULO 2 SESIÓN 3', '0', 0, 1, 1, NULL, NULL),
	(17, 1, 6, 'M2S4', 'MODULO 2 SESIÓN 4', '0', 0, 1, 1, NULL, NULL),
	(18, 1, 6, 'M2S6', 'MODULO 3 SESIÓN 1', 'Este parámetro permite evidenciar novedades durante esta actividad, la cual hace parte de los Módulos de competencias transversales, proceso introductorio de convenios de formación técnica.', 1, 1, 1, NULL, NULL),
	(19, 1, 6, 'M3S2', 'MODULO 3 SESIÓN 2', 'Este parámetro permite evidenciar novedades durante esta actividad, la cual hace parte de los Módulos de competencias transversales, proceso introductorio de convenios de formación técnica.', 1, 1, 1, NULL, NULL),
	(20, 1, 6, 'M3S3', 'MODULO 3 SESIÓN 3', '0', 0, 1, 1, NULL, NULL),
	(21, 1, 6, 'M3S4', 'MODULO 3 SESIÓN 4', '0', 0, 1, 1, NULL, NULL),
	(22, 1, 6, 'M4S2', 'MODULO 4 EMPREND SESIÓN 2', 'Este parámetro permite evidenciar novedades durante esta actividad, la cual hace parte de los Módulos de competencias transversales, proceso introductorio de convenios de formación técnica. Adicionalmente permite evidenciar la culminación de los módulos de competencias transversales por parte de beneficiario.', 1, 1, 1, NULL, NULL),
	(23, 1, 6, 'M4S3', 'MODULO 4 EMPREND SESIÓN 3', '0', 0, 1, 1, NULL, NULL),
	(24, 1, 6, 'MAS4', 'MODULO 4 EMPREND SESIÓN 4', '0', 0, 1, 1, NULL, NULL),
	(25, 1, 6, 'M4S1', 'MODULO 4 EMPRENDE SESIÓN 1', 'Este parámetro permite evidenciar novedades durante esta actividad, la cual hace parte de los Módulos de competencias transversales, proceso introductorio de convenios de formación técnica.', 1, 1, 1, NULL, NULL),
	(26, 1, 6, 'BA15', 'MODULO 4 EMPRENDER SESIÓN 3', '0', 0, 1, 1, NULL, NULL),
	(27, 1, 6, 'BA16', 'MODULO 4 EMPRENDER SESIÓN 4', '0', 0, 1, 1, NULL, NULL),
	(28, 1, 6, 'PDE', 'PRUEBA DE ENTRADA', 'Este parámetro permite identificar la autoevaluaión del joven es sus diferentes áreas personales despues de culminar los Módulos de competencias transversales.', 1, 1, 1, NULL, NULL),
	(29, 1, 6, 'PDS', 'PRUEBA DE SALIDA', 'Este parámetro permite identificar la autoevaluaión del joven es sus diferentes áreas personales antes de iniciar los Módulos de competencias transversales.', 1, 1, 1, NULL, NULL),
	(30, 1, 7, 'AN56', 'ACADÉMICA', 'Este multivalor lo usan los docentes para registrar las atenciones brindadas a los beneficiarios cuando solicitan alguna nivelación académica extra.', 1, 1, 1, NULL, NULL),
	(31, 1, 8, 'RA47', 'ACADÉMICO', 'Este multivalor lo usan los docentes para registrar las atenciones brindadas a los beneficiarios cuando solicitan alguna nivelación académica extra.', 1, 1, 1, NULL, NULL),
	(32, 1, 9, 'RG58', 'COMISION EVALUACION Y PROMOC', '0', 0, 1, 1, NULL, NULL),
	(33, 1, 10, 'RG58', 'GRADO 10', '0', 0, 1, 1, NULL, NULL),
	(34, 1, 10, 'RG60', 'GRADO 11', '0', 0, 1, 1, NULL, NULL),
	(35, 1, 10, 'ROG5', 'GRADO 5', '0', 0, 1, 1, NULL, NULL),
	(36, 1, 10, 'ROG6', 'GRADO 6', '0', 0, 1, 1, NULL, NULL),
	(37, 1, 10, 'ROG7', 'GRADO 7', '0', 0, 1, 1, NULL, NULL),
	(38, 1, 10, 'ROG8', 'GRADO 8', '0', 0, 1, 1, NULL, NULL),
	(39, 1, 10, 'ROG9', 'GRADO 9', '0', 0, 1, 1, NULL, NULL),
	(40, 1, 11, 'RO65', 'GRADO 10', '0', 0, 1, 1, NULL, NULL),
	(41, 1, 11, 'RO66', 'GRADO 11', '0', 0, 1, 1, NULL, NULL),
	(42, 1, 11, 'RO67', 'GRADO 5', '0', 0, 1, 1, NULL, NULL),
	(43, 1, 11, 'RO68', 'GRADO 6', '0', 0, 1, 1, NULL, NULL),
	(44, 1, 11, 'RO69', 'GRADO 7', '0', 0, 1, 1, NULL, NULL),
	(45, 1, 11, 'RO70', 'GRADO 8', '0', 0, 1, 1, NULL, NULL),
	(46, 1, 11, 'RO71', 'GRADO 9', '0', 0, 1, 1, NULL, NULL),
	(47, 1, 12, 'SS72', 'A SITUACIONES CONVIVEN O COMPORTAM', 'Este multivalor se usa para que los docentes y apoyos académicos registren las situaciones de tipo convivencial que tenga lugar dentro de los espacios académicos.', 1, 1, 1, NULL, NULL),
	(48, 1, 12, 'SSC', 'A SITUACIONES CONVIVEN. O COMPORTAME.', '0', 0, 1, 1, NULL, NULL),
	(49, 1, 12, 'SSP', 'A SITUACIONES PEDAGOGICAS', '0', 0, 1, 1, NULL, NULL),
	(50, 1, 12, 'FSTS', 'A TERRITORIO Y/O SEDE', 'Este parámetro se utiliza para evidenciar novedades de seguimiento en los diferentes centros de formación, se solicita cambio de nombre a FT/SEGUIMIENTO EN CENTRO DE FORMACIÓN dicho nombre permite mayor claridad.', 1, 1, 1, NULL, NULL),
	(51, 1, 12, 'BA20', 'ASISTENCIA', 'Se crea este criterio de cargue para evidenciar la asistencia de los AJ a los Programas de Formación para el Trabajo y el desarrollo Huamano.', 1, 1, 1, NULL, NULL),
	(52, 1, 12, '0008', 'PRÁCTICA PRODUCTIVA', '0', 0, 1, 1, NULL, NULL),
	(53, 1, 12, 'BA21', 'RECONOCIMIENTO', 'Se crea este criterio de cargue para evidenciar el proceso exitoso desde las competencias desarrolladas por el AJ en los Programas de Formación para el Trabajo y el desarrollo Humano.', 1, 1, 1, NULL, NULL),
	(54, 1, 12, 'SVYO', 'VOCACIONAL Y OCUPACIONAL', 'Este multivalor se usa para que los docentes y apoyos académicos registren las situaciones de tipo convivencial que tenga lugar dentro de los espacios académicos.', 1, 1, 1, NULL, NULL),
	(55, 1, 13, 'AX75', 'ARGUMENTA TEXTOS/COMUNIC/ORAL Y ESCR', '0', 0, 1, 1, NULL, NULL),
	(56, 1, 13, 'AXCE', 'ARGUMENTA TEXTOS/COMUNIC/ORAL Y ESCRI', '0', 0, 1, 1, NULL, NULL),
	(57, 1, 13, 'LN76', 'LENGU. NO VERBAL/DESARRO/PROCE/COMUN', '0', 0, 1, 1, NULL, NULL),
	(58, 1, 13, 'LNVP', 'LENGU. NO VERBAL/DESARRO/PROCE/COMUNI', '0', 0, 1, 1, NULL, NULL),
	(59, 1, 13, 'LCCN', 'LENGUAJE PARA CONSTRUÍR CONOCIMIENTO', '0', 0, 1, 1, NULL, NULL),
	(60, 1, 13, 'UE78', 'UTILIZA ESTRATEGIAS DESCRIP. Y ANALO', '0', 0, 1, 1, NULL, NULL),
	(61, 1, 13, 'UEDA', 'UTILIZA ESTRATEGIAS DESCRIP. Y ANALOG', '0', 0, 1, 1, NULL, NULL),
	(62, 1, 14, 'IO24', 'IDENTIFICA/OBRA LITERARIA/CARACTERÍ', '0', 0, 1, 1, NULL, NULL),
	(63, 1, 14, 'IOLC', 'IDENTIFICA/OBRAS LITERARIAS/CARACTERÍS', '0', 0, 1, 1, NULL, NULL),
	(64, 1, 15, 'CNTX', 'CREA Y NARRA TEXTOS', '0', 0, 1, 1, NULL, NULL),
	(65, 1, 15, 'DCRT', 'DEFINE LAS CARCATERÍSTICAS DEL TEXTO', '0', 0, 1, 1, NULL, NULL),
	(66, 1, 15, 'ECPV', 'ELABORA CUENTOS/ RTA/PROPIA VIVENCIA', '0', 0, 1, 1, NULL, NULL),
	(67, 1, 15, 'ESPL', 'ESCRIBE Y SEPARA CORRECTA. PALABRAS', '0', 0, 1, 1, NULL, NULL),
	(68, 1, 15, 'PTOE', 'PRODUCE TEXTOS ORALES/ESCRITOS', '0', 0, 1, 1, NULL, NULL),
	(69, 1, 15, 'EL84', 'REAL. LECTURA ORAL ACORDE CON LA ENTO', '0', 0, 1, 1, NULL, NULL),
	(70, 1, 15, 'ELOE', 'REAL. LECTURA ORAL ACORDE CON LA ENTON', '0', 0, 1, 1, NULL, NULL),
	(71, 1, 16, 'ATOE', 'ARGUMENTA TEXTOS ORALES Y ESCRITOS', '0', 0, 1, 1, NULL, NULL),
	(72, 1, 16, 'CA90', 'CONSTRUYE ADECUAD. TEXTOS ORALES Y ESC', '0', 0, 1, 1, NULL, NULL),
	(73, 1, 16, 'CATE', 'CONSTRUYE ADECUAD.TEXTOS ORALES Y ESC', '0', 0, 1, 1, NULL, NULL),
	(74, 1, 16, 'CAOE', 'CONSTRUYE/ARGUMENTA/TEXTO ORAL Y ESC.', '0', 0, 1, 1, NULL, NULL),
	(75, 1, 16, 'ESCR', 'ESCRIBE', '0', 0, 1, 1, NULL, NULL),
	(76, 1, 16, 'LEAD', 'LEE ADECUADAMENTE', '0', 0, 1, 1, NULL, NULL),
	(77, 1, 17, 'CAIF', 'CLASIFICA Y ALMACENA INFORMACIÓN', '0', 0, 1, 1, NULL, NULL),
	(78, 1, 17, 'ELNV', 'EMPLEA LENGUAJE NO VERBAL', '0', 0, 1, 1, NULL, NULL),
	(79, 1, 17, 'TEXT', 'PROD. TEXTOS ESCRI/ESTABLECE NEXOS INT', '0', 0, 1, 1, NULL, NULL),
	(80, 1, 18, 'CARI', 'CAPACIDAD ARGUMENTATIVA/INTERPRETATIVA', '0', 0, 1, 1, NULL, NULL),
	(81, 1, 18, 'CTAC', 'COMPRENDE/INTERPRETA TEXTOS/ACTI. CRÍT', '0', 0, 1, 1, NULL, NULL),
	(82, 1, 18, 'DT19', 'DISTINGUE ELEM. TEXTO/OBRAS LATINOA', '0', 0, 1, 1, NULL, NULL),
	(83, 1, 18, 'DTOL', 'DISTINGUE ELEM. TEXTOS/OBRAS LATINOAM.', '0', 0, 1, 1, NULL, NULL),
	(84, 1, 18, 'ES21', 'ENFATIZA SIGN/SIMB/REGL/COMUNICACI.', '0', 0, 1, 1, NULL, NULL),
	(85, 1, 18, 'ESMR', 'ENFATIZA SIGN/SIMB/REGL/COMUNICACION', '0', 0, 1, 1, NULL, NULL),
	(86, 1, 18, 'SI39', 'SELECCI/INFORM/MEDIOS COMUNIC/MASIV', '0', 0, 1, 1, NULL, NULL),
	(87, 1, 18, 'SIMM', 'SELECIONA/INFORM/MEDIOS COMUNIC/MASIVO', '0', 0, 1, 1, NULL, NULL),
	(88, 1, 19, 'RD27', 'REPRESENTACI.DECIMAL/ENTE/RACI E I', '0', 0, 1, 1, NULL, NULL),
	(89, 1, 19, 'RDRI', 'REPRESENTACIÓN DECIMAL/ENTE/RACI E IR', '0', 0, 1, 1, NULL, NULL),
	(90, 1, 20, 'CI11', 'COMPARA E IDENTIFICA NÚME. REALES', '0', 0, 1, 1, NULL, NULL),
	(91, 1, 20, 'CINR', 'COMPARA E IDENTIFICA NÚMEROS REALES', '0', 0, 1, 1, NULL, NULL),
	(92, 1, 20, 'CT13', 'CONSTRUYE TABULAD/FUNCIONES REALES', '0', 0, 1, 1, NULL, NULL),
	(93, 1, 20, 'CTFR', 'CONSTRUYE TABULADOS/FUNCIONES REALES', '0', 0, 1, 1, NULL, NULL),
	(94, 1, 20, 'CTHL', 'CONSTRUYE TABULADOS/HALLAR LÍMITES', '0', 0, 1, 1, NULL, NULL),
	(95, 1, 20, 'DP18', 'DIFERENCIA PROPIE, RELACION Y OPER', '0', 0, 1, 1, NULL, NULL),
	(96, 1, 20, 'DPRP', 'DIFERENCIA PROPIE, RELACIONES Y OPERA', '0', 0, 1, 1, NULL, NULL),
	(97, 1, 20, 'DE16', 'DISEÑA EXPERIMENT/FISI/CIEN/SOCIAL', '0', 0, 1, 1, NULL, NULL),
	(98, 1, 20, 'DEFS', 'DISEÑA EXPERIMENTO/FISI/CIEN/SOCIAL.', '0', 0, 1, 1, NULL, NULL),
	(99, 1, 20, 'IFPO', 'IDENTIFICA FUNCIONES POLINÓMICAS', '0', 0, 1, 1, NULL, NULL),
	(100, 1, 20, 'ID22', 'INTERPRETA DERIVADA/CAMBIO MATEM', '0', 0, 1, 1, NULL, NULL),
	(101, 1, 20, 'IDCM', 'INTERPRETA LA DERIVADA/CAMBIO MATEMA', '0', 0, 1, 1, NULL, NULL),
	(102, 1, 20, 'MD25', 'MEDIDA DESCENTRAL/DISPERSI Y COREL', '0', 0, 1, 1, NULL, NULL),
	(103, 1, 20, 'MDDC', 'MEDIDAS DE DESCENTRA/DISPERSI Y COREL', '0', 0, 1, 1, NULL, NULL),
	(104, 1, 20, 'RP35', 'RELACIONO PROPIEDA./FIGEO/CONICAS', '0', 0, 1, 1, NULL, NULL),
	(105, 1, 20, 'RPFC', 'RELACIONO PROPIEDADES/FIGEO/CONICAS', '0', 0, 1, 1, NULL, NULL),
	(106, 1, 20, 'RP33', 'RESUELVE PROBLEM/APLICACIÓN DERIVA', '0', 0, 1, 1, NULL, NULL),
	(107, 1, 20, 'RP34', 'RESUELVE PROBLEMA DE CONTEO/PROBABL', '0', 0, 1, 1, NULL, NULL),
	(108, 1, 20, 'RPCP', 'RESUELVE PROBLEMAS DE CONTEO/PROBABIL', '0', 0, 1, 1, NULL, NULL),
	(109, 1, 20, 'RPAD', 'RESUELVE PROBLEMAS/APLICACIÓN DERIVAD', '0', 0, 1, 1, NULL, NULL),
	(110, 1, 21, 'ATF7', 'APLICA TRANSFORMACION./FIGURAS PLAN', '0', 0, 1, 1, NULL, NULL),
	(111, 1, 21, 'ATFP', 'APLICA TRANSFORMACIONES/FIGURAS PLANO', '0', 0, 1, 1, NULL, NULL),
	(112, 1, 21, 'ADO1', 'APLICA/DESARROLLA/OPERACION BASICA', '0', 0, 1, 1, NULL, NULL),
	(113, 1, 21, 'ADOB', 'APLICA/DESARROLLA/OPERATIVIDAD BASICA', '0', 0, 1, 1, NULL, NULL),
	(114, 1, 21, 'RRNU', 'RECONOCE/REPRESENTACION/NUMEROS', '0', 0, 1, 1, NULL, NULL),
	(115, 1, 21, 'RP36', 'RESUELVE PROBLE/OPERACIÓNES BASICAS', '0', 0, 1, 1, NULL, NULL),
	(116, 1, 21, 'RPOB', 'RESUELVE PROBLEMAS/OPERACIÓNES BASICAS', '0', 0, 1, 1, NULL, NULL),
	(117, 1, 22, 'CAV9', 'CALCULA ÁREAS/VOLÚMENES/FIG. PLANAS', '0', 0, 1, 1, NULL, NULL),
	(118, 1, 22, 'CAVF', 'CALCULA ÁREAS/VOLÚMENES/FIGURAS PLANAS', '0', 0, 1, 1, NULL, NULL),
	(119, 1, 22, 'RF29', 'RESUELVE/FORMULA PROBLEM/NUM Y OPER', '0', 0, 1, 1, NULL, NULL),
	(120, 1, 22, 'RFPO', 'RESUELVE/FORMULA PROBLEMAS/NUM Y OPER', '0', 0, 1, 1, NULL, NULL),
	(121, 1, 22, 'UN41', 'UTILIZA REPRESE/FRACCION Y DECIMAL', '0', 0, 1, 1, NULL, NULL),
	(122, 1, 22, 'UNFD', 'UTILIZA REPRESE/FRACCIONES Y DECIMALES', '0', 0, 1, 1, NULL, NULL),
	(123, 1, 23, 'CLPO', 'CLASIFICA POLÍGONOS', '0', 0, 1, 1, NULL, NULL),
	(124, 1, 23, 'DESO', 'DESCOMPONE SÓLIDOS', '0', 0, 1, 1, NULL, NULL),
	(125, 1, 23, 'EO20', 'EXPLICA OPERACION DIFERENT MANERAS', '0', 0, 1, 1, NULL, NULL),
	(126, 1, 23, 'EODM', 'EXPLICA OPERACION DIFERENTES MANERAS', '0', 0, 1, 1, NULL, NULL),
	(127, 1, 23, 'RS38', 'REPRESE SITUACIONES/VARIAC/DIAGRAMA', '0', 0, 1, 1, NULL, NULL),
	(128, 1, 23, 'RSVD', 'REPRSENTA SITUACIONES/VARIAC/DIAGRAMAS', '0', 0, 1, 1, NULL, NULL),
	(129, 1, 23, 'UR42', 'UTILIZA RADICACIÓN Y POTENCIALIZA.', '0', 0, 1, 1, NULL, NULL),
	(130, 1, 23, 'URPO', 'UTILIZA RADICACIÓN Y POTENCIALIZACIÓN', '0', 0, 1, 1, NULL, NULL),
	(131, 1, 24, 'RG30', 'REPRESE GRÁFICA/ FL/CUADRA/CÚBICAS.', '0', 0, 1, 1, NULL, NULL),
	(132, 1, 24, 'RG31', 'REPRESE GRÁFICA/ POLINÓM/EXPONENCI.', '0', 0, 1, 1, NULL, NULL),
	(133, 1, 24, 'RGCC', 'REPRESENTA GRÁFICA/ FL/CUADRA/CÚBICAS.', '0', 0, 1, 1, NULL, NULL),
	(134, 1, 24, 'RGPE', 'REPRESENTA GRÁFICA/ POLINÓM/EXPONENCI.', '0', 0, 1, 1, NULL, NULL),
	(135, 1, 24, 'RF28', 'RESUEL/FORMULA PROBLE/CONGRUE/SEMEJ', '0', 0, 1, 1, NULL, NULL),
	(136, 1, 24, 'RFCS', 'RESUELVE/FORMULA PROBLE/CONGRUE/SEMEJ', '0', 0, 1, 1, NULL, NULL),
	(137, 1, 24, 'SJRT', 'SIEMPRE JUSTIFICA SUS RESPUESTAS', '0', 0, 1, 1, NULL, NULL),
	(138, 1, 25, 'CT15', 'COMPRENDE TEOREMA/T MILETO Y DE PIT', '0', 0, 1, 1, NULL, NULL),
	(139, 1, 25, 'CTMP', 'COMPRENDE TEOREMAS/T. MILETO Y DE PITA', '0', 0, 1, 1, NULL, NULL),
	(140, 1, 25, 'CC10', 'CONCEP. Y APLICA/CIRCUN/ESFER/PERÍM', '0', 0, 1, 1, NULL, NULL),
	(141, 1, 25, 'CCEP', 'CONCEPTOS Y APLICA/CIRCUN/ESFER/PERÍME', '0', 0, 1, 1, NULL, NULL),
	(142, 1, 25, 'RO32', 'REALIZA OPERACIO/ NUME. IRRACIONALE', '0', 0, 1, 1, NULL, NULL),
	(143, 1, 25, 'RONI', 'REALIZA OPERACIO/ NÚMEROS IRRACIONALES', '0', 0, 1, 1, NULL, NULL),
	(144, 1, 25, 'RARG', 'RELACIONES ALGEBRAICAS/REPRESEN. GRÁFI', '0', 0, 1, 1, NULL, NULL),
	(145, 1, 26, 'BA22', 'MUSICAL INGRESO', '0', 1, 1, 1, NULL, NULL),
	(146, 1, 26, 'BA23', 'MUSICAL MODULAR', '0', 1, 1, 1, NULL, NULL),
	(147, 1, 26, 'AC09', 'TERAPIA OCUPACIONAL AREA TECNICA', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(148, 2, 62, 'AC09', 'A ACTIVIDADES EMPRENDER', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(149, 2, 62, 'AC09', 'NO POBLACION IDIPRON', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(150, 2, 62, 'AC09', 'INICIAL', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(151, 2, 62, 'AC09', 'EMPLEABILIDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(152, 2, 62, 'AC09', 'EMPRENDIMIENTO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(153, 2, 62, 'AC09', 'DE EMPLEABILIDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(154, 2, 62, 'AC09', 'EMPLEABILIDAD CIERRE SATISFACTOR', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(155, 2, 62, 'AC09', 'EMPLEABILIDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(156, 2, 62, 'AC09', 'EMPRENDER', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(157, 2, 62, 'AC09', 'EMPLEABILIDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(158, 2, 62, 'AC09', 'EMPRENDIMIENTO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(159, 2, 62, 'AC09', 'EN EMPRENDIMIENTO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(160, 2, 62, 'AC09', 'EMPLEABILIDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(161, 2, 62, 'AC09', 'EMPRENDER', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(162, 2, 62, 'AC09', 'FASE ANÁLISIS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(163, 2, 62, 'AC09', 'FASE EJECUCIÓN', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(164, 2, 62, 'AC09', 'FASE PLANEACIÓN', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(165, 2, 62, 'AC09', 'FASE SEGUIMIENTO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(166, 2, 62, 'AC09', 'GRADO 10', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(167, 2, 62, 'AC09', 'EMPLEABILIDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(168, 2, 62, 'AC09', 'EN EMPRENDIMIENTO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(169, 3, 26, 'AC09', 'DECESO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(170, 3, 26, 'AC09', 'DESERCIÓN', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(171, 3, 41, 'AC09', 'PEDAGÓGICA', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(172, 3, 42, 'AC09', 'EN CAMPO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(173, 3, 43, 'AC09', 'FAMILIAR', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(174, 3, 43, 'AC09', 'SOCIAL INDIVIDUAL', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(175, 3, 44, 'AC09', 'CPS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(176, 3, 45, 'AC09', 'AMPLIADO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(177, 3, 45, 'AC09', 'TÉCNICO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(178, 3, 46, 'AC09', 'EN CPS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(179, 3, 46, 'AC09', 'ESTÍMULO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(180, 3, 47, 'AC09', 'DEL CONVENIO/ESTRATEGIA', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(181, 3, 48, 'AC09', 'POR COMITÉ AMPLIADO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(182, 3, 48, 'AC09', 'POR SITUACION LEGAL', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(183, 3, 48, 'AC09', 'VOLUNTARIA', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(184, 3, 49, 'AC09', 'DE EPP POR EL JOVEN', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(185, 3, 50, 'AC09', 'REDES INSTITUCIONALES (INTRA/INTER)', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(186, 3, 51, 'AC09', 'DE CPS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(187, 3, 52, 'AC09', 'DE EPP', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(188, 3, 52, 'AC09', 'DE EPP A JOVEN', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(189, 3, 53, 'AC09', 'DE CONTINUIDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(190, 3, 54, 'AC09', 'AGOTAMIENTO OBJ, CPS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(191, 3, 54, 'AC09', 'ANTICIPADA CPS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(192, 3, 54, 'AC09', 'CESION CPS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(193, 3, 54, 'AC09', 'COMPORTAMIENTO INDEBIDO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(194, 3, 54, 'AC09', 'CULMINACIÓN AC', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(195, 3, 54, 'AC09', 'DECESO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(196, 3, 54, 'AC09', 'DESAFILIACIÓN SALUD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(197, 3, 54, 'AC09', 'EDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(198, 3, 54, 'AC09', 'INASISTENCIA', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(199, 3, 54, 'AC09', 'INASISTENCIA ACADÉMICA', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(200, 3, 54, 'AC09', 'INCUMPLIMIENTO CPS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(201, 3, 54, 'AC09', 'NO TRÁMITE DOCUMENTO IDENTIDAD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(202, 3, 54, 'AC09', 'PARTICIPACIÓN HURTO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(203, 3, 54, 'AC09', 'POR COMITÉ AMPLIADO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(204, 3, 54, 'AC09', 'PRÁCTICA PRODUCTIVA SENA', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(205, 3, 54, 'AC09', 'RETIRO VOLUNTARIO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(206, 3, 54, 'AC09', 'RIESGO SALUD', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(207, 3, 54, 'AC09', 'SITUACIÓN LEGAL', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(208, 3, 54, 'AC09', 'SUPERACIÓN TIEMPO EN AC', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(209, 3, 54, 'AC09', 'VINCULACIÓN A CPS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(210, 3, 55, 'AC09', 'DE ACUERDO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(211, 3, 55, 'AC09', 'E INDUCCIÓN', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(212, 3, 56, 'AC09', 'ADMINISTRATIVOS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(213, 3, 57, 'AC09', 'POSITIVO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(214, 3, 58, 'AC09', 'DE SEGUIMIENTO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(215, 3, 58, 'AC09', 'EPE', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(216, 3, 59, 'AC09', 'ACADÉMICO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(217, 3, 59, 'AC09', 'AGRESIÓN', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(218, 3, 59, 'AC09', 'BAJO RENDIMIENTO AC', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(219, 3, 59, 'AC09', 'COMPORTAMIENTO INDEBIDO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(220, 3, 59, 'AC09', 'DESEMPEÑO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(221, 3, 59, 'AC09', 'DETERIORO IMPLEMENTOS Y/O EQUIPOS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(222, 3, 59, 'AC09', 'INASISTENCIAS', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(223, 3, 59, 'AC09', 'LENGUAJE INDEBIDO', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(224, 3, 59, 'AC09', 'NO PORTE EPP', 'Hace referencia al seguimiento que se efectúa con el/la  joven que durante la realización de sus Actividades de Corresponsabilidad, no porta la dotación, identificación visual y/o elementos de protección personal para el ejercicio de sus actividades en campo. ', 1, 1, 1, NULL, NULL),
	(225, 3, 59, 'AC10', 'NO PORTE IDENTIFICACIÓN', 'Hace referencia al seguimiento que se efectúa con e/la joven por no portar la documentación requerida(cédula, vincualción EPS) para el ejercicio de sus Actividades de Corresponsabilidad Modalidad estimulo. ', 1, 1, 1, NULL, NULL),
	(226, 3, 59, 'ACSA', 'POR AGRESIÓN', '0', 0, 1, 1, NULL, NULL),
	(227, 3, 59, 'ACSC', 'POR CONSUMO', '0', 0, 1, 1, NULL, NULL),
	(228, 3, 59, 'ACPH', 'PRESUNTO HURTO', 'Se refiere al seguimiento realizado con el/la joven si se encuentra implicado o implicada en situaciones de hurto durante las Actividades de Corresponsabilidad, en el marco del debido proceso del acuerdo de convivencia para actividades de corresponsabilidad. Se consigna la realización del Comité Misional correspondiente ', 1, 1, 1, NULL, NULL),
	(229, 3, 59, 'AC22', 'PRESUNTO SPA', 'Hace referencia al seguimiento profesional que se realiza con el/la joven por presentarse en bajo el efecto de sustancias psicoactivas, consumir o expender durante el ejercicio de sus Actividades de Corresponsabilidad, aplica para las dos Modalidades.', 1, 1, 1, NULL, NULL),
	(230, 3, 59, 'ACSS', 'SALUD', 'Hace referencia a las acciones de seguimiento profesional realizadas en situaciones donde el/la joven presenta quebrantos de salud que afectan su participación y/o realización de las actividades de corresponsabildiad y/o formativas. Se consigna la realización del Comité Misional correspondiente ', 1, 1, 1, NULL, NULL),
	(231, 3, 59, 'AC12', 'SITUACIÓN MILITAR', 'Se refiere al seguimiento profesional que se efectúa con e/la joven vincualdo a actividades de corresponsabilidad Modalidad estimulo o CPS, relacionado con la definición de su situación militar.', 1, 1, 1, NULL, NULL),
	(232, 3, 59, 'AC13', 'SOLICITAR DINERO O EN ESPECIE', 'Hace referencia al seguimiento profesional  a el/la joven que Realiza solicitud de ayuda monetaria o en especie a particulares, en el ejercicio de sus Actividades de Corresponsabilidad.', 1, 1, 1, NULL, NULL),
	(233, 3, 59, 'ACTD', 'TRIMESTRAL DESEMPEÑO', ' Se consigna los resultados del seguimiento pedagógico  trimestral a las Actividades de Corresponsabilidad Modalidad estimulo, incluyendo información cuantitativa y cualitativa del ejercicio de evaluación y coevaluación desarrollado, a cada uno de los/las jóvenes. ', 1, 1, 1, NULL, NULL),
	(234, 3, 60, 'ACVF', 'FINAL', 'Hace referencia a la valoración final que se efectúa como parte del seguimiento pedagógico a las Actividad de Corresponsabilidad (seguimiento al desempeño) que se realiza previa finalización de la vinculación de el/la joven a la Actividad de Corresponsabilidad.', 1, 1, 1, NULL, NULL),
	(235, 3, 61, 'AC14', 'POSTULACIONES', 'Se emplea para consignar el resultado de la verificación en SIMI y en otras bases de datos de los/las jóvenes postulados Actividades de Corresponsabilidad por parte de unidades o diversos contextos y pedagógicos. ', 1, 1, 1, NULL, NULL),
	(236, 3, 62, 'ACVS', 'A CPS', 'Hace referencia a la firma de contrato de prestación de servicios de un o una joven  a Actividad de Corresponsabilidad Modalidad CPS que se formaliza a partir de la fecha de firma de acta de inicio y firma de Acuerdo de corresponsabiliad CPS. ', 1, 1, 1, NULL, NULL),
	(237, 4, 63, 'AFO', 'ASPECTOS A FORTALECER', 'Aquí se relaciona las dificultades que se ven en el NNAJ y afectan su proceso de formacion (semillero, lideres, multiplicador, convivencia). Ejemplo: vocabulario, falata de convivencia, agresividad, consumo, etc', 1, 1, 1, NULL, NULL),
	(238, 4, 63, 'CIN', 'CENTROS DE INTERES', 'Se relaciona los intereses deportivas, artísticas, religiosos, introspectivos y/o liderazgo del NNAJ, siempre y cuando este tenga una destreza y habilidades construidas. Esto busca ser un espacio para resaltar y promover dicho interés del NNAJ.', 1, 1, 1, NULL, NULL),
	(239, 4, 63, '00A7', 'FALTAS', '0', 1, 1, 1, NULL, NULL),
	(240, 4, 63, 'FLID', 'FORMACIÓN DE LIDERAZGO', 'Este espacio es para registrar a los NNAJ que están iniciando y/o asistiendo a cualquiera de las cinco (5) etapa del proceso de formación de liderazgo. Este sirve para informar el inicio y avance a cada etapa del proceso.', 1, 1, 1, NULL, NULL),
	(241, 4, 63, 'HYF', 'HABILIDADES Y FORTALEZAS', 'Aquí se relaciona las habilidades que se identifican en los NNAJ en relacion a las diferentes actividades que realiza el area. Ejemplo: orden, liderazgo, capacidad de analisis, manejo de grupo, etc', 1, 1, 1, NULL, NULL),
	(242, 4, 63, 'MUL', 'MULTIPLICADOR', 'Este espacio es para registrar a los NNAJ que están iniciando y/o participando de la etapa formativa de multiplicadores para replicar y/o apoyar los semilleros deportivos y artísticos', 1, 1, 1, NULL, NULL),
	(243, 4, 63, '0006', 'RECONOCIMIENTO Y ESTIMULOS', 'Aquí se dejan los avances que se ha visto en el NNAJ, en relación a sus conductas, procesos y/o habilidades. Como también se relaciona los reconocimientos a que se llegue por la participación y formación del NNAJ a los diferentes procesos del Área de Espiritualidad.', 1, 1, 1, NULL, NULL),
	(244, 4, 63, '0005', 'SEGUIMIENTO', 'Aquí se relaciona alguna actividad o novedad especifica en relacion ha algun proyecto en particular, algun compromiso o avance que el NNAJ realice en compañía del funcionario de espiritualidad. Asistencia vista como acompañamiento y seguimiento al proceso de liderazgo y/o multiplicador del NNAJ', 1, 1, 1, NULL, NULL),
	(245, 4, 64, 'ROA', 'A OTRA AREA', 'Este se relaciona cuando un NNAJ solicita apoyo al area y en la consulta se evidencia que tiene algun caso en el cual debe ser revisado por alguna area en especifica: ya sea sociolegal, emprendimiento, academica, salud, etc', 1, 1, 1, NULL, NULL),
	(246, 5, 65, 'ASDT', 'TAMIZAJE AUDITIVO (INICIAL)', 'Examen físico del oido mediante otoscopia; una prueba corta para identificar los NNAJ que requieren de un diagnóstico y/o evaluación más específica. El tamizaje permite identificar una dificultad que no es evidente, esto se realiza empleando pruebas y procedimientos que pueden ser aplicados rápidamente por la Fonoaudióloga.', 1, 1, 1, NULL, NULL),
	(247, 5, 65, 'ADTS', 'TAMIZAJE AUDITIVO (SEGUIMI)', 'Seguimiento periodico a causa de un hallazgo anterior de un Tamizaje inicial o de promocion y prevencion en el cuidado auditivo por medio de examen físico mediante otoscopia una prueba corta para identificar los NNAJ que requieren de un diagnóstico y/o evaluación más específica', 1, 1, 1, NULL, NULL),
	(248, 5, 66, 'MTIP', 'CONSUMO SPA', 'CMG esta designada en el Sistema de Información Misional para designar las acciones adelantadas específicamente por el componente de Mitigación, se ha venido utilizando en la ficha de Observación y Seguimiento para describir las 5 preguntas base para la atención de los beneficiarios que acceden a los servicios interdisciplinarios en medicina alternativa y talleres pedagógicos en las diversas unidades. Estas preguntas dan cuenta del desarrollo de aspectos característicos de los NNAJ asistentes, informan sobre el sueño, apetito, niveles de consumo y sustancia, estado de ánimo.', 1, 1, 1, NULL, NULL),
	(249, 5, 67, 'SVYO', 'VOCACIONAL Y OCUPACIONAL', '0', 1, 1, 1, NULL, NULL),
	(250, 5, 68, 'CAEN', 'NUTRICIÓN', 'Se requiere crear un parametro que permita que el área de Nutrición registrar FOS diarias, en relación a los seguimientos, observaciones o cualquier novedad que de los jóvenes requiera ser registrada en relación a esta área.', 1, 1, 1, NULL, NULL),
	(251, 6, 69, 'SL12', 'A DOMICILIO EFECTIVO (ADE)', '0', 1, 1, 1, NULL, NULL),
	(252, 6, 69, 'SL13', 'A DOMICILIO FALLIDO (ADCF)', '0', 1, 1, 1, NULL, NULL),
	(253, 6, 69, 'AAD', 'AL DOMICILIO', 'Hace referencia al acercamiento que se realiza al domicilio del NNAJ por pérdida de contacto, seguimiento por condiciones de riesgos dentificados en el proceso del beneficiario y/o acercamiento por consulta social en domicilio no efectiva, es decir no se recibe al profesional en la vivienda para la ejecución de la CSD.', 1, 1, 1, NULL, NULL),
	(254, 6, 70, 'AIE', 'INTERINSTITUCIONALES', '0', 0, 1, 1, NULL, NULL),
	(255, 6, 70, 'AGIT', 'INTRAINSTITUCIONALES', '0', 0, 1, 1, NULL, NULL),
	(256, 6, 71, 'AP32', 'A REDES INTRAINSTITUCIONALES', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ a la secretaria de educación, sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(257, 6, 71, 'AP32', 'INTERINSTITUCIONALES', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ a la secretaria de educación, sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(258, 6, 72, 'AP32', 'COMISARIA DE FAMILIA', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ a la secretaria de educación, sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(259, 6, 72, 'AP32', 'EDUCACION', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ a la secretaria de educación, sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(260, 6, 72, 'AP31', 'ICBF', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ con el Instituto Colombiano de Bienestar Familiar (ICBF), sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(261, 6, 72, 'AP39', 'JUDICIALES', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ al: Sisben, movilidad, Defensoría del pueblo, IDIGER, IPES, alcaldías locales, secretarias distritales del Hábitat, hacienda, desarrollo económica, de seguridad, convivencia y justicia, de cultura, recreación y deporte (IDRD), defensoría del espacio público, personería, secretaria de gobierno, hacienda, planeación y/o catastro.', 1, 1, 1, NULL, NULL),
	(262, 6, 72, 'AP36', 'ONG', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ a (organizaciones no gubernamentales) ONG, sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(263, 6, 72, 'AP41', 'OTRAS INSTITUCIONES', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ al: Sisben, movilidad, Defensoría del pueblo, IDIGER, IPES, alcaldías locales,\nsecretarias distritales del Hábitat, hacienda, desarrollo económica, de seguridad, convivencia y justicia, de cultura, recreación y deporte (IDRD), defensoría del espacio público, personería, secretaria de gobierno,\nhacienda, planeación y/o catastro.', 1, 1, 1, NULL, NULL),
	(264, 6, 72, 'AP35', 'REGISTRADURIA', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ a la registraduria nacional, sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(265, 6, 72, 'AP29', 'SALUD', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o\ntrabajo social con el NNAJ a otras instituciones del sistema de salud sin que el profesional realice algún tipo\nde articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(266, 6, 72, 'AP30', 'SDIS', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ con la secretaria de integración social, sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(267, 6, 72, 'AP33', 'SECRETARIA DE LA MUJER', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ a la secretaria de la mujer, sin que el profesional realice algún tipo de articulación o vinculación.', 1, 1, 1, NULL, NULL),
	(268, 6, 73, 'AP21', 'EDUCACION', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ al Área de derechos del IDIPRON (EDUCACIÓN).', 1, 1, 1, NULL, NULL),
	(269, 6, 73, 'AP22', 'EMPRENDER', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ al Área de derechos del IDIPRON EMPREDER.', 1, 1, 1, NULL, NULL),
	(270, 6, 73, 'AP23', 'ESPIRITUALIDAD', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ al Área de derechos del IDIPRON (ESPIRITUALIDAD).', 1, 1, 1, NULL, NULL),
	(271, 6, 73, 'AP18', 'SALUD', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ al Área de derechos del IDIPRON (SALUD-componente mitigación).', 1, 1, 1, NULL, NULL),
	(272, 6, 73, 'AP20', 'SOCIO LEGAL', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ al Área de derechos del IDIPRON (SOCIOLEGAL).', 1, 1, 1, NULL, NULL),
	(273, 6, 74, 'APN', 'A FAMILIA', '0', 0, 1, 1, NULL, NULL),
	(274, 6, 74, 'ACP', 'A NNAJ', '0', 1, 1, 1, NULL, NULL),
	(275, 6, 75, 'ACP', 'INTERINSTITUCIONALES', '0', 1, 1, 1, NULL, NULL),
	(276, 6, 75, 'ACP', 'INTRAINSTITUCIONALES', '0', 1, 1, 1, NULL, NULL),
	(277, 6, 76, 'ACP', 'A NNAJ Y FAMILIAS', '0', 1, 1, 1, NULL, NULL),
	(278, 6, 76, 'SL21', 'ACOMPAÑAMIENTO', '0', 1, 1, 1, NULL, NULL),
	(279, 6, 76, 'SL17', 'EDUCACION', '0', 1, 1, 1, NULL, NULL),
	(280, 6, 76, 'SL20', 'INSTITUC CARACTER SOCIA', '0', 1, 1, 1, NULL, NULL),
	(281, 6, 76, 'SL19', 'INSTITUCIÓN PROTECCION', '0', 1, 1, 1, NULL, NULL),
	(282, 6, 76, 'ARN', 'NO POBLACION IDIPRON', '0', 0, 1, 1, NULL, NULL),
	(283, 6, 76, 'SL18', 'SALUD', '0', 1, 1, 1, NULL, NULL),
	(284, 6, 77, 'SL15', 'ACOMPAÑA UPI-ÁREA DEREC', '0', 1, 1, 1, NULL, NULL),
	(285, 6, 77, 'SL14', 'COMUNICACIÓN UPI (ARU)', '0', 1, 1, 1, NULL, NULL),
	(286, 6, 77, 'SL16', 'REMISIÓN ÁREA O CONTEXT', '0', 1, 1, 1, NULL, NULL),
	(287, 6, 78, 'SL06', 'REDES INTER', '0', 1, 1, 1, NULL, NULL),
	(288, 6, 78, 'SL05', 'REDES INTRA', '0', 1, 1, 1, NULL, NULL),
	(289, 6, 79, 'ASPF', 'FAMILIAR', '0', 0, 1, 1, NULL, NULL),
	(290, 6, 79, 'ASAJ', 'INDIVIDUAL', '0', 0, 1, 1, NULL, NULL),
	(291, 6, 79, 'ASPN', 'NNAJ', '0', 0, 1, 1, NULL, NULL),
	(292, 6, 80, 'ASTN', 'NNAJ', '0', 0, 1, 1, NULL, NULL),
	(293, 6, 81, 'SPF', 'FAMILIAR', '0', 0, 1, 1, NULL, NULL),
	(294, 6, 82, 'SL03', 'A FAMILIA', '0', 1, 1, 1, NULL, NULL),
	(295, 6, 82, 'API', 'A NNAJ', '0', 1, 1, 1, NULL, NULL),
	(296, 6, 83, 'ATSF', 'A FAMILIA', 'Se crea el criterio de cargue para que el profesional en trabajo social registe atención realizada con la familia y/o redes de apoyo NNAJ respecto a información, orientación y seguimiento inmediato.', 1, 1, 1, NULL, NULL),
	(297, 6, 83, 'ATNN', 'A NNAJ', 'Se crea el criterio de cargue para que el profesional en trabajo social registe atención realizada a el/la NNAJ respecto a información, orientación y seguimiento inmediato.', 1, 1, 1, NULL, NULL),
	(298, 6, 84, 'APAN', 'A NNAJ', 'Se crea el criterio de cargue para que el profesional en psicología registe atención realizada con el NNAJ respecto a información, orientación y seguimiento inmediato.', 1, 1, 1, NULL, NULL),
	(299, 6, 84, 'APPF', 'FAMILIARES', 'Se crea el criterio de cargue para que el profesional en psicología registe atención realizada con la familia o redes de apoyo del NNAJ respecto a información, orientación y seguimiento inmediato.', 1, 1, 1, NULL, NULL),
	(300, 6, 85, 'BUPI', 'AL NNAJ A LA UPI', 'La acción relacionada, se registra cuando el NNAJ ingresa a la UPI inicialmente o realiza un ingreso con antecedentes institucionales, en este espacio el equipo psicosocial realiza una atención con el beneficiario y se dan a conocer dinámicas de la Unidad, horarios, normas, y reglas, acompañado de un recorrido por la Unidad.', 1, 1, 1, NULL, NULL),
	(301, 6, 86, 'SL29', 'DECESO', '0', 1, 1, 1, NULL, NULL),
	(302, 6, 86, 'SL24', 'DIRECCIONA INSTITU-VERIF VULNE DER', '0', 1, 1, 1, NULL, NULL),
	(303, 6, 86, 'SL23', 'ESTABLECIM DERECHOS ACTIVACIÓN RED', '0', 1, 1, 1, NULL, NULL),
	(304, 6, 86, 'SL27', 'FALTA DE INTERÉS DEL/LA JOVEN.', '0', 1, 1, 1, NULL, NULL),
	(305, 6, 86, 'SL30', 'PÉRDIDA DE CONTACTO', '0', 1, 1, 1, NULL, NULL),
	(306, 6, 86, 'SL25', 'REINGRESO INSTITUCIONAL', '0', 1, 1, 1, NULL, NULL),
	(307, 6, 86, 'SL26', 'VERIFICACIÓN DE PROCESO', '0', 1, 1, 1, NULL, NULL),
	(308, 6, 86, 'SL22', 'VERIFICACIÓN GOCE EFECTIVO DERECHO', '0', 1, 1, 1, NULL, NULL),
	(309, 6, 86, 'SL28', 'VERIFICACIÓN GOCE PARCIAL DEREC AJ', '0', 1, 1, 1, NULL, NULL),
	(310, 6, 87, 'SL08', 'RESTAURATIVA', '0', 1, 1, 1, NULL, NULL),
	(311, 6, 88, 'SL08', 'MISIONAL', '0', 1, 1, 1, NULL, NULL),
	(312, 6, 89, 'CTCP', 'SEGUIMIENTO PROCESOS', '0', 0, 1, 1, NULL, NULL),
	(313, 6, 90, 'CTCI', 'CAMBIO DE INSTITUCIÓN', 'Se crea criterio de registrar acciones que aplican para NNA que cuentan con Proceso Administrativo de Restablecimiento de derechos (PARD), el equipo psicosocial de la unidad participa junto al equipo de la defensoría y defensor de familia de ICBF, en la evaluación de cambio de institución, es decir que no continúe con la vinculación en el IDIPRON.', 1, 1, 1, NULL, NULL),
	(314, 6, 90, 'APS5', 'PROCESO TERAPÉUTICO', 'Se crea criterio de registro, aplica para NNA que cuentan con Proceso Administrativo de Restablecimiento de derechos (PARD), la acción hace referencia a la participación del equipo sicosocial del IDIPRON en el comité técnico convocado y ejecutado por el defensor de familia y equipo interdisciplinar del ICBF, aquí se define si el NNA requiere activación de redes en proceso terapéutico siguiendo los lineamientos que establezca el ICBF.', 1, 1, 1, NULL, NULL),
	(315, 6, 90, 'ICBF', 'REINTEGRO FAMILIAR', 'Se crea criterio de registro de acciones que aplican para NNA que cuentan con Proceso Administrativo de Restablecimiento de derechos (PARD), el equipo psicosocial de la Unidad participa junto al equipo de la defensoría y defensor de familia de ICBF, en la evaluación del proceso y seguimiento a los NNA respecto a reintegro familiar del NNA, se obtiene como evidencia la boleta de egreso del ICBF para dar reintegro familiar.', 1, 1, 1, NULL, NULL),
	(316, 6, 90, 'APS6', 'SEGUIMIENTO PROCESOS', 'Aplica para NNA que cuentan con Proceso Administrativo de Restablecimiento de derechos (PARD), el equipo psicosocial de la unidad participa junto al equipo de la defensoría y defensor de familia de ICBF, en la evaluación del proceso y seguimiento a los NNA respecto a continuidad en el IDIPRON, de acuerdo a las necesidades de los mismos.', 1, 1, 1, NULL, NULL),
	(317, 6, 91, 'SL36', 'REINGRESO EFECTIVO', '0', 1, 1, 1, NULL, NULL),
	(318, 6, 92, 'SL09', 'A NNAJ Y/O RED DE APOYO', '0', 1, 1, 1, NULL, NULL),
	(319, 6, 92, 'APS7', 'DEFENSOR DE FAMILIA', 'Se crea este criterio con el fin de registrar el contacto telefónico que realiza el profesional del equipo psicosocial, con el defensor de familia quien es representante legal del NNA quien cuenta con proceso Administrativo de Restablecimiento de Derechos.', 1, 1, 1, NULL, NULL),
	(320, 6, 92, 'SL31', 'EFECTIVO', '0', 1, 1, 1, NULL, NULL),
	(321, 6, 92, 'SL32', 'FALLIDO', '0', 1, 1, 1, NULL, NULL),
	(322, 6, 93, 'APS8', 'DEFENSOR DE FAMILIA', 'Se crea este criterio con el fin de registrar el contacto mediante correo electrónico que realiza el profesional del equipo psicosocial (psicólogo y/o trabajo social), con el defensor de familia quien es representante legal del NNA quien cuenta con proceso Administrativo de Restablecimiento de Derechos.', 1, 1, 1, NULL, NULL),
	(323, 6, 94, 'CNFI', 'NUEVA FICHA DE INGRESO', '0', 0, 1, 1, NULL, NULL),
	(324, 6, 95, 'SL04', 'CORRESPONSABILIDAD', '0', 1, 1, 1, NULL, NULL),
	(325, 6, 96, 'AP13', 'FAMILIAR EN UPI', 'Elaboración de informe psicosocial para evidenciar avances y dificultades del NNAJ desde cada una de las áreas de atención. Se debe registrar en la observación fecha de la elaboración y radicación, nombre de la entidad y motivo por el cual se da la remisión.', 1, 1, 1, NULL, NULL),
	(326, 6, 97, 'AP13', 'EGRESO', 'Elaboración de informe psicosocial para evidenciar avances y dificultades del NNAJ desde cada una de las áreas de atención. Se debe registrar en la observación fecha de la elaboración y radicación, nombre de la entidad y motivo por el cual se da la remisión.', 1, 1, 1, NULL, NULL),
	(327, 6, 98, 'AP13', 'VINCULACION', 'Elaboración de informe psicosocial para evidenciar avances y dificultades del NNAJ desde cada una de las áreas de atención. Se debe registrar en la observación fecha de la elaboración y radicación, nombre de la entidad y motivo por el cual se da la remisión.', 1, 1, 1, NULL, NULL),
	(328, 6, 99, 'AP13', 'COMISARIA DE FAMILIA', 'Elaboración de informe psicosocial para evidenciar avances y dificultades del NNAJ desde cada una de las áreas de atención. Se debe registrar en la observación fecha de la elaboración y radicación, nombre de la entidad y motivo por el cual se da la remisión.', 1, 1, 1, NULL, NULL),
	(329, 6, 99, 'AP13', 'EDUCACION', 'Elaboración de informe psicosocial para evidenciar avances y dificultades del NNAJ desde cada una de las áreas de atención. Se debe registrar en la observación fecha de la elaboración y radicación, nombre de la entidad y motivo por el cual se da la remisión.', 1, 1, 1, NULL, NULL),
	(330, 6, 99, 'AP12', 'ICBF', 'Elaboración de informe psicosocial para evidenciar avances y dificultades del NNAJ desde cada una de las áreas de atención. Se debe registrar en la observación fecha de la elaboración y radicación, nombre de la entidad y motivo por el cual se da la remisión.', 1, 1, 1, NULL, NULL),
	(331, 6, 99, 'AP38', 'JUDICIALES', 'Hace referencia al acompañamiento y/o desplazamiento que realiza el profesional en psicología o trabajo social con el NNAJ al: Sisben, movilidad, Defensoría del pueblo, IDIGER, IPES, alcaldías locales, secretarias distritales del Hábitat, hacienda, desarrollo económica, de seguridad, convivencia y justicia, de cultura, recreación y deporte (IDRD), defensoría del espacio público, personería, secretaria de gobierno, hacienda, planeación y/o catastro.', 1, 1, 1, NULL, NULL),
	(332, 6, 99, 'AP17', 'ONG', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con las ONG (organizaciones no gubernamentales). Referenciar en la descripción la organización y servicio.', 1, 1, 1, NULL, NULL),
	(333, 6, 99, 'AP40', 'OTRAS INSTITUCIONES', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con Sisben, movilidad, Defensoría del pueblo, IDIGER, IPES, alcaldías locales, secretarias distritales del Hábitat, hacienda, desarrollo económica, de seguridad, convivencia y justicia, de cultura, recreación y deporte (IDRD), defensoría del espacio público, personería, secretaria de gobierno, hacienda, planeación y/o catastro.', 1, 1, 1, NULL, NULL),
	(334, 6, 99, 'AP16', 'REGISTRADURIA', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con la Registraduria Nacional.', 1, 1, 1, NULL, NULL),
	(335, 6, 99, 'AP10', 'SALUD', 'Hace referencia a la gestión interinstitucional que realiza el profesional psicosocial (en psicología o trabajo social) con entidades prestadoras del sistema de salud (EPS o red hospitalaria).', 1, 1, 1, NULL, NULL),
	(336, 6, 99, 'AP11', 'SDIS', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con la Secretaria de Integración Social (SDIS).', 1, 1, 1, NULL, NULL),
	(337, 6, 99, 'AP14', 'SECRETARIA DE LA MUJER', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con la Secretaria de la Mujer.', 1, 1, 1, NULL, NULL),
	(338, 6, 100, 'AP26', 'EDUCACION', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con las ONG (organizaciones no gubernamentales). Referenciar en la descripción la organización y servicio.', 1, 1, 1, NULL, NULL),
	(339, 6, 100, 'AP27', 'EMPRENDER', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con las ONG (organizaciones no gubernamentales). Referenciar en la descripción la organización y servicio.', 1, 1, 1, NULL, NULL),
	(340, 6, 100, 'AP28', 'ESPIRITUALIDAD', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con las ONG (organizaciones no gubernamentales). Referenciar en la descripción la organización y servicio.', 1, 1, 1, NULL, NULL),
	(341, 6, 100, 'GITI', 'INSTITUCIONAL', '0', 0, 1, 1, NULL, NULL),
	(342, 6, 100, 'AP24', 'SALUD', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con las ONG (organizaciones no gubernamentales). Referenciar en la descripción la organización y servicio.', 1, 1, 1, NULL, NULL),
	(343, 6, 100, 'AP25', 'SOCIO LEGAL', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con las ONG (organizaciones no gubernamentales). Referenciar en la descripción la organización y servicio.', 1, 1, 1, NULL, NULL),
	(344, 6, 101, 'GRIO', 'ORIENTACIÓN', '0', 0, 1, 1, NULL, NULL),
	(345, 6, 101, 'GRIF', 'REFERENCIACION', '0', 0, 1, 1, NULL, NULL),
	(346, 6, 102, 'GRIF', 'INTERINSTITUCIONALES', '0', 0, 1, 1, NULL, NULL),
	(347, 6, 102, 'GRIF', 'INTRAINSTITUCIONALES', '0', 0, 1, 1, NULL, NULL),
	(348, 6, 103, 'APS9', 'REMISION', 'Hace referencia cuando el profesional del equipo psicosocial realiza remisión por medio de contacto directo con algún funcionario de la institución receptora, y mediante diligenciamiento del formato Direccionamiento y referenciación M-MTE-FT-011 se presenta el caso del NNAJ para el servicio interinstitucional.', 1, 1, 1, NULL, NULL),
	(349, 6, 104, 'APS1', 'INTERINSTITUCIONALES', '0', 0, 1, 1, NULL, NULL),
	(350, 6, 105, 'AS10', 'PSICOSOCIAL NNAJ', 'Elaboración de informe psicosocial para evidenciar avances y dificultades del NNAJ desde cada una de las áreas de atención. Se debe registrar en la observación fecha de la elaboración y radicación, nombre de la entidad y motivo por el cual se da la remisión.', 1, 1, 1, NULL, NULL),
	(351, 6, 106, 'LLA', 'ATENCION ORIENTACION O ACOMPAÑAMIENTO', '0', 1, 1, 1, NULL, NULL),
	(352, 6, 107, 'NCSA', 'SEGUIMIENTO', '0', 0, 1, 1, NULL, NULL),
	(353, 6, 108, 'N2F', 'FALLECIMIENTO', '0', 1, 1, 1, NULL, NULL),
	(354, 6, 109, 'SL11', 'JUSTICIA RESTAURATIVA', '0', 1, 1, 1, NULL, NULL),
	(355, 6, 110, 'PJC', 'DE JOVENES A CONVENIO', 'Se crea el criterio, con el fin de registrar la información de postulación de jóvenes a convenios, en esta acción se incluye la ejecución de comité misional de UPI donde se postula a los Jóvenes a la Modalidad de Estimulo de Corresponsabilidad, se remiten el listado de Jóvenes que cumplen con los requisitos para iniciar proceso al área de convenios.', 1, 1, 1, NULL, NULL),
	(356, 6, 111, 'SL33', 'A COMITÉ', '0', 1, 1, 1, NULL, NULL),
	(357, 6, 112, 'PII', 'DE INGRESO A IDIPRON', 'Se crea este criterio, con el fin de registrar las acciones realizadas por el área Sicosocial en el proceso de ingreso de los NNA al contexto pedagógico internado en Unidades de Protección Integral del IDIPRON.', 1, 1, 1, NULL, NULL),
	(358, 6, 113, 'AP37', 'PSICOESPECIALIZADA', 'Hace referencia a la gestión interinstitucional (referenciación, orientación o vinculación) que realiza el profesional psicosocial (en psicología o trabajo social) con las ONG (organizaciones no gubernamentales). Referenciar en la descripción la organización y servicio.', 1, 1, 1, NULL, NULL),
	(359, 6, 114, 'PSEV', 'EVASION', '0', 0, 1, 1, NULL, NULL),
	(360, 6, 115, 'ASYP', 'MAYORES', '0', 0, 1, 1, NULL, NULL),
	(361, 6, 116, 'SL10', 'EGRESO-SOCIO LEGAL', '0', 0, 1, 1, NULL, NULL),
	(362, 6, 116, 'SL34', 'PRESENCIAL', '0', 1, 1, 1, NULL, NULL),
	(363, 6, 116, 'SVI', 'VALORACION INICIAL PSICOSOCIAL', '0', 0, 1, 1, NULL, NULL),
	(364, 6, 117, 'SL35', 'DE REINGRESO', '0', 1, 1, 1, NULL, NULL),
	(365, 6, 118, 'VPIB', 'PSICOSOCIAL INICIAL BASE PLANA', 'Se crea criterio de cargue para evidenciar la aplicación y diligenciamiento del instrumento de aplicación Valoración Sicosocial.', 1, 1, 1, NULL, NULL),
	(366, 6, 119, 'SL37', 'DE ESTADO DE AFILIACIÓN SALUD', '0', 1, 1, 1, NULL, NULL),
	(367, 6, 119, 'SL38', 'DE HISTORIA SOCIAL', '0', 1, 1, 1, NULL, NULL),
	(368, 6, 119, 'SL39', 'DE INFORMACIÓN SIMI', '0', 1, 1, 1, NULL, NULL),
	(369, 6, 119, 'SL40', 'SIMAT', '0', 1, 1, 1, NULL, NULL),
	(370, 7, 120, 'SL12', 'A DOMICILIO EFECTIVO (ADE)', '0', 1, 1, 1, NULL, NULL),
	(371, 7, 120, 'SL13', 'A DOMICILIO FALLIDO (ADCF)', '0', 1, 1, 1, NULL, NULL),
	(372, 7, 121, 'APF', 'A FAMILIAS', 'A criterio del profesional en derecho o psicosocial es necesario realizar acompañamiento a las familias a la entidad correspondiente para garantizar el goce efectivo de los derechos del NNA.', 1, 1, 1, NULL, NULL),
	(373, 7, 122, 'ACP', 'A NNAJ', 'Se hace necesario acompañar al NNAJ por parte del profesional en derecho o psicosocial para garantizar la garantía y goce efectivo de sus derechos.', 1, 1, 1, NULL, NULL),
	(374, 7, 123, 'SL20', 'INTERINSTITUCIONALES', '0', 1, 1, 1, NULL, NULL),
	(375, 7, 123, 'SL20', 'INTRAINSTITUCIONALES', '0', 1, 1, 1, NULL, NULL),
	(376, 7, 123, 'SL20', 'POBLACION NO IDIPRON', '0', 1, 1, 1, NULL, NULL),
	(377, 7, 124, 'SL20', 'ACOMPAÑAMIENTO', '0', 1, 1, 1, NULL, NULL),
	(378, 7, 124, 'SL20', 'EDUCACION', '0', 1, 1, 1, NULL, NULL),
	(379, 7, 124, 'SL20', 'INSTITUC CARACTER SOCIA', '0', 1, 1, 1, NULL, NULL),
	(380, 7, 124, 'SL19', 'INSTITUCIÓN PROTECCION', '0', 1, 1, 1, NULL, NULL),
	(381, 7, 124, 'SL18', 'SALUD', '0', 1, 1, 1, NULL, NULL),
	(382, 7, 125, 'SL15', 'ACOMPAÑA UPI-ÁREA DEREC', '0', 1, 1, 1, NULL, NULL),
	(383, 7, 125, 'SL14', 'COMUNICACIÓN UPI (ARU)', '0', 1, 1, 1, NULL, NULL),
	(384, 7, 125, 'SL16', 'REMISIÓN ÁREA O CONTEXT', '0', 1, 1, 1, NULL, NULL),
	(385, 7, 126, 'SL06', 'DE REDES INTER', '0', 1, 1, 1, NULL, NULL),
	(386, 7, 126, 'SL05', 'DE REDES INTRA', '0', 1, 1, 1, NULL, NULL),
	(387, 7, 127, 'SL03', 'A FAMILIAS', 'Es la atención y orientación que se otorga por parte del profesional en derecho o psicosocial a la familia del NNAJ con el propósito de identificar la petición, necesidad e inquietud en su proceso de ingreso, permanencia y egreso.', 1, 1, 1, NULL, NULL),
	(388, 7, 127, 'API', 'A NNAJ', 'Es la atención y orientación que se otorga por parte del profesional en derecho o psicosocial al NNAJ en el proceso de ingreso, permanencia y egreso a fin de garantizar el goce efectivo de sus derechos.', 1, 1, 1, NULL, NULL),
	(389, 7, 128, 'CAS', 'DE ASISTENCIA', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(390, 7, 129, 'CAS', 'DE PRÁCTICA RESTAURATIVA', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(391, 7, 130, 'CAS', 'DECESO', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(392, 7, 130, 'CAS', 'DIRECCIONA INSTITU-VERIF VULNE DER', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(393, 7, 130, 'CAS', 'ESTABLECIM DERECHOS ACTIVACIÓN RED', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(394, 7, 130, 'CAS', 'FALTA DE INTERÉS DEL/LA JOVEN.', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(395, 7, 130, 'CAS', 'PÉRDIDA DE CONTACTO', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(396, 7, 130, 'CAS', 'REINGRESO INSTITUCIONAL', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(397, 7, 130, 'CAS', 'VERIFICACIÓN DE PROCESO', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(398, 7, 130, 'CAS', 'VERIFICACIÓN GOCE EFECTIVO DERECHO', 'Son certificaciones de asistencia a las Unidades de Protección Integral y programas del IDIPRON en las que se informa el tiempo, la unidad y/o programa en la que el NNAJ ha participado.', 1, 1, 1, NULL, NULL),
	(399, 7, 130, 'SL08', 'VERIFICACIÓN GOCE PARCIAL DEREC AJ', '0', 1, 1, 1, NULL, NULL),
	(400, 7, 131, 'SL36', 'REINGRESO EFECTIVO', '0', 1, 1, 1, NULL, NULL),
	(401, 7, 132, 'SL09', 'A NNAJ Y/O RED DE APOYO', '0', 1, 1, 1, NULL, NULL),
	(402, 7, 132, 'SL31', 'EFECTIVO', '0', 1, 1, 1, NULL, NULL),
	(403, 7, 132, 'SL32', 'FALLIDO', '0', 1, 1, 1, NULL, NULL),
	(404, 7, 133, 'SL04', 'DE CORRESPONSABILIDAD', 'De acuerdo al Art. 10 de la Ley 1098/2006 es la concurrencia de actores y acciones conducentes a garantizar el ejercicio de los derechos de los niños, las niñas y los adolescentes. La familia, la sociedad y el Estado son corresponsables en su atención, cuidado y protección.', 1, 1, 1, NULL, NULL),
	(405, 7, 134, 'SL01', 'DEL EGRESO', '0', 0, 1, 1, NULL, NULL),
	(406, 7, 135, 'SL07', 'DE PRÁCTICA RESTAURATIVA', '0', 1, 1, 1, NULL, NULL),
	(407, 7, 136, 'LLA', 'PARA ATENCION ORIENTACION O ACOMPAÑ.', 'Son contactos telefónicos a los números registrados en SIMI o Historia Social, la cual tiene objetivo conocer por medio del sistema familiar o el NNAJ su situación actual.', 1, 1, 1, NULL, NULL),
	(408, 7, 137, 'N2F', 'FALLECIMIENTO', 'Es cuando ocurre un siniestro de los NNAJ', 1, 1, 1, NULL, NULL),
	(409, 7, 138, 'SL11', 'JUSTICIA RESTAURATIVA', '0', 1, 1, 1, NULL, NULL),
	(410, 7, 139, 'SL33', 'A COMITÉ', '0', 1, 1, 1, NULL, NULL),
	(411, 7, 140, 'SL10', 'AL EGRESO-SOCIO LEGAL', '0', 0, 1, 1, NULL, NULL),
	(412, 7, 140, 'SL34', 'PRESENCIAL', '0', 1, 1, 1, NULL, NULL),
	(413, 7, 141, 'SL35', 'DE REINGRESO', '0', 1, 1, 1, NULL, NULL),
	(414, 7, 142, 'SL37', 'DE ESTADO DE AFILIACIÓN SALUD', '0', 1, 1, 1, NULL, NULL),
	(415, 7, 142, 'SL38', 'DE HISTORIA SOCIAL', '0', 1, 1, 1, NULL, NULL),
	(416, 7, 142, 'SL39', 'DE INFORMACIÓN SIMI', '0', 1, 1, 1, NULL, NULL),
	(417, 7, 142, 'SL40', 'SIMAT', '0', 1, 1, 1, NULL, NULL),
	(418, 8, 143, 'AÑOT', 'A OTRAS ACTIVIDADES', '0', 0, 1, 1, NULL, NULL),
	(419, 8, 143, '002', 'SOCIAL INDIVIDUAL', 'Hace referencia al seguimiento en los aspectos que tienen que ver con el proceso personal del NNAJ en donde se encuentran fortalezas y aspectos a mejorar en los aspectos de vivienda com presentación personal, hábitos saludables en alimentación, organización y cuidado de sus pertenencias. Tambien las felicitaciones pr los avances en el proceso.', 1, 1, 1, NULL, NULL),
	(420, 8, 144, '009', 'EN LAS ETAPAS DEL MODELO PEDAGOGICO.', 'Se registran todas las actividades que se lleven a cabo cuando los NNAJ se vinculan a las diferentes etapas del modelo pedagogico, recepción, acogida, servicios, pactos de convivencia, entre otros.', 1, 1, 1, NULL, NULL),
	(421, 8, 145, 'AIS', 'FICHA DE INGRESO', 'Se crea el criterio, con el fin de registrar la realización de modificación de información y/o actualización de datos básicos y generales de la ficha de ingreso.', 1, 1, 1, NULL, NULL),
	(422, 8, 146, 'AM68', 'A MENORES DE 6 A 8 AÑOS', 'Se registra la atención de Niños y Niñas de 6 a 8 años, con el cual se informa que la atención brindada se brinda de acuerdo a la Ley 1098 de Infancia y Adolescencia para la atención inmediata porque tienen vulnerados los derechos de los niños y Niñas de 6 a 8 años.', 1, 1, 1, NULL, NULL),
	(423, 8, 147, '004', 'DE CONVIVENCIA', 'Hace referencia a los criterios definidos en el formato para identificar los avances en el proceso individual de convivencia.', 1, 1, 1, NULL, NULL),
	(424, 8, 148, 'CCPE', 'COMISION EVALUACION Y PROMOCION', 'Se crea criterio de registro donde los profesionales en psicología y trabajo social, realiza concepto psicosocial para la comisión y evaluación del NNAJ vinculado al modelo pedagógico del Instituto.', 1, 1, 1, NULL, NULL),
	(425, 8, 149, '4CAE', 'EMPIEZA VINCULACION UPI', 'Se requiere crear el parametro expuesto anteriormente para registrar los jóvenes que egresan del CAE por libertad o cambio de medida y se incorporan a una UPI del Instituto para iniciar proceso a través del Modelo Pedagógico del IDIPRON', 1, 1, 1, NULL, NULL),
	(426, 8, 150, 'TFFL', 'DE LIDERAZGO', '0', 0, 1, 1, NULL, NULL),
	(427, 8, 151, 'OO7', 'A SITUACIONES CONVIVENCIALES ESPECIALES DE LA UPI', 'Los Responsables de Unidad intervienen en casos especiales donde se requiere su participación por ser situaciones de dificil manejo.', 1, 1, 1, NULL, NULL),
	(428, 8, 152, 'OO5', 'PACTO CONVIVENCIA', 'Se registran acciones que conlleven a la resolución de los conflictos que se presenten dentro de las dinamicas de las unidades.', 1, 1, 1, NULL, NULL),
	(429, 8, 153, 'NRES', 'DE PERMISO', '0', 0, 1, 1, NULL, NULL),
	(430, 8, 154, 'NRES', 'FALLECIMIENTO', '0', 0, 1, 1, NULL, NULL),
	(431, 8, 155, 'NRES', 'DEL NNAJ EN PRESENTACION PERSONAL', '0', 0, 1, 1, NULL, NULL),
	(432, 8, 155, 'NRES', 'DEL NNAJ EN SU ASPECTO FISICO (NAF)', '0', 0, 1, 1, NULL, NULL),
	(433, 8, 155, 'NRES', 'FAMILIARES DE LOS NNAJ', '0', 0, 1, 1, NULL, NULL),
	(434, 8, 155, 'NRES', 'NNAJ EN RUTAS ESCOLARES-IDIPRON', '0', 0, 1, 1, NULL, NULL),
	(435, 8, 156, 'TVPA', 'EN ACTIVIDADES', '0', 0, 1, 1, NULL, NULL),
	(436, 8, 157, '001', 'ACCIÓN PEDAGÓGICA', 'Practica acordada para promover espacios reflexivos y de aprendizaje del NNAJ frente a las situaciones comportamentales, en el marco de la actividad formativa y de corresponsabilidad.', 1, 1, 1, NULL, NULL),
	(437, 8, 158, 'RAM', 'ACOMPAÑAMIENTO', '0', 0, 1, 1, NULL, NULL),
	(438, 8, 159, '0020', 'A LA INASISTENCIA', 'Lo constituyen cada una de las acciones que se realizan una vez presentada la no asistencia del NNAJ por un periodo menor o igual a un (1) mes a la UPI modalidad internado, menor o igual a 45 días a la UPI modalidad externado y no mayor a 1 semana a la UPI Riesgo ESCNNA modalidad externado, buscando establecer condiciones de los NNAJ así como la posibilidad de retorno a las Unidades o la pertinencia de trámite de egreso con las gestiones intra e inter institucionales a que hubiere lugar para garantizar su goce de derechos (Consultado en Manual de Procesos y Procedimientos: M-MSL-PR-001, M-MSL-PR-002 y M-SEG-IN-001).', 1, 1, 1, NULL, NULL),
	(439, 8, 159, '3CAE', 'PEDAGOGICO', 'Registro mensual de los seguimientos que se hacen desde el área de Pedagogía.\n', 1, 1, 1, NULL, NULL),
	(440, 8, 159, 'ST', 'TELEFÓNICO', 'Cuando se establece contacto telefónico con la familia y/o el NNAJ para dar información del proceso, realizar convocatoria a eventos, encuentros familiares; así como la comunicación que el NNAJ establece con su red de apoyo familiar con el fin de fortalecimiento del vínculo.', 1, 1, 1, NULL, NULL),
	(441, 8, 160, '1CAE', 'DATOS GENERALES', 'el joven ingresa con su respectiva boleta judicial, se ubica en la sección acogida y antes de hacer cualquier registro y/o entrega formal, el joven se evade (todo sucede en el transcurso de pocas horas). No hay acceso a información puntual má allá de lo que dice la boleta del juzgado que es solamente nombre y número de documento de identidad. Por ser información judicial es reservada y no se puede acceder a ella. Similar ocurre con los jóvenes que no se tiene ficha de ingreso; estuvieron en el CAE antes del 15 de marzo/19 (fecha en que se acordó inicir el registro SIMI) y fueron trasladados a otros CAE con su carpeta incluida.', 1, 1, 1, NULL, NULL),
	(442, 8, 161, '2CAE', 'FICHA DE INGRESO', 'el joven ingresa con su respectiva boleta judicial, se ubica en la sección acogida y antes de hacer cualquier registro y/o entrega formal, el joven se evade (todo sucede en el transcurso de pocas horas). No hay acceso a información puntual má allá de lo que dice la boleta del juzgado que es solamente nombre y número de documento de identidad. Por ser información judicial es reservada y no se puede acceder a ella. Similar ocurre con los jóvenes que no se tiene ficha de ingreso; estuvieron en el CAE antes del 15 de marzo/19 (fecha en que se acordó inicir el registro SIMI) y fueron trasladados a otros CAE con su carpeta incluida.', 1, 1, 1, NULL, NULL),
	(443, 8, 162, 'OO6', 'APOYO OTRAS AREAS NECESIDADES NNAJ', 'Se registran acciones de remisión a las diferentes áresa de atención en la Unidad y áreas de SE3.', 1, 1, 1, NULL, NULL),
	(444, 8, 163, 'TRPP', 'DEL PROCESO DE PREVENCION', 'Se crea este parametro de cargue para el seguimiento de los NNAJ que participan de los procesos de prevencion territorial, en las diferentes localidades de la ciudad. Esto con el fin de poder observar el proceso evolutivo de cada NNAJ, participantes de las diferentes lineas de accion territorial. Este seguimiento se llevara a cabo dos veces al mes.', 1, 1, 1, NULL, NULL),
	(445, 8, 164, 'TRRT', 'DE TRANSLADO A UPI', 'Se crea este parametro de cargue para el seguimiento de los NNAJ que participan de los procesos de prevencion territorial, en las diferentes localidades de la ciudad. Esto con el fin de poder observar el proceso evolutivo de cada NNAJ, participantes de las diferentes lineas de accion territorial.', 1, 1, 1, NULL, NULL),
	(446, 8, 165, 'TFDT', 'DESTREZAS Y TALENTO', '0', 0, 1, 1, NULL, NULL),
	(447, 8, 165, '008', 'FOMENTO PARA UNA SANA CONVIVENCIA.', 'Se registran los encuentros y/o intervenciones que se realicen con los NNAJ, frente a espacios de reflexión, connotaciones positivas y reconocimientos al cumplimiento de logros, abordajes motivacionales, arreglo de situaciones entre las partes cuando se presenten conflictos, entre otros.', 1, 1, 1, NULL, NULL),
	(448, 8, 165, '003', 'NOVEDADES', 'Hace referencia a las situaciones especiales que se presentan cuando se encuentran los NNAJ bajo su cuidado y acompañamiento (Situaciones de salud, Visitas de familiares)', 1, 1, 1, NULL, NULL),
	(449, 8, 165, 'RYES', 'RECONOCIMIENTO Y ESTIMULO', '0', 0, 1, 1, NULL, NULL),
	(450, 8, 165, 'TRRP', 'TERRITORIOS/PERMANENCIA', 'Se crea este parametro de cargue para el seguimiento de los NNAJ que participan de los procesos de prevencion territorial, en las diferentes localidades de la ciudad. Esto con el fin de poder observar el proceso evolutivo de cada NNAJ, participantes de las diferentes lineas de accion territorial.', 1, 1, 1, NULL, NULL),
	(451, 8, 166, 'CAEN', 'NUTRICIÓN', 'Se requiere crear un parametro que permita que el área de Nutrición registrar FOS diarias, en relación a los seguimientos, observaciones o cualquier novedad que de los jóvenes requiera ser registrada en relación a esta área.', 1, 1, 1, NULL, NULL);