<?php
require_once('web_indicado.php');
require_once('web_areaindi.php');
require_once('web_indiarea.php');
require_once('web_indiliba.php');
require_once('web_libagrup.php');
require_once('web_grupregu.php');
require_once('web_pregresp.php');
require_once('web_linebase.php');
