<?php



use Illuminate\Database\Seeder;

class CsdBienvenidasTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('csd_bienvenidas')->delete();
        
        \DB::table('csd_bienvenidas')->insert(array (
            0 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '78',
                'id' => '1',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            1 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '14',
                'id' => '2',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            2 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '19',
                'id' => '3',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            3 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '6',
                'id' => '4',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            4 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '16',
                'id' => '5',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            5 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '36',
                'id' => '6',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            6 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '70',
                'id' => '7',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            7 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '33',
                'id' => '8',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            8 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '66',
                'id' => '9',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            9 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '32',
                'id' => '10',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            10 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '83',
                'id' => '11',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            11 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '25',
                'id' => '12',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            12 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '29',
                'id' => '13',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            13 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '85',
                'id' => '14',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            14 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '87',
                'id' => '15',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            15 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '48',
                'id' => '16',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            16 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '54',
                'id' => '17',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            17 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '10',
                'id' => '18',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            18 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '8',
                'id' => '19',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            19 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '13',
                'id' => '20',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            20 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '51',
                'id' => '21',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            21 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '15',
                'id' => '22',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            22 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '67',
                'id' => '23',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            23 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '7',
                'id' => '24',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            24 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '12',
                'id' => '25',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            25 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '11',
                'id' => '26',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            26 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '43',
                'id' => '27',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            27 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '80',
                'id' => '28',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            28 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '73',
                'id' => '29',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            29 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '63',
                'id' => '30',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            30 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '40',
                'id' => '31',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            31 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '53',
                'id' => '32',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            32 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '41',
                'id' => '33',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            33 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '52',
                'id' => '34',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            34 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '49',
                'id' => '35',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            35 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '2',
                'id' => '36',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            36 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '18',
                'id' => '37',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            37 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '86',
                'id' => '38',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            38 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '20',
                'id' => '39',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            39 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '72',
                'id' => '40',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            40 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '39',
                'id' => '41',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            41 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '26',
                'id' => '42',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            42 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '55',
                'id' => '43',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            43 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '71',
                'id' => '44',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            44 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '57',
                'id' => '45',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            45 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '90',
                'id' => '46',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            46 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '75',
                'id' => '47',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            47 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '23',
                'id' => '48',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            48 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '31',
                'id' => '49',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            49 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '69',
                'id' => '50',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            50 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '82',
                'id' => '51',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            51 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '5',
                'id' => '52',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            52 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '17',
                'id' => '53',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            53 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '79',
                'id' => '54',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            54 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '42',
                'id' => '55',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            55 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '22',
                'id' => '56',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            56 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '68',
                'id' => '57',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            57 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '47',
                'id' => '58',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            58 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '37',
                'id' => '59',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            59 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '81',
                'id' => '60',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            60 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '1',
                'id' => '61',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            61 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '56',
                'id' => '62',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            62 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '89',
                'id' => '63',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            63 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '21',
                'id' => '64',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            64 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '91',
                'id' => '65',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            65 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '77',
                'id' => '66',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            66 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '62',
                'id' => '67',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            67 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '45',
                'id' => '68',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            68 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '59',
                'id' => '69',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            69 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '65',
                'id' => '70',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            70 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '61',
                'id' => '71',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            71 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '60',
                'id' => '72',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            72 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '34',
                'id' => '73',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            73 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '64',
                'id' => '74',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            74 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '38',
                'id' => '75',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            75 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '46',
                'id' => '76',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            76 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '24',
                'id' => '77',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            77 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '74',
                'id' => '78',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            78 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '92',
                'id' => '79',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            79 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'prm_tipofuen_id' => '2316',
                'prm_persona_id' => '2316',
                'csd_id' => '27',
                'id' => '80',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:10',
                'created_at' => '2021-04-27 12:01:10',
            ),
            80 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'prm_tipofuen_id' => '2315',
                'prm_persona_id' => '859',
                'csd_id' => '96',
                'id' => '84',
                'deleted_at' => NULL,
                'updated_at' => '2021-06-02 20:16:25',
                'created_at' => '2021-06-02 20:16:25',
            ),
            81 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'prm_tipofuen_id' => '2315',
                'prm_persona_id' => '857',
                'csd_id' => '94',
                'id' => '81',
                'deleted_at' => NULL,
                'updated_at' => '2021-05-25 11:11:41',
                'created_at' => '2021-05-25 11:11:41',
            ),
            82 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'prm_tipofuen_id' => '2315',
                'prm_persona_id' => '859',
                'csd_id' => '95',
                'id' => '83',
                'deleted_at' => NULL,
                'updated_at' => '2021-05-27 14:51:57',
                'created_at' => '2021-05-27 14:51:57',
            ),
            83 => 
            array (
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'prm_tipofuen_id' => '2315',
                'prm_persona_id' => '857',
                'csd_id' => '93',
                'id' => '82',
                'deleted_at' => NULL,
                'updated_at' => '2021-05-27 10:48:54',
                'created_at' => '2021-05-27 10:48:54',
            ),
        ));
        
        
    }
}