<?php



use Illuminate\Database\Seeder;

class VsiBienvenidaMotivoTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vsi_bienvenida_motivo')->delete();
        
        \DB::table('vsi_bienvenida_motivo')->insert(array (
            0 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '332',
                'id' => '85',
            ),
            1 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '332',
                'id' => '86',
            ),
            2 => 
            array (
                'sys_nc00011$' => '337',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '337',
                'id' => '97',
            ),
            3 => 
            array (
                'sys_nc00011$' => '337',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '337',
                'id' => '98',
            ),
            4 => 
            array (
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '344',
                'id' => '110',
            ),
            5 => 
            array (
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '344',
                'id' => '111',
            ),
            6 => 
            array (
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '344',
                'id' => '112',
            ),
            7 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '335',
                'id' => '91',
            ),
            8 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '764',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '764',
                'vsi_bienvenida_id' => '335',
                'id' => '92',
            ),
            9 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '335',
                'id' => '93',
            ),
            10 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '335',
                'id' => '94',
            ),
            11 => 
            array (
                'sys_nc00011$' => '338',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '338',
                'id' => '99',
            ),
            12 => 
            array (
                'sys_nc00011$' => '338',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '338',
                'id' => '100',
            ),
            13 => 
            array (
                'sys_nc00011$' => '345',
                'sys_nc00010$' => '764',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'parametro_id' => '764',
                'vsi_bienvenida_id' => '345',
                'id' => '113',
            ),
            14 => 
            array (
                'sys_nc00011$' => '345',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '345',
                'id' => '114',
            ),
            15 => 
            array (
                'sys_nc00011$' => '345',
                'sys_nc00010$' => '769',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'parametro_id' => '769',
                'vsi_bienvenida_id' => '345',
                'id' => '115',
            ),
            16 => 
            array (
                'sys_nc00011$' => '347',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '347',
                'id' => '117',
            ),
            17 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2035',
                'user_crea_id' => '2035',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '348',
                'id' => '118',
            ),
            18 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '764',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2035',
                'user_crea_id' => '2035',
                'parametro_id' => '764',
                'vsi_bienvenida_id' => '348',
                'id' => '119',
            ),
            19 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2035',
                'user_crea_id' => '2035',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '348',
                'id' => '120',
            ),
            20 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '769',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2035',
                'user_crea_id' => '2035',
                'parametro_id' => '769',
                'vsi_bienvenida_id' => '348',
                'id' => '121',
            ),
            21 => 
            array (
                'sys_nc00011$' => '4',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '4',
                'id' => '1',
            ),
            22 => 
            array (
                'sys_nc00011$' => '12',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '12',
                'id' => '2',
            ),
            23 => 
            array (
                'sys_nc00011$' => '19',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '19',
                'id' => '3',
            ),
            24 => 
            array (
                'sys_nc00011$' => '20',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '20',
                'id' => '4',
            ),
            25 => 
            array (
                'sys_nc00011$' => '25',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '25',
                'id' => '5',
            ),
            26 => 
            array (
                'sys_nc00011$' => '39',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '39',
                'id' => '6',
            ),
            27 => 
            array (
                'sys_nc00011$' => '46',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '46',
                'id' => '7',
            ),
            28 => 
            array (
                'sys_nc00011$' => '48',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '48',
                'id' => '8',
            ),
            29 => 
            array (
                'sys_nc00011$' => '49',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '49',
                'id' => '9',
            ),
            30 => 
            array (
                'sys_nc00011$' => '58',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '58',
                'id' => '10',
            ),
            31 => 
            array (
                'sys_nc00011$' => '73',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '73',
                'id' => '11',
            ),
            32 => 
            array (
                'sys_nc00011$' => '113',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '113',
                'id' => '12',
            ),
            33 => 
            array (
                'sys_nc00011$' => '151',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '151',
                'id' => '13',
            ),
            34 => 
            array (
                'sys_nc00011$' => '160',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '160',
                'id' => '14',
            ),
            35 => 
            array (
                'sys_nc00011$' => '181',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '181',
                'id' => '15',
            ),
            36 => 
            array (
                'sys_nc00011$' => '197',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '197',
                'id' => '16',
            ),
            37 => 
            array (
                'sys_nc00011$' => '199',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '199',
                'id' => '17',
            ),
            38 => 
            array (
                'sys_nc00011$' => '209',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '209',
                'id' => '18',
            ),
            39 => 
            array (
                'sys_nc00011$' => '246',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '246',
                'id' => '19',
            ),
            40 => 
            array (
                'sys_nc00011$' => '257',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '257',
                'id' => '20',
            ),
            41 => 
            array (
                'sys_nc00011$' => '258',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '258',
                'id' => '21',
            ),
            42 => 
            array (
                'sys_nc00011$' => '268',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '268',
                'id' => '22',
            ),
            43 => 
            array (
                'sys_nc00011$' => '270',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '270',
                'id' => '23',
            ),
            44 => 
            array (
                'sys_nc00011$' => '278',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '278',
                'id' => '24',
            ),
            45 => 
            array (
                'sys_nc00011$' => '286',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '286',
                'id' => '25',
            ),
            46 => 
            array (
                'sys_nc00011$' => '289',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '289',
                'id' => '26',
            ),
            47 => 
            array (
                'sys_nc00011$' => '296',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '296',
                'id' => '27',
            ),
            48 => 
            array (
                'sys_nc00011$' => '297',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '297',
                'id' => '28',
            ),
            49 => 
            array (
                'sys_nc00011$' => '301',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '301',
                'id' => '29',
            ),
            50 => 
            array (
                'sys_nc00011$' => '307',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '307',
                'id' => '30',
            ),
            51 => 
            array (
                'sys_nc00011$' => '12',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '12',
                'id' => '31',
            ),
            52 => 
            array (
                'sys_nc00011$' => '17',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '17',
                'id' => '32',
            ),
            53 => 
            array (
                'sys_nc00011$' => '34',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '34',
                'id' => '33',
            ),
            54 => 
            array (
                'sys_nc00011$' => '35',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '35',
                'id' => '34',
            ),
            55 => 
            array (
                'sys_nc00011$' => '37',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '37',
                'id' => '35',
            ),
            56 => 
            array (
                'sys_nc00011$' => '39',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '39',
                'id' => '36',
            ),
            57 => 
            array (
                'sys_nc00011$' => '50',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '50',
                'id' => '37',
            ),
            58 => 
            array (
                'sys_nc00011$' => '51',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '51',
                'id' => '38',
            ),
            59 => 
            array (
                'sys_nc00011$' => '52',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '52',
                'id' => '39',
            ),
            60 => 
            array (
                'sys_nc00011$' => '60',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '60',
                'id' => '40',
            ),
            61 => 
            array (
                'sys_nc00011$' => '70',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '70',
                'id' => '41',
            ),
            62 => 
            array (
                'sys_nc00011$' => '73',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '73',
                'id' => '42',
            ),
            63 => 
            array (
                'sys_nc00011$' => '75',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '75',
                'id' => '43',
            ),
            64 => 
            array (
                'sys_nc00011$' => '80',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '80',
                'id' => '44',
            ),
            65 => 
            array (
                'sys_nc00011$' => '87',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '87',
                'id' => '45',
            ),
            66 => 
            array (
                'sys_nc00011$' => '137',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '137',
                'id' => '46',
            ),
            67 => 
            array (
                'sys_nc00011$' => '141',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '141',
                'id' => '47',
            ),
            68 => 
            array (
                'sys_nc00011$' => '144',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '144',
                'id' => '48',
            ),
            69 => 
            array (
                'sys_nc00011$' => '176',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '176',
                'id' => '49',
            ),
            70 => 
            array (
                'sys_nc00011$' => '177',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '177',
                'id' => '50',
            ),
            71 => 
            array (
                'sys_nc00011$' => '183',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '183',
                'id' => '51',
            ),
            72 => 
            array (
                'sys_nc00011$' => '200',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '200',
                'id' => '52',
            ),
            73 => 
            array (
                'sys_nc00011$' => '203',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '203',
                'id' => '53',
            ),
            74 => 
            array (
                'sys_nc00011$' => '205',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '205',
                'id' => '54',
            ),
            75 => 
            array (
                'sys_nc00011$' => '206',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '206',
                'id' => '55',
            ),
            76 => 
            array (
                'sys_nc00011$' => '259',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '259',
                'id' => '56',
            ),
            77 => 
            array (
                'sys_nc00011$' => '263',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '263',
                'id' => '57',
            ),
            78 => 
            array (
                'sys_nc00011$' => '268',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '268',
                'id' => '58',
            ),
            79 => 
            array (
                'sys_nc00011$' => '270',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '270',
                'id' => '59',
            ),
            80 => 
            array (
                'sys_nc00011$' => '278',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '278',
                'id' => '60',
            ),
            81 => 
            array (
                'sys_nc00011$' => '286',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '286',
                'id' => '61',
            ),
            82 => 
            array (
                'sys_nc00011$' => '17',
                'sys_nc00010$' => '763',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '763',
                'vsi_bienvenida_id' => '17',
                'id' => '62',
            ),
            83 => 
            array (
                'sys_nc00011$' => '4',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '4',
                'id' => '63',
            ),
            84 => 
            array (
                'sys_nc00011$' => '141',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '141',
                'id' => '64',
            ),
            85 => 
            array (
                'sys_nc00011$' => '151',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '151',
                'id' => '65',
            ),
            86 => 
            array (
                'sys_nc00011$' => '263',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '263',
                'id' => '66',
            ),
            87 => 
            array (
                'sys_nc00011$' => '268',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '268',
                'id' => '67',
            ),
            88 => 
            array (
                'sys_nc00011$' => '274',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '274',
                'id' => '68',
            ),
            89 => 
            array (
                'sys_nc00011$' => '278',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '278',
                'id' => '69',
            ),
            90 => 
            array (
                'sys_nc00011$' => '308',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '308',
                'id' => '70',
            ),
            91 => 
            array (
                'sys_nc00011$' => '4',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '4',
                'id' => '71',
            ),
            92 => 
            array (
                'sys_nc00011$' => '146',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '146',
                'id' => '72',
            ),
            93 => 
            array (
                'sys_nc00011$' => '195',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '195',
                'id' => '73',
            ),
            94 => 
            array (
                'sys_nc00011$' => '263',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '263',
                'id' => '74',
            ),
            95 => 
            array (
                'sys_nc00011$' => '2',
                'sys_nc00010$' => '769',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '769',
                'vsi_bienvenida_id' => '2',
                'id' => '75',
            ),
            96 => 
            array (
                'sys_nc00011$' => '151',
                'sys_nc00010$' => '769',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '769',
                'vsi_bienvenida_id' => '151',
                'id' => '76',
            ),
            97 => 
            array (
                'sys_nc00011$' => '316',
                'sys_nc00010$' => '769',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '769',
                'vsi_bienvenida_id' => '316',
                'id' => '77',
            ),
            98 => 
            array (
                'sys_nc00011$' => '7',
                'sys_nc00010$' => '2317',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '2317',
                'vsi_bienvenida_id' => '7',
                'id' => '78',
            ),
            99 => 
            array (
                'sys_nc00011$' => '82',
                'sys_nc00010$' => '2317',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '2317',
                'vsi_bienvenida_id' => '82',
                'id' => '79',
            ),
            100 => 
            array (
                'sys_nc00011$' => '98',
                'sys_nc00010$' => '2317',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '2317',
                'vsi_bienvenida_id' => '98',
                'id' => '80',
            ),
            101 => 
            array (
                'sys_nc00011$' => '99',
                'sys_nc00010$' => '2317',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '2317',
                'vsi_bienvenida_id' => '99',
                'id' => '81',
            ),
            102 => 
            array (
                'sys_nc00011$' => '106',
                'sys_nc00010$' => '2317',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '2317',
                'vsi_bienvenida_id' => '106',
                'id' => '82',
            ),
            103 => 
            array (
                'sys_nc00011$' => '233',
                'sys_nc00010$' => '2317',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '2317',
                'vsi_bienvenida_id' => '233',
                'id' => '83',
            ),
            104 => 
            array (
                'sys_nc00011$' => '259',
                'sys_nc00010$' => '2317',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:22',
                'created_at' => '2021-04-27 12:01:22',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'parametro_id' => '2317',
                'vsi_bienvenida_id' => '259',
                'id' => '84',
            ),
            105 => 
            array (
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '333',
                'id' => '87',
            ),
            106 => 
            array (
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '333',
                'id' => '88',
            ),
            107 => 
            array (
                'sys_nc00011$' => '334',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '334',
                'id' => '89',
            ),
            108 => 
            array (
                'sys_nc00011$' => '334',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '334',
                'id' => '90',
            ),
            109 => 
            array (
                'sys_nc00011$' => '336',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '336',
                'id' => '95',
            ),
            110 => 
            array (
                'sys_nc00011$' => '336',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '336',
                'id' => '96',
            ),
            111 => 
            array (
                'sys_nc00011$' => '342',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '342',
                'id' => '106',
            ),
            112 => 
            array (
                'sys_nc00011$' => '342',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '342',
                'id' => '107',
            ),
            113 => 
            array (
                'sys_nc00011$' => '346',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '346',
                'id' => '116',
            ),
            114 => 
            array (
                'sys_nc00011$' => '340',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '340',
                'id' => '102',
            ),
            115 => 
            array (
                'sys_nc00011$' => '340',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '340',
                'id' => '103',
            ),
            116 => 
            array (
                'sys_nc00011$' => '340',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '340',
                'id' => '104',
            ),
            117 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '762',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '762',
                'vsi_bienvenida_id' => '343',
                'id' => '108',
            ),
            118 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '766',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'parametro_id' => '766',
                'vsi_bienvenida_id' => '343',
                'id' => '109',
            ),
            119 => 
            array (
                'sys_nc00011$' => '339',
                'sys_nc00010$' => '761',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'parametro_id' => '761',
                'vsi_bienvenida_id' => '339',
                'id' => '101',
            ),
            120 => 
            array (
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '765',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'parametro_id' => '765',
                'vsi_bienvenida_id' => '341',
                'id' => '105',
            ),
        ));
        
        
    }
}