<?php



use Illuminate\Database\Seeder;

class VsiNnajEmocionalTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vsi_nnaj_emocional')->delete();
        
        \DB::table('vsi_nnaj_emocional')->insert(array (
            0 => 
            array (
                'sys_nc00011$' => '356',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_id' => '356',
                'parametro_id' => '871',
                'id' => '85',
            ),
            1 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '348',
                'parametro_id' => '869',
                'id' => '79',
            ),
            2 => 
            array (
                'sys_nc00011$' => '352',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'vsi_id' => '352',
                'parametro_id' => '871',
                'id' => '81',
            ),
            3 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '332',
                'parametro_id' => '869',
                'id' => '58',
            ),
            4 => 
            array (
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '333',
                'parametro_id' => '871',
                'id' => '59',
            ),
            5 => 
            array (
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_id' => '344',
                'parametro_id' => '871',
                'id' => '80',
            ),
            6 => 
            array (
                'sys_nc00011$' => '355',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_id' => '355',
                'parametro_id' => '866',
                'id' => '82',
            ),
            7 => 
            array (
                'sys_nc00011$' => '338',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '338',
                'parametro_id' => '869',
                'id' => '69',
            ),
            8 => 
            array (
                'sys_nc00011$' => '338',
                'sys_nc00010$' => '870',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '338',
                'parametro_id' => '870',
                'id' => '70',
            ),
            9 => 
            array (
                'sys_nc00011$' => '355',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_id' => '355',
                'parametro_id' => '869',
                'id' => '83',
            ),
            10 => 
            array (
                'sys_nc00011$' => '355',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_id' => '355',
                'parametro_id' => '871',
                'id' => '84',
            ),
            11 => 
            array (
                'sys_nc00011$' => '4',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '4',
                'parametro_id' => '865',
                'id' => '1',
            ),
            12 => 
            array (
                'sys_nc00011$' => '7',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '7',
                'parametro_id' => '865',
                'id' => '2',
            ),
            13 => 
            array (
                'sys_nc00011$' => '37',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '37',
                'parametro_id' => '865',
                'id' => '3',
            ),
            14 => 
            array (
                'sys_nc00011$' => '73',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '73',
                'parametro_id' => '865',
                'id' => '4',
            ),
            15 => 
            array (
                'sys_nc00011$' => '177',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '177',
                'parametro_id' => '865',
                'id' => '5',
            ),
            16 => 
            array (
                'sys_nc00011$' => '181',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '181',
                'parametro_id' => '865',
                'id' => '6',
            ),
            17 => 
            array (
                'sys_nc00011$' => '200',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '200',
                'parametro_id' => '865',
                'id' => '7',
            ),
            18 => 
            array (
                'sys_nc00011$' => '209',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '209',
                'parametro_id' => '865',
                'id' => '8',
            ),
            19 => 
            array (
                'sys_nc00011$' => '268',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '268',
                'parametro_id' => '865',
                'id' => '9',
            ),
            20 => 
            array (
                'sys_nc00011$' => '274',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '274',
                'parametro_id' => '865',
                'id' => '10',
            ),
            21 => 
            array (
                'sys_nc00011$' => '296',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '296',
                'parametro_id' => '865',
                'id' => '11',
            ),
            22 => 
            array (
                'sys_nc00011$' => '2',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '2',
                'parametro_id' => '866',
                'id' => '12',
            ),
            23 => 
            array (
                'sys_nc00011$' => '35',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '35',
                'parametro_id' => '866',
                'id' => '13',
            ),
            24 => 
            array (
                'sys_nc00011$' => '46',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '46',
                'parametro_id' => '866',
                'id' => '14',
            ),
            25 => 
            array (
                'sys_nc00011$' => '48',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '48',
                'parametro_id' => '866',
                'id' => '15',
            ),
            26 => 
            array (
                'sys_nc00011$' => '49',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '49',
                'parametro_id' => '866',
                'id' => '16',
            ),
            27 => 
            array (
                'sys_nc00011$' => '51',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '51',
                'parametro_id' => '866',
                'id' => '17',
            ),
            28 => 
            array (
                'sys_nc00011$' => '80',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '80',
                'parametro_id' => '866',
                'id' => '18',
            ),
            29 => 
            array (
                'sys_nc00011$' => '146',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '146',
                'parametro_id' => '866',
                'id' => '19',
            ),
            30 => 
            array (
                'sys_nc00011$' => '160',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '160',
                'parametro_id' => '866',
                'id' => '20',
            ),
            31 => 
            array (
                'sys_nc00011$' => '181',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '181',
                'parametro_id' => '866',
                'id' => '21',
            ),
            32 => 
            array (
                'sys_nc00011$' => '203',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '203',
                'parametro_id' => '866',
                'id' => '22',
            ),
            33 => 
            array (
                'sys_nc00011$' => '286',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '286',
                'parametro_id' => '866',
                'id' => '23',
            ),
            34 => 
            array (
                'sys_nc00011$' => '301',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '301',
                'parametro_id' => '866',
                'id' => '24',
            ),
            35 => 
            array (
                'sys_nc00011$' => '307',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '307',
                'parametro_id' => '866',
                'id' => '25',
            ),
            36 => 
            array (
                'sys_nc00011$' => '316',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '316',
                'parametro_id' => '866',
                'id' => '26',
            ),
            37 => 
            array (
                'sys_nc00011$' => '80',
                'sys_nc00010$' => '867',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '80',
                'parametro_id' => '867',
                'id' => '27',
            ),
            38 => 
            array (
                'sys_nc00011$' => '274',
                'sys_nc00010$' => '867',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '274',
                'parametro_id' => '867',
                'id' => '28',
            ),
            39 => 
            array (
                'sys_nc00011$' => '146',
                'sys_nc00010$' => '868',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '146',
                'parametro_id' => '868',
                'id' => '29',
            ),
            40 => 
            array (
                'sys_nc00011$' => '246',
                'sys_nc00010$' => '868',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '246',
                'parametro_id' => '868',
                'id' => '30',
            ),
            41 => 
            array (
                'sys_nc00011$' => '7',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '7',
                'parametro_id' => '869',
                'id' => '31',
            ),
            42 => 
            array (
                'sys_nc00011$' => '113',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '113',
                'parametro_id' => '869',
                'id' => '32',
            ),
            43 => 
            array (
                'sys_nc00011$' => '141',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '141',
                'parametro_id' => '869',
                'id' => '33',
            ),
            44 => 
            array (
                'sys_nc00011$' => '176',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '176',
                'parametro_id' => '869',
                'id' => '34',
            ),
            45 => 
            array (
                'sys_nc00011$' => '206',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '206',
                'parametro_id' => '869',
                'id' => '35',
            ),
            46 => 
            array (
                'sys_nc00011$' => '257',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '257',
                'parametro_id' => '869',
                'id' => '36',
            ),
            47 => 
            array (
                'sys_nc00011$' => '270',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '270',
                'parametro_id' => '869',
                'id' => '37',
            ),
            48 => 
            array (
                'sys_nc00011$' => '2',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '2',
                'parametro_id' => '871',
                'id' => '38',
            ),
            49 => 
            array (
                'sys_nc00011$' => '7',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '7',
                'parametro_id' => '871',
                'id' => '39',
            ),
            50 => 
            array (
                'sys_nc00011$' => '12',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '12',
                'parametro_id' => '871',
                'id' => '40',
            ),
            51 => 
            array (
                'sys_nc00011$' => '19',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '19',
                'parametro_id' => '871',
                'id' => '41',
            ),
            52 => 
            array (
                'sys_nc00011$' => '20',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '20',
                'parametro_id' => '871',
                'id' => '42',
            ),
            53 => 
            array (
                'sys_nc00011$' => '34',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '34',
                'parametro_id' => '871',
                'id' => '43',
            ),
            54 => 
            array (
                'sys_nc00011$' => '39',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '39',
                'parametro_id' => '871',
                'id' => '44',
            ),
            55 => 
            array (
                'sys_nc00011$' => '52',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '52',
                'parametro_id' => '871',
                'id' => '45',
            ),
            56 => 
            array (
                'sys_nc00011$' => '73',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '73',
                'parametro_id' => '871',
                'id' => '46',
            ),
            57 => 
            array (
                'sys_nc00011$' => '98',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '98',
                'parametro_id' => '871',
                'id' => '47',
            ),
            58 => 
            array (
                'sys_nc00011$' => '99',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '99',
                'parametro_id' => '871',
                'id' => '48',
            ),
            59 => 
            array (
                'sys_nc00011$' => '141',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '141',
                'parametro_id' => '871',
                'id' => '49',
            ),
            60 => 
            array (
                'sys_nc00011$' => '160',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '160',
                'parametro_id' => '871',
                'id' => '50',
            ),
            61 => 
            array (
                'sys_nc00011$' => '177',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '177',
                'parametro_id' => '871',
                'id' => '51',
            ),
            62 => 
            array (
                'sys_nc00011$' => '197',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '197',
                'parametro_id' => '871',
                'id' => '52',
            ),
            63 => 
            array (
                'sys_nc00011$' => '200',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '200',
                'parametro_id' => '871',
                'id' => '53',
            ),
            64 => 
            array (
                'sys_nc00011$' => '268',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '268',
                'parametro_id' => '871',
                'id' => '54',
            ),
            65 => 
            array (
                'sys_nc00011$' => '289',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '289',
                'parametro_id' => '871',
                'id' => '55',
            ),
            66 => 
            array (
                'sys_nc00011$' => '297',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '297',
                'parametro_id' => '871',
                'id' => '56',
            ),
            67 => 
            array (
                'sys_nc00011$' => '321',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:51',
                'created_at' => '2021-04-27 12:01:51',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_id' => '321',
                'parametro_id' => '871',
                'id' => '57',
            ),
            68 => 
            array (
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '868',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'vsi_id' => '341',
                'parametro_id' => '868',
                'id' => '74',
            ),
            69 => 
            array (
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'vsi_id' => '341',
                'parametro_id' => '869',
                'id' => '75',
            ),
            70 => 
            array (
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'vsi_id' => '341',
                'parametro_id' => '871',
                'id' => '76',
            ),
            71 => 
            array (
                'sys_nc00011$' => '334',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '334',
                'parametro_id' => '865',
                'id' => '64',
            ),
            72 => 
            array (
                'sys_nc00011$' => '334',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '334',
                'parametro_id' => '869',
                'id' => '65',
            ),
            73 => 
            array (
                'sys_nc00011$' => '339',
                'sys_nc00010$' => '865',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'vsi_id' => '339',
                'parametro_id' => '865',
                'id' => '71',
            ),
            74 => 
            array (
                'sys_nc00011$' => '339',
                'sys_nc00010$' => '867',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'vsi_id' => '339',
                'parametro_id' => '867',
                'id' => '72',
            ),
            75 => 
            array (
                'sys_nc00011$' => '339',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '45',
                'user_crea_id' => '45',
                'vsi_id' => '339',
                'parametro_id' => '871',
                'id' => '73',
            ),
            76 => 
            array (
                'sys_nc00011$' => '336',
                'sys_nc00010$' => '871',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_id' => '336',
                'parametro_id' => '871',
                'id' => '66',
            ),
            77 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '335',
                'parametro_id' => '869',
                'id' => '67',
            ),
            78 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '870',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '335',
                'parametro_id' => '870',
                'id' => '68',
            ),
            79 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '866',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '343',
                'parametro_id' => '866',
                'id' => '77',
            ),
            80 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '869',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_id' => '343',
                'parametro_id' => '869',
                'id' => '78',
            ),
        ));
        
        
    }
}