<?php



use Illuminate\Database\Seeder;

class VsiRelfamMotivoTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vsi_relfam_motivo')->delete();
        
        \DB::table('vsi_relfam_motivo')->insert(array (
            0 => 
            array (
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '665',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_relfamiliar_id' => '332',
                'parametro_id' => '665',
                'id' => '44',
            ),
            1 => 
            array (
                'sys_nc00011$' => '334',
                'sys_nc00010$' => '665',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_relfamiliar_id' => '334',
                'parametro_id' => '665',
                'id' => '47',
            ),
            2 => 
            array (
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '335',
                'parametro_id' => '904',
                'id' => '48',
            ),
            3 => 
            array (
                'sys_nc00011$' => '337',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_relfamiliar_id' => '337',
                'parametro_id' => '904',
                'id' => '50',
            ),
            4 => 
            array (
                'sys_nc00011$' => '347',
                'sys_nc00010$' => '960',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2132',
                'user_crea_id' => '2132',
                'vsi_relfamiliar_id' => '347',
                'parametro_id' => '960',
                'id' => '63',
            ),
            5 => 
            array (
                'sys_nc00011$' => '348',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2035',
                'user_crea_id' => '2035',
                'vsi_relfamiliar_id' => '348',
                'parametro_id' => '904',
                'id' => '64',
            ),
            6 => 
            array (
                'sys_nc00011$' => '37',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '37',
                'parametro_id' => '664',
                'id' => '1',
            ),
            7 => 
            array (
                'sys_nc00011$' => '82',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '82',
                'parametro_id' => '664',
                'id' => '2',
            ),
            8 => 
            array (
                'sys_nc00011$' => '199',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '199',
                'parametro_id' => '664',
                'id' => '3',
            ),
            9 => 
            array (
                'sys_nc00011$' => '308',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '308',
                'parametro_id' => '664',
                'id' => '4',
            ),
            10 => 
            array (
                'sys_nc00011$' => '263',
                'sys_nc00010$' => '665',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '263',
                'parametro_id' => '665',
                'id' => '5',
            ),
            11 => 
            array (
                'sys_nc00011$' => '2',
                'sys_nc00010$' => '807',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '2',
                'parametro_id' => '807',
                'id' => '6',
            ),
            12 => 
            array (
                'sys_nc00011$' => '51',
                'sys_nc00010$' => '807',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '51',
                'parametro_id' => '807',
                'id' => '7',
            ),
            13 => 
            array (
                'sys_nc00011$' => '52',
                'sys_nc00010$' => '807',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '52',
                'parametro_id' => '807',
                'id' => '8',
            ),
            14 => 
            array (
                'sys_nc00011$' => '113',
                'sys_nc00010$' => '807',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '113',
                'parametro_id' => '807',
                'id' => '9',
            ),
            15 => 
            array (
                'sys_nc00011$' => '3',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '3',
                'parametro_id' => '904',
                'id' => '10',
            ),
            16 => 
            array (
                'sys_nc00011$' => '19',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '19',
                'parametro_id' => '904',
                'id' => '11',
            ),
            17 => 
            array (
                'sys_nc00011$' => '39',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '39',
                'parametro_id' => '904',
                'id' => '12',
            ),
            18 => 
            array (
                'sys_nc00011$' => '58',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '58',
                'parametro_id' => '904',
                'id' => '13',
            ),
            19 => 
            array (
                'sys_nc00011$' => '70',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '70',
                'parametro_id' => '904',
                'id' => '14',
            ),
            20 => 
            array (
                'sys_nc00011$' => '73',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '73',
                'parametro_id' => '904',
                'id' => '15',
            ),
            21 => 
            array (
                'sys_nc00011$' => '80',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '80',
                'parametro_id' => '904',
                'id' => '16',
            ),
            22 => 
            array (
                'sys_nc00011$' => '141',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '141',
                'parametro_id' => '904',
                'id' => '17',
            ),
            23 => 
            array (
                'sys_nc00011$' => '195',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '195',
                'parametro_id' => '904',
                'id' => '18',
            ),
            24 => 
            array (
                'sys_nc00011$' => '197',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '197',
                'parametro_id' => '904',
                'id' => '19',
            ),
            25 => 
            array (
                'sys_nc00011$' => '199',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '199',
                'parametro_id' => '904',
                'id' => '20',
            ),
            26 => 
            array (
                'sys_nc00011$' => '200',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '200',
                'parametro_id' => '904',
                'id' => '21',
            ),
            27 => 
            array (
                'sys_nc00011$' => '203',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '203',
                'parametro_id' => '904',
                'id' => '22',
            ),
            28 => 
            array (
                'sys_nc00011$' => '206',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '206',
                'parametro_id' => '904',
                'id' => '23',
            ),
            29 => 
            array (
                'sys_nc00011$' => '257',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '257',
                'parametro_id' => '904',
                'id' => '24',
            ),
            30 => 
            array (
                'sys_nc00011$' => '258',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '258',
                'parametro_id' => '904',
                'id' => '25',
            ),
            31 => 
            array (
                'sys_nc00011$' => '259',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '259',
                'parametro_id' => '904',
                'id' => '26',
            ),
            32 => 
            array (
                'sys_nc00011$' => '268',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '268',
                'parametro_id' => '904',
                'id' => '27',
            ),
            33 => 
            array (
                'sys_nc00011$' => '274',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '274',
                'parametro_id' => '904',
                'id' => '28',
            ),
            34 => 
            array (
                'sys_nc00011$' => '286',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '286',
                'parametro_id' => '904',
                'id' => '29',
            ),
            35 => 
            array (
                'sys_nc00011$' => '304',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '304',
                'parametro_id' => '904',
                'id' => '30',
            ),
            36 => 
            array (
                'sys_nc00011$' => '307',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '307',
                'parametro_id' => '904',
                'id' => '31',
            ),
            37 => 
            array (
                'sys_nc00011$' => '199',
                'sys_nc00010$' => '957',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '199',
                'parametro_id' => '957',
                'id' => '32',
            ),
            38 => 
            array (
                'sys_nc00011$' => '139',
                'sys_nc00010$' => '958',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '139',
                'parametro_id' => '958',
                'id' => '33',
            ),
            39 => 
            array (
                'sys_nc00011$' => '4',
                'sys_nc00010$' => '960',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '4',
                'parametro_id' => '960',
                'id' => '34',
            ),
            40 => 
            array (
                'sys_nc00011$' => '278',
                'sys_nc00010$' => '960',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '278',
                'parametro_id' => '960',
                'id' => '35',
            ),
            41 => 
            array (
                'sys_nc00011$' => '296',
                'sys_nc00010$' => '960',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '296',
                'parametro_id' => '960',
                'id' => '36',
            ),
            42 => 
            array (
                'sys_nc00011$' => '176',
                'sys_nc00010$' => '961',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '176',
                'parametro_id' => '961',
                'id' => '37',
            ),
            43 => 
            array (
                'sys_nc00011$' => '7',
                'sys_nc00010$' => '962',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '7',
                'parametro_id' => '962',
                'id' => '38',
            ),
            44 => 
            array (
                'sys_nc00011$' => '12',
                'sys_nc00010$' => '962',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '12',
                'parametro_id' => '962',
                'id' => '39',
            ),
            45 => 
            array (
                'sys_nc00011$' => '34',
                'sys_nc00010$' => '962',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '34',
                'parametro_id' => '962',
                'id' => '40',
            ),
            46 => 
            array (
                'sys_nc00011$' => '46',
                'sys_nc00010$' => '962',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '46',
                'parametro_id' => '962',
                'id' => '41',
            ),
            47 => 
            array (
                'sys_nc00011$' => '187',
                'sys_nc00010$' => '962',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '187',
                'parametro_id' => '962',
                'id' => '42',
            ),
            48 => 
            array (
                'sys_nc00011$' => '270',
                'sys_nc00010$' => '962',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:31',
                'created_at' => '2021-04-27 12:01:31',
                'sis_esta_id' => '1',
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_relfamiliar_id' => '270',
                'parametro_id' => '962',
                'id' => '43',
            ),
            49 => 
            array (
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '333',
                'parametro_id' => '664',
                'id' => '45',
            ),
            50 => 
            array (
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '665',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '333',
                'parametro_id' => '665',
                'id' => '46',
            ),
            51 => 
            array (
                'sys_nc00011$' => '336',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_relfamiliar_id' => '336',
                'parametro_id' => '664',
                'id' => '49',
            ),
            52 => 
            array (
                'sys_nc00011$' => '338',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'vsi_relfamiliar_id' => '338',
                'parametro_id' => '664',
                'id' => '51',
            ),
            53 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '343',
                'parametro_id' => '904',
                'id' => '57',
            ),
            54 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '961',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '343',
                'parametro_id' => '961',
                'id' => '58',
            ),
            55 => 
            array (
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '962',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '343',
                'parametro_id' => '962',
                'id' => '59',
            ),
            56 => 
            array (
                'sys_nc00011$' => '345',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1196',
                'user_crea_id' => '1196',
                'vsi_relfamiliar_id' => '345',
                'parametro_id' => '904',
                'id' => '62',
            ),
            57 => 
            array (
                'sys_nc00011$' => '340',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '340',
                'parametro_id' => '664',
                'id' => '52',
            ),
            58 => 
            array (
                'sys_nc00011$' => '340',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '340',
                'parametro_id' => '904',
                'id' => '53',
            ),
            59 => 
            array (
                'sys_nc00011$' => '342',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '342',
                'parametro_id' => '904',
                'id' => '54',
            ),
            60 => 
            array (
                'sys_nc00011$' => '342',
                'sys_nc00010$' => '960',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '342',
                'parametro_id' => '960',
                'id' => '55',
            ),
            61 => 
            array (
                'sys_nc00011$' => '342',
                'sys_nc00010$' => '962',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_relfamiliar_id' => '342',
                'parametro_id' => '962',
                'id' => '56',
            ),
            62 => 
            array (
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '664',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'vsi_relfamiliar_id' => '344',
                'parametro_id' => '664',
                'id' => '60',
            ),
            63 => 
            array (
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '904',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'vsi_relfamiliar_id' => '344',
                'parametro_id' => '904',
                'id' => '61',
            ),
        ));
        
        
    }
}