<?php



use Illuminate\Database\Seeder;

class VsiSitespRiesgoTableMigSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vsi_sitesp_riesgo')->delete();
        
        \DB::table('vsi_sitesp_riesgo')->insert(array (
            0 => 
            array (
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_sitespecial_id' => '335',
                'parametro_id' => '853',
                'id' => '55',
                'sys_nc00011$' => '335',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            1 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '7',
                'parametro_id' => '853',
                'id' => '1',
                'sys_nc00011$' => '7',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            2 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '12',
                'parametro_id' => '853',
                'id' => '2',
                'sys_nc00011$' => '12',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            3 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '17',
                'parametro_id' => '853',
                'id' => '3',
                'sys_nc00011$' => '17',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            4 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '19',
                'parametro_id' => '168',
                'id' => '4',
                'sys_nc00011$' => '19',
                'sys_nc00010$' => '168',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            5 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '20',
                'parametro_id' => '853',
                'id' => '5',
                'sys_nc00011$' => '20',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            6 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '25',
                'parametro_id' => '853',
                'id' => '6',
                'sys_nc00011$' => '25',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            7 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '34',
                'parametro_id' => '853',
                'id' => '7',
                'sys_nc00011$' => '34',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            8 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '35',
                'parametro_id' => '853',
                'id' => '8',
                'sys_nc00011$' => '35',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            9 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '37',
                'parametro_id' => '853',
                'id' => '9',
                'sys_nc00011$' => '37',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            10 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '39',
                'parametro_id' => '853',
                'id' => '10',
                'sys_nc00011$' => '39',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            11 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '46',
                'parametro_id' => '853',
                'id' => '11',
                'sys_nc00011$' => '46',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            12 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '48',
                'parametro_id' => '853',
                'id' => '12',
                'sys_nc00011$' => '48',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            13 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '49',
                'parametro_id' => '853',
                'id' => '13',
                'sys_nc00011$' => '49',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            14 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '50',
                'parametro_id' => '853',
                'id' => '14',
                'sys_nc00011$' => '50',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            15 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '51',
                'parametro_id' => '853',
                'id' => '15',
                'sys_nc00011$' => '51',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            16 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '52',
                'parametro_id' => '853',
                'id' => '16',
                'sys_nc00011$' => '52',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            17 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '58',
                'parametro_id' => '853',
                'id' => '17',
                'sys_nc00011$' => '58',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            18 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '73',
                'parametro_id' => '853',
                'id' => '18',
                'sys_nc00011$' => '73',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            19 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '80',
                'parametro_id' => '853',
                'id' => '19',
                'sys_nc00011$' => '80',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            20 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '82',
                'parametro_id' => '853',
                'id' => '20',
                'sys_nc00011$' => '82',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            21 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '99',
                'parametro_id' => '853',
                'id' => '21',
                'sys_nc00011$' => '99',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            22 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '106',
                'parametro_id' => '853',
                'id' => '22',
                'sys_nc00011$' => '106',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            23 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '137',
                'parametro_id' => '853',
                'id' => '23',
                'sys_nc00011$' => '137',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            24 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '141',
                'parametro_id' => '853',
                'id' => '24',
                'sys_nc00011$' => '141',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            25 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '144',
                'parametro_id' => '853',
                'id' => '25',
                'sys_nc00011$' => '144',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            26 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '151',
                'parametro_id' => '853',
                'id' => '26',
                'sys_nc00011$' => '151',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            27 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '176',
                'parametro_id' => '853',
                'id' => '27',
                'sys_nc00011$' => '176',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            28 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '177',
                'parametro_id' => '853',
                'id' => '28',
                'sys_nc00011$' => '177',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            29 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '187',
                'parametro_id' => '853',
                'id' => '29',
                'sys_nc00011$' => '187',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            30 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '197',
                'parametro_id' => '853',
                'id' => '30',
                'sys_nc00011$' => '197',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            31 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '199',
                'parametro_id' => '853',
                'id' => '31',
                'sys_nc00011$' => '199',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            32 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '200',
                'parametro_id' => '853',
                'id' => '32',
                'sys_nc00011$' => '200',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            33 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '203',
                'parametro_id' => '853',
                'id' => '33',
                'sys_nc00011$' => '203',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            34 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '205',
                'parametro_id' => '853',
                'id' => '34',
                'sys_nc00011$' => '205',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            35 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '206',
                'parametro_id' => '853',
                'id' => '35',
                'sys_nc00011$' => '206',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            36 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '209',
                'parametro_id' => '853',
                'id' => '36',
                'sys_nc00011$' => '209',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            37 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '233',
                'parametro_id' => '853',
                'id' => '37',
                'sys_nc00011$' => '233',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            38 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '246',
                'parametro_id' => '853',
                'id' => '38',
                'sys_nc00011$' => '246',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            39 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '257',
                'parametro_id' => '853',
                'id' => '39',
                'sys_nc00011$' => '257',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            40 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '258',
                'parametro_id' => '853',
                'id' => '40',
                'sys_nc00011$' => '258',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            41 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '259',
                'parametro_id' => '853',
                'id' => '41',
                'sys_nc00011$' => '259',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            42 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '268',
                'parametro_id' => '853',
                'id' => '42',
                'sys_nc00011$' => '268',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            43 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '270',
                'parametro_id' => '853',
                'id' => '43',
                'sys_nc00011$' => '270',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            44 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '286',
                'parametro_id' => '853',
                'id' => '44',
                'sys_nc00011$' => '286',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            45 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '297',
                'parametro_id' => '853',
                'id' => '45',
                'sys_nc00011$' => '297',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            46 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '301',
                'parametro_id' => '853',
                'id' => '46',
                'sys_nc00011$' => '301',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            47 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '304',
                'parametro_id' => '853',
                'id' => '47',
                'sys_nc00011$' => '304',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            48 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '307',
                'parametro_id' => '853',
                'id' => '48',
                'sys_nc00011$' => '307',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            49 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '316',
                'parametro_id' => '853',
                'id' => '49',
                'sys_nc00011$' => '316',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            50 => 
            array (
                'user_edita_id' => '1',
                'user_crea_id' => '1',
                'vsi_sitespecial_id' => '321',
                'parametro_id' => '853',
                'id' => '50',
                'sys_nc00011$' => '321',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => '2021-04-27 12:01:40',
                'created_at' => '2021-04-27 12:01:40',
                'sis_esta_id' => '1',
            ),
            51 => 
            array (
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_sitespecial_id' => '332',
                'parametro_id' => '853',
                'id' => '51',
                'sys_nc00011$' => '332',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            52 => 
            array (
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_sitespecial_id' => '333',
                'parametro_id' => '853',
                'id' => '52',
                'sys_nc00011$' => '333',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            53 => 
            array (
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_sitespecial_id' => '334',
                'parametro_id' => '853',
                'id' => '54',
                'sys_nc00011$' => '334',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            54 => 
            array (
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_sitespecial_id' => '336',
                'parametro_id' => '853',
                'id' => '56',
                'sys_nc00011$' => '336',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            55 => 
            array (
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_sitespecial_id' => '337',
                'parametro_id' => '853',
                'id' => '57',
                'sys_nc00011$' => '337',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            56 => 
            array (
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_sitespecial_id' => '342',
                'parametro_id' => '853',
                'id' => '63',
                'sys_nc00011$' => '342',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            57 => 
            array (
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_sitespecial_id' => '340',
                'parametro_id' => '853',
                'id' => '61',
                'sys_nc00011$' => '340',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            58 => 
            array (
                'user_edita_id' => '1559',
                'user_crea_id' => '1559',
                'vsi_sitespecial_id' => '341',
                'parametro_id' => '853',
                'id' => '62',
                'sys_nc00011$' => '341',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            59 => 
            array (
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_sitespecial_id' => '344',
                'parametro_id' => '853',
                'id' => '65',
                'sys_nc00011$' => '344',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            60 => 
            array (
                'user_edita_id' => '1436',
                'user_crea_id' => '1436',
                'vsi_sitespecial_id' => '346',
                'parametro_id' => '853',
                'id' => '67',
                'sys_nc00011$' => '346',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            61 => 
            array (
                'user_edita_id' => '2133',
                'user_crea_id' => '2133',
                'vsi_sitespecial_id' => '338',
                'parametro_id' => '853',
                'id' => '58',
                'sys_nc00011$' => '338',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            62 => 
            array (
                'user_edita_id' => '1989',
                'user_crea_id' => '1989',
                'vsi_sitespecial_id' => '343',
                'parametro_id' => '853',
                'id' => '64',
                'sys_nc00011$' => '343',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
            63 => 
            array (
                'user_edita_id' => '398',
                'user_crea_id' => '398',
                'vsi_sitespecial_id' => '345',
                'parametro_id' => '853',
                'id' => '66',
                'sys_nc00011$' => '345',
                'sys_nc00010$' => '853',
                'deleted_at' => NULL,
                'updated_at' => NULL,
                'created_at' => NULL,
                'sis_esta_id' => '1',
            ),
        ));
        
        
    }
}