<?php
include_once('web_ag_actividad.php');
include_once('web_ag_contexto.php');
include_once('web_ag_convenio.php');
include_once('web_ag_dependencia.php');
include_once('web_ag_recurso.php');
include_once('web_ag_subtema.php');
include_once('web_ag_taller.php');
include_once('web_ag_tema.php');
include_once('web_ag_taller_ag_tema.php');
include_once('web_modulo.php');
